### ISSUE TITLE
[MySQL] One container per site OR single container for multiple sites - which is better?

### ISSUE THREAD

**Issue by mbtamuli** [EasyEngine/easyengine#1001]
We have two approaches we can use for EEv4.
* a single database container for multiple sites 
* a dedicated database container for each site.

Each approach has their pros and cons. 
Single database container will require less resources but will be accessible by all sites.
Per site database container will ensure one site and its database is completely isolated, but will require more resources.

**Comment by michacassola** [comment]
Make it a dedicated one please as you could also use some other docker features like resource limiting on it. Just a thought :)

**Comment by andremacola** [comment]
That depends. If it is a shared dedicated server for hosting clients or not.
Another case is about a remote database server (my case)

**Comment by dmhendricks** [comment]
I would prefer the resource savings. +1 single container

**Comment by nsgoyat** [comment]
+1 for Single Database Container for Multiple Sites.

**Comment by eddr** [comment]
If we need to choose only one option (??), then personally I'd go with 1on1 approach, for the typical WP performance sites. It's important to think about the scenario:

1. Security implications are much worse than +10% resources/response times in almost any case

2. Even for typical performance focused WP site, much of the DB work can be negated using caching anyway, either via memory cache or page cache. For small sites, there isn't much significance for 10% response times on DB queries.

3. And, if you really need lots of DB queries and you think that this 10% response times diff is important, then: (a) you probably better upgrade the hardware anyway and (b) You probably running very active  site, and security is more important.

4. If you have an active site without users and security is not important, but still you don't use caching, then what exactly are you doing? computation? vast crawling? that's an edge case and perhaps more suitable for other systems or you're doing something wrong.


Having said that, security doesn't start or end in docker..

**Comment by dmhendricks** [comment]
Putting everything from cron to mkdir in its own container is fine until your mobile phone has more RAM than your client is willing to pay for in a VPS instance.

**Comment by eddr** [comment]
I think like @VirtuBox. Let us use the power of docker. Small performance difference is not worth ditching it all.

**Comment by mikelittle** [comment]
+1 for one container per site. 
Migration, isolation, and security are important for me. 
Almost by definition if my sites aren't busy enough to need their own VPS, then they won't need the minor performance increase of having a shared DB container.

**Comment by codente** [comment]
+1 a dedicated database container for each site.

**Comment by overdigo** [comment]
I think dedicated database container is more useful

**Comment by pserafini** [comment]
+1 Dedicated database for each site. 
Reasons :
- security
- fine-tuning
- ressource allocation
- easier backup / duplication
- etc...

**Comment by rahul286** [comment]
Thanks all for your inputs. 

We did performance testing by creating 100s of WP sites with single shared MySQL container as well as one container per site. The results were quite close and inconclusive for practical performance consideration.

Here is how we are progressing:

1. The default will be a one mysql container per site. 
2. EE v4, like v3 will support remote mysql connection during in `site create` command. The real-life use case for us to use Amazon RDS with WordPress sites. But if somebody wants to connect to "a single shared mysql container", they can create on such mysql host container and then pass its connection parameters during site creation.

If you see any issues with above, please report.

**Comment by michacassola** [comment]
Should be moved to done in the project board. 😃

**Comment by rahul286** [comment]
@michacassola done :)
