### ISSUE TITLE
Support to RockDB in v4

### ISSUE THREAD

**Issue by vibhi19** [EasyEngine/easyengine#1004]
Is it possible to add support to Myrocks.io
As per Them it better than innodb use less storage and Faster

Take a look hope it can make WordPress more faster

**Comment by vibhi19** [comment]
https://mariadb.com/resources/blog/facebook-myrocks-mariadb

**Comment by rahul286** [comment]
@vibhi19 please provide more details? Did you already try it with WordPress? Any benchmarking you did?

If you have more details please share. We are closing issue for now.
