### ISSUE TITLE
Add service command in v4

### ISSUE THREAD

**Issue by mrrobot47** [EasyEngine/easyengine#1010]
Add service command in v4 to:

- [x] Reload and Restart per site containers.
- [x] Add check for global container before starting any container.
- [x] Use docker-compose.yml for global services.
- [x] Reload and Restart global containers.

Also edit site command to control site specific services.

**Comment by rahul286** [comment]
For per site container, better use:

```
ee site [start|stop|restart|reload] example.com [--all|--nginx|--php|--mysql|--redis|--mailcatcher|--elasticache]
```

For global site container, maybe we can do:

```
ee stack [start|stop|restart|reload] [--all|traefik]
```

**Comment by mbtamuli** [comment]
For this command,
```
ee site [start|stop|restart|reload] example.com [--all|--nginx|--php|--mysql|--redis|--mailcatcher|--elasticache]
```
The site specific services will be fixed for beta1. We'll give the option of site specific service operations in beta2.

The global service command will be handled in beta1 itself.

**Comment by mbtamuli** [comment]
Admin Tools
MailHog - Site specific container
Other PHP Based - In `/opt/easyengine/admin-tools` mounted read-only to PHP container

**Comment by kirtangajjar** [comment]
TODO: Add option for swiching mysql to global service
