### ISSUE TITLE
22222 Site Throwing Nginx Bad Gateway

### ISSUE THREAD

**Issue by kinkod** [EasyEngine/easyengine#1018]
I have created a site with --php7 flag, all went ok. Then I tried accessing 22222 site to access adminer and didn't worked (threw bad gateway error in nginx). I went and edited the 22222 nginx config file to use php7 instead of php5 and it worked. 

System Information
- [x] lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial

- [x] ee -v
EasyEngine v3.8.0
Copyright (c) 2016 rtCamp Solutions Pvt. Ltd.

- [x] ee info
NGINX (1.10.3):

user                             www-data
worker_processes                 auto
worker_connections               4096
keepalive_timeout                30
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1 
PHP5.6 is not installed

- [x] wp --allow-root --info
wp: command not found

**Comment by rahul286** [comment]
Sorry for a delayed reply. I hope your issue is fixed by now.

If you are still facing the issue, please use http://community.rtcamp.com/c/easyengine for further support.

We are cleaning up issue tracker and closing this issue because we won't be able to contribute to this discussion further.
