### ISSUE TITLE
--letsencrypt doesn't work

### ISSUE THREAD

**Issue by kinkod** [EasyEngine/easyengine#1019]
--letsencrypt doesn't work. First i only had domain.com in DNS pointing to server, ran --letsencrypt and i got an error:

Unable to setup, Let's Encrypt
Please make sure that your site is pointed to
same server on which you are running Let's Encrypt Client
to allow it to verify the site automatically.

Searched online, found a thread where somebody was saying to also add www.domain.com in DNS, I added it, but again didn't worked. I got same error.

System Information
- [x] lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial

- [x] ee -v
EasyEngine v3.8.0
Copyright (c) 2016 rtCamp Solutions Pvt. Ltd.

- [x] ee info
NGINX (1.10.3):

user                             www-data
worker_processes                 auto
worker_connections               4096
keepalive_timeout                30
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1 
PHP5.6 is not installed

- [x] wp --allow-root --info
wp: command not found

**Comment by mbtamuli** [comment]
Please use http://community.rtcamp.com/c/easyengine for support questions. This is a specific question related to letsencrypt. 
Closing this issue for now, feel free to continue the discussion.
