### ISSUE TITLE
Possibility to choose primary domain (with-www or without-www) and redirect from one to the other

### ISSUE THREAD

**Issue by kinkod** [EasyEngine/easyengine#1021]
Feature request: Possibility to choose primary domain (with-www or without-www) and redirect from one to the other. Could be added as a --www and --nonwww flags.

**Comment by rahul286** [comment]
There are four possibilities:

| Command        |    Domain       |
| ------------- |-------------|
| ee site create example.com      | http://example.com |
| ee site create www.example.com      | http://www.example.com      |
| ee site create example.com --le | https://example.com      |
| ee site create www.example.com --le | https://www.example.com |

**What we need**

- [ ] Whenever somebody runs a command with `--le` the remaining three options should redirect to the primary domain specified in the executed command
- [ ] Whenever somebody runs a command without `--le` i.e. just for plain HTTP site, the other version, www or non-www should redirect to the primary domain specified in the executed command

**Comment by kinkod** [comment]
@rahul286 Yeah, that's a very good breakdown

**Comment by michacassola** [comment]
What about adding alias domains like:
`ee site create example.com example.de --le`

Should I make a separate feature request for that?

**Comment by rahul286** [comment]
@michacassola yep. We would like to defer it. We want to get v4 out asap.

**Comment by michacassola** [comment]
Ok, heres the issue: https://github.com/EasyEngine/easyengine/issues/1033

**Comment by mbtamuli** [comment]
Fixed in https://github.com/EasyEngine/site-command/pull/70
