### ISSUE TITLE
--letsencrypt to work without adding www domain to DNS

### ISSUE THREAD

**Issue by kinkod** [EasyEngine/easyengine#1022]
Currently letsencrypt requires both domain.com and www.domain.com to be added to DNS. It would be nice to have it work with just one of them in DNS.

**Comment by rahul286** [comment]
Related to #1021.

@mbtamuli I think for subdomains, www variant is not required. So may need to add a check for the subdomain and handle it a bit differently for www variation.

**Comment by mrrobot47** [comment]
Closing the issue, it has been taken care of in Letsencrypt integration PR in beta.3 release: https://github.com/EasyEngine/site-command/pull/52
