### ISSUE TITLE
v4 --letsencrypt can not used

### ISSUE THREAD

**Issue by caaol** [EasyEngine/easyengine#1023]
ee site create ***.com --wpredis  --letsencrypt

no https

**Comment by mbtamuli** [comment]
Are you using the EasyEngine v4? We haven't released it yet, though we'd be super excited to have you test our alpha release when it is ready. (We'll mention through a blog post and send a newsletter.)

A [WIP PR](https://github.com/EasyEngine/easyengine/pull/1005) is already raised against develop-v4 branch which will add letsencrypt support to EasyEngine v4

If you're using EasyEngine v3, please create a new issue and close this issue.
