### ISSUE TITLE
v4 - Sending emails reliably from container (Docker)

### ISSUE THREAD

**Issue by rahul286** [EasyEngine/easyengine#1028]
All the production docker workload we are using is configured to use Amazon SES for email delivery.

Does anyone use postfix or some native SMTP based email/MTA solution in the containerized world?

___

**Test Case**

1. Test using WordPress plugin https://wordpress.org/plugins/check-email/
2. Test email score https://www.mail-tester.com/

**Comment by eddr** [comment]
I'm using a 3rd party mail service (mailgun right now)

**Comment by rahul286** [comment]
@eddr we need to check if postfix is reliable with Docker
