### ISSUE TITLE
Convert v4 reverse-proxy to traefik

### ISSUE THREAD

**Issue by mrrobot47** [EasyEngine/easyengine#1036]
Convert v4 revers-proxy from [jwilder/nginx-proxy](https://github.com/jwilder/nginx-proxy) to [traefik](https://github.com/containous/traefik) as the default reverse-proxy as the `nginx-proxy` is not being updated as frequently as the `traefik`, also it does not support the letsencrypt wild-card certificates.

**Comment by michacassola** [comment]
Definitely Traefik yes, it is the docker standard.

**Comment by mbtamuli** [comment]
This was fixed in #1041
