### ISSUE TITLE
Security block for :22222 endpoint

### ISSUE THREAD

**Issue by kinkod** [EasyEngine/easyengine#1038]
When accessing :22222 site (in FireFox) I am getting the following error:

Your connection is not secure

The website tried to negotiate an inadequate level of security.

***server_ip_edited_out*** uses security technology that is outdated and vulnerable to attack. An attacker could easily reveal information which you thought to be safe. The website administrator will need to fix the server first before you can visit the site.

Error code: NS_ERROR_NET_INADEQUATE_SECURITY

System Information
- [x] lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial

- [x] ee -v
EasyEngine v3.8.1
Copyright (c) 2016 rtCamp Solutions Pvt. Ltd.

- [x] ee info
NGINX (1.14.0):

user                             www-data
worker_processes                 auto
worker_connections               4096
keepalive_timeout                30
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1 
PHP5.6 is not installed

- [x] wp --allow-root --info
wp: command not found

**Comment by matheusfbraga** [comment]
I'm having the same problem. I'm able to create sites using ssh, but I don't have any idea how is the web gui. Also I'm searching for autodeploy features.

Tried on ubuntu 16.04 and 18.04, same problem.

# ee -v
EasyEngine v3.8.1
Copyright (c) 2016 rtCamp Solutions Pvt. Ltd.

# ee info

NGINX (1.14.0):

user                             www-data
worker_processes                 auto
worker_connections               4096
keepalive_timeout                30
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1 

PHP (5.6.36-1):

user                             
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  500
pm.max_children                  100
pm.start_servers                 20
pm.min_spare_servers             10
pm.max_spare_servers             30
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           127.0.0.1:9000

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  500
pm.max_children                  100
pm.start_servers                 20
pm.min_spare_servers             10
pm.max_spare_servers             30
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9001

MySQL (10.1.33-MariaDB) on localhost:

port                             3306
wait_timeout                     600
interactive_timeout              28800
max_used_connections             3
datadir                          /var/lib/mysql/
socket                           /var/run/mysqld/mysqld.sock
my.cnf [PATH]                    /etc/mysql/conf.d/my.cnf

**Comment by janiosarmento** [comment]
There is no web GUI for EEv3. Also, I don't get what you mean by "autodeploy features".

Perhaps you should ask for support on the Community forum: https://community.rtcamp.com/

**Comment by anvychow** [comment]
Hello,

The same issue happening... I'm unable to access phpmyadmin due to this issue.

How to solve this?

**Comment by rahul286** [comment]
@kinkod in V4, admin tools will be handled differently so `:22222` wont be needed.

Ref -  https://github.com/EasyEngine/easyengine/issues/1013

We are not accepting any new PR's in V3 unless they are security fixes. So I need to close this without a merge. Sorry.

Regards.
