### ISSUE TITLE
EE doesn't renew SSL certificate if --all option is added and SSL certificate already expired

### ISSUE THREAD

**Issue by dethmix** [EasyEngine/easyengine#1069]
This issue tracker is only for issues related to EasyEngine. Please use http://community.rtcamp.com/c/easyengine for support questions.

If you feel the issue is a EasyEngine core specific issue, please attach the output of the following commands.

System Information
- [ ] lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
- [ ] ee -v
EasyEngine v3.7.4
- [ ] ee info
NGINX (1.10.3):

user                             www-data
worker_processes                 auto
worker_connections               4096
keepalive_timeout                30
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1

PHP (5.6.32-1):

user
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  500
pm.max_children                  100
pm.start_servers                 20
pm.min_spare_servers             10
pm.max_spare_servers             30
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           127.0.0.1:9000

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  500
pm.max_children                  100
pm.start_servers                 20
pm.min_spare_servers             10
pm.max_spare_servers             30
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9001

MySQL (10.1.30-MariaDB) on localhost:

port                             3306
wait_timeout                     600
interactive_timeout              28800
max_used_connections             5
datadir                          /var/lib/mysql/
socket                           /var/run/mysqld/mysqld.sock
my.cnf [PATH]                    /etc/mysql/conf.d/my.cnf
- [ ] wp --allow-root --info

Due to following part of code in file https://github.com/EasyEngine/easyengine/blob/master/ee/cli/plugins/site.py  cron EE skips to renew certificates that have already been expired:
```python
        if pargs.all and pargs.letsencrypt == "renew":

            if check_ssl:
                expiry_days = SSL.getExpirationDays(self,ee_domain,True)
                if expiry_days < 0:
                    return 0
                min_expiry_days = 30
                if (expiry_days <= min_expiry_days):
                    renewLetsEncrypt(self,ee_domain)
```
More over it doesn't log any error message because of 
```python
        if (days_left > 0):
            return days_left
        else:
            # return "Certificate Already Expired ! Please Renew soon."
            return -1
```
in https://github.com/EasyEngine/easyengine/blob/master/ee/core/sslutils.py

As far as I can see this code is still used into newest version of EE v3 and imported to EE v4. I think this code should be optimized to proceed expired certificates or at least log proper error message.

**Comment by mbtamuli** [comment]
This code is not being used in EEv4. If you have figured out this issue, you can send a PR to resolve it.  We accept PR like all other open source projects.

**Comment by rahul286** [comment]
@dethmix We are closing v3 issues that are not related to security. V4 handles this differently.
