### ISSUE TITLE
EE4 Beta1: WordPress does not finish installation

### ISSUE THREAD

**Issue by codente** [EasyEngine/easyengine#1072]
I'm on a Mac using terminal.  Server is from Vultr.

System Information
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial

Note: when I ran the command for the below output, this appears above it:
`PHP Notice:  Undefined index: ssh in phar:///usr/local/bin/ee/php/EE/Runner.php on line 730`
+-------------------+--------------------------------------+
| OS                | Linux 4.4.0-127-generic #153-Ubuntu  |
|                   | SMP Sat May 19 10:58:46 UTC 2018 x86 |
|                   | _64                                  |
| Shell             | /bin/bash                            |
| PHP binary        | /usr/bin/php7.2                      |
| PHP version       | 7.2.6-1+ubuntu16.04.1+deb.sury.org+1 |
| php.ini used      | /etc/php/7.2/cli/php.ini             |
| EE root dir       | phar://ee.phar                       |
| EE vendor dir     | phar://ee.phar/vendor                |
| EE phar path      | /root                                |
| EE packages dir   |                                      |
| EE global config  | /opt/easyengine/config.yml           |
| EE project config |                                      |
| EE version        | 4.0.0-beta.1                         |
+-------------------+--------------------------------------+

Trying to use this command: ee site create example.com --wp

Everything seems to go okay as far as what I see in Terminal but when I actually visit the site, it takes me to the WP install page. (wp-admin/setup-config.php).

**Comment by mrrobot47** [comment]
@codente This issue was occurring because the mysql service of the database container was not ready by the time EasyEngine tried to install WordPress. This issue has been reported here https://github.com/EasyEngine/site-command/issues/33 and taken care of here [https://github.com/EasyEngine/site-command/pull/34] by adding proper health check so that EasyEngine starts the installation of WordPress only when the database container is ready and healthy. It will be shipped in the next release.

**Comment by codente** [comment]
Hi - thanks.  What causes this?  By this I mean "mysql service of the database container was not ready by the time EasyEngine tried to install WordPress. "

**Comment by kirtangajjar** [comment]
@codente What was happening was that while installing wordpress, it was expecting that the mysql container would've been up and running. However mysql takes some time to start and it wasn't running till our code reached that point.

We fixed it by waiting for mysql server to start before proceeding with site install.
