### ISSUE TITLE
V4 Cleanup composer packages/lib which is not required.

### ISSUE THREAD

**Issue by rahulsprajapati** [EasyEngine/easyengine#1076]
We have some unused/unrequired packages in v4 composer.json. Check all packages and it's usage and remove if not needed.

Like: 

> ramsey/array_column 

This is only required for php version < 5.5 and we will be using php min version 7.0.

Also we might able to replace `rmccue/requests` lib with `curl` since we already have `curl` module required for php.

https://github.com/EasyEngine/easyengine/blob/b506dc91487618bc41d3212284efab94a0b861f2/composer.json#L27-L48

**Comment by mrrobot47** [comment]
Closing this as this has been cleaned up and completed.
