### ISSUE TITLE
My whole server was hacked because all WP installations are created under same user 'www-data'

### ISSUE THREAD

**Issue by jasomdotnet** [EasyEngine/easyengine#1083]
Hi,
when one site became compromised, attacker can spread his malicious code to entire server, because EE creates all WP installations under same user 'www-data'. This is what happened to my on Friday evening :-) I have about 15 WP sites installed.

I suggest to add functionality to EE so every WP installation is under new user. Something like 'example_com'.

**Comment by jasomdotnet** [comment]
perfect, when we can expect v4 to come?

**Comment by Helmi** [comment]
sorry for your hack. Not really EE related but any more information about how they managed to compromise in the first place and what they did to compromise the other blogs would be helpful.

**Comment by rahul286** [comment]
@jasomdotnet Sorry for the problem you have faced. 

We do not have any plans to handle this in v3. V4 will some webroot isolation so you shouldn't face this. 

You can follow v4 updates here http://easyengine.io/blog
