### ISSUE TITLE
Remove default php 5.6 configurations

### ISSUE THREAD

**Issue by pojke** [EasyEngine/easyengine#1090]
It's not really a bug but feature that should be considered for version 4.
A lot of configurations for Easy Engine default to PHP 5.6 which is already outdated and often not used. Without PHP 5.6 running, for instance, you cannot run phpmyadmin. Easy Engine should take into consideration PHP version running in order to use for all packages.

Here's a simple use case. I want to run a very simple landing page and collect subsriptions. All I need is a VPS, database, phpmyadmin and php7 (because it's the current one).

- I install current Easy Engine (still version 3)
- I execute "sudo ee site create mysite.com --php7"
- I then execute "ee stack install --phpmyadmin"

I expect phpmyadmin to work, instead, configuration is set for php 5.6 which at this stage is missing.

**Comment by renatonascalves** [comment]
Better than that, the person should choose which PHP version he/she wants to install in the server. If it is going to default at one, that be the recent version, PHP 7+.

**Comment by michacassola** [comment]
Yes @renatonascalves that sounds really good!
Already at installation time it could be set as the standard for everything thereafter with something like this:
`wget -qO ee rt.cx/ee4beta && sudo bash ee --php7.2`

**Comment by rahul286** [comment]
@pojke v4 uses php7 by default
