### ISSUE TITLE
Use jwilder/nginx-proxy

### ISSUE THREAD

**Issue by mbtamuli** [EasyEngine/easyengine#1096]
Porting the current code to use [jwilder/nginx-proxy](https://github.com/jwilder/nginx-proxy) and test all site types are working properly.

**Comment by michacassola** [comment]
Why not Traefik anymore?

**Comment by mrrobot47** [comment]
Taken care of in beta.3 release, merged PR: https://github.com/EasyEngine/site-command/pull/51

**Comment by michacassola** [comment]
Why not Traefik anymore? Is there any explanation about this? @mbtamuli @rahul286 @mrrobot47

**Comment by mbtamuli** [comment]
@michacassola Yes. We'll be posting a blog post soon about the beta3 release and why we're not including Traefik anymore.

**Comment by michacassola** [comment]
Thanks! Sorry for rushing you then.
