### ISSUE TITLE
How to install easyengine 4?

### ISSUE THREAD

**Issue by jasomdotnet** [EasyEngine/easyengine#1101]
How to install easyengine 4? Command from Easyengine.io

`wget -qO ee rt.cx/ee && sudo bash ee`

installs 3.x version only. Is there any tutorial?

**Comment by mbtamuli** [comment]
Hey @jasomdotnet. Thanks for you interest in v4 beta. You can find all information, including installation instruction, related to v4 beta1 here https://easyengine.io/blog/ee-v4-beta-1-release/ and v4 beta2 here https://easyengine.io/blog/ee-v4-beta-2-release/.

**Comment by jasomdotnet** [comment]
great, thanks.
