### ISSUE TITLE
Add auth on admin tools

### ISSUE THREAD

**Issue by kirtangajjar** [EasyEngine/easyengine#1119]
All admin tools on `/ee-admin/` should be protected by http auth. Preferably the password should be generated randomly rather than a static default.

TODO

- [ ] @mrrobot47 please check https://github.com/EasyEngine/easyengine/issues/520 for allowed characters

**Comment by rahul286** [comment]
**Sample command structure**

```
ee auth set --user=easyengine          (frontend nginx)
ee auth set foo.com --user=easyengine  (backend nginx)
ee auth set bar.com <--user=barcom>

ee auth reset --user=mb
ee auth set --user=rahul
ee auth set --user=rb
ee auth set --user=rahul --password=123123214

ee auth list
ee auth list foo.com
ee auth list bar.com
```

**TODO** 

Check if multiple auth file works

```
http {
    auth-global

   server { 
        auth-site-specific
    }
}```
