### ISSUE TITLE
Allow provisions for global containers

### ISSUE THREAD

**Issue by kirtangajjar** [EasyEngine/easyengine#1120]
Currently in easyengine v4, each site creates following containers -

 * nginx
 * mysql
 * php
 * redis(optional)

However it might start creating issues when one starts to create more and more sites as each container consumes more resources(especially ram).

Hence if the user passes any flag during `ee site create`, we should use the global container.

It does not make sense to allow `php` and `nginx` global containers due to security implication and because they're pretty lightweight containers. 

Hence it seems only `mysql` and `redis` would benifit most from global containers as they're more resource intensive(esp mysql) so there should be provison for these two atleast.

**Comment by mbtamuli** [comment]
This is being tracked in https://github.com/EasyEngine/easyengine/issues/1010
