### ISSUE TITLE
Deleting a secure site and recreating the site fails to make it secure.

### ISSUE THREAD

**Issue by mikelittle** [EasyEngine/easyengine#1123]
This issue tracker is only for issues related to EasyEngine. Please use http://community.rtcamp.com/c/easyengine for support questions.

If you feel the issue is a EasyEngine core specific issue, please attach the output of the following commands.

System Information
- [X] lsb_release -a
- [X] ee -v
- [X] ee info
- [X] wp --allow-root --info

$lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:    16.04
Codename:   xenial

$ee --version
EE 4.0.0-beta.3

$ee cli info
+-------------------+----------------------------------------------------------+
| OS                | Linux 4.4.0-128-generic #154-Ubuntu SMP Fri May 25 14:15 |
|                   | :18 UTC 2018 x86_64                                      |
| Shell             | /bin/bash                                                |
| PHP binary        | /usr/bin/php7.2                                          |
| PHP version       | 7.2.7-1+ubuntu16.04.1+deb.sury.org+1                     |
| php.ini used      | /etc/php/7.2/cli/php.ini                                 |
| EE root dir       | phar://ee.phar                                           |
| EE vendor dir     | phar://ee.phar/vendor                                    |
| EE phar path      | /var/www                                                 |
| EE packages dir   |                                                          |
| EE global config  | /opt/easyengine/config.yml                               |
| EE project config |                                                          |
| EE version        | 4.0.0-beta.3                                             |
+-------------------+----------------------------------------------------------+

$wp --allow-root --info
OS: Linux 4.4.0-128-generic #154-Ubuntu SMP Fri May 25 14:15:18 UTC 2018 x86_64
Shell:
PHP binary: /usr/local/bin/php
PHP version:    7.2.7
php.ini used:   /usr/local/etc/php/php.ini
WP-CLI root dir:    phar://wp-cli.phar
WP-CLI vendor dir:  phar://wp-cli.phar/vendor
WP_CLI phar path:   /var/www/html
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 1.5.1

## Steps to re-create

I created a site using

`$ ee site create sitename.tld --le`

This created the site and it worked under https.

I then deleted the site because I wanted to try with --wpredis flag

`$ ee site delete site01.wpexample.xyz`
```
[sitename.tld] Docker Containers removed.
[sitename.tld] Disconnected from Docker network of ee-nginx-proxy
[sitename.tld] Docker container removed from network ee-nginx-proxy.
[sitename.tld] site root removed.
Removing ssl certs.
Removing database entry.
Site sitename.tld deleted.
```
Note it says 'removing ssl certs'

I then tried to recreate the site with the --wpredis flag

```
$ ee site create sitename.tld --wpredis --le
Warning: This is a beta version. Please don't use it in production.
Configuring project.
Success: Network started.
Success: Site connected to ee-nginx-proxy.
Creating WordPress site sitename.tld.
Copying configuration files.
Success: Configuration files copied.
Pulling latest images. This may take some time.
Starting site's services.
Downloading and configuring WordPress.
Host entry already exists.
Checking and verifying site-up status. This may take some time.
.
Installing WordPress site.
Success: https://sitename.tld has been created successfully!
The authorization check was successful!
Loading current certificate for sitename.tld
Current certificate is valid until 2018-10-11 16:21:51, renewal is not necessary.
Details for site sitename.tld:
+--------------------+------------------------------------------------+
| Site               | https://sitename.tld                   |
+--------------------+------------------------------------------------+
...
Site entry created.
```
Note the messages about the certificate:
"Loading current certificate... Current certificate is valid ... renewal is not necessary."

But in actual fact, it created the WordPress site with only an http address and set up the nginx config only listening on port 80.

I investigated and can see the delete command had removed the `.crt` and `.key` from `/opt/easyengine/nginx/certs` but not deleted the certificate files from `/opt/easyengine/acme-conf/certs`

I then deleted the site again. But this time I deleted the site folder in `/opt/easyengine/nginx/certs` by hand.

When I created the site again 

`$ ee site create sitename.tld --wpredis --le`

This time is worked properly.

**Comment by mbtamuli** [comment]
Thanks @mikelittle for reporting this issue. We also came to know about this issue and have already worked on it. We should have this fixed in the next beta release.

**Comment by mrrobot47** [comment]
@mikelittle instead of deleting the certs from `/opt/easyengine/acme-conf/certs`, it would be better to check if the certificate is valid inside it, and if it is then to copy it to the `nginx-proxy` location for certs `/opt/easyengine/nginx/certs`.

Raised a [PR](https://github.com/EasyEngine/site-command/pull/75) to achieve the same. This updated function will now check for the backup certs inside the `acme-conf` and if it is still valid, it will copy them to the `nginx-proxy`, otherwise if they have expired, it will issue a new certificate and copy it to `nginx-proxy` as well as back it up in `acme-conf`.

**Comment by mbtamuli** [comment]
> if it is still valid
@mrrobot47  How are you checking the validity?

**Comment by mikelittle** [comment]
@mrrobot47 I agree, deleting non-expired certificates doesn't make sense, just in case the site is recreated. 
Especially as Let's Encrypt place limits on how many times you can re-create a certificate for the same domain.  

Maybe sometime later there can be a cleanup-certs command, but given the size of the files, it's not urgent.

**Comment by mrrobot47** [comment]
@mikelittle I had a discussion with @rahul286 @mbtamuli and @kirtangajjar and going with total cleanup was the final decision. Anyways, the letsencrypt api rate limit is generous and real use cases it should not affect at all. So, going ahead with total cleanup of certificate files on deletion.

Also, thinking of provisioning something like [this](https://github.com/EasyEngine/site-command/issues/77) very soon, most probably in the next beta itself. This should also improve certificate management, reduce the certificate files maintained and ease the cleanup.
