### ISSUE TITLE
502 error after upgrading bionic and rebooting

### ISSUE THREAD

**Issue by WCat13** [EasyEngine/easyengine#1130]
This issue tracker is only for issues related to EasyEngine. Please use http://community.rtcamp.com/c/easyengine for support questions.

If you feel the issue is a EasyEngine core specific issue, please attach the output of the following commands.

System Information
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04 LTS
Release:	18.04
Codename:	bionic
- [ ] ee cli version
EE 4.0.0-beta.3
ee cli info
+-------------------+----------------------------------------------------------------------------+
| OS                | Linux 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 |
| Shell             | /bin/bash                                                                  |
| PHP binary        | /usr/bin/php7.2                                                            |
| PHP version       | 7.2.7-1+ubuntu18.04.1+deb.sury.org+1                                       |
| php.ini used      | /etc/php/7.2/cli/php.ini                                                   |
| EE root dir       | phar://ee.phar                                                             |
| EE vendor dir     | phar://ee.phar/vendor                                                      |
| EE phar path      | /home/wcat                                                                |
| EE packages dir   |                                                                            |
| EE global config  | /opt/easyengine/config.yml                                                 |
| EE project config |                                                                            |
| EE version        | 4.0.0-beta.3                                                               |
+-------------------+----------------------------------------------------------------------------+

Just poking around a bit, created wpredis with le on eev4.example.com. I ran apt upgrade && apt autoremove.
Wanted to see how fast the stack came back up.
rebooted and now have 502 error trying to reach that site.

All I did was upgrade and chose keep currently installed versions of grub files when promtped. This is on a DO droplet.

I will leave droplet up and check here after work today to see if you awesome people need more info.

**Comment by mrrobot47** [comment]
@WCat13 we were busy with the [beta.4](https://github.com/EasyEngine/easyengine/releases/tag/v4.0.0-beta.4) release and could not look into the issue earlier. You have just closed it, so was this solved or not?
