### ISSUE TITLE
Independently version docker image and EE 

### ISSUE THREAD

**Issue by kirtangajjar** [EasyEngine/easyengine#1156]
Currently EE version "4.0.0-beta.5" will try to pull image tagged "v4.0.0-beta.5" off all containers. This means we would have to update docker images even if there wasn't any change in it.

This isn't the ideal case and both EE and docker image versions can be independent. Then we can have EE version `4.0.0-beta.5` can depend on a specific docker image verison i.e. `easyengine/php:1.3.0` and so on...

**Comment by rahul286** [comment]
Agree with you. 

https://github.com/EasyEngine/dockerfiles/releases should have been independently versioned. Sorry I missed that.

Ideally, I would have started them versioning 0.1, 0.2 and so on with the goal of reaching dockerfiles v1.0 with ee v4.0.

If there is any special reason to map version numbers, please elaborate.

**Comment by kirtangajjar** [comment]
> If there is any special reason to map version numbers, please elaborate.

Earlier we thought it was best way to go forward since in each release, there were changes in image itself and it was mandatory to update the image. So we put a constraint that the code will pull the version of image matching current easyengine version.

However since last 2 releases, there are minor changes in few images but still we have to update every image because of this constraint. So now it's clear to us that there's no benefit in coupling easyengine and docker image versions.
