### ISSUE TITLE
Add support for multiples wordpress languages

### ISSUE THREAD

**Issue by willmkt** [EasyEngine/easyengine#116]
Hi, it would be great to be able to install wordpress in multiples languages by setting the option on the ee config file.

**Comment by rahul286** [comment]
Just an update - WordPress 4.0 added language change option in UI.

**Comment by rahul286** [comment]
By the way, if you like to send pull request, we can merge it.

WP-CLI has support for locale http://wp-cli.org/commands/core/download/

**Comment by JosefJezek** [comment]
Could you add switch for choice language by installation of wp?

Example: --lang=cs_CZ

**Comment by MiteshShah** [comment]
@rahul286 @gau1991  I'll fix this issue and learn some python code hacks.

**Comment by rahul286** [comment]
@MiteshShah Actually I am planning to support all wp-cli option.

Say when a user enters `ee site --create example.com --wp` then he can enter additional parameters like `ee site --create example.com --wp --wp-cli-lang=cs_CZ`

Idea is every `--wp-cli-*` will be passed directly to wp-cli. That way we can support most wp-cli options without much coding efforts.

If not all wp-cli options makes sense, then we can narrow down options like `--lang` and just pass them to wp-cli.

**Comment by MiteshShah** [comment]
:+1: Nice idea

**Comment by JosefJezek** [comment]
:+1:  I need also specify version...

**Comment by katzkawai** [comment]
:+1: That would be great.

**Comment by ingobaab** [comment]
+1 from me! :)

**Comment by hamidfzm** [comment]
+1

**Comment by alexkappel** [comment]
+1

**Comment by gresakg** [comment]
+1

**Comment by gresakg** [comment]
Also add default language in ee.conf

**Comment by christoferw** [comment]
+1

**Comment by christoferw** [comment]
what if that could be defined in a ee config file?

**Comment by mrrobot47** [comment]
This has been taken care of in https://github.com/EasyEngine/easyengine/issues/1029.

You can now pass `--locale=<locale>` argument while site-creation along with multiple other `wp-cli` parameters to customize your WordPress installation according to your needs.

Also, @willmkt @christoferw the default language for WordPress installation can now be set in the config file located at `/opt/easyengine/config.yml`.

You just need to change the locale in the file to the language you want. It is by default `en_US` and looks as shown below. 
```bash
locale: en_US
```

The preference for language selection is as follows:
 `--locale` parameter during site creation (if passed) **>** `config file`.
