### ISSUE TITLE
Add `ee config` command to setup default configurations

### ISSUE THREAD

**Issue by mrrobot47** [EasyEngine/easyengine#1168]
There is a need for a command to setup configurations for EasyEngine. For example, configuring the default mail-id that should be used for letsencrypt, the default site-type that should be created if no parameter is passed, etc. 

A command to enlist and setup these defaults interactively as well as headlessly for smooth and configured running of EasyEngine is required.

**Comment by mrrobot47** [comment]
Completed in https://github.com/EasyEngine/config-command/pull/1

**Comment by renrayut** [comment]
how to ee request letsencrypt RSA-2048 cos default configure is RSA-4096 bit?

**Comment by mbtamuli** [comment]
@renrayut Please create a new issue for this.
