### ISSUE TITLE
php7 list index out of range

### ISSUE THREAD

**Issue by johnnyvernin** [EasyEngine/easyengine#1169]
Hello guys,

While executing the following command, it fail :

ee site update example.com --php7

> PHP7.0 is experimental feature and it may not work with all plugins of your site.
> You can disable it by passing --php7=off later.
> Do you wish to enable PHP now for example.com?
> Type "y" to continue [n]:y
> Running pre-update checks, please wait...
> Backup location : /var/www/example.com/backup/12Aug2018224749
> Backing up Webroot              [Done]
> Backing up database             [Done]
> Check logs for reason `tail /var/log/ee/ee.log` & Try Again!!!

And the tail logs:

> 2018-08-12 22:47:56,488 (DEBUG) ee : Copying files, Source:/var/www/example.com/htdocs, Dest:/var/www/example.com/backup/12Aug2018224749/htdocs
> 2018-08-12 22:48:24,206 (INFO) ee : [Done]
> 2018-08-12 22:48:24,209 (DEBUG) ee : Config files not found in /var/www/example.com/
> 2018-08-12 22:48:24,210 (INFO) ee : Backing up database
> 2018-08-12 22:48:24,210 (DEBUG) ee : Running command: mysqldump example_com > /var/www/example.com/backup/12Aug2018224749/example_com.sql
> 2018-08-12 22:48:24,411 (DEBUG) ee : Command Output: ,
> Command Error:
> 2018-08-12 22:48:24,412 (INFO) ee : [Done]
> 2018-08-12 22:48:24,412 (DEBUG) ee : list index out of range
> 2018-08-12 22:48:24,413 (INFO) ee : Check logs for reason `tail /var/log/ee/ee.log` & Try Again!!!

Could you help me? Thanks!

> Distributor ID: Debian
> Description:    Debian GNU/Linux 8.10 (jessie)
> Release:        8.10
> Codename:       jessie

> EasyEngine v3.8.1

System Information
- [ X ] lsb_release -a
- [ X ] ee cli version
- [ ] ee cli info
- [ ] wp --allow-root --info

**Comment by kirtangajjar** [comment]
This seems to be a v3 issue. Since we don't support v3 anymore, I'm going to close this issue. We're only planning to give security fixes for v3 till January 2019.
