### ISSUE TITLE
Any option to use SPDY?

### ISSUE THREAD

**Issue by deprito** [EasyEngine/easyengine#117]
SPDY now available for nginx. Any plan to do automatically?

Thanks :)

**Comment by cm896** [comment]
Yes - Love that SPDY is enabled.  Thank you.
FYI - you can check your compliance here:  
https://spdycheck.org/

Also, you might want to add this to the server block to add the HSTS header.
  # config to enable HSTS(HTTP Strict Transport Security) https://developer.mozilla.org/en-US/docs/Security/HTTP_Strict_Transport_Security
  add_header Strict-Transport-Security "max-age=31536000; includeSubdomains;";

Reference Links/Information:
https://scotthelme.co.uk/setting-up-hsts-in-nginx
https://gist.github.com/plentz/6737338
https://raymii.org/s/tutorials/HTTP_Strict_Transport_Security_for_Apache_NGINX_and_Lighttpd.html

**Comment by pnommensen** [comment]
Just add listen 80 spdy; to any server block to enable spdy.

This shouldn't be done. SPDY doesn't use port 80 like regular HTTP does. 

Also, since HTTP/2 will be released soon SPDY will no longer be relevant so I suggest closing this issue, @rahul286.

**Comment by rahul286** [comment]
Closing this as we now have HTTP2 :)
