### ISSUE TITLE
Improve the EE security with adding Fail2Ban

### ISSUE THREAD

**Issue by chiotis** [EasyEngine/easyengine#118]
I was wondering, how possible would be to focus on the security of the LEMP server of EasyEngine by adding Fail2Ban, in the package.

The idea came to me by reading this article http://kovshenin.com/2014/fail2ban-wordpress-nginx/

I am not a security expert. I just think that if EasyEngine focuses more to the security side, it would be a top-notch tool for easy wordpress deployment.

**Comment by adambreen** [comment]
@rahul286 have you made any progress on including fail2ban and ufw? sorry if this is a dumb question, I'm new to EE.

**Comment by rahul286** [comment]
We don't have fail2ban integrated into EE yet. 

In case you want to setup manually, please check https://easyengine.io/tutorials/nginx/fail2ban/

**Comment by rahul286** [comment]
**Update:** closing this as v4 is docker based and we are avoiding any tools that are specific to OS. Users may follow our article above ☝️for manual instructions.
