### ISSUE TITLE
Add labels in network creation

### ISSUE THREAD

**Issue by kirtangajjar** [EasyEngine/easyengine#1189]
EasyEngine follows [label schema](http://label-schema.org/rc1/) notation for labelling containers. i.e. - https://github.com/EasyEngine/dockerfiles/blob/develop/nginx/Dockerfile#L2 Labelling containers helps as we know which containers are created by easyengine and which containers belong to a site.

However, we still don't label networks. we need to add label when doing `docker network create` to identify which networks were created by EasyEngine(will be helpful while deleting them).

Hint: the code change should be done in `easyengine/easyengine` repo.

**Comment by mbtamuli** [comment]
https://docs.docker.com/engine/reference/commandline/network_create/
Docker Documentaton for the same
