### ISSUE TITLE
Enhance self-uninstall

### ISSUE THREAD

**Issue by mrrobot47** [EasyEngine/easyengine#1202]
`ee cli self-uninstall` currently removes all the site, their data, containers etc. Only remaining part is that it does not remove the networks created by EasyEngine. Once the vendor label of EasyEngine is added to the networks by the following PRs:
https://github.com/EasyEngine/easyengine/pull/1192
https://github.com/EasyEngine/site-command/pull/102
https://github.com/EasyEngine/site-wp-command/pull/28

The `self-uninstall` command needs to be updated to accommodate network removals.

**Comment by mbtamuli** [comment]
For removing networks, we need to use this docker command - [docker network prune](https://docs.docker.com/engine/reference/commandline/network_prune/#examples) with filter using the labels we're adding in the above mentioned PRs

**Comment by kirtangajjar** [comment]
Since networks are managed by docker-compose, this issue is now not relevant.
