### ISSUE TITLE
webroot challenge of letsencrypt fails when global auth is enabled

### ISSUE THREAD

**Issue by mrrobot47** [EasyEngine/easyengine#1205]
The path `~/ee-sites/site-name/app/src/.well-known/acme-challenge/` should be excluded from global auth so that letsencrypt webroot challenge can validate the challenge by reading the file in that folder.

**Comment by mbtamuli** [comment]
#### Step 1 
A file `/opt/easyengine/vhost.d/default` should contain the following location block.

```
location ^~ /.well-known/acme-challenge/ {
    auth_basic off;
    allow all;
    root /usr/share/nginx/html;
    try_files $uri =404;
    break;
}
```

This file should be created before acmephp invocation, and removed after acmephp invocation.

#### Step 2
https://github.com/EasyEngine/site-command/blob/b487904942a192727e110788a0241f454f84de2a/src/helper/site-utils.php#L174
This directory needs to be host mounted. `/usr/share/nginx/html:/opt/easyengine/nginx/html`

The acme challenge needs to be created here  - `/opt/easyengine/nginx/html`

Then cleaned up on successful generation of certificates.
