### ISSUE TITLE
Allows creating site without passing site name as parameter

### ISSUE THREAD

**Issue by abhijitrakas** [EasyEngine/easyengine#1217]
When I run  
>`sudo bin/ee site create --prompt`  

this create `http://create ` site. Please check attachment for details.  

![empty-site-name-parameter](https://user-images.githubusercontent.com/26354653/45357420-c9a46d00-b5e3-11e8-8d36-01506963be39.png)

**Comment by mbtamuli** [comment]
This ```--prompt``` command will be removed in v4.0. We might bring it in a later version so adding this issue in later v4.

**Comment by kirtangajjar** [comment]
@mrrobot47 @mbtamuli Moved this issue to maintenance release as we still need to remove `--prompt`.
