### ISSUE TITLE
Add Option to Add HTTP Auth (.htaccess)

### ISSUE THREAD

**Issue by jfschubert** [EasyEngine/easyengine#122]
**Summary added by @rahul286:**

Add `--auth` option like `ee site create example.com --auth` command.
- [ ] only `--auth` will use same HTTP user and password as admin tools
- [ ]  `--auth` with `--httpuser` and `--httppass` will create new HTTP user and password for that site
- [ ] Add above to `ee site update` command as well

---

Please add a Option to enable HTTP Auth Process 
eg.

ee site create example.com --wp --auth
- or -

ee auth create example.com

The First one will create a WP Instance (also changeable with other WP Options)
and the required ".htaccess" Stuff.

The Second one will create Authentifaction Credentials for example.com (and will through an error if the site does not exist). 
Other Commands (e.g the same as the "subcommand" for the "site" command)

enable  -> to enable Authentification (only if was generated Previously)
disable -> to disable Authentification
delete -> to complete Delete Authenification
add ->  to create new Authenfication Credential set  (for n-th user)

Standardusername can  be changed in the Config file like WP Admin Name 
same goes for the Password

**Comment by rahul286** [comment]
Similar to #342

**Comment by rahul286** [comment]
Will be handled in https://github.com/EasyEngine/easyengine/issues/1119
