### ISSUE TITLE
Wrong cache type when using shell command

### ISSUE THREAD

**Issue by renatonascalves** [EasyEngine/easyengine#1221]
System Information
- [x] lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic

- [x] ee cli version
EE 4.0.0-beta.6

- [x] ee cli info
```
+-------------------+----------------------------------------------------------------------------+
| OS                | Linux 4.15.0-30-generic #32-Ubuntu SMP Thu Jul 26 17:42:43 UTC 2018 x86_64 |
| Shell             | /bin/bash                                                                  |
| PHP binary        | /usr/bin/php7.2                                                            |
| PHP version       | 7.2.9-1+ubuntu18.04.1+deb.sury.org+1                                       |
| php.ini used      | /etc/php/7.2/cli/php.ini                                                   |
| EE root dir       | phar://ee.phar                                                             |
| EE vendor dir     | phar://ee.phar/vendor                                                      |
| EE phar path      | /root                                                                      |
| EE packages dir   |                                                                            |
| EE global config  | /opt/easyengine/config.yml                                                 |
| EE project config |                                                                            |
| EE version        | 4.0.0-beta.6                                                               |
+-------------------+----------------------------------------------------------------------------+
```

- [x] wp --allow-root --info
PHP binary:     /usr/local/bin/php
PHP version:    7.2.9
php.ini used:   /usr/local/etc/php/php.ini
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /var/www/htdocs
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 2.0.1

Steps to reproduce the problem:

- Create a site with cache `ee site create site_name --type=wp --cache --le`
- Use CLI, `ee shell site_name`
- Now see which cache is being used. `wp cache type`
- The result should not be `default` as EasyEngine should be using Redis.

**Comment by renatonascalves** [comment]
Actually, I'm not sure if it is a bug on EasyEngine or WP CLI because of the shell. But I presume the value there should not be default.

**Comment by kirtangajjar** [comment]
@renatonascalves I've looked into it and [what wp-cli does is](https://github.com/wp-cli/cache-command/blob/master/src/Cache_Command.php) [it checks if there are specific plugins](https://github.com/wp-cli/wp-cli/blob/master/php/utils-wp.php#L249) (like wp-redis ) and shows output based in that. Currenly we have haven't added any object cache plugin, but based on [this issue](https://github.com/EasyEngine/easyengine/issues/1082#issuecomment-421244887), we'll soon add `wp-redis` by default. 

For now you can follow following manual steps to enable redis cache in wp - 
```bash
ee shell <sitename>
wp plugin install wp-redis
wp plugin activate wp-redis
wp redis enable
vim wp-content/plugins/wp-redis/object-cache.php (search for 127.0.0.1 and replace it with redis)
```

After this if you type `wp cache type`, you'll see output `Redis`.

**Comment by renatonascalves** [comment]
@kirtangajjar Question!

What exactly does `--cache` do if no install the redis cache?

**Comment by rahul286** [comment]
> vim wp-content/plugins/wp-redis/object-cache.php (search for 127.0.0.1 and replace it with redis)

This is the wrong way. You shouldn't edit plugin files but do install as per 

@renatonascalves please follow setup instruction here https://github.com/pantheon-systems/wp-redis#installation

Please use `redis` instead of `127.0.0.1`.  `redis` is hostname for redis-server.

**Comment by renatonascalves** [comment]
@rahul286 Thanks! I'm not against installing it manually, I'm more concerned about the expectation of such a cache.

If the flag `---cache` exists, one would expect a cache to be installed. In the past, I don't remember the issue, it was debated and chosen redis for the default cache.

So I presumed that EasyEngine would install it automatically. So is it something EE will do in the future or my expectations are wrong?

**Comment by renatonascalves** [comment]
@kirtangajjar Understood. I was under the impression the redis object cache would come by default, not page cache.

Thanks for the feedback.

**Comment by rahul286** [comment]
@renatonascalves 

> If the flag ---cache exists, one would expect a cache to be installed. In the past, I don't remember the issue, it was debated and chosen redis for the default cache.

Your expectation is correct. `wp-redis` should be installed and configured automatically when a `ee site create --wp` is run with `--cache` flag.

This is a bug.

**Comment by renatonascalves** [comment]
@rahul286 Got it! Thanks again! Will continue testing the current RC. :)

**Comment by poshtone-cs** [comment]
@rahul286 this site install cache flag and subsequent lack of cache related features backend confused me too, in the past an install with cache had a cache plugin installed and we could clear cache from backend of wp. new installs on v4 as of today do not. i will try the [manual install ](https://github.com/pantheon-systems/wp-redis#installation)

**Comment by mbtamuli** [comment]
`--cache` implementation is broken currently.

Closing this issue in favor of https://github.com/EasyEngine/site-type-wp/issues/50
