### ISSUE TITLE
Getting error in health-check plugin: A plugin has prevented updates by disabling wp_version_check()

### ISSUE THREAD

**Issue by kirtangajjar** [EasyEngine/easyengine#1225]
Following error is shown after installing plugin - 
https://github.com/WordPress/health-check

![6upy4h](https://user-images.githubusercontent.com/8456197/45750464-c71dc500-bc2c-11e8-8edc-5b1fe72041a8.jpg)

**Comment by rahul286** [comment]
@kirtangajjar better paste WordPress logs.

**Comment by mrrobot47** [comment]
Closing this issue as it has been fixed in https://github.com/EasyEngine/site-type-wp/pull/48
