### ISSUE TITLE
Controlling nginx and other Modules

### ISSUE THREAD

**Issue by sagargulati** [EasyEngine/easyengine#1229]
This issue tracker is only for issues related to EasyEngine. Please use http://community.rtcamp.com/c/easyengine for support questions.

If you feel the issue is an EasyEngine core specific issue, please attach the output of the following commands.

System Information
```
- [ ] lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial
```

```
- [ ] ee cli version
EE 4.0.0-beta.6
```

```
- [ ] ee cli info
+-------------------+------------------------------------------------------------------------------------+
| OS                | Linux 4.15.0-29-generic #31~16.04.1-Ubuntu SMP Wed Jul 18 08:54:04 UTC 2018 x86_64 |
| Shell             | /bin/bash                                                                          |
| PHP binary        | /usr/bin/php7.2                                                                    |
| PHP version       | 7.2.9-1+ubuntu16.04.1+deb.sury.org+1                                               |
| php.ini used      | /etc/php/7.2/cli/php.ini                                                           |
| EE root dir       | phar://ee.phar                                                                     |
| EE vendor dir     | phar://ee.phar/vendor                                                              |
| EE phar path      | /root                                                                              |
| EE packages dir   |                                                                                    |
| EE global config  | /opt/easyengine/config.yml                                                         |
| EE project config |                                                                                    |
| EE version        | 4.0.0-beta.6                                                                       |
+-------------------+------------------------------------------------------------------------------------+
```

---
Unlike the stable version, I see the 4.0.x version is completely re-written, can you tell me how do we control the PHP version, generating MySQL database config or a database for each site and putting nginx with it? I see no stack option in it.
Also, when I added a site `"ee site create mysite.com --type=php"` what I'm getting is a 503 error.

**Comment by kirtangajjar** [comment]
@sagargulati Sorry at the time you asked the question, we didn't have much documentation around v4. Now we have documented much of it. Have a look at our [release blog post](https://easyengine.io/blog/v4-first-stable-release/) and have a look at the documentation section linked there. I think it would answer most of your questions.

I'm closing this issue for now. In case you still have more questions, you can ask them in our [community forum](https://community.easyengine.io). We use GitHub issue tracker only for tracking issues or feature request of EasyEngine. General questions like this are better suited in the community forum.
