### ISSUE TITLE
In v4, move FPM config to host machine and mount as a volume

### ISSUE THREAD

**Issue by devbhosale** [EasyEngine/easyengine#1230]
Feature Request. 

In v4 beta 6, I noticed that nginx config resides on the host and is mounted as a volume to docker container. However, same thing is not done for PHP FPM configs. 

i suggest moving this config outside the container and mounting it to corresponding directory per container.

**Comment by michacassola** [comment]
Will this not be in the ee-admin area @rahul286 ?

I dont care where the configs are as long as I can change them permanently in an easy way (and per site).

**Comment by rahul286** [comment]
As far as I know, you can always override PHP INI config per directory basis http://php.net/manual/en/configuration.file.per-user.php

Still, the intention is to mount all config related to a site the way we mapped Nginx config. So this will be taken care.

Thanks @devbhosale for testing and reporting the issue. 🙏

**Comment by kirtangajjar** [comment]
@devbhosale This issue has been fixed in v4.0 and all PHP configs are mounted on the host 🎉.
