### ISSUE TITLE
Significant Bug (beta6) - Page Caching Persists across sites, even after site is deleted

### ISSUE THREAD

**Issue by devbhosale** [EasyEngine/easyengine#1237]
Version: EE 4.0.0-beta.6

Steps to reproduce:
1. Create first site site1 ( i used  sudo ee site create ee1.mydomain.com --ssl=le  --wpredis )
2. Create second site site2 ( i used  sudo ee site create ee2.mydomain.com --ssl=le  --wpredis )

Then, I brought site2 down. I could still see that going to ee2.mydomain.com returned a valid page.
Confused. I deleted second site. Visted, ee2.mydomain.com and then page was still returned.

However, going to ee2.mydomain.com was actually returning ee1.mydomain.com  (see the screenshot)

https://imgur.com/a/IbvNiCb

It was a redis page cache HIT. 

First issue:
1. Irrespective of a site status (delete/down), going to one site (site2) should not return any data from another site (site1). 
   
 Are you using site domain as a one of the redis cache key? Not sure if nginx-helper plugin uses it as well but might be worth to look into it as well.

Second issue:
2. Cache should be purged on deletes and/or down. 

Following http headers were observed:.
x-srcache-fetch-status: HIT
x-srcache-store-status: BYPASS

**Comment by mbtamuli** [comment]
https://github.com/EasyEngine/site-type-wp/blob/9718ccf780973911b9de28a48b2246f52d3de67a/src/WordPress.php#L283

https://github.com/EasyEngine/site-type-wp/blob/9718ccf780973911b9de28a48b2246f52d3de67a/templates/config/nginx/main.conf.mustache#L52

@sagarnasit The string `nginx-cache:` should be replaced with `$salt_value`, that is `$this->site_data['site_url'] . ':';`

**Comment by mbtamuli** [comment]
1. Need to add 

```
        aliases:
          - ${VIRTUAL_HOST}_php
```
to the PHP service's network `global-backend-network` in `docker-compose.yml`. Similar for nginx service.

2. Need to edit
`php:9000` with `$site_name_php:9000` in
`/opt/easyengine/sites/example.com/config/nginx/main.conf`
