### ISSUE TITLE
Config root: /opt/easyengine is not writable by EasyEngine

### ISSUE THREAD

**Issue by devbhosale** [EasyEngine/easyengine#1238]
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic

sudo ee cli version
EE 4.0.0-beta.6

Should non-root ( e.g. sudoers) users be able to run ee commands?

I see following error while running as a user command:
 ee cli version
Error: Config root: /opt/easyengine is not writable by EasyEngine

If you feel the issue is a EasyEngine core specific issue, please attach the output of the following commands.

System Information
- [ ] lsb_release -a
- [ ] ee cli version
- [ ] ee cli info
- [ ] wp --allow-root --info

**Comment by mrrobot47** [comment]
EasyEngine v4 for now needs administrative access, i.e., you can run EasyEngine using:

1. Root account or
2. Using `sudo` command with a non-root user. (e.g., `sudo ee cli version`)

This will go into documentation before release.

**Comment by mbtamuli** [comment]
@kirtangajjar Please check this and any other issue mentioned with `kind/docs` label.

**Comment by kirtangajjar** [comment]
Closing this issue as we've documented it in README itself.

**Comment by mbtamuli** [comment]
> Note: :warning: EasyEngine will currently only run with root privileges. You can run ee help, ee help site and ee help site create to get all the details about the various commands and subcommands that you can run.

Source: https://github.com/EasyEngine/easyengine/blob/v4.0.0/README.md#usage

**Comment by esa1975** [comment]
Sorry to comment on an old, closed issue but I still get this error when trying to use tab completion with sudo on Ubuntu 18.04 server. I don't see anything in this issue or the readme that accounts for this or a way to work around it. If tab completion isn't supported when using sudo so be it but it's confusing if that's the case and you don't state that. That said, thanks for all the hard work on this. It's a fantastic toolkit that makes my life much easier.

**Comment by swissbuechi** [comment]
> Sorry to comment on an old, closed issue but I still get this error when trying to use tab completion with sudo on Ubuntu 18.04 server. I don't see anything in this issue or the readme that accounts for this or a way to work around it. If tab completion isn't supported when using sudo so be it but it's confusing if that's the case and you don't state that. That said, thanks for all the hard work on this. It's a fantastic toolkit that makes my life much easier.

I noticed exactly the same behavior.
This is not really a problem of ee.
Evalated permissions from "sudo" are only applied if you press enter.

**Comment by iamahmedshahh** [comment]
Hello I am unable to remove EE and even when searching folder I am unable to manually delete the EE folder?

```
ahmed@ahmed-HP-ProBook-430-G1:~$ sudo ee cli self-uninstall
Are you sure you want to remove EasyEngine and all its sites(along with their data)?
This is an irreversible action. No backup will be kept. [y/n] y
Error: could not find driver
ahmed@ahmed-HP-ProBook-430-G1:~$ 
```
