### ISSUE TITLE
in beta-6 include custom nginx conf

### ISSUE THREAD

**Issue by devbhosale** [EasyEngine/easyengine#1241]
the default.conf file which is mounted as a volume does not include files user supplied custom nginx conf. 
Unless the file is included with something like "include  DIRECTORY/*.conf" custom configs will not be included.

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 18.04.1 LTS
Release: 18.04
Codename: bionic

sudo ee cli version
EE 4.0.0-beta.6

**Comment by mrrobot47** [comment]
Closing this issue as it has been fixed.
