### ISSUE TITLE
PHP SOAP Client Package is not installed on the docker image in the v4 beta 6

### ISSUE THREAD

**Issue by aksuited** [EasyEngine/easyengine#1245]
I originally brought this issue up on the support forums and it was suggested I post the issue here as per: https://community.easyengine.io/t/ee-v4-beta-6-any-docs-available-php-soap-package-missing-how-can-i-add-for-testing/11203

The PHP SOAP Client Package is not installed on the docker image in the v4 beta 6 release and users can not add it.   The SOAP Client is required by many Wordpress and Woocommerce Plugins.

> If you feel the issue is a EasyEngine core specific issue, please attach the output of the following commands.
> 
> System Information
> - [ ] lsb_release -a
> - [ ] ee cli version
> - [ ] ee cli info
> - [ ] wp --allow-root --info

`root:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic

root:~# ee cli version
EE 4.0.0-beta.6

root:~# ee cli info
+-------------------+----------------------------------------------------------------------------+
| OS                | Linux 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 |
| Shell             | /bin/bash                                                                  |
| PHP binary        | /usr/bin/php7.2                                                            |
| PHP version       | 7.2.11-1+ubuntu18.04.1+deb.sury.org+1                                      |
| php.ini used      | /etc/php/7.2/cli/php.ini                                                   |
| EE root dir       | phar://ee.phar                                                             |
| EE vendor dir     | phar://ee.phar/vendor                                                      |
| EE phar path      | /root                                                                      |
| EE packages dir   |                                                                            |
| EE global config  | /opt/easyengine/config.yml                                                 |
| EE project config |                                                                            |
| EE version        | 4.0.0-beta.6                                                               |
+-------------------+----------------------------------------------------------------------------+

root:~# wp --allow-root --info
wp: command not found
`

**Comment by kirtangajjar** [comment]
Closing this issue as it has been fixed in https://github.com/EasyEngine/dockerfiles/pull/35
