### ISSUE TITLE
EEv4 - ee help discrepancies

### ISSUE THREAD

**Issue by miloszorica** [EasyEngine/easyengine#1249]
I've bumped into some ee help discrepancies between the instructions and actual command syntax.

For example:

`ee config set le-mail='abc@example.com'`

while the actual syntax is

`ee config set le-mail abc@example.com`

How can I contribute to fixing help and writing documentation?

**Comment by mbtamuli** [comment]
Sure you can help. :+1:  Can you please mention a few details so I can guide you.
1. Which release of EasyEngine v4 are you using? You can check using ```ee cli version```
2. Where did you find the instructions that you mention?

**Comment by mbtamuli** [comment]
You'd have to edit this line - https://github.com/EasyEngine/config-command/blob/853a265ab424b55ba6811c7318919c25b00a44e9/src/Config_Command.php#L62 to fix this.

But if you take a look at this PR, https://github.com/EasyEngine/config-command/pull/2/files you will see it has already been merged. Now you just have to wait for the next release. Please report any other issue you find and try to send a PR next time. :+1:

**Comment by miloszorica** [comment]
Thanks!
