### ISSUE TITLE
Your connection is not secure

### ISSUE THREAD

**Issue by rromanv** [EasyEngine/easyengine#1257]
I just created a wordpress site with v3, enabled ssl anf got this error:

Your connection is not secure

The website tried to negotiate an inadequate level of security.

SITE-URL-HERE uses security technology that is outdated and vulnerable to attack. An attacker could easily reveal information which you thought to be safe. The website administrator will need to fix the server first before you can visit the site.

Error code: NS_ERROR_NET_INADEQUATE_SECURITY

System Information
- No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

- OS:	Linux 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64
Shell:	/bin/bash
PHP binary:	/usr/bin/php5.6
PHP version:	5.6.38-2+ubuntu18.04.1+deb.sury.org+1
php.ini used:	/etc/php/5.6/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/root
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version:	1.5.1

**Comment by lanceloti** [comment]
Thanks!

**Comment by kirtangajjar** [comment]
Closing this issue as it seems v3 specific. If the issue is still not solved, you can ask for support in our community forum - https://community.easyengine.io/
