### ISSUE TITLE
Ensure parity between code and docker images.

### ISSUE THREAD

**Issue by mbtamuli** [EasyEngine/easyengine#1262]
Currently there is no parity between the code and the Docker images. We can do the following changes

Branching for EasyEngine v4.

Release tags    - public usage.                     `easyengine.phar`
Master branch   - stable at all times.              `easyengine-nightly.phar`
Develop branch  - may have code that breaks things. `easyengine-edge.phar`

Docker image tags.
( Will be built from EasyEngine/dockerfiles repo )

`easyengine/php:<semver>`     - Tagged separately from EasyEngine. Used by `easyengine.phar`.
`easyengine/php:nightly`      - Built from master branch. Used by `easyengine-nightly.phar`. Works consistently with easyengine-nightly.phar.
`easyengine/php:edge`         - Built from develop branch. Used by `easyengine-edge.phar`. The Docker image may have inconsistency with the phar.

For release tag(default):   `ee cli update [--stable]`
For master code:            `ee cli update --nightly`
For develop code:           `ee cli update --edge`

We'll also pin the docker image with the image digest.
We can put this in the CI,
```
docker pull easyengine/php:v4.0.0-beta.6
docker inspect --format='{{index .RepoDigests 0}}' easyengine/php:v4.0.0-beta.6
```
The output will be a hash like
`easyengine/php@sha256:29934af957c53004d7fb6340139880d23fb1952505a15d69a03af0d1418878cb`

**Comment by mrrobot47** [comment]
Need to remove `-nightly` tagged images from EasyEngine nightly builds completely. Docker images will have their own versioning independent of EasyEngine versioning.
