### ISSUE TITLE
Redis and nginx helper wordpress plugins not installed

### ISSUE THREAD

**Issue by b167er** [EasyEngine/easyengine#1263]
I created a new site with the flags type=wp and --cache, and the plugins for redis and nginx are not installed. If I manually install the plugins, redis plugin shows that it is not connected to the redis server. The nginx helper plugin is also not connecting to nginx after I've manually installed it. I have tried clearing the cache (via the nginx plugin), to no success. I tried both settings (fastcgi & redis modes). I have tested this by enabling maintenance mode on the website, and after clearing my browser cache I am still seeing the website. So it seems that redis cache is indeed running, but I am unable to communicate with it via both plugins due to a configuration error.

How do I find the hostname, port and prefix used by redis on easyengine 4?

**Comment by b167er** [comment]
I now have redis working by following these steps:

`ee shell mysite.com.au
wp plugin install wp-redis
wp plugin activate wp-redis
wp redis enable
vim wp-content/plugins/wp-redis/object-cache.php (search for 127.0.0.1 and replace it with redis)`

I still needed to flush the cache, so after this I entered the command `wp cache flush` and now I can see my site is coming up in maintenance mode.

**Comment by mrrobot47** [comment]
@b167er thank you for reporting this issue. `--cache` is not working properly with `beta.6` version. It has been reported and properly fixed, [in this issue](https://github.com/EasyEngine/site-type-wp/issues/50).
With the new fix, it will automatically install and setup the redis as well as nginx-helper plugin with proper configurations. It will be available soon in the next release.

As far as the preference for shell editor goes, there has been an enhancement in the `https://github.com/EasyEngine/shell-command/issues/2`. So, from the next release, you'll be able to use `ee shell <site-name> --user=root` and drop into the the shell with root user and be able to install nano or whatever you prefer.
