### ISSUE TITLE
MySQL website creation

### ISSUE THREAD

**Issue by miloszorica** [EasyEngine/easyengine#1264]
When I execute ee site create domain --type=php, MySQL doesn't get installed. In v3 you could easily have a MySQL site created by ee site create domain --mysql . How do I go about in v4?

**Comment by mrrobot47** [comment]
Until the documentation is completely prepared and launched, you can use `ee help <command-name>` or `ee help <command-name> <sub-command-name>`, in your case you can use `ee help site create --type=php`. 

Specifically in your case, passing additional flag [--with-db](https://github.com/easyengine/site-type-php#usage) will create MySql database for your php site.
