### ISSUE TITLE
wpcacheWarning: There was some error in docker-compose up and wpcachePHP: command not found

### ISSUE THREAD

**Issue by baiyuanlab** [EasyEngine/easyengine#1271]
ee cli
#ee site create wpcache.baiyuan.cloud --type=wp --cache

Warning notice as follows
```
wpcacheWarning: There was some error in docker-compose up.
Warning: Initiating clean-up.
[wpcache.baiyuan.cloud] site root removed.
PHP Notice:  Trying to get property 'cache_host' of non-object in phar:///usr/local/bin/ee/vendor/easyengine/site-command/src/helper/hooks.php on line 56
Site wpcache.baiyuan.cloud deleted.
root@ip-172-31-63-5:/home/ubuntu# wpcachePHP Notice:  Trying to get property 'cache_host' of non-object in phar:///usr/local/bin/ee/vendor/easyengine/site-command/src/helper/hooks.php on line 56
wpcachePHP: command not found

```

System Information
- [x] lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic

- [x] ee cli version
EE 4.0.0-rc.1

- [x] ee cli info
+-------------------+--------------------------------------------------------------------------+
| OS                | Linux 4.15.0-1019-aws #19-Ubuntu SMP Fri Aug 10 09:34:35 UTC 2018 x86_64 |
| Shell             | /bin/bash                                                                |
| PHP binary   | /usr/bin/php7.2                                                          |
| PHP version  | 7.2.11-3+ubuntu18.04.1+deb.sury.org+1                                    |
| php.ini used  | /etc/php/7.2/cli/php.ini                                                 |
| EE root dir       | phar://ee.phar                                                           |
| EE vendor dir     | phar://ee.phar/vendor                                                    |
| EE phar path      | /home/ubuntu                                                             |
| EE packages dir   |                                                                          |
| EE global config  | /opt/easyengine/config/config.yml                                        |
| EE project config |                                                                          |
| EE version        | 4.0.0-rc.1                                                               |
+-------------------+--------------------------------------------------------------------------+

- [x] wp --allow-root --info
wp: command not found

**Comment by kirtangajjar** [comment]
Closing issue as stale
