### ISSUE TITLE
Errors while installing ee4-rc1

### ISSUE THREAD

**Issue by fikret** [EasyEngine/easyengine#1273]
After clear ubuntu installition. I run `wget -qO ee rt.cx/ee4 && sudo bash ee`
command. 
I took some errors while installing ee4-rc1

```
 5050K .......... .......... .......... .......... .......... 99% 39.4M 0s
  5100K .......... .......... ...                             100% 36.7M=0.4s

2018-11-06 00:55:11 (13.0 MB/s) - ‘/usr/local/bin/ee’ saved [5245983/5245983]

Checking/Pulling required images
**Error: Errors were encountered while processing: 20181016052850_easyengine_insert_docker_images_version.php**
**Unable to pull easyengine/cron:v4.0.0-rc.1. Please check logs for more details.**
```

syslog:
```
Nov  6 00:53:58 wpokulu systemd[1]: Starting Cleanup of Temporary Directories...
Nov  6 00:53:58 wpokulu systemd-tmpfiles[10926]: [/usr/lib/tmpfiles.d/var.conf:14] Duplicate line for path "/var/log", ignoring.
Nov  6 00:53:58 wpokulu systemd[1]: Started Cleanup of Temporary Directories.
**Nov  6 00:55:25 wpokulu dockerd[4052]: time="2018-11-06T00:55:25.562330621+03:00" level=error msg="Not continuing with pull after error: error pulling image configuration: Get https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/00/00af70907ec0bd6c8399356df6f64d7a3af192286904c7695bb0eeaa64ce7587/data?verify=1541457915-uYBbLsyKwQubn4Egc55HpYjtunc%3D: net/http: TLS handshake timeout"**
```

If you feel the issue is a EasyEngine core specific issue, please attach the output of the following commands.

System Information

Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial

**Comment by fikret** [comment]
I found solution here https://serverfault.com/a/928164 
This problem reason is TLS handshake and it is related MTU size.
I canged MTU size to 1300
`ip link set dev **eth0** mtu 1300
/etc/init.d/networking restart `
After that I installed EE4-rc1 succesfully.

**Comment by mbtamuli** [comment]
@fikret We've not seen this issue and we have tried RC.1 on AWS and DIgitalOcean.
Could you please mention the details about your machine?

1. Which cloud provider were you using?
2. What is the kernel version?

**Comment by fikret** [comment]
Hello @mbtamuli ,
I use a vps server on my dedicate machine. 
Kernel version : 4.4.0-131-generic
