### ISSUE TITLE
Problem with letsencrypt 

### ISSUE THREAD

**Issue by rsmith4321** [EasyEngine/easyengine#1279]
I don’t know if I’m doing something wrong, but I get the following error when trying to create a letsencrypt site.

Starting SSL verification. Warning: Server error: GET http://www.ryansmithphotography.com/.well-known/acme-challenge/WrdruVilRxBxS-Kltt1jHn4sckeOM12I1zwMziVS_Iw resulted in a 521 Origin Down response: <!DOCTYPE html> <!–[if lt IE 7]> <html class=“no-js ie6 oldie” lang=“en-US”> <![endif]–> <!–[if IE 7]> <html class (truncated…)

It seems to me the problem is it’s trying to get a http address, but this isn’t possible my site has hsts on it’s not going to allow a http connection.

**Comment by b167er** [comment]
You could create a 301 redirect to redirect all http to https?

**Comment by rsmith4321** [comment]
No I'm testing EEV4 RC1 on a new Ubuntu 18.04 VM.  My site is running behind cloudflare so it automatically redirects http to https.  I'm familiar with configuring this with EE3 but was testing EE4 and got this error, I think I will have to wait for docs on EE4 because I assume I can't just edit nginx.conf like I could with EE3.  I can try it with the --wildcard flag and see.

**Comment by kirtangajjar** [comment]
Hey @rsmith4321, [EasyEngine v4 has been released](https://easyengine.io/blog/v4-first-stable-release/). Can you try to create a site with it and let us know if the issue is still there?

**Comment by rsmith4321** [comment]
I tried it with the wildcard option and it worked fine, I could just add the verification to my dns.  I haven't tried it again without the wildcard.
