### ISSUE TITLE
Isolate website folders

### ISSUE THREAD

**Issue by lutfuahmet** [EasyEngine/easyengine#1285]
Hi,

Is there any plan isolate website folders?

Because if one of websites has malicious script, it is going to infecting other sites. I faced up multiple times. May be you should use docker upcoming releases.

**Comment by kirtangajjar** [comment]
@lutfuahmet We've built v4 around Docker. In v4, all sites have their own PHP and Nginx containers which provides some level of isolation and ensures malicious script on one site do not affect other sites.

You can read our [blog post](https://easyengine.io/blog/v4-first-stable-release/) if you want to know more about v4.
