### ISSUE TITLE
Install script and alternative not working

### ISSUE THREAD

**Issue by michacassola** [EasyEngine/easyengine#1290]
Using the install script or the alternative two commands both don't work in my sudo environment.
Please add support to install through sudo... in the final version.

**Comment by mbtamuli** [comment]
@michacassola Can you please clarify what you mean by _sudo environment_?

**Comment by michacassola** [comment]
First step for me always is to run my security hardening bash script when I first spin up a server. It includes changing the user from root to something else so all I can do from that point forward is to sudo. Please make it possible to use your install script through sudo in the release.

**Comment by kirtangajjar** [comment]
@michacassola Can let us know if the issue still persists with v4 stable?

In case the issue still persists, let us know additional details like 
* Command executed and it's output, 
* Output of `lsb_release -a`
* Output of `/opt/easyengine/logs/install.log`(if it exists)

**Comment by michacassola** [comment]
Issue has been resolved in the latest version. Thank you very much!
