### ISSUE TITLE
Brew Formula for Mac 

### ISSUE THREAD

**Issue by rahul286** [EasyEngine/easyengine#1291]
On Mac, we can make installation easier and familiar with:

```
brew install easyengine
```

Please refer - https://github.com/Homebrew/homebrew-core/blob/master/Formula/wp-cli.rb

**Comment by PatelUtkarsh** [comment]
Once we have phar release compatible with Mac we can do this.

**Comment by mbtamuli** [comment]
Also need to check how to add dependencies.
We need these php extensions - https://github.com/EasyEngine/installer/blob/master/setup.sh#L56

**Comment by PatelUtkarsh** [comment]
https://gist.github.com/PatelUtkarsh/035fe5f6257398f114a8f524f6f3f03a Waiting for https://github.com/EasyEngine/easyengine/pull/1298 and release for Mac.

**Comment by mbtamuli** [comment]
On a brand new MacOS machine, I needed to
```
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew install php
brew cask install docker
# Manually start docker
wget -O /usr/local/bin/ee https://raw.githubusercontent.com/EasyEngine/easyengine-builds/master/phar/easyengine.phar
chmod +x /usr/local/bin/ee
```

**Comment by PatelUtkarsh** [comment]
@mbtamuli Did you try with default osx php? 
>brew install php

**Comment by mbtamuli** [comment]
@PatelUtkarsh Yes
> default osx php

The default one was php7.1 and didn't have the `pcntl` extension

**Comment by rahul286** [comment]
@mbtamuli as brew formula is now merged, I am closing this.
