### ISSUE TITLE
EasyEngine v3 to v4 Migration Script - 404 Not Found

### ISSUE THREAD

**Issue by joelcieslar** [EasyEngine/easyengine#1304]
While this issue isn't pertinent to the EasyEngine product itself, the documentation on easyengine.io references the following command to upgrade from v3 to v4:

`wget -o migrate.sh https://rt.cx/ee3to4 && chmod +x migrate.sh`

However, the URL `https://rt.cx/ee3to4` which redirects to `https://raw.githubusercontent.com/easyengine/installer/master/migration/migrate.sh` results in a 404 Not Found error.

This is the documentation page in question:

https://easyengine.io/handbook/v3-to-v4-migration/script/

**Comment by ovidiubica** [comment]
Looks like [migration script](https://github.com/EasyEngine/installer/pull/16) is still WIP ...

**Comment by mbtamuli** [comment]
@joelcieslar @ovidiubica The PR has been merged. Closing this issue for now. If you face any further problems, you can create a new issue.
