### ISSUE TITLE
SSL bug?

### ISSUE THREAD

**Issue by buzucan** [EasyEngine/easyengine#1305]
Take a look in the first image, I have this error.
![image](https://user-images.githubusercontent.com/8757017/48928601-75720f00-eee9-11e8-9cc0-6ee3bef671b8.png)
![image](https://user-images.githubusercontent.com/8757017/48928609-8458c180-eee9-11e8-8ac4-873c790a573f.png)
![image](https://user-images.githubusercontent.com/8757017/48928613-8c186600-eee9-11e8-8451-2762e523d729.png)
![image](https://user-images.githubusercontent.com/8757017/48928620-963a6480-eee9-11e8-9c0b-27b801258cc7.png)
![image](https://user-images.githubusercontent.com/8757017/48928627-9fc3cc80-eee9-11e8-964a-8e1bef4a490a.png)

This issue tracker is only for issues related to EasyEngine. Please use http://community.rtcamp.com/c/easyengine for support questions.

If you feel the issue is a EasyEngine specific issue, please attach the output of the following commands.

System Information
- [ ] ee cli info
- [ ] lsb_release -a
- [ ] docker version
- [ ] docker-compose version

**Comment by kirtangajjar** [comment]
@buzucan Which command did you use to create the site?

**Comment by kirtangajjar** [comment]
In that case, you don't need to run `ee site ssl`. You need to run `ee site ssl` only if you've used `--wildcard` flag during site create.

Running below command should create a SSL site for you. You don't need to run `ee site ssl` after it.
```
ee site create yamasha.info --type=wp --ssl=le
```

**Comment by buzucan** [comment]
i understand. after I reinstalled all is fine. i think there was a problem with DNS and letsencrypt server.

**Comment by mrrobot47** [comment]
Closing as it has been resolved.
