### ISSUE TITLE
Add custom PHP modules to a site

### ISSUE THREAD

**Issue by buzucan** [EasyEngine/easyengine#1313]
In V3 with sudo apt-get install php-intl I was able to install intl extension, but now, with V4 and docker I don't know how to enable this.
Can you help us?

I read documentation from here but it doesn't help.

**Comment by buzucan** [comment]
when i try to use shell (docker-php-ext-install intl) for specific site i recieve this error
![image](https://user-images.githubusercontent.com/8757017/48969083-fae8e280-f001-11e8-9652-691c82e32bfd.png)

**Comment by buzucan** [comment]
i found an installer for intl maybe it will be standard in V4 https://github.com/prooph/docker-files

**Comment by buzucan** [comment]
I really need intl for my plugins so... I`m looking for a solution. :)

**Comment by mbtamuli** [comment]
@buzucan As a temporary measure, you can run the `docker-php-ext-install` command as root. (https://easyengine.io/commands/shell/)

```ee shell example.com --user=root```

**Comment by buzucan** [comment]
it worked. thanks :)

**Comment by buzucan** [comment]
btw, after that i`ve installed admin tools and i`ve removed. Then the php intl was removed, too. :)

**Comment by gabrielwohlfart** [comment]
I also need the intl extension.
I liked the suggestion to add it in the core

**Comment by pserafini** [comment]
yes please. All Prestashop (and many other Ecommerce solutions)users will need intl + Mysql PDO
Please make this happen in core :)

**Comment by CryptoDragonLady** [comment]
Why not have dockerfiles for each core component so custom additions can be made and retained through container rebuilds?

**Comment by kirtangajjar** [comment]
@CryptoDragonLady @pserafini @gabrielwohlfart This can be now done with custom docker compose feature added in v4.2.0. Please check https://easyengine.io/blog/easyengine-v4-2-0-released/ and https://easyengine.io/handbook/customising-docker-compose-stack-in-easyengine-v4/

**Comment by steve231293** [comment]
Hello @kirtangajjar 
Could you give me details instuctions how to install an PHP extension with custom docket added in EE 4.2.0?

**Comment by ry167** [comment]
I wrote on how to add PHP extensions/modules here: https://github.com/EasyEngine/easyengine/issues/1419#issuecomment-1884089199
