### ISSUE TITLE
installation error v4 stable

### ISSUE THREAD

**Issue by eddr** [EasyEngine/easyengine#1314]
OS: Fresh Debian 9 64 install (vultr image)

the command : "wget -qO ee https://rt.cx/ee4 && sudo bash ee"
Attached the third attempt. First attempt failed on "sudo" not existing in the fresh install.

1. There is an error reading the sources file due to "----->" phrase at the beginning of the line
"E: Type '----->' is not known on line 1 in source list /etc/apt/sources.list.d/php.list
E: The list of sources could not be read."
removing it manually and running the script again results in this error again.

2. Then, the installation continues and finally I get this error:
"/usr/bin/env: ‘php’: No such file or directory"

and can't really operate ee.

[output.txt](https://github.com/EasyEngine/easyengine/files/2613012/output.txt)

**Comment by mbtamuli** [comment]
@eddr This has been fixed.
You can run the script again and it should work.

**Comment by eddr** [comment]
Indeed works now, thanks.

However, creating WP site results in an error (same fresh installation):

**command** : ee site create earlybirds.info --type=wp --ssl=le

Checking and Pulling required images. This may take some time.
Checking and Pulling docker image easyengine/cron:v4.0.0
v4.0.0: Pulling from easyengine/cron
Digest: sha256:db18187c93b754b84cba7a0cb4c68c0eb6d92d5861e0ecd4f4af3ad3ebf5d265
Status: Image is up to date for easyengine/cron:v4.0.0
Checking and Pulling docker image easyengine/mailhog:v4.0.0
v4.0.0: Pulling from easyengine/mailhog
Digest: sha256:f9fed10b479d2d6892ca93c90d1313f3370c1fb290e0dae03d1deb7e0f627486
Status: Image is up to date for easyengine/mailhog:v4.0.0
Checking and Pulling docker image easyengine/mariadb:v4.0.0
v4.0.0: Pulling from easyengine/mariadb
Digest: sha256:acabff937931c5cb24f96f5f0058c4122a8d077d61b944fed990a9f24052584e
Status: Image is up to date for easyengine/mariadb:v4.0.0
Checking and Pulling docker image easyengine/nginx-proxy:v4.0.0
v4.0.0: Pulling from easyengine/nginx-proxy
Digest: sha256:84926045c7749fae3ef6df7d16d0eb0a6801412a506a5097ccbc516bc56b93f7
Status: Image is up to date for easyengine/nginx-proxy:v4.0.0
Checking and Pulling docker image easyengine/nginx:v4.0.0
Error response from daemon: error parsing HTTP 404 response body: invalid character 'p' after top-level value: "404 page not found\n"
Error: Errors were encountered while processing: 20181016052850_easyengine_insert_docker_images_version.php
Unable to pull easyengine/nginx:v4.0.0. Please check logs for more details.

**Comment by mrrobot47** [comment]
@eddr can you try this again. The issue you faced was not related to EasyEngine. [DockerHub API was down and there was a partial outage](https://github.com/docker/hub-feedback/issues/1693).

It is fully operational and back online: https://status.docker.com/

Closing the issue for now. If you face any other issue while installation, feel free to re-open.

**Comment by eddr** [comment]
Thanks. Works.

**Comment by codente** [comment]
I'm getting this same issue with Ubuntu 16.04  

```-----> Pulling EasyEngine docker images
-----> Pulling EasyEngine docker images
/usr/bin/env: 'php': No such file or directory```

I only tried 16.04 because I thought 18 was not supported.

**Comment by codente** [comment]
Still seeing this issue with Ubuntu 16.04 on UpCloud server
