### ISSUE TITLE
Error when running cron

### ISSUE THREAD

**Issue by gabrielwohlfart** [EasyEngine/easyengine#1317]
When running any cron with:
ee cron run-now 

I always get the feedback:
Error: No such container: mycontainer_php_1

I already tried with several cron with different container
I always get the same error.

EE 4.0.1
Ubuntu 18.04 x64

**Comment by gabrielwohlfart** [comment]
As it was a test server I ended up destroying and I can not make a comeback now.

Soon I will set aside time for the EEv4 and I will comment again here if the error occurs again.
Thanks for the answer.

**Comment by kirtangajjar** [comment]
@gabrielwohlfart I'm closing this issue for now. If you face the issue again, feel free to reopen it or create new issue.
