### ISSUE TITLE
can't create new site in EasyEngine v4 Stable Release

### ISSUE THREAD

**Issue by renrayut** [EasyEngine/easyengine#1318]
Hi Easyengine
i try update RC2 to v4 Stable Release by commend "ee cli update" it "Success: EasyEngine is at the latest version."
cli info show : 
OS                | Linux 4.15.0-39-generic #42-Ubuntu SMP Tue Oct 23 15:48: |
|                   | 01 UTC 2018 x86_64                                       |
| Shell             | /bin/bash                                                |
| PHP binary        | /usr/bin/php7.2                                          |
| PHP version       | 7.2.12-1+ubuntu18.04.1+deb.sury.org+1                    |
| php.ini used      | /etc/php/7.2/cli/php.ini                                 |
| EE root dir       | phar://ee.phar                                           |
| EE vendor dir     | phar://ee.phar/vendor                                    |
| EE phar path      | /root                                                    |
| EE packages dir   |                                                          |
| EE global config  | /opt/easyengine/config/config.yml                        |
| EE project config |                                                          |
| EE version        | 4.0.1  

but when i try to create new site : ee site create example.ga --type=wp --cache --ssl=le
global-db: Service already running
Warning: Could not create user kohnews.ga-TJHqNL. Please check logs.
Warning: Initiating clean-up.
PHP Notice:  Undefined index: site_fs_path in phar:///usr/local/bin/ee/vendor/easyengine/site-type-wp/src/WordPress.php on line 1103
Site kohnews.ga deleted.

it not successes. 
please suggestion help 
thanks you

**Comment by renrayut** [comment]
Error ee.log
[27-11-2018 04:01:31] ee.DEBUG: -----------------------  
[27-11-2018 04:01:31] ee.DEBUG: COMMAND: docker exec ee-global-db sh db_exec  
[27-11-2018 04:01:31] ee.DEBUG: STDERR: ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)   
[27-11-2018 04:01:31] ee.DEBUG: RETURN CODE: 1  
[27-11-2018 04:01:31] ee.DEBUG: -----------------------  
[27-11-2018 04:01:31] ee.DEBUG: -----------------------  
[27-11-2018 04:01:31] ee.DEBUG: COMMAND: docker cp /tmp/db_exec ee-global-db:/db_exec  
[27-11-2018 04:01:31] ee.DEBUG: RETURN CODE: 0  
[27-11-2018 04:01:31] ee.DEBUG: -----------------------  
[27-11-2018 04:01:31] ee.DEBUG: -----------------------  
[27-11-2018 04:01:31] ee.DEBUG: COMMAND: docker exec ee-global-db sh db_exec  
[27-11-2018 04:01:32] ee.DEBUG: STDERR: ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)   
[27-11-2018 04:01:32] ee.DEBUG: RETURN CODE: 1

**Comment by b167er** [comment]
Hey @renrayut did you setup a fresh server and reinstall EE or are you still having this issue? I was having the same problem as you and here is what I did to fix it: https://github.com/EasyEngine/easyengine/issues/1333

**Comment by mrrobot47** [comment]
@renrayut if you have not reset this server, then a patch for the same has been added. Try `ee cli update --stable --yes` and you should be good to go for creating new sites.

**Comment by wzub** [comment]
Hi there - I updated to 4.0.4 but still seem to be running into this issue

> Debug: RETURN CODE: 127 (81.989s)
> Debug: ----------------------- (81.99s)
> Debug: ----------------------- (81.99s)
> Debug: COMMAND: docker cp /tmp/db_exec ee-global-db:/db_exec (81.99s)
> Debug: STDERR: lstat /tmp/db_exec: no such file or directory
>  (82.267s)
> Debug: RETURN CODE: 1 (82.268s)
> Debug: ----------------------- (82.268s)
> Debug: ----------------------- (82.268s)
> Debug: COMMAND: docker exec ee-global-db sh db_exec (82.268s)
> Debug: STDERR: sh: 0: Can't open db_exec
>  (82.549s)
> Debug: RETURN CODE: 127 (82.549s)
> Debug: ----------------------- (82.549s)
> Warning: Exiting gracefully after rolling back. This may take some time.
> Success: Rollback complete. Exiting now.

Is there anything else I can try?

**Comment by mrrobot47** [comment]
@wzub from the debug log it seems you've most probably run out of space on your machine. EasyEngine is unable to create a temporary file it needs. Can you check your disk space first and then check if you can create a file in `/tmp` directory.

**Comment by wzub** [comment]
Could it be a permissions issue? This is a fresh install of 20GB with nothing else on it.

> wmz@kvm202:~$ touch /tmp/test.txt
> wmz@kvm202:~$ ls /tmp
> snap.0_docker_G0r16A
> test.txt

**Comment by wzub** [comment]
@mrrobot47 I am still running into this issue after updating to 4.0.5. Any troubleshooting steps I can try?

**Comment by mrrobot47** [comment]
@wzub this issue is particular to your system. It will be best if you start a discussion about your issue on https://community.easyengine.io/. Also, send your entire logs (located at `/opt/easyengine/logs/`) to ee@rtcamp.com as that will give a full picture and more information to infer the exact cause of the issue you are facing.

**Comment by codente** [comment]
I am also running into this issue on a regular basis.  I've tried new servers, fresh installs of EE4 and I always, at some point, end up with this issue preventing me from doing anything.

**Comment by b167er** [comment]
> 
> 
> I am also running into this issue on a regular basis. I've tried new servers, fresh installs of EE4 and I always, at some point, end up with this issue preventing me from doing anything.

You might want to check out WordOps then. It's a fork of EEv3 except with all the latest packages. Wordops.org - they have an active Slack chat server too if you ever need help, but it's all the same commands as EEv3, just change ee to wo when running commands.

**Comment by codente** [comment]
I definitely will if this doesn't get fixed but would think the team would like to get to the bottom of the issue as well.
