### ISSUE TITLE
renew letsencrypt

### ISSUE THREAD

**Issue by buzucan** [EasyEngine/easyengine#1319]
i saw that in crontab is not set anything like in v3. There is any mode to renew SSL from LE automaticaly?

BTW, i`ve tested V4 in Debian 9 and all works fine.

**Comment by kirtangajjar** [comment]
Hey @buzucan. Thank you very much for testing it on Debian 9 :)

> I saw that in crontab is not set anything like in v3. There is any mode to renew SSL from LE automatically?

In upcoming releases, we will add a migration, which will add cron for renewing SSL on all existing sites. Hence you don't need to worry about it :)
