### ISSUE TITLE
Cannot upgrade from 4.0.0-rc1 to 4.0.1

### ISSUE THREAD

**Issue by b167er** [EasyEngine/easyengine#1322]
I get an error message when I run (sudo) ee cli update. Do I need to switch over to root to update it? I never had to before with the previous builds.

The error message is as such: 

```
You have version 4.0.0-rc.1. Would you like to update to 4.0.1? [y/n] y
Downloading from https://github.com/EasyEngine/easyengine/releases/download/v4.0.1/easyengine.phar...
md5 hash verified: d15be35d63096aca4e7aa501d3a2391b
Updating EasyEngine to new version. This might take some time.
```

1st error: 
```
Error: Encountered error while processing reload-oneofmydomains.com.au-nginx-containers in EE\Migration\SiteContainers::reload_nginx. Exception: Could not reload nginx. Check logs.
```

2nd error: 
```
Error: Errors were encountered while processing: 20181105125012_site-command_update_nginx_config.php
```

3rd Error: 
```
Unable to run nginx-config upadte migrations.
Error: The downloaded PHAR is broken, try running ee cli update again.
```

```
[+-------------------+----------------------------------------------------------------------------+
| OS                | Linux 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 |
| Shell             | /bin/bash                                                                  |
| PHP binary        | /usr/bin/php7.2                                                            |
| PHP version       | 7.2.12-1+ubuntu16.04.1+deb.sury.org+1                                      |
| php.ini used      | /etc/php/7.2/cli/php.ini                                                   |
| EE root dir       | phar://ee.phar                                                             |
| EE vendor dir     | phar://ee.phar/vendor                                                      |
| EE phar path      | /home/ecommerce                                                            |
| EE packages dir   |                                                                            |
| EE global config  | /opt/easyengine/config/config.yml                                          |
| EE project config |                                                                            |
| EE version        | 4.0.0-rc.1                                                                 |
+-------------------+----------------------------------------------------------------------------+]
```

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial
```
```

Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:48:57 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:16:44 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

```
docker-compose version 1.21.2, build a133471
docker-py version: 3.3.0
CPython version: 3.6.5
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

**Comment by kirtangajjar** [comment]
Actually, update functionality in RC.1 is broken. You might need to start again on a fresh server.
Sorry for the inconvenience caused.

**Comment by b167er** [comment]
That sucks. I have already had to wipe the server and start again twice because of previous issues in the beta, I would prefer not to do it again as my host charges $60 to reinstall the OS.

What is the best method to fully wipe ee, nginx redis etc and all dependencies it has installed from my server? I remember the last time I used the self-uninstall in the beta it still left behind lots of things as after re-installing, I was still getting the same error messages prior to uninstalling. So it seems that the self-uninstall doesn't wipe everything.

**Comment by kirtangajjar** [comment]
@b167er In that case, you might want to run 
```
ee cli self-uninstall
````

It will remove EasyEngine completely from your system.

After it's done, run 
```
which ee
ls -al /opt/easyengine/
```` 
to verify easyengine has been removed from the system.

Now you can run the installer script to install latest version of EasyEngine - 
```
wget -qO ee https://rt.cx/ee4 && sudo bash ee
```

**Comment by b167er** [comment]
Can I copy all my SSL cert chains for all my domains, and then restore them to the appropriate dir once I re-install ee? If so, once I run the ssl command again will it just detect the certificates already installed? Or am I going to need to create TXT records for all my domains again?

**Comment by kirtangajjar** [comment]
@b167er I'm not sure if it might work but you can try the following - 

1. Backup `/opt/easyengine/services/nginx-proxy/acme-conf`.
```
cp -r /opt/easyengine/services/nginx-proxy/acme-conf ~
```
2. Remove EasyEngine and run installer script as described in previous comment.
3. Create dummy http site and delete it. This is needed as `/opt/easyengine/*` folders are created after creating first site. 
```
ee site create temp.test && ee site delete temp.test
```
4. Restore `/opt/easyengine/services/nginx-proxy/acme-conf`.
```
mv ~/acme-conf /opt/easyengine/services/nginx-proxy/acme-conf
```
5. Run your site create commands.

> If so, once I run the ssl command again will it just detect the certificates already installed?

It will not keep your existing certs, but when you create a site with `ee site create example.com --ssl=le --wildcard`, it will give you the same TXT records as you had before, so you won't have to re-enter your TXT records. Then you can simply run `ee site ssl example.com` and it will receive certs for you directly.

**Comment by b167er** [comment]
Thanks @kirtangajjar -- just to clarify when you say self-uninstall is broken on RC1..Given I'm on RC1 now do I run the self-uninstall and verify easyengine is gone from /opt/, and then remove the docker volumes? Or do I just remove the docker volumes?

I tried out your method for the ssl certs on a secondary server and it did the trick, thanks for that.

**Comment by b167er** [comment]
Upgraded, ran in to issues, fixed. Now on stable EE. https://github.com/EasyEngine/easyengine/issues/1333
