### ISSUE TITLE
Warning: There was some error in docker-compose up. When using --cache

### ISSUE THREAD

**Issue by petebytes** [EasyEngine/easyengine#1331]
**Overview**
On new server install create site with --cache fails due to undefined network global-backend-network.
global-backend-network does not exist, perhaps it should be using ee-global-backend-network

**Reproducing the issue**
On new Ubuntu 18.04 server try to create site using
ee site create test.example.com --type=wp --version=4.9.8 --skip-content --cache --title="WP Site" --admin-user=pete --admin-pass=mypass --admin-email=test@test.com --local-db --php=7.2 --ssl=le

Configuring project.
Creating WordPress site test.example.com
Copying configuration files.
Starting site's services.
**Warning: There was some error in docker-compose up.**
Warning: Initiating clean-up.
[test.example.com] site root removed.
Site test.example.com deleted.

**ee.log** 
[30-11-2018 17:15:54] ee.DEBUG: COMMAND: docker-compose up -d nginx postfix
[30-11-2018 17:15:55] ee.DEBUG: STDERR: Service "nginx" uses an undefined network "global-backend-network"

**docker network list**
```
NETWORK ID          NAME                         DRIVER              SCOPE
44d03d682ec8        bridge                       bridge              local
38a7b75a7261        ee-global-backend-network    bridge              local
aeb232a0ca7f        ee-global-frontend-network   bridge              local
b1b9f22d1843        host                         host                local
7ad014fe9aeb        none                         null                local
```
System Information
- [x] ee cli info
```
+-------------------+----------------------------------------------------------------------------+
| OS                | Linux 4.15.0-39-generic #42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018 x86_64 |
| Shell             | /bin/bash                                                                  |
| PHP binary        | /usr/bin/php7.2                                                            |
| PHP version       | 7.2.12-1+ubuntu18.04.1+deb.sury.org+1                                      |
| php.ini used      | /etc/php/7.2/cli/php.ini                                                   |
| EE root dir       | phar://ee.phar                                                             |
| EE vendor dir     | phar://ee.phar/vendor                                                      |
| EE phar path      | /opt/easyengine/logs                                                       |
| EE packages dir   |                                                                            |
| EE global config  | /opt/easyengine/config/config.yml                                          |
| EE project config |                                                                            |
| EE version        | 4.0.3                                                                      |
+-------------------+----------------------------------------------------------------------------+
```

- [x] lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

- [x] docker version
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:49:01 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:16:44 2018
  OS/Arch:          linux/amd64
  Experimental:     false

- [x] docker-compose version
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0f  25 May 2017

**Comment by petebytes** [comment]
note: site create will complete but not operational if I add --with-local-redis OR remove --local-db

**Comment by petebytes** [comment]
Some additional notes.

- Create Works
```
ee site create test.example.com --type=wp
ee site create test.example.com --type=wp --cache
ee site create test.example.com --type=wp --cache --version=4.9.8 --skip-content --title="WP Site" --admin-user=pete --admin-email=pete@test.com --php=7.2
ee site create test.example.com --type=wp --version=4.9.8 --skip-content --title="WP Site" --admin-user=pete --admin-email=pete@test.com --php=7.2 --local-db
```

- Create fails and rollsback: Warning: There was some error in docker-compose up.
```
ee site create test.example.com --type=wp --cache --version=4.9.8 --skip-content --title="WP Site" --admin-user=pete --admin-email=pete@test.com --php=7.2 --local-db
```

- Create completes but site has HTTP ERROR 500
```
ee site create test.example.com --type=wp --cache --version=4.9.8 --skip-content --title="WP Site" --admin-user=pete --admin-email=pete@test.com --php=7.2 --local-db --with-local-redis
```

**Comment by handpressed** [comment]
I'm having this issue, too.

[https://community.easyengine.io/t/warning-there-was-some-error-in-docker-compose-up/11435/4?u=purbeckpixels](https://community.easyengine.io/t/warning-there-was-some-error-in-docker-compose-up/11435/4?u=purbeckpixels)

Frustrating because I'd like to use both local DBs and Redis caches.

**Comment by handpressed** [comment]
Have sent log files for the command:

`ee site create example.com --type=wp --cache --with-local-redis --local-db`

Results in 500/white screen because of the errors shown in ee.log.

**Comment by petebytes** [comment]
Yep worked for me as well :) thanks
