### ISSUE TITLE
Use port other than 80 and 443

### ISSUE THREAD

**Issue by Enterpr1se** [EasyEngine/easyengine#1335]
This issue tracker is only for issues related to EasyEngine. Please use http://community.rtcamp.com/c/easyengine for support questions.

If you feel the issue is a EasyEngine specific issue, please attach the output of the following commands.

System Information
- [ ] ee cli info
- [ ] lsb_release -a
- [ ] docker version
lient:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:49:01 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:16:44 2018
  OS/Arch:          linux/amd64
  Experimental:     false

- [ ] docker-compose version
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0f  25 May 2017

One of my application use webscoket on port 10000, but it seems easyengine does not support that

**Comment by kirtangajjar** [comment]
Sorry, no plans to support it as of now, maybe with more extensibility options that might come in the future like custom site types, it might be possible.
