### ISSUE TITLE
docker doesn't install OpenVZ Debian 8

### ISSUE THREAD

**Issue by buzucan** [EasyEngine/easyengine#1336]
i tried to install EE on with fresh install in a VPS with OpenVZ, debian 8 and can't start docker.

![image](https://user-images.githubusercontent.com/8757017/49418696-1d11fb80-f78c-11e8-82a6-57238804d3a9.png)

This issue tracker is only for issues related to EasyEngine. Please use http://community.rtcamp.com/c/easyengine for support questions.

If you feel the issue is a EasyEngine specific issue, please attach the output of the following commands.

System Information
- [ ] ee cli info
- [ ] lsb_release -a
- [ ] docker version
- [ ] docker-compose version

**Comment by kirtangajjar** [comment]
@buzucan Can you share the output of `/opt/easyengine/logs/install.log`?

**Comment by mbtamuli** [comment]
@buzucan There seems to be some trouble getting Docker to run with OpenVZ. You can take a look at these SO answers - 
1. https://stackoverflow.com/a/45456039/4108721
2. https://stackoverflow.com/a/35951482/4108721

and this wiki link - https://wiki.openvz.org/Docker_inside_CT


As for running EasyEngine, once you are able to get Docker up and running, which you can check using `systemctl status docker`, you should be able to run `ee site create`

**Comment by kirtangajjar** [comment]
@buzucan You'll have to get docker running on OpenVZ by yourself. After that you'll be able to install and run EasyEngine without any issues :)
