### ISSUE TITLE
How to update an existing site with "--ssl=le" as "ee site update" not available in ee4

### ISSUE THREAD

**Issue by prinzjoseph** [EasyEngine/easyengine#1343]
I want to migrate a wordpress site to easy engine 4. If I enable --ssl=le at the time of site creation, after replacing wp-content with my site's wp-content the browser shows "connection is not secure, Parts of this page are not secure (such as images)." Is there any way to resolve this issue. Or anyway to update the site with ssl after migration?

**Comment by michacassola** [comment]
I did also not figure out how to update a site with --ssl=le after it was created. Please someone have a look?

**Comment by kirtangajjar** [comment]
Site update command is currently WIP. Once it will be introduced, you'll be able to do it. See the discussion at - https://community.easyengine.io/t/ee-v4-how-to-update-install-ssl-after-installing-domain-without-ssl/11466/3 for more info

**Comment by mrrobot47** [comment]
You can track `ee site update` progress here: https://github.com/EasyEngine/site-command/issues/116

**Comment by mrrobot47** [comment]
>Parts of this page are not secure (such as images)

@prinzjoseph this is not the issue with site created with `--ssl=le`. Are all the images coming to your page from your site only? It is possible that they are from some external source which is not serving them over https. 

Also, if all of them are from your site have you run `wp search-replace` of http to https after importing your data post migration?

**Comment by nick-jansen** [comment]
@mrrobot47 @kirtangajjar thanks!
