### ISSUE TITLE
Admin tool for redis not working when using --with-local-redis command

### ISSUE THREAD

**Issue by seyntjim** [EasyEngine/easyengine#1363]
ERROR: php_network_getaddresses: getaddrinfo failed: Name or service not known [tcp://global-redis:6379]

This only happens when I install redis like this
ee site create example.com --type=wp --cache --with-local-redis --local-db

But when I install without --with-local-redis, admin tools for redis is working fine.

**Comment by mbtamuli** [comment]
@seyntjim Thanks for reporting the issue. We're looking into it.

**Comment by seyntjim** [comment]
Hello, any temporary fix for this bug? I don't want to change my website to global redis. I don't want to reinstall it again. Please if you could give me a temporary fix for this issue. Thanks.

**Comment by mrrobot47** [comment]
@seyntjim you the fix has been merged and will be released in the next version. Till then if you would like to test it, you can update to the nightly version of EasyEngine using `ee cli update --nightly` and the admin-tools with local-redis will start working.
