### ISSUE TITLE
Add cron container in global docker compose

### ISSUE THREAD

**Issue by kirtangajjar** [EasyEngine/easyengine#1365]
All global services are being managed through docker-compose.  Only cron container is being managed through `docker run` command.

Cron container should also run through docker-compose.

**Comment by LotusJeff** [comment]
I think this is a symptom of Cron being a run command.  Running Cron on Ubuntu. Have one site running.  Created a second site.  Deleted a second site. Cron no-longer is running. reboot the server. Cron does not come up.

**Comment by LotusJeff** [comment]
I have looked in the code to start eye-cron-scheduler and cannot find it. Can you provide the command?

**Comment by L0RD-ZER0** [comment]
Please update EasyEngine to the latest version using ``ee cli update`` command. This issue has been resolved in newer EasyEngine releases.
