### ISSUE TITLE
Installation fails on new ubuntu 18.04 vps on SkySilk

### ISSUE THREAD

**Issue by Sh3nron** [EasyEngine/easyengine#1385]
I created a new vps on SkySilk (tried two different plans) and it fails to fully install. Both VPS are fully up to date and have been restarted prior to install. There seems to be a permission issue. Can't find any open or closed issues on github related to this.

```
2019-02-01 23:45:10 (23.8 MB/s) - '/usr/local/bin/ee' saved [5554787/5554787]

-----> Pulling EasyEngine docker images
-----> Pulling EasyEngine docker images
Checking and Pulling required images. This may take some time.
Checking and Pulling docker image easyengine/cron:v4.0.0
v4.0.0: Pulling from easyengine/cron
8b608f890652: Pulling fs layer
8b608f890652: Verifying Checksum
8b608f890652: Download complete
failed to register layer: ApplyLayer exit status 1 stdout:  stderr: permission denied
Error: Errors were encountered while processing: 20181016052850_easyengine_insert_docker_images_version.php
Unable to pull easyengine/cron:v4.0.0. Please check logs for more details.
-----> Run "ee help site" for more information on how to create a site.
```

If I try to run a command to create a wordpress site I'm presented with this.

```
Checking and Pulling required images. This may take some time.
Checking and Pulling docker image easyengine/cron:v4.0.0
v4.0.0: Pulling from easyengine/cron
8b608f890652: Pulling fs layer
8b608f890652: Verifying Checksum
8b608f890652: Download complete
failed to register layer: ApplyLayer exit status 1 stdout:  stderr: permission denied
Error: Errors were encountered while processing: 20181016052850_easyengine_insert_docker_images_version.php
Unable to pull easyengine/cron:v4.0.0. Please check logs for more details.

```

Is there an issue with the install or the cron docker image?

**Comment by Sh3nron** [comment]
> Hi @Sh3nron, currently we (SkySilk) don't offer Docker support though it's on our to-do list for this year.

Are you (SkySilk) actively blocking it?

**Comment by SkySilk-Matt** [comment]
We are not actively blocking anything, the way our infrastructure is setup currently does not allow for Docker support. We are hoping to have Docker support as a main focus for this year.

**Comment by SkySilk-Matt** [comment]
If you have any SkySilk specific issues feel free to check out our[ Support Portal](https://help.skysilk.com) and [Public Discord chat](https://invite.gg/skysilk) for community support.

**Comment by kirtangajjar** [comment]
Closing this issue as it does not seem to be related to EasyEngine
