### ISSUE TITLE
Improvement - ability to add multidomain

### ISSUE THREAD

**Issue by pojke** [EasyEngine/easyengine#1394]
There needs to be a simple ability to add more than one domain on one docker. Currently, the setup is manual and quite painful, especially with acme letsencrypt setup.

There are at least 2 use cases that are quite common:
1) A misspelt domains redirects and multiple extensions (e.g. co.nz and .nz for NZ). 
2) Multisite with 2 domains (e.g google.co.uk and google.gr)

Something like:
ee site create google.com --alternative_url=gogle.com,gooogle.com

**Comment by kirtangajjar** [comment]
Hey @pojke, We already have an issue for it [here](https://github.com/EasyEngine/feature-requests/issues/23) so I'll be closing this issue. Also, we even have open pull requests for it(You can check it on the issue). So you can expect this feature to land soon in EE ;)
