### ISSUE TITLE
Ports of current running nginx-proxy and ports specified in EasyEngine config file don't match.

### ISSUE THREAD

**Issue by bradleeduffy** [EasyEngine/easyengine#1396]
This issue tracker is only for issues related to EasyEngine. Please use http://community.rtcamp.com/c/easyengine for support questions.

If you feel the issue is a EasyEngine specific issue, please attach the output of the following commands.

System Information
- [x] ee cli info
root@easyengine:~# ee cli info
+-------------------+---------------------------------------------------------------------------+
| OS                | Linux 4.18.0-15-generic #16-Ubuntu SMP Thu Feb 7 10:56:39 UTC 2019 x86_64 |
| Shell             | /bin/bash                                                                 |
| PHP binary        | /usr/bin/php7.2                                                           |
| PHP version       | 7.2.15-1+ubuntu18.10.1+deb.sury.org+1                                     |
| php.ini used      | /etc/php/7.2/cli/php.ini                                                  |
| EE root dir       | phar://ee.phar                                                            |
| EE vendor dir     | phar://ee.phar/vendor                                                     |
| EE phar path      | /root                                                                     |
| EE packages dir   |                                                                           |
| EE global config  | /opt/easyengine/config/config.yml                                         |
| EE project config |                                                                           |
| EE version        | 4.0.10-nightly-2a1bc0e                                                    |
+-------------------+---------------------------------------------------------------------------+

- [x] lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.10
Release:	18.10
Codename:	cosmic
- [x] docker version
Docker version 18.09.2, build 6247962

- [x] docker-compose version
docker-compose version 1.23.2, build 1110ad01

root@easyengine:~# docker ps
CONTAINER ID        IMAGE                               COMMAND                  CREATED             STATUS                          PORTS               NAMES
be03b14430bf        easyengine/postfix:v4.0.0           "postfix start-fg"       16 minutes ago      Up 13 minutes                   25/tcp              managebradleeduffycom_postfix_1
f88ad9362f46        easyengine/nginx:v4.0.0             "/usr/bin/openresty …"   16 minutes ago      Up 13 minutes                   80/tcp              managebradleeduffycom_nginx_1
7f747b3b2dc8        easyengine/php:v4.0.2               "docker-entrypoint.s…"   16 minutes ago      Up 13 minutes                   9000/tcp            managebradleeduffycom_php_1
5747be65361f        easyengine/postfix:v4.0.0           "postfix start-fg"       17 minutes ago      Up 13 minutes                   25/tcp              capecoralracquetclubcom_postfix_1
5ebc9be92115        easyengine/nginx:v4.0.0             "/usr/bin/openresty …"   17 minutes ago      Up 13 minutes                   80/tcp              capecoralracquetclubcom_nginx_1
4d744eb1f6d4        easyengine/php:v4.0.2               "docker-entrypoint.s…"   17 minutes ago      Up 13 minutes                   9000/tcp            capecoralracquetclubcom_php_1
6569d0af513e        easyengine/postfix:v4.0.0           "postfix start-fg"       17 minutes ago      Up 13 minutes                   25/tcp              webtalklinkcom_postfix_1
58f29977a45e        easyengine/nginx:v4.0.0             "/usr/bin/openresty …"   17 minutes ago      Up 13 minutes                   80/tcp              webtalklinkcom_nginx_1
23286f933d84        easyengine/php:v4.0.2               "docker-entrypoint.s…"   17 minutes ago      Up 13 minutes                   9000/tcp            webtalklinkcom_php_1
003188da1cce        easyengine/postfix:v4.0.0           "postfix start-fg"       17 minutes ago      Up 13 minutes                   25/tcp              neonblueconsultingcom_postfix_1
0084376abb87        easyengine/nginx:v4.0.0             "/usr/bin/openresty …"   17 minutes ago      Up 13 minutes                   80/tcp              neonblueconsultingcom_nginx_1
8d5f7b5e408b        easyengine/php:v4.0.2               "docker-entrypoint.s…"   17 minutes ago      Up 13 minutes                   9000/tcp            neonblueconsultingcom_php_1
9c4d4660b234        easyengine/postfix:v4.0.0           "postfix start-fg"       17 minutes ago      Up 13 minutes                   25/tcp              marknclarkcom_postfix_1
57ccb7b4fc70        easyengine/nginx:v4.0.0             "/usr/bin/openresty …"   17 minutes ago      Up 13 minutes                   80/tcp              marknclarkcom_nginx_1
58b471b0cd24        easyengine/php:v4.0.2               "docker-entrypoint.s…"   17 minutes ago      Up 13 minutes                   9000/tcp            marknclarkcom_php_1
e1b26125a33c        easyengine/postfix:v4.0.0           "postfix start-fg"       18 minutes ago      Up 13 minutes                   25/tcp              jcproductions-uscom_postfix_1
225ded0a4811        easyengine/nginx:v4.0.0             "/usr/bin/openresty …"   18 minutes ago      Up 13 minutes                   80/tcp              jcproductions-uscom_nginx_1
1cf96b738c9e        easyengine/php:v4.0.2               "docker-entrypoint.s…"   18 minutes ago      Up 13 minutes                   9000/tcp            jcproductions-uscom_php_1
6c78353e9be7        easyengine/postfix:v4.0.0           "postfix start-fg"       18 minutes ago      Up 13 minutes                   25/tcp              jacksrabbitholecom_postfix_1
378f05153b91        easyengine/nginx:v4.0.0             "/usr/bin/openresty …"   18 minutes ago      Up 13 minutes                   80/tcp              jacksrabbitholecom_nginx_1
a85b3b8e1ef8        easyengine/php:v4.0.2               "docker-entrypoint.s…"   18 minutes ago      Up 13 minutes                   9000/tcp            jacksrabbitholecom_php_1
6cfc934617fd        easyengine/postfix:v4.0.0           "postfix start-fg"       18 minutes ago      Up 13 minutes                   25/tcp              feldtechllccom_postfix_1
67fb2372266f        easyengine/nginx:v4.0.0             "/usr/bin/openresty …"   18 minutes ago      Up 13 minutes                   80/tcp              feldtechllccom_nginx_1
d0b14939d94e        easyengine/php:v4.0.2               "docker-entrypoint.s…"   18 minutes ago      Up 13 minutes                   9000/tcp            feldtechllccom_php_1
33e68a9ea3c6        easyengine/postfix:v4.0.0           "postfix start-fg"       18 minutes ago      Up 13 minutes                   25/tcp              dpsliftscom_postfix_1
0e058f62b1f6        easyengine/nginx:v4.0.0             "/usr/bin/openresty …"   19 minutes ago      Up 13 minutes                   80/tcp              dpsliftscom_nginx_1
d0df5ed9e8c4        easyengine/php:v4.0.2               "docker-entrypoint.s…"   19 minutes ago      Up 13 minutes                   9000/tcp            dpsliftscom_php_1
3983ec3c65db        easyengine/postfix:v4.0.0           "postfix start-fg"       19 minutes ago      Up 13 minutes                   25/tcp              devpodspackandloadservicescom_postfix_1
5357d3a54cbd        easyengine/nginx:v4.0.0             "/usr/bin/openresty …"   19 minutes ago      Up 13 minutes                   80/tcp              devpodspackandloadservicescom_nginx_1
df1e9970f9c8        easyengine/php:v4.0.2               "docker-entrypoint.s…"   19 minutes ago      Up 13 minutes                   9000/tcp            devpodspackandloadservicescom_php_1
229bd317cc24        easyengine/postfix:v4.0.0           "postfix start-fg"       19 minutes ago      Up 13 minutes                   25/tcp              craftautospacom_postfix_1
fbd8b8fe766d        easyengine/nginx:v4.0.0             "/usr/bin/openresty …"   19 minutes ago      Up 13 minutes                   80/tcp              craftautospacom_nginx_1
e3fd63112b07        easyengine/php:v4.0.2               "docker-entrypoint.s…"   19 minutes ago      Up 13 minutes                   9000/tcp            craftautospacom_php_1
65579a9a93a9        easyengine/postfix:v4.0.0           "postfix start-fg"       19 minutes ago      Up 13 minutes                   25/tcp              cforddentalcom_postfix_1
1c7f59cfc3f0        easyengine/nginx:v4.0.0             "/usr/bin/openresty …"   19 minutes ago      Up 13 minutes                   80/tcp              cforddentalcom_nginx_1
0945a259e135        easyengine/php:v4.0.2               "docker-entrypoint.s…"   19 minutes ago      Up 13 minutes                   9000/tcp            cforddentalcom_php_1
e64f652ec632        easyengine/nginx-proxy:v4.0.1       "/app/docker-entrypo…"   20 minutes ago      Restarting (0) 13 seconds ago                       services_global-nginx-proxy_1
062381bd12ee        easyengine/newrelic-daemon:v4.0.0   "sh -c '/usr/local/b…"   20 minutes ago      Up 13 minutes                                       services_global-newrelic-daemon_1
c17db2827bae        easyengine/mariadb:v4.0.0           "docker-entrypoint.s…"   20 minutes ago      Up 13 minutes                   3306/tcp            services_global-db_1
1029561f11ba        easyengine/redis:v4.0.0             "docker-entrypoint.s…"   20 minutes ago      Up 13 minutes                   6379/tcp            services_global-redis_1

root@easyengine:~# netstat
Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0     36 easyengine.bradleed:ssh 104-11-149-250.li:53901 ESTABLISHED
tcp        0      0 easyengine.bradleed:ssh 186.217.184.22:55486    ESTABLISHED
Active UNIX domain sockets (w/o servers)
Proto RefCnt Flags       Type       State         I-Node   Path
unix  2      [ ]         DGRAM                    26095    /run/user/0/systemd/notify
unix  3      [ ]         DGRAM                    1947     /run/systemd/notify
unix  2      [ ]         DGRAM                    1960     /run/systemd/journal/syslog
unix  10     [ ]         DGRAM                    1967     /run/systemd/journal/socket
unix  43     [ ]         DGRAM                    12325    /run/systemd/journal/dev-log
unix  3      [ ]         STREAM     CONNECTED     56030    
unix  3      [ ]         DGRAM                    15190    
unix  3      [ ]         STREAM     CONNECTED     55034    
unix  3      [ ]         STREAM     CONNECTED     35661    @/containerd-shim/moby/5357d3a54cbda5790cec945082127f9af1953def32e9ef170345fabe9b958af7/shim.sock@
unix  3      [ ]         STREAM     CONNECTED     19328    
unix  3      [ ]         STREAM     CONNECTED     18859    
unix  3      [ ]         STREAM     CONNECTED     55019    
unix  3      [ ]         STREAM     CONNECTED     20058    
unix  3      [ ]         STREAM     CONNECTED     55030    
unix  3      [ ]         DGRAM                    15587    
unix  3      [ ]         STREAM     CONNECTED     36166    
unix  3      [ ]         STREAM     CONNECTED     36235    @/containerd-shim/moby/7f747b3b2dc8bf8d4f02e16a2033af12aabbcbf457bf198e5c1fc162b711caa6/shim.sock@
unix  3      [ ]         STREAM     CONNECTED     19329    
unix  3      [ ]         STREAM     CONNECTED     56023    /var/run/docker.sock
unix  2      [ ]         DGRAM                    16889    
unix  3      [ ]         STREAM     CONNECTED     55035    /var/run/docker.sock
unix  2      [ ]         DGRAM                    25199    
unix  3      [ ]         STREAM     CONNECTED     17103    
unix  3      [ ]         STREAM     CONNECTED     55974    /var/run/docker.sock
unix  3      [ ]         STREAM     CONNECTED     15356    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     55044    /var/run/docker.sock
unix  3      [ ]         STREAM     CONNECTED     55016    
unix  3      [ ]         STREAM     CONNECTED     19487    
unix  3      [ ]         STREAM     CONNECTED     16144    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     55031    
unix  3      [ ]         STREAM     CONNECTED     55017    /var/run/docker.sock
unix  3      [ ]         STREAM     CONNECTED     20059    /var/run/dbus/system_bus_socket
unix  3      [ ]         STREAM     CONNECTED     16887    
unix  3      [ ]         DGRAM                    16398    
unix  3      [ ]         STREAM     CONNECTED     55043    
unix  2      [ ]         STREAM     CONNECTED     20411    
unix  3      [ ]         STREAM     CONNECTED     36276    @/containerd-shim/moby/df1e9970f9c88c81903c6978bc0b5a7cd1928b175765cabd12b854293a6a8e98/shim.sock@
unix  3      [ ]         STREAM     CONNECTED     35570    
unix  3      [ ]         STREAM     CONNECTED     55010    
unix  3      [ ]         STREAM     CONNECTED     20386    
unix  3      [ ]         STREAM     CONNECTED     18832    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     15090    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     55026    
unix  3      [ ]         STREAM     CONNECTED     20428    /run/containerd/containerd.sock
unix  3      [ ]         STREAM     CONNECTED     55014    /var/run/docker.sock
unix  3      [ ]         DGRAM                    15189    
unix  3      [ ]         STREAM     CONNECTED     55978    /var/run/docker.sock
unix  3      [ ]         DGRAM                    15584    
unix  3      [ ]         STREAM     CONNECTED     36216    @/containerd-shim/moby/378f05153b9117274058c7734a7563e4b98d58c8366db1f663daa75a29b718a1/shim.sock@
unix  3      [ ]         STREAM     CONNECTED     18812    
unix  3      [ ]         STREAM     CONNECTED     56022    
unix  3      [ ]         STREAM     CONNECTED     20382    
unix  3      [ ]         STREAM     CONNECTED     18858    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     17101    
unix  3      [ ]         DGRAM                    16397    
unix  3      [ ]         STREAM     CONNECTED     15089    
unix  3      [ ]         STREAM     CONNECTED     55038    /var/run/docker.sock
unix  3      [ ]         STREAM     CONNECTED     55020    /var/run/docker.sock
unix  3      [ ]         STREAM     CONNECTED     20387    
unix  3      [ ]         STREAM     CONNECTED     18831    /run/systemd/journal/stdout
unix  2      [ ]         DGRAM                    16606    
unix  3      [ ]         DGRAM                    15191    
unix  3      [ ]         STREAM     CONNECTED     55040    
unix  3      [ ]         STREAM     CONNECTED     19526    /var/run/dbus/system_bus_socket
unix  3      [ ]         DGRAM                    15586    
unix  3      [ ]         STREAM     CONNECTED     36161    
unix  3      [ ]         STREAM     CONNECTED     36154    @/containerd-shim/moby/4d744eb1f6d4dd5266b2d799ff64e423395db438532ebe97d7036d621df9f6b9/shim.sock@
unix  3      [ ]         STREAM     CONNECTED     19528    /var/run/dbus/system_bus_socket
unix  3      [ ]         STREAM     CONNECTED     55023    /var/run/docker.sock
unix  3      [ ]         DGRAM                    16395    
unix  2      [ ]         DGRAM                    15182    
unix  3      [ ]         STREAM     CONNECTED     55032    /var/run/docker.sock
unix  3      [ ]         DGRAM                    15583    
unix  3      [ ]         STREAM     CONNECTED     35579    @/containerd-shim/moby/d0df5ed9e8c49aec04f47686539a83e23c3cb9fdd314e0cc951bc07392b3280d/shim.sock@
unix  3      [ ]         STREAM     CONNECTED     56031    /var/run/docker.sock
unix  3      [ ]         STREAM     CONNECTED     19525    /var/run/dbus/system_bus_socket
unix  3      [ ]         STREAM     CONNECTED     19524    /var/run/dbus/system_bus_socket
unix  3      [ ]         STREAM     CONNECTED     15159    
unix  3      [ ]         STREAM     CONNECTED     55037    
unix  3      [ ]         STREAM     CONNECTED     20430    /run/containerd/containerd.sock
unix  3      [ ]         STREAM     CONNECTED     55011    /var/run/docker.sock
unix  3      [ ]         STREAM     CONNECTED     17981    
unix  3      [ ]         DGRAM                    16396    
unix  3      [ ]         DGRAM                    15192    
unix  3      [ ]         STREAM     CONNECTED     15160    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     55027    /var/run/docker.sock
unix  3      [ ]         STREAM     CONNECTED     55025    
unix  3      [ ]         STREAM     CONNECTED     18141    
unix  3      [ ]         STREAM     CONNECTED     55041    /var/run/docker.sock
unix  3      [ ]         STREAM     CONNECTED     35509    
unix  3      [ ]         STREAM     CONNECTED     55013    
unix  3      [ ]         STREAM     CONNECTED     18830    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     15354    
unix  3      [ ]         STREAM     CONNECTED     55029    
unix  3      [ ]         STREAM     CONNECTED     36170    
unix  3      [ ]         STREAM     CONNECTED     18826    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     55022    
unix  3      [ ]         STREAM     CONNECTED     20383    /var/run/dbus/system_bus_socket
unix  3      [ ]         STREAM     CONNECTED     18061    
unix  3      [ ]         STREAM     CONNECTED     17102    
unix  2      [ ]         DGRAM                    16393    
unix  3      [ ]         STREAM     CONNECTED     55976    /var/run/docker.sock
unix  3      [ ]         STREAM     CONNECTED     32920    @/containerd-shim/moby/c17db2827baec8984931e2c7aaaf04c208f28339690259d6ee53bde49b337da4/shim.sock@
unix  3      [ ]         STREAM     CONNECTED     18560    
unix  3      [ ]         STREAM     CONNECTED     18642    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     13344    
unix  3      [ ]         STREAM     CONNECTED     28861    @/containerd-shim/moby/65579a9a93a9cd542f561d00d73256a6ebfeea700a4705ac51a18239dc8bbefa/shim.sock@
unix  3      [ ]         STREAM     CONNECTED     27954    
unix  3      [ ]         STREAM     CONNECTED     30490    @/containerd-shim/moby/1029561f11ba57dbd03493c9969ace0ead38450bac15f8012b4a2aca0314e705/shim.sock@
unix  3      [ ]         STREAM     CONNECTED     19522    
unix  3      [ ]         STREAM     CONNECTED     18724    
unix  3      [ ]         STREAM     CONNECTED     56235    /var/run/docker.sock
unix  3      [ ]         STREAM     CONNECTED     20205    
unix  3      [ ]         STREAM     CONNECTED     55128    
unix  3      [ ]         STREAM     CONNECTED     28812    
unix  3      [ ]         STREAM     CONNECTED     27926    
unix  3      [ ]         STREAM     CONNECTED     32771    
unix  3      [ ]         STREAM     CONNECTED     55046    
unix  3      [ ]         STREAM     CONNECTED     27985    @/containerd-shim/moby/be03b14430bf3ef98d7087ce8586b516f113233f1da94eeddc3b04e8834066c2/shim.sock@
unix  3      [ ]         STREAM     CONNECTED     19523    
unix  3      [ ]         STREAM     CONNECTED     55124    
unix  3      [ ]         STREAM     CONNECTED     20204    
unix  3      [ ]         STREAM     CONNECTED     27853    
unix  3      [ ]         STREAM     CONNECTED     28932    
unix  3      [ ]         STREAM     CONNECTED     13660    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     55127    /var/run/docker.sock
unix  3      [ ]         STREAM     CONNECTED     28821    @/containerd-shim/moby/33e68a9ea3c69d4b6a714f09f8bbb29f984bd73bcc60807197c3eb39fe84ff6f/shim.sock@
unix  3      [ ]         STREAM     CONNECTED     28032    @/containerd-shim/moby/6cfc934617fd2b353cb008f9a3320ed01227b94edf95f9d486954d584800672d/shim.sock@
unix  2      [ ]         DGRAM                    19521    
unix  3      [ ]         STREAM     CONNECTED     27459    @/containerd-shim/moby/003188da1cce4eb48975210b7a374832554cb4989825ff8bd0e5273aaf69a14d/shim.sock@
unix  3      [ ]         STREAM     CONNECTED     55982    /var/run/docker.sock
unix  3      [ ]         STREAM     CONNECTED     28992    @/containerd-shim/moby/9c4d4660b234966fbcd7e6e1ba0b8403e6bae33994535688192e98e75bdd0cc4/shim.sock@
unix  3      [ ]         STREAM     CONNECTED     35746    
unix  3      [ ]         STREAM     CONNECTED     26049    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     56061    /var/run/docker.sock
unix  3      [ ]         STREAM     CONNECTED     19274    
unix  3      [ ]         STREAM     CONNECTED     19186    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     19171    
unix  3      [ ]         STREAM     CONNECTED     56054    
unix  3      [ ]         STREAM     CONNECTED     27631    @/containerd-shim/moby/3983ec3c65db7b1c473f4a422dc66dc965f67570f2cec293340bb94028877759/shim.sock@
unix  2      [ ]         DGRAM                    20176    
unix  3      [ ]         STREAM     CONNECTED     35718    
unix  3      [ ]         STREAM     CONNECTED     33545    
unix  3      [ ]         STREAM     CONNECTED     28029    
unix  3      [ ]         STREAM     CONNECTED     20169    
unix  3      [ ]         STREAM     CONNECTED     37125    
unix  3      [ ]         STREAM     CONNECTED     18888    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     35776    @/containerd-shim/moby/5ebc9be92115c1575b00a6e54c408e37326a67c057f8d9c6fbbc53e6e7607ff0/shim.sock@
unix  2      [ ]         DGRAM                    12441    
unix  3      [ ]         STREAM     CONNECTED     36492    @/containerd-shim/moby/0e058f62b1f67a1864f948d9d21f46e116e4b983ba1e524271a432cc4d27cb15/shim.sock@
unix  3      [ ]         STREAM     CONNECTED     27528    
unix  2      [ ]         DGRAM                    19954    
unix  3      [ ]         STREAM     CONNECTED     35734    
unix  3      [ ]         STREAM     CONNECTED     36031    @/containerd-shim/moby/062381bd12ee6135ea3e9e41ee3a1c995d420abe6b8d690705f9bf3854adba1f/shim.sock@
unix  3      [ ]         STREAM     CONNECTED     31221    
unix  3      [ ]         STREAM     CONNECTED     56217    /var/run/docker.sock
unix  3      [ ]         STREAM     CONNECTED     37248    @/containerd-shim/moby/0084376abb87ad87684a6f69a23c0bafd608fc5205f589a74954c2a83cd75695/shim.sock@
unix  3      [ ]         STREAM     CONNECTED     19278    
unix  3      [ ]         STREAM     CONNECTED     19944    
unix  3      [ ]         STREAM     CONNECTED     26040    
unix  3      [ ]         DGRAM                    16893    
unix  3      [ ]         STREAM     CONNECTED     56060    
unix  3      [ ]         STREAM     CONNECTED     29688    
unix  3      [ ]         STREAM     CONNECTED     28115    @/containerd-shim/moby/229bd317cc240f98c860c5b62e9ed13681626e3235715d234a06ecb831501853/shim.sock@
unix  3      [ ]         STREAM     CONNECTED     30515    @/containerd-shim/moby/225ded0a4811e32e5815eb0bef8f564726bde4828168f614082078fee029e843/shim.sock@
unix  3      [ ]         STREAM     CONNECTED     56216    
unix  3      [ ]         STREAM     CONNECTED     27645    @/containerd-shim/moby/6c78353e9be70eed4b3eff846367bdd18745d84b1acd849fb35130dc01fe1da4/shim.sock@
unix  3      [ ]         STREAM     CONNECTED     35782    @/containerd-shim/moby/1c7f59cfc3f0d7a118de2673bfb7121eddecf6683b36838bdbd9c3483c55c726/shim.sock@
unix  3      [ ]         STREAM     CONNECTED     56058    /var/run/docker.sock
unix  3      [ ]         STREAM     CONNECTED     28691    
unix  3      [ ]         STREAM     CONNECTED     19831    
unix  3      [ ]         STREAM     CONNECTED     31599    
unix  3      [ ]         STREAM     CONNECTED     20060    /var/run/dbus/system_bus_socket
unix  3      [ ]         DGRAM                    16894    
unix  3      [ ]         STREAM     CONNECTED     56057    
unix  3      [ ]         STREAM     CONNECTED     36567    @/containerd-shim/moby/fbd8b8fe766da0644d352098f33d356d8fa074c71159f3ad8c3bc0fa66b49866/shim.sock@
unix  3      [ ]         STREAM     CONNECTED     28715    
unix  3      [ ]         STREAM     CONNECTED     19019    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     31896    
unix  3      [ ]         STREAM     CONNECTED     35818    
unix  3      [ ]         DGRAM                    15644    
unix  3      [ ]         STREAM     CONNECTED     27643    
unix  3      [ ]         STREAM     CONNECTED     35749    
unix  2      [ ]         DGRAM                    12546    
unix  3      [ ]         STREAM     CONNECTED     56055    /var/run/docker.sock
unix  3      [ ]         STREAM     CONNECTED     37223    
unix  3      [ ]         STREAM     CONNECTED     31592    @/containerd-shim/moby/a85b3b8e1ef88f21decaf68bda0db9627643c7a1a3f5222719835460d33af95a/shim.sock@
unix  3      [ ]         STREAM     CONNECTED     17292    /run/systemd/journal/stdout
unix  3      [ ]         DGRAM                    1948     
unix  3      [ ]         STREAM     CONNECTED     36345    @/containerd-shim/moby/8d5f7b5e408bfe914f465d9fbd20f760f48726d16c36c7caf3a8fdfb12ca42b8/shim.sock@
unix  3      [ ]         STREAM     CONNECTED     36594    @/containerd-shim/moby/e3fd63112b070b52859b932002baca9e64dea08464bc9752a924b2ab9f748ba2/shim.sock@
unix  2      [ ]         DGRAM                    20391    
unix  3      [ ]         DGRAM                    1949     
unix  3      [ ]         STREAM     CONNECTED     17512    
unix  3      [ ]         STREAM     CONNECTED     37032    
unix  3      [ ]         STREAM     CONNECTED     28067    @/containerd-shim/moby/6569d0af513ecfb90bf13cd7780afee132f46a3f710cc7c4aa39aac56047e07d/shim.sock@
unix  3      [ ]         STREAM     CONNECTED     20379    /var/run/dbus/system_bus_socket
unix  3      [ ]         STREAM     CONNECTED     19277    
unix  3      [ ]         STREAM     CONNECTED     19732    
unix  3      [ ]         STREAM     CONNECTED     37008    @/containerd-shim/moby/1cf96b738c9e0c598f219c24a66b3392a8c24178a53868b6b124a3606227f41a/shim.sock@
unix  3      [ ]         STREAM     CONNECTED     32892    @/containerd-shim/moby/58f29977a45e706fd53d0ab4179e73176c4a8274535626719a35911b5b1ab04c/shim.sock@
unix  3      [ ]         DGRAM                    15645    
unix  3      [ ]         STREAM     CONNECTED     18889    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     55998    
unix  3      [ ]         STREAM     CONNECTED     33471    
unix  3      [ ]         STREAM     CONNECTED     56040    
unix  3      [ ]         STREAM     CONNECTED     56007    
unix  3      [ ]         STREAM     CONNECTED     56041    /var/run/docker.sock
unix  3      [ ]         STREAM     CONNECTED     55993    /var/run/docker.sock
unix  3      [ ]         STREAM     CONNECTED     29051    @/containerd-shim/moby/e1b26125a33c1909bcbda02b3d77507af33a51ae5023714ebad8425d8513431c/shim.sock@
unix  3      [ ]         STREAM     CONNECTED     17286    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     19529    /var/run/dbus/system_bus_socket
unix  3      [ ]         STREAM     CONNECTED     56038    /var/run/docker.sock
unix  3      [ ]         STREAM     CONNECTED     29884    
unix  3      [ ]         STREAM     CONNECTED     55985    /var/run/docker.sock
unix  3      [ ]         STREAM     CONNECTED     26099    
unix  3      [ ]         STREAM     CONNECTED     17372    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     56034    /var/run/docker.sock
unix  3      [ ]         STREAM     CONNECTED     56008    /var/run/docker.sock
unix  3      [ ]         STREAM     CONNECTED     17283    
unix  3      [ ]         STREAM     CONNECTED     56048    /var/run/docker.sock
unix  3      [ ]         STREAM     CONNECTED     29217    @/containerd-shim/moby/5747be65361f01a1726a68233faa4b38d1997b6ac0ac17f84fd39c9a2a5a8cf1/shim.sock@
unix  3      [ ]         STREAM     CONNECTED     55989    
unix  3      [ ]         STREAM     CONNECTED     35388    @/containerd-shim/moby/67fb2372266f1bd92d33858a7aa056afde3eee7a150109ff59798e1b960db376/shim.sock@
unix  2      [ ]         DGRAM                    19948    
unix  3      [ ]         STREAM     CONNECTED     56053    
unix  3      [ ]         STREAM     CONNECTED     55990    /var/run/docker.sock
unix  3      [ ]         STREAM     CONNECTED     29019    
unix  3      [ ]         DGRAM                    26097    
unix  3      [ ]         STREAM     CONNECTED     55053    /var/run/docker.sock
unix  3      [ ]         STREAM     CONNECTED     33942    @/containerd-shim/moby/0945a259e13512546a63bc46ba6a9600b98adab5a301b1f5634637ce81e8ec8e/shim.sock@
unix  3      [ ]         STREAM     CONNECTED     56005    /var/run/docker.sock
unix  3      [ ]         STREAM     CONNECTED     33484    
unix  3      [ ]         DGRAM                    26096    
unix  3      [ ]         STREAM     CONNECTED     56033    
unix  3      [ ]         STREAM     CONNECTED     35192    @/containerd-shim/moby/d0b14939d94eaa3f88752b0740f494ed47d5cdb6689dfec8b27632cba2845faf/shim.sock@
unix  3      [ ]         STREAM     CONNECTED     55992    
unix  3      [ ]         STREAM     CONNECTED     35994    @/containerd-shim/moby/58b471b0cd248bb235e86df70a932c5b8ba94d59c26532f05a98d34a59cbbe66/shim.sock@
unix  3      [ ]         STREAM     CONNECTED     56037    
unix  3      [ ]         STREAM     CONNECTED     32004    
unix  3      [ ]         STREAM     CONNECTED     55999    /var/run/docker.sock
unix  3      [ ]         STREAM     CONNECTED     33201    
unix  3      [ ]         STREAM     CONNECTED     56045    /var/run/docker.sock
unix  3      [ ]         STREAM     CONNECTED     35565    
unix  3      [ ]         STREAM     CONNECTED     56001    
unix  3      [ ]         STREAM     CONNECTED     26100    /var/run/dbus/system_bus_socket
unix  3      [ ]         STREAM     CONNECTED     56047    
unix  3      [ ]         STREAM     CONNECTED     56002    /var/run/docker.sock
unix  3      [ ]         STREAM     CONNECTED     56036    
unix  3      [ ]         STREAM     CONNECTED     32680    
unix  3      [ ]         STREAM     CONNECTED     28602    
unix  3      [ ]         STREAM     CONNECTED     56020    /var/run/docker.sock
unix  2      [ ]         DGRAM                    26063    
unix  3      [ ]         STREAM     CONNECTED     56051    /var/run/docker.sock
unix  3      [ ]         STREAM     CONNECTED     30015    @/containerd-shim/moby/f88ad9362f46e9af696327ccc93884bdb99be6320ee13dddaa5406a9a6c8322a/shim.sock@
unix  3      [ ]         STREAM     CONNECTED     55984    
unix  3      [ ]         STREAM     CONNECTED     33254    @/containerd-shim/moby/57ccb7b4fc7095d49fe12919565a841f719dcb061cbf619f00e3a0fdbc6612e8/shim.sock@
unix  3      [ ]         STREAM     CONNECTED     17371    
unix  3      [ ]         STREAM     CONNECTED     55051    /var/run/docker.sock
unix  3      [ ]         STREAM     CONNECTED     34526    
unix  3      [ ]         STREAM     CONNECTED     56019    
unix  2      [ ]         DGRAM                    26051    
unix  3      [ ]         STREAM     CONNECTED     56050    
unix  3      [ ]         STREAM     CONNECTED     33232    @/containerd-shim/moby/23286f933d840ac2b6b6110a191da1ad5e531e82ddeff4560fd9ad481c6c49f2/shim.sock@
unix  3      [ ]         STREAM     CONNECTED     56004    
unix  3      [ ]         STREAM     CONNECTED     56044

**Comment by bradleeduffy** [comment]
It was much easier for me to start up a new VPS with 16.04 and just start fresh. I would still like to know what took a service running for 6 months without issue down all of a sudden.

**Comment by kirtangajjar** [comment]
@bradleeduffy Can you run this command and let us know it's output - `docker logs services_global-nginx-proxy_1`
