### ISSUE TITLE
Subdirectory on Subdomain installation fail

### ISSUE THREAD

**Issue by niamulrox** [EasyEngine/easyengine#1399]
I was trying to create a site using the following command 
ee site create demo.themerox.com/publisher --wpsubdir --wpredis

Where demo.themerox.com is my subdirectory and there is no WordPress install and required. I only need to create site at this domain subdirectory like 
demo.themerox.com/publisher 
demo.themerox.com/cworld 
demo.themerox.com/ayyash 
So when I am writing create site command its actually generating error 

```
root@localhost:~# ee site create demo.themerox.com/publisher --wpsubdir --wpredis
Warning: Could not create user demo.themerox.com/publisher-off2CL. Please check logs.
Warning: Initiating clean-up.
Site demo.themerox.com/publisher deleted.
```
I think its unable to create user due to / . Any idea how to do that ? I think its a bug.

**Comment by kirtangajjar** [comment]
@niamulrox The correct command to run would be `ee site create demo.themerox.com  --type=wp --mu=subdom --cache`. Then you can create all the sites you mentioned with WordPress.

You can reopen the issue if it does not solve your problem.
