### ISSUE TITLE
ee databases look deleted

### ISSUE THREAD

**Issue by puccaso** [EasyEngine/easyengine#1408]
my ee database sync seems off, 

Nginx configuration	wp wpfc (enabled)
PHP Version	7.0
HHVM	enabled
SSL	enabled
SSL PROVIDER Lets Encrypt
SSL EXPIRY DATE Wed May 29 08:37:53 EDT 2019

access_log	/xxxxxxxx/mahirsayar.com/logs/access.log
error_log	/xxxxxxxx/mahirsayar.com/logs/error.log
Webroot	/xxxxxxxx/mahirsayar.com
DB_NAME	deleted
DB_USER	deleted
DB_PASS	deleted

i can see all the correct info in my wp-config.php - and the site works fine,
but i can't upgrade because i cant seem to get ee to accept whats actually there..

System Information
- [mahirsayar.com$ sudo ee cli info
usage: ee (sub-commands ...) [options ...] {arguments ...}
ee: error: unrecognized arguments: cli info
 ] ee cli info

- [mahirsayar.com$  lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
mahir@txaqo:/var/www/mahirsa ] lsb_release -a
- [ ] docker version
- [ ] docker-compose version

**Comment by kirtangajjar** [comment]
@puccaso This issue seems to be of EasyEngine v3. Since we've dropped support of v3, I'm closing this issue. However you can still post this issue in [community forums](https://community.easyengine.io) -  and someone might help you out.

**Comment by puccaso** [comment]
See, if i could get EE to just accept the databases are present, i'd be able to free myself of v3, and be happy!
i'll try on the forums. thanks. 
:(
