### ISSUE TITLE
Docker logs excessive disk usage

### ISSUE THREAD

**Issue by jasmith86** [EasyEngine/easyengine#1412]
EasyEngine 4.0.12 does not rotate logs, so they will grow indefinitely. 

Logs are located in `/var/lib/docker/containers/*/*-json.log`

Running ``` sudo find /var/lib/docker/containers/ -iname "*-json.log" -exec ls -sh {} \; | sort -hk1 -r ``` showed that one of my log files had grown to over 17gb. 

I posted my quick fix on the [EE forum](https://community.easyengine.io/t/excessive-disk-usage-ee-v-4-0-12/12712), but it would be nice if log rotation ([as on the docker site](https://docs.docker.com/config/containers/logging/json-file/)) were implemented.

System Information
- [x] ee cli info

|   |  |
|---|---|
| OS                | Linux 4.15.0-48-generic #51-Ubuntu SMP Wed A |
|                   | pr 3 08:28:49 UTC 2019 x86_64                |
| Shell             | /bin/bash                                    |
| PHP binary        | /usr/bin/php7.2                              |
| PHP version       | 7.2.17-1+ubuntu18.04.1+deb.sury.org+3        |
| php.ini used      | /etc/php/7.2/cli/php.ini                     |
| EE root dir       | phar://ee.phar                               |
| EE vendor dir     | phar://ee.phar/vendor                        |
| EE phar path      | /home/wp                                     |
| EE packages dir   |                                              |
| EE global config  | /opt/easyengine/config/config.yml            |
| EE project config |                                              |
| EE version        | 4.0.12                                       |

- [x] lsb_release -a

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

- [x] docker version

Client:
 Version:           18.09.5
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        e8ff056
 Built:             Thu Apr 11 04:43:57 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.5
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       e8ff056
  Built:            Thu Apr 11 04:10:53 2019
  OS/Arch:          linux/amd64
  Experimental:     false

- [x] docker-compose version

docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0f  25 May 2017

**Comment by kirtangajjar** [comment]
Hey, @jasmith86 Thanks for reporting the issue. 

This is a known issue and you can track its progress in https://github.com/EasyEngine/feature-requests/issues/73. Also, there's a WIP PR for it - https://github.com/EasyEngine/dockerfiles/pull/76/files.

Hence, I am closing this issue as a duplicate.
