### ISSUE TITLE
Can't manually renew LE certificate

### ISSUE THREAD

**Issue by sillyonthestreet** [EasyEngine/easyengine#1413]
+
| OS                | Linux 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:0 |
|                   | 7 UTC 2019 x86_64                                        |
| Shell             | /bin/bash                                                |
| PHP binary        | /usr/bin/php7.2                                          |
| PHP version       | 7.2.17-1+ubuntu18.04.1+deb.sury.org+3                    |
| php.ini used      | /etc/php/7.2/cli/php.ini                                 |
| EE root dir       | phar://ee.phar                                           |
| EE vendor dir     | phar://ee.phar/vendor                                    |
| EE phar path      | /root                                                    |
| EE packages dir   |                                                          |
| EE global config  | /opt/easyengine/config/config.yml                        |
| EE project config |                                                          |
| EE version        | 4.0.12   

Ubuntu 18.04.2 LTS. 
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0f  25 May 2017

When running ee site update mysite.com --letsencrypt=renew it just says 
Error: Site mysite.com already contains SSL.
This command worked before.

**Comment by mrrobot47** [comment]
The syntax has changed, run:

```bash
ee site ssl-renew mysite.com
```
