### ISSUE TITLE
Help ME

### ISSUE THREAD

**Issue by 23h** [EasyEngine/easyengine#1423]
This issue tracker is only for issues related to EasyEngine. Please use http://community.rtcamp.com/c/easyengine for support questions.

If you feel the issue is a EasyEngine specific issue, please attach the output of the following commands.

System Information
- [ ] ee cli info
- [ ] lsb_release -a
- [ ] docker version
- [ ] docker-compose version

**Comment by 23h** [comment]
root@CTTN-Corporation:~# ee site create store.23h.online --wpfc
Running pre-update checks, please wait...
Setting up NGINX configuration  [Done]
Setting up webroot              [Done]
Downloading WordPress           [Done]
Setting up database             [Done]
Oops Something went wrong !!
Calling cleanup actions ...
Reload : nginx     [OK]
Check logs for reason `tail /var/log/ee/ee.log` & Try Again!!!

**Comment by jasperf** [comment]
Did you check the logs? What did `tail /var/log/ee/ee.log` give you?

**Comment by kirtangajjar** [comment]
@23h Support related questions are better asked on our [community forums](https://community.easyengine.io ) as there are more people checking that out instead of this issue tracker.
