### ISSUE TITLE
EE4 Install is Broken on Debian 8

### ISSUE THREAD

**Issue by Endda** [EasyEngine/easyengine#1424]
The FAQ on the EE website says that it supports Debian 7 and Debian 8 (along with some versions of Ubuntu).

On a freshly created VPS of Ubuntu the install works just fine. Using that same installer command on Debian 8 doesn't install EasyEngine 4 due to a critical error.

More details here. . .

 - https://community.easyengine.io/t/install-fails-on-debian-8-vps-sudo-command-not-found/12867

I get how easy it is to get around this error, but it isn't mentioned anywhere on the website and I would think a couple of lines 'checking for debian' and then 'installing sudo' if it's found that it isn't installed.

**Comment by L0RD-ZER0** [comment]
This issue as been resolved as of latest revisions of the installation script. You can use the installation script using the shell command ``wget -qO ee rt.cx/ee4 && sudo bash ee`` for the installation.
