### ISSUE TITLE
Why we still can't update a WP site to whatever newest php version out there?

### ISSUE THREAD

**Issue by monecchi** [EasyEngine/easyengine#1439]
I'm running latest EE v4 version, with some regret I migrated to it. I see there are a lot of enhancements towards the way EE v4 now works, but "tweaking" php, nginx and other WordPress settings is at least (pardon my words), "a pain in the asss", literally!

Ok, I should thank you guys behind the project first for all the great stuff EE allows us to do, however, now EE v4 uses docker and all that fancy spin up server's approach, but where's the EasyEngine v4 "easy" approach we had on EE v3? Gone?

I mean, you guys behind the project should bring us back the easy way to update the server's resources to whatever newest version out there, or at least, give us an official tutorial on how to safely upgrade a site's php to its newest versions ( 7.3, 7.4 ), as also other minor but also important stuff, such as nginx custom configuration, additional php libraries installation, database upgrade and so on.

The cool thing about EE v3 was that we had all those easy commands to accomplish all that kind of stuff, but now on EE v4 we haven't.

Thanks for your attention.

System Information
- [x] ee cli info
+-------------------+----------------------------------------------------------------------------+
| OS                | Linux 4.15.0-70-generic #79-Ubuntu SMP Tue Nov 12 10:36:11 UTC 2019 x86_64 |
| Shell             | /bin/bash                                                                  |
| PHP binary        | /usr/bin/php7.2                                                            |
| PHP version       | 7.2.25-1+ubuntu18.04.1+deb.sury.org+1                                      |
| php.ini used      | /etc/php/7.2/cli/php.ini                                                   |
| EE root dir       | phar://ee.phar                                                             |
| EE vendor dir     | phar://ee.phar/vendor                                                      |
| EE phar path      | /root                                                                      |
| EE packages dir   |                                                                            |
| EE global config  | /opt/easyengine/config/config.yml                                          |
| EE project config |                                                                            |
| EE version        | 4.0.14                                                                     |
+-------------------+----------------------------------------------------------------------------+
- [x] lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
- [x] docker version
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:29:52 2019
 OS/Arch:           linux/amd64
 Experimental:      false

    Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:22 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510dsfrt852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88erdgt6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
- [x] docker-compose version
docker-compose version 1.24.0, build 0aa59064
docker-py version: 3.7.2
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018

**Comment by dhsathiya** [comment]
We have implemented PHP update feature as well as PHP 7.4 support in [EasyEngine v4.0.15](https://github.com/EasyEngine/easyengine/releases/tag/v4.0.15)
