### ISSUE TITLE
EasyEngine V3 breaking when installing nginx package on Debian 8.

### ISSUE THREAD

**Issue by ikolubr** [EasyEngine/easyengine#1441]
I believe nginx got updated on dotdeb and it is breaking the installation on Debian 8
Log:
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nginx-custom : Depends: nginx-common (= 1.14.0-1ppa~stable) but 1.14.2-1~dotdeb+8.1 is to be installed
 nginx-ee : Depends: nginx-common (= 1.14.0-1ppa~stable) but 1.14.2-1~dotdeb+8.1 is to be installed
E: Unable to correct problems, you have held broken packages.

If you could help, that would be very appreciated.

**Comment by kirtangajjar** [comment]
EasyEngine v3 issues are no longer being tracked here. [WordOps](https://wordops.net/) is a good alternative of EEv3
