### ISSUE TITLE
Can't restart site

### ISSUE THREAD

**Issue by LongDe-ACB** [EasyEngine/easyengine#1445]
Hello!
I want restart my site. But i can't restart. It's error:

`root@VPS-DangLongDe:/# ee site restart dearrainy.com
Restarting nginx
Restarting dearrainycom_nginx_1 ... done                                                                                                                                                                                          
Restarting php
Restarting dearrainycom_php_1 ... error                                                                                                                                                                                           
ERROR: for dearrainycom_php_1  Cannot restart container 12789e66ae77b23df93cb0cb39eee8a4f305c5ce098b67131d8e303ef7a6ccd3: OCI runtime create failed: container with id exists: 12789e66ae77b23df93cb0cb39eee8a4f305c5ce098b67131d8e303ef7a6ccd3: unknown`

Please help me! Mysite error 505.
Thank's very much!

**Comment by nordurljosahvida** [comment]
+1

**Comment by L0RD-ZER0** [comment]
Please update EasyEngine to the latest version using ``ee cli update`` command. This issue has been resolved in newer EasyEngine releases.
