### ISSUE TITLE
PDO_MYSQL extension of PHP

### ISSUE THREAD

**Issue by kanet0x** [EasyEngine/easyengine#1453]
Can someone help me solve this error when I try to use the pdo_mysql plugin

I tried running this command

ee shell example.com --command = ‘docker-php-ext-install pdo_mysql’ --user = root

The command is executed successfully, but there is no effect on the plugin.

but it still did not work, I tried to rename some things in php.ini and also without success,

I also restarted the ngnix service and nothing was resolved.

Please, if someone knows how to solve it and I can write it step by step.

**Comment by mrrobot47** [comment]
This has been fixed. `pdo_mysql` is there by default in the latest version of EasyEngine.
Update your EE to latest via: `ee cli update --yes`
