### ISSUE TITLE
New Relic, docker and PHP container problem

### ISSUE THREAD

**Issue by slaklad** [EasyEngine/easyengine#1455]
Hi,

Trying to setup New Relic following the official EE docs https://easyengine.io/handbook/configure-new-relic-in-ee4/ . When it comes to the point to disable and enable site. PHP container loops restarting forever.

I tried docker-compose down and up and that’s what I get:

docker-compose up
Starting 5290201108_mailhog_1 … done
Starting 5290201108_php_1 … done
Starting 5290201108_postfix_1 … done
Starting 5290201108_nginx_1 … done
Attaching to 5290201108_postfix_1, 5290201108_mailhog_1, 5290201108_php_1, 5290201108_nginx_1
mailhog_1 | 2020/05/07 14:58:51 Using in-memory storage
mailhog_1 | 2020/05/07 14:58:51 [SMTP] Binding to address: 0.0.0.0:1025
mailhog_1 | [HTTP] Binding to address: 0.0.0.0:8025
mailhog_1 | Creating API v1 with WebPath:
mailhog_1 | Creating API v2 with WebPath:
mailhog_1 | 2020/05/07 14:58:51 Serving under http://0.0.0.0:8025/
php_1 | sed: couldn’t open temporary file /usr/local/etc/php/conf.d/sedPtmUY8: Permission denied
5290201108_php_1 exited with code 4
php_1 | sed: couldn’t open temporary file /usr/local/etc/php/conf.d/sedEqEVux: Permission denied
php_1 | sed: couldn’t open temporary file /usr/local/etc/php/conf.d/sedOoYvlu: Permission denied
php_1 | sed: couldn’t open temporary file /usr/local/etc/php/conf.d/sedeKo25n: Permission denied
php_1 | sed: couldn’t open temporary file /usr/local/etc/php/conf.d/sedaWWVKZ: Permission denied
php_1 | sed: couldn’t open temporary file /usr/local/etc/php/conf.d/sed9v2SsB: Permission denied
php_1 | sed: couldn’t open temporary file /usr/local/etc/php/conf.d/sedYaWZD6: Permission denied
php_1 | sed: couldn’t open temporary file /usr/local/etc/php/conf.d/seddoqHrw: Permission denied
php_1 | sed: couldn’t open temporary file /usr/local/etc/php/conf.d/sedrLJ5TQ: Permission denied
php_1 | sed: couldn’t open temporary file /usr/local/etc/php/conf.d/sedZYlPyX: Permission denied
php_1 | sed: couldn’t open temporary file /usr/local/etc/php/conf.d/sedB2uiRM: Permission denied
php_1 | sed: couldn’t open temporary file /usr/local/etc/php/conf.d/sedQJONnK: Permission denied
php_1 | sed: couldn’t open temporary file /usr/local/etc/php/conf.d/sedkdiy9D: Permission denied
php_1 | sed: couldn’t open temporary file /usr/local/etc/php/conf.d/sedP4VPs5: Permission denied
php_1 | sed: couldn’t open temporary file /usr/local/etc/php/conf.d/sedekkIQT: Permission denied
php_1 | sed: couldn’t open temporary file /usr/local/etc/php/conf.d/sedmf211c: Permission denied
php_1 | sed: couldn’t open temporary file /usr/local/etc/php/conf.d/sedPtmUY8: Permission denied
php_1 | sed: couldn’t open temporary file /usr/local/etc/php/conf.d/sedjbgk77: Permission denied
php_1 | sed: couldn’t open temporary file /usr/local/etc/php/conf.d/sedcnAUU2: Permission denied
5290201108_postfix_1 exited with code 1
5290201108_php_1 exited with code 4

Anyone made it to make it work New Relic?

System Information
- [x ] ee cli info

| OS                | Linux 4.4.0-1052-aws #61-Ubuntu SMP Mon Feb 12 23:05:58 UTC 2018 x86_64 |
| Shell             | /bin/bash                                                               |
| PHP binary        | /usr/bin/php7.3                                                         |
| PHP version       | 7.3.17-1+ubuntu16.04.1+deb.sury.org+1                                   |
| php.ini used      | /etc/php/7.3/cli/php.ini                                                |
| EE root dir       | phar://ee.phar                                                          |
| EE vendor dir     | phar://ee.phar/vendor                                                   |
| EE phar path      | /opt/easyengine/sites/52.90.201.108                                     |
| EE packages dir   |                                                                         |
| EE global config  | /opt/easyengine/config/config.yml                                       |
| EE project config |                                                                         |
| EE version        | 4.0.17                                                                  |
+-------------------+-------------------------------
- [ x] lsb_release -a

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial

- [x ] docker version
Docker version 19.03.8, build afacb8b7f0

- [x ] docker-compose version
docker-compose version 1.22.0, build f46880fe

**Comment by freedog96150** [comment]
I have experienced similar issues with Newrelic.  I get logs that indicate they cannot parse the newrelic.ini file and similar permissions errors as shown above.  I could not even use ee service disable newrelic_daemon to undo newrelic and eventually had to go to the docker-compose.yml file for each site and delete the entries relating to newrelic.

**Comment by mrrobot47** [comment]
Thanks for reporting this issue. It has been fixed in the latest EE release and will not be happening from now on while enabling newrelic.

Please update to latest version using: `ee cli update` and then run `ee site enable example.com --refresh` to get this error fixed on sites that are having trouble.
