### ISSUE TITLE
Connect to multiple remote MySQL database and database server (host) choice

### ISSUE THREAD

**Issue by andremacola** [EasyEngine/easyengine#147]
It is possible when creating a site to determine in which database host?

For example. In ee configuration file:

dbhost1: mysql.myhost.com
dbroot1: root
dbpass1: mypassword

dbhost2: mysql.myhost.com
dbroot2: root
dbpass2: mypassword

ee site create mywebsite.com --wpsc --dbhost1
ee site create mywebsite2.com --wpsc --dbhost2

**Comment by rahul286** [comment]
In v4, every site will have its own mysql container. So this is no longer relevant.

Please refer #1001
