### ISSUE TITLE
I having docker compose up error while creating a site

### ISSUE THREAD

**Issue by Sifatul22** [EasyEngine/easyengine#1470]
This issue tracker is only for issues related to EasyEngine. Please use http://community.rtcamp.com/c/easyengine for support questions.

If you feel the issue is a EasyEngine specific issue, please attach the output of the following commands.

**Here is the error I got**
**-[ ] ee site create portland.thewebengineer.com --type=wp --mu=subdir**
Starting site creation.
Configuring project.
Creating WordPress site portland.thewebengineer.com
Copying configuration files.
Starting site's services.
Warning: There was some error in docker-compose up.
Warning: Initiating clean-up.
[portland.thewebengineer.com] site root removed.
Success: Site portland.thewebengineer.com deleted.
Report bugs here: https://github.com/EasyEngine/site-type-wp

System Information
**- [ ] ee cli info**
+-------------------+-----------------------------------------------------------------------------+
| OS                | Linux 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 |
| Shell             | /bin/bash                                                                   |
| PHP binary        | /usr/bin/php7.3                                                             |
| PHP version       | 7.3.21-1+ubuntu18.04.1+deb.sury.org+1                                       |
| php.ini used      | /etc/php/7.3/cli/php.ini                                                    |
| EE root dir       | phar://ee.phar                                                              |
| EE vendor dir     | phar://ee.phar/vendor                                                       |
| EE phar path      | /root                                                                       |
| EE packages dir   |                                                                             |
| EE global config  | /opt/easyengine/config/config.yml                                           |
| EE project config |                                                                             |
| EE version        | 4.1.4                                                                       |
+-------------------+-----------------------------------------------------------------------------+

**- [ ] lsb_release -a**
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic

**- [ ] docker version**
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:07 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**- [ ] docker-compose version**
docker-compose version 1.22.0, build f46880fe
docker-py version: 3.4.1
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0f  25 May 2017

**Comment by kirtangajjar** [comment]
For support related queries, please post at https://community.easyengine.io/.
