### ISSUE TITLE
The container created with the php56 doesn’t include phpredis extension

### ISSUE THREAD

**Issue by Chipmank** [EasyEngine/easyengine#1472]
The container created with the php56 doesn’t include phpredis extension

How could it be installed?

System Information
-OS                | Linux 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 |
| Shell             | /bin/bash                                                                 |
| PHP binary        | /usr/bin/php7.4                                                           |
| PHP version       | 7.4.10                                                                    |
| php.ini used      | /etc/php/7.4/cli/php.ini                                                  |
| EE root dir       | phar://ee.phar                                                            |
| EE vendor dir     | phar://ee.phar/vendor                                                     |
| EE phar path      | /root                                                                     |
| EE packages dir   |                                                                           |
| EE global config  | /opt/easyengine/config/config.yml                                         |
| EE project config |                                                                           |
| EE version        | 4.1.3

**Comment by L0RD-ZER0** [comment]
To install customised extensions in a running container, you can use the ``ee shell`` command to get a shell session inside the container for PHP, then run the relevant installations commands for the extension mentioned.
