### ISSUE TITLE
Can't add more than 27 websites in Easyengine

### ISSUE THREAD

**Issue by sandeepkapri** [EasyEngine/easyengine#1482]
This issue tracker is only for issues related to EasyEngine. Please use http://community.rtcamp.com/c/easyengine for support questions.

If you feel the issue is a EasyEngine specific issue, please attach the output of the following commands.

System Information
- [ ] ee cli info
- [ ] lsb_release -a
- [ ] docker version
- [ ] docker-compose version

**Comment by kirtangajjar** [comment]
This is a known limitation. We have a fix for it in the pipeline.
