### ISSUE TITLE
JSON module installed but still getting Fatal Error JSON plugin needed

### ISSUE THREAD

**Issue by aljaz0** [EasyEngine/easyengine#1487]
As stated in subject upon installation of latest  EasyEngine it installs but crashes with the error stating the php JSON plugin is missing. I have checked with apt list --installed and it shows the plugin php7.3-json is installed. If i try to run ee it crashes with the same error. 
I am including the error text and the required outputs for lsb_release and docker 
[easyengine errors.txt](https://github.com/EasyEngine/easyengine/files/5647291/easyengine.errors.txt)

**Comment by kirtangajjar** [comment]
@aljaz0 Can you share the output of `php -v` ?

**Comment by aljaz0** [comment]
yes, here it is 

PHP 7.3.19-1~deb10u1 (cli) (built: Jul  5 2020 06:46:45) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.19, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.19-1~deb10u1, Copyright (c) 1999-2018, by Zend Technologies

**Comment by kirtangajjar** [comment]
@aljaz0  Okay, now can you show us the output of 
```
which php
php -m
sudo update-alternatives --list php
```

**Comment by kirtangajjar** [comment]
Closing this issue as stale. Feel free to reopen the issue if you're still facing this issue.
