### ISSUE TITLE
easyengine connect to remote sql server

### ISSUE THREAD

**Issue by vncloudsco** [EasyEngine/easyengine#1521]
i use wordpress, i want when i create a website there is an option to let me not use sql on my server i want it to connect to a mysql server i specify elsewhere how can i do this

**Comment by dhsathiya** [comment]
You can update WordPress's wp-config.php file with your DB-related parameters.
```php
/** The name of the database for WordPress */
define( 'DB_NAME', 'db_name' );

/** MySQL database username */
define( 'DB_USER', 'awesome-user' );

/** MySQL database password */
define( 'DB_PASSWORD', 'P4ssw0rd' );

/** MySQL hostname */
define( 'DB_HOST', 'global-db:3306' );
```
