### ISSUE TITLE
Windows SubSystem For Linux (WSL) issue 

### ISSUE THREAD

**Issue by jamsheerkrd** [EasyEngine/easyengine#1578]
Cannot install site in WSL Ubuntu 
Shows error `Warning: Failed to create "/opt/easyengine/services/nginx-proxy/conf.d": mkdir(): File exists`
 
![image](https://user-images.githubusercontent.com/3595187/133240987-ccc2ddc1-9f45-41c0-beb8-9f0fbe3fba7b.png)

**Comment by kirtangajjar** [comment]
@jamsheerkrd We're aware of this issue, but I'm not sure we will take it up for fixing since we don't support windows. 

Feel free to contribute incase you've found a fix :)
