### ISSUE TITLE
No user has SFTP access to site folders. Fresh setup

### ISSUE THREAD

**Issue by Th0rHere** [EasyEngine/easyengine#1631]
Just get permission denied when trying to access the folders.

Tried using the SFTP guide to setup container and mount volumes that way, but doesn't seem to be working at all. If someone has a guide on how that is suppose to work, but checking docker ps it was showing it as running, however trying to connect via port 2222 just doesn't connect.

**Comment by Th0rHere** [comment]
Will to pay for support on this. Been wasting time trying to find alternatives without breaking anything

**Comment by mrrobot47** [comment]
https://easyengine.io/handbook/configure-sftp-on-ee4-server/
