### ISSUE TITLE
New Install fails with PHP Fatal error

### ISSUE THREAD

**Issue by julianengel** [EasyEngine/easyengine#1635]
This issue tracker is only for issues related to EasyEngine. Please use http://community.rtcamp.com/c/easyengine for support questions.

If you feel the issue is a EasyEngine specific issue, please attach the output of the following commands.

System Information
- [x] ee cli info

```
PHP Fatal error:  Uncaught TypeError: array_pop(): Argument #1 ($array) must be of type array, bool given in phar:///usr/local/bin/ee/php/class-ee.php:324
Stack trace:
#0 phar:///usr/local/bin/ee/php/class-ee.php(324): array_pop()
#1 phar:///usr/local/bin/ee/php/commands/cli.php(7): EE::add_command()
#2 phar:///usr/local/bin/ee/php/EE/Bootstrap/RegisterFrameworkCommands.php(32): include_once('...')
#3 phar:///usr/local/bin/ee/php/bootstrap.php(74): EE\Bootstrap\RegisterFrameworkCommands->process()
#4 phar:///usr/local/bin/ee/php/init-ee.php(27): EE\bootstrap()
#5 phar:///usr/local/bin/ee/php/boot-phar.php(8): include('...')
#6 /usr/local/bin/ee(5): include('...')
#7 {main}
  thrown in phar:///usr/local/bin/ee/php/class-ee.php on line 324

```

- [x] lsb_release -a

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
```

- [x] docker version

```
Client: Docker Engine - Community
 Version:           20.10.11
 API version:       1.41
 Go version:        go1.16.9
 Git commit:        dea9396
 Built:             Thu Nov 18 00:37:06 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
```

- [x] docker-compose version
```
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

Upon trying to install on a brand-new droplet, it fails after pulling the easy-engine docker images. When trying to run anything ee related, the above issue pops up.

**Comment by julianengel** [comment]
@kirtangajjar When looking into the install script and log, this is caused when trying to run the phar. `Running ee cli update --nightly` is not an option, as that fails with the same bug as above.

**Comment by kirtangajjar** [comment]
@julianengel What's the output of `php -v`

**Comment by kirtangajjar** [comment]
By any chance are you using PHP 8.1? Can you switch to PHP 8.0 and see if the issue still persists?

**Comment by julianengel** [comment]
@kirtangajjar Unfortunately 8.0

PHP 8.0.13 (cli) (built: Nov 19 2021 06:34:49) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.13, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.13, Copyright (c), by Zend Technologies

**Comment by julianengel** [comment]
Tried running it across 5 droplets, issue persistent on all, with `apt-get upgrade` and without.

**Comment by mrrobot47** [comment]
@julianengel the issue has been identified. I will update here when the fix is live.

**Comment by mrrobot47** [comment]
This has been fixed. Please install on a fresh machine.

**Comment by julianengel** [comment]
Thank you @mrrobot47  and @kirtangajjar, the fix you released has worked on a clean machine!
