### ISSUE TITLE
SSL cert revoked and broken if moving domain to another site

### ISSUE THREAD

**Issue by ssuess** [EasyEngine/easyengine#1639]
as mentioned here: https://github.com/EasyEngine/easyengine/discussions/1627

This has happened to me on several different ee systems, either newly installed or upgraded to 4.4.3 (both on ubuntu 20):

TO REPRODUCE:
1. create a site (example.com) and enable ssl
2. create a second site (test.example.com) and enable ssl
3. `ee site delete example.com`
4. `ee site update test.example.com --add-alias-domains="example.com"`

RESULT:
Visiting https://example.com fails with notice of revoked cert, no amount of attempting to renew certs will work without manipulating the file system, see workaround.

WORKAROUND:
1. `ee site update test.example.com --ssl="off"`
2. One must then go into /opt/easyengine/services/nginx-proxy/certs and remove cert for test.example.com
3. `ee site update test.example.com --ssl=le`

**Comment by mrrobot47** [comment]
@ssuess Fix for this is now available in the nightly release. Please update to the latest nightly via `ee cli update --nightly` and test this.

**Comment by ssuess** [comment]
thanks!
