### ISSUE TITLE
Add webp to Nginx configuration 

### ISSUE THREAD

**Issue by danish17** [EasyEngine/easyengine#1655]
Currently, in EasyEngine site-specific Nginx configs, we cache static files but we do not provision `webp` files. 
```
location ~* \.(ogg|ogv|svg|svgz|eot|otf|woff|woff2|mp4|ttf|rss|atom|jpg|jpeg|gif|png|ico|zip|tgz|gz|rar|bz2|doc|xls|exe|ppt|tar|mid|midi|wav|bmp|rtf|swf)$ {...
```

Since, `webp` is increasingly becoming the de facto standard of next gen image formats, it might be a good idea to add support for it.

**Comment by cerbenus** [comment]
Agreed. Please add webp support to EE/Nginx

**Comment by dhsathiya** [comment]
https://github.com/EasyEngine/dockerfiles/pull/149
https://github.com/EasyEngine/site-type-wp/pull/219
https://github.com/EasyEngine/site-command/pull/425

**Comment by prionkor** [comment]
this will be a nice to have feature, although if you are using cdn like cloudflare it should be handled by default.
