### ISSUE TITLE
Mustache.php v2.14.1 security release

### ISSUE THREAD

**Issue by bobthecow** [EasyEngine/easyengine#1658]
Mustache.php v2.14.1 was released today. It contains a security improvement, and should be a straightforward update.

https://github.com/bobthecow/mustache.php/releases/tag/v2.14.1

(You're receiving this issue because Packagist says you depend on Mustache.php)

**Comment by mrrobot47** [comment]
Thanks for the issue. Fixed in https://github.com/EasyEngine/easyengine/commit/4a512d5fa1d426528de61b35a8b2fa8eae32c311
