### ISSUE TITLE
Why latest distros not supported?

### ISSUE THREAD

**Issue by kangarooo** [EasyEngine/easyengine#1676]
Latest today version
is project dead?
https://easyengine.io/faq/
Q 9. Which operating systems are supported by EasyEngine?
v3 and v4 support Ubuntu version 12.04 , 14.04, 16.04, 18.04 and Debian 7 & 8.

CentOS or any other Linux Distro is not currently supported. They are also not on the product roadmap in the near future.

**Comment by mikelittle** [comment]
On the [readme](https://github.com/EasyEngine/easyengine) for this project it states:

```
For Linux, we have created an installer script which will install all the dependencies for you. We have tested this on Ubuntu 14.04, 16.04, 18.04, 20.04 and Debian 8, Debian 10.
```

The last release was December 2021, and I think there have been commits to the main repo in January

**Comment by kirtangajjar** [comment]
@kangarooo as @mikelittle pointed out, the content on the website was older than the one in the repo. I have updated the content on the website to match what is in the repo.

Regarding running EasyEngine on CentOS, you can run EasyEngine on any Linux machine that [has the necessary dependencies ](https://github.com/EasyEngine/easyengine#requirements). Just [grab the latest PHAR](https://github.com/EasyEngine/easyengine/releases) and you should be good to go. 

LMK if you have any further questions :)
