### ISSUE TITLE
[release] easyengine.phar is not uploaded for the 4.5.5 release

### ISSUE THREAD

**Issue by chenrui333** [EasyEngine/easyengine#1694]
This issue tracker is only for issues related to EasyEngine. Please use https://github.com/EasyEngine/easyengine/discussions for support questions.

If you feel the issue is a EasyEngine specific issue, please attach the output of the following commands.

System Information
- [ ] ee cli info
- [ ] lsb_release -a
- [ ] docker version
- [ ] docker-compose version

----

not quite sure if this should go to discussion or not. Thanks!

**Comment by mrrobot47** [comment]
https://github.com/EasyEngine/easyengine/releases/download/v4.5.5/easyengine.phar
