### ISSUE TITLE
Error installing EasyEngine

### ISSUE THREAD

**Issue by afruit** [EasyEngine/easyengine#1741]
I'm trying to install EasyEngine on a new Digital Ocean Droplet, just as I have done many times before on other droplets, however I am met with errors this time. 

I have attached a txt with the terminal output from running the EasyEngine install command: 

`wget -qO ee rt.cx/ee4 && sudo bash ee`

[see attached txt file for resulting output]
[easyengine-output.txt](https://github.com/EasyEngine/easyengine/files/9932114/easyengine-output.txt)

----------------------------

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.10
Release:        22.10
Codename:       kinetic

----------------------------

docker version
Client: Docker Engine - Community
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:02:14 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 18:00:01 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.9
  GitCommit:        1c90a442489720eec95342e1789ee8a5e1b9536f
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

----------------------------

docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

[easyengine-output.txt](https://github.com/EasyEngine/easyengine/files/9932114/easyengine-output.txt)

**Comment by afruit** [comment]
### **Update:**

I Tried again with a previous version of Ubuntu **[v 22.04 (LTS) x64]**, and everything worked as expected.

Seems like whatever the conflict is, it exists in Ubuntu 22.10 x64 (which is the default selected version of Ubuntu when creating a new Droplet in Digital Ocean).

**Comment by joebailey26** [comment]
The readme suggests they've only tested on 22.04 and below

> For Linux, we have created an installer script that will install all the dependencies for you. We have tested this on Ubuntu 14.04, 16.04, 18.04, 20.04, 22.04 and Debian 8, Debian 10.

**Comment by L0RD-ZER0** [comment]
This issue stems from the PHP PPA being added , ``ppa:ondrej/php``, to your ubuntu system during the installation. During the installation, the script tries to install a version of PHP compatible with the phar for EasyEngine.

The source PPA doesn't have a release file, which causes apt to not proceed with a PHP install, which in turn doesn't allow EasyEngine to run, due to a lack of php cli required to execute the phar.

Please consider using a version of Ubuntu/Debian for which the release file for this PPA exists.
