### ISSUE TITLE
PHPRedis not available on PHP 8.1

### ISSUE THREAD

**Issue by joebailey26** [EasyEngine/easyengine#1742]
Is there a way to add this package to the PHP 8.1 docker container?

**Comment by joebailey26** [comment]
I disabled and re-enabled the site and PHPRedis worked again.

**Comment by joebailey26** [comment]
I've now done a thorough test and ensured PHPRedis is working as expected on PHP8, which it is. But if I update the site to PHP8.1, I get `Warning! PHPRedis extension is unavailable, which is required by WP Redis object cache.` And I can't see redis in the output of `php -info` either.

**Comment by joebailey26** [comment]
After a bit of digging, I found that the packages were being installed, but not included in PHP's extensions. There were 4 packages total that hadn't made it to the PHP8.1 install, `apcu`, `mcrypt`, `redis`, and `timezonedb`. I realised there wasn't an .ini file for these in the following directory: `/var/lib/docker/volumes/wwwjoebaileyphotographycom_config_php/_data/php/conf.d` so I copied the files over from a PHP8.0 site, reloaded the PHP8.1 site and now the extensions are working.

I wonder if somewhere in EasyEngine's build step these files have just been missed and need to be added?

**Comment by joebailey26** [comment]
Further update, this is only happening when updating sites. New sites are not affected by the lack of files.

**Comment by L0RD-ZER0** [comment]
Please update EasyEngine to the latest version using ``ee cli update`` command. This issue has been resolved in newer EasyEngine releases. In order for a fresh installation, consider using the command ``wget -qO ee rt.cx/ee4 && sudo bash ee`` to use the automated installation script to install the latest version of EasyEngine.
