### ISSUE TITLE
Install script not working today. 

### ISSUE THREAD

**Issue by codeverlan** [EasyEngine/easyengine#1802]
Tried to install this morning. The script is operating at a CRAWL. I know it is not usually this way. How do you install via cloning the repo?

**Comment by mrrobot47** [comment]
The issue was temporary due to GitHub incident. (Setup script is a short link to GitHub URL only.)

ee can alternatively also be installed via:
````bash
curl -fsSL https://raw.githubusercontent.com/EasyEngine/installer/master/setup.sh | bash
````
