### ISSUE TITLE
Ownership index.php leads to failure to create php site

### ISSUE THREAD

**Issue by hnzz** [EasyEngine/easyengine#1806]
Creating a PHP site fails as the index.php file is owned by root. When creating a PHP site with —skip-status-checks and afterwards changing the ownership of index.php it all works …

**Comment by L0RD-ZER0** [comment]
This issue has been resolved in newer EasyEngine releases.. Please update EasyEngine to the latest version using ``ee cli update`` command.  In order for a fresh installation instead, consider using the command ``wget -qO ee rt.cx/ee4 && sudo bash ee`` to use the automated installation script to install the latest version of EasyEngine.

This issue occurs as during the site creation, EasyEngine tries to check if the created site works, and if it doesn't, considers the created output faulty, and rolls back the changes made to create the site. So if you skip tests, and fix the permission issue with ``index.php``, site works. As mentioned before, consider updating EasyEngine to the latest version using the aforementioned command.
