### ISSUE TITLE
Error when enabling SSL with creation or updating

### ISSUE THREAD

**Issue by iamimmanuelraj** [EasyEngine/easyengine#1823]
This issue tracker is only for issues related to EasyEngine. Please use https://github.com/EasyEngine/easyengine/discussions for support questions.

If you feel the issue is a EasyEngine specific issue, please attach the output of the following commands.

System Information
- [x] ee cli info
╰─➤  ee cli  info                                                                                                                         130 ↵
+-------------------+-----------------------------------------------------------------------------+
| OS                | Linux 5.15.0-101-generic #111-Ubuntu SMP Tue Mar 5 20:16:58 UTC 2024 x86_64 |
| Shell             | /usr/bin/zsh                                                                |
| PHP binary        | /usr/bin/php8.3                                                             |
| PHP version       | 8.3.4                                                                       |
| php.ini used      | /etc/php/8.3/cli/php.ini                                                    |
| EE root dir       | phar://ee.phar                                                              |
| EE vendor dir     | phar://ee.phar/vendor                                                       |
| EE phar path      | /opt/easyengine/sites/immanuelraj.rt.gw                                     |
| EE packages dir   |                                                                             |
| EE global config  | /opt/easyengine/config/config.yml                                           |
| EE project config |                                                                             |
| EE version        | 4.6.6                                                                       |
+-------------------+-----------------------------------------------------------------------------+

- [x] lsb_release -a
╰─➤  lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy
- [x] docker version
╰─➤  docker version
Client: Docker Engine - Community
 Version:           26.0.0
 API version:       1.45
 Go version:        go1.21.8
 Git commit:        2ae903e
 Built:             Wed Mar 20 15:17:48 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          26.0.0
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.8
  Git commit:       8b79278
  Built:            Wed Mar 20 15:17:48 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
- [x] docker-compose version
╰─➤  docker-compose version
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

<img width="1439" alt="image" src="https://github.com/EasyEngine/easyengine/assets/26855364/1c6ce896-d4af-4523-aede-799c217d51b4">

<img width="815" alt="image" src="https://github.com/EasyEngine/easyengine/assets/26855364/9cee0be6-c240-4b1b-b7c0-dfe99513c63c">

Happens when using --ssl-le when creating or updating site

FIX : go to your site: /opt/easyengine/sites/example.com and run `docker compose down` then `docker-compose -f docker-compose.yml  up -d nginx` and `docker compose up` then you can rerun the command with --ssl and it will work

Thanks to @xieyt for the fix

**Comment by dlackty** [comment]
For those who uses ubuntu 20.04, you could downgrade docker-ce via following command as a workaround:

```
apt-get install docker-ce=5:25.0.5-1~ubuntu.20.04~focal
```

**Comment by mrrobot47** [comment]
The issue has been fixed in https://github.com/EasyEngine/easyengine/releases/tag/v4.7.0
Which supports latest `docker` and `docker compose`

**Comment by mrrobot47** [comment]
Update your setup using command
```bash
ee cli update
```
