### ISSUE TITLE
docker-compose errors [incompatible Docker Compose v2)

### ISSUE THREAD

**Issue by pagaling** [EasyEngine/easyengine#1825]
### Discussed in https://github.com/EasyEngine/easyengine/discussions/1822

<div type='discussions-op-text'>

<sup>Originally posted by **raduganea** April  2, 2024</sup>
Hi guys, anyone facing docker-compose issues lately?

**This is my error from ee.log:**
Failed to execute script docker-compose  ERROR: for 0b2ffadff097_sitecom_nginx_1  'ContainerConfig'  ERROR: for nginx  'ContainerConfig' Traceback (most recent call last):   File "docker-compose", line 3, in <module>   File "compose/cli/main.py", line 81, in main   File "compose/cli/main.py", line 203, in perform_command   File "compose/metrics/decorator.py", line 18, in wrapper   File "compose/cli/main.py", line 1186, in up   File "compose/cli/main.py", line 1182, in up   File "compose/project.py", line 702, in up   File "compose/parallel.py", line 108, in parallel_execute   File "compose/p
arallel.py", line 206, in producer   File "compose/project.py", line 688, in do   File "compose/service.py", line 581, in execute_convergence_plan   File
"compose/service.py", line 503, in _execute_convergence_recreate   File "compose/parallel.py", line 108, in parallel_execute   File "compose/parallel.py", line 206, in producer   File "compose/service.py", line 496, in recreate   File "compose/service.py", line 615, in recreate_container   File "compose/ser
vice.py", line 334, in create_container   File "compose/service.py", line 922, in _get_container_create_options   File "compose/service.py", line 962, in
_build_container_volume_options   File "compose/service.py", line 1549, in merge_volume_bindings   File "compose/service.py", line 1579, in get_container_data_volumes KeyError: 'ContainerConfig'

**ee cli info**
OS                | Linux 5.15.0-91-generic #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64 
Shell             | /bin/bash                                                                   
PHP binary        | /usr/bin/php8.0                                                             
PHP version       | 8.0.30                                                                      
php.ini used      | /etc/php/8.0/cli/php.ini                                                    
EE root dir       | phar://ee.phar                                                              
EE vendor dir     | phar://ee.phar/vendor                                                       
EE phar path      | /root                                                                       
EE packages dir   |                                                                             
EE global config  | /opt/easyengine/config/config.yml                                           
EE project config |                                                                             
EE version        | 4.6.6

**lsb_release -a**
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy

**docker version**
Client: Docker Engine - Community
 Version:           26.0.0
 API version:       1.45
 Go version:        go1.21.8
 Git commit:        2ae903e
 Built:             Wed Mar 20 15:17:48 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          26.0.0
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.8
  Git commit:       8b79278
  Built:            Wed Mar 20 15:17:48 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**docker-compose version**
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019</div>

**Comment by L0RD-ZER0** [comment]
The latest version of EasyEngine adds support for Docker Compose v2. You can find out more about the latest release at our [Release v4.7.0 Blogpost](https://easyengine.io/blog/easyengine-v4-7-0-released/).

Please update EasyEngine to the latest version using ``ee cli update`` command.  In order for a fresh installation instead, consider using the command ``wget -qO ee rt.cx/ee4 && sudo bash ee`` to use the automated installation script to install the latest version of EasyEngine.
