### ISSUE TITLE
Ofelia (ee cron run-now) doesn't work

### ISSUE THREAD

**Issue by aippolito** [EasyEngine/easyengine#1840]
This issue tracker is only for issues related to EasyEngine. Please use https://github.com/EasyEngine/easyengine/discussions for support questions.

If you feel the issue is a EasyEngine specific issue, please attach the output of the following commands.

System Information
ee cli info
+-------------------+------------------------------------------------------------------------------------+
| OS                | Linux 6.5.0-1023-oracle #23~22.04.1-Ubuntu SMP Thu May  2 14:36:16 UTC 2024 x86_64 |
| Shell             | /bin/bash                                                                          |
| PHP binary        | /usr/bin/php8.3                                                                    |
| PHP version       | 8.3.7                                                                              |
| php.ini used      | /etc/php/8.3/cli/php.ini                                                           |
| EE root dir       | phar://ee.phar                                                                     |
| EE vendor dir     | phar://ee.phar/vendor                                                              |
| EE phar path      | /var/lib/docker/volumes/appartamentilenaviincieloit_htdocs/_data                   |
| EE packages dir   |                                                                                    |
| EE global config  | /opt/easyengine/config/config.yml                                                  |
| EE project config |                                                                                    |
| EE version        | 4.7.0                                                                              |
+-------------------+------------------------------------------------------------------------------------+

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy

docker version
Client: Docker Engine - Community
 Version:           26.1.3
 API version:       1.45
 Go version:        go1.21.10
 Git commit:        b72abbb
 Built:             Thu May 16 08:33:29 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          26.1.3
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.10
  Git commit:       8e96db1
  Built:            Thu May 16 08:33:29 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.32
  GitCommit:        8b3b7ca2e5ce38e8f31a34f35b2b68ceb8470d89
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

docker-compose version
Docker Compose version v2.27.0

ee cron list
+----+------------------------------+----------+---------------------------------------------+----------------+
| id | site_url                     | user     | command                                     | schedule       |
+----+------------------------------+----------+---------------------------------------------+----------------+
| 1  | example.it | www-data | sh -c 'wp cron event run --due-now'         | 0 8/10 * * * * |
+----+------------------------------+----------+---------------------------------------------+----------------+

ee cron run-now 1
Error response from daemon: No such container: exampleit_php_1

**Real PHP container site is named: exampleit-php-1 and not exampleit_php_1**
Workaround is to use ee shell command 

ee shell --command='wp cron event run --due-now'
Executed the cron event 'action_scheduler_run_queue' in 0.026s.
Executed the cron event 'wp_privacy_delete_old_export_files' in 0.01s.
Executed the cron event 'recovery_mode_clean_expired_keys' in 0.007s.
Executed the cron event 'wp_version_check' in 2.709s.
Executed the cron event 'wp_update_plugins' in 0.465s.
Executed the cron event 'wp_update_themes' in 0.009s.
Executed the cron event 'wp_scheduled_delete' in 0.298s.
Executed the cron event 'delete_expired_transients' in 0.007s.
Executed the cron event 'wpseo-reindex-links' in 0.006s.
Executed the cron event 'mwp_update_public_keys' in 0.006s.
Executed the cron event 'sucuriscan_scheduled_scan' in 4.556s.
Executed the cron event 'rt_wp_nginx_helper_check_log_file_size_daily' in 0.025s.
Executed the cron event 'sucuriscan_autoseckeyupdater' in 0.352s.
Executed the cron event 'wpml-tm-check-overdue-jobs-event' in 0.01s.
Executed the cron event 'wp_scheduled_auto_draft_delete' in 0.007s.
Executed the cron event 'wp_update_user_counts' in 0.006s.
Executed the cron event 'wp_delete_temp_updater_backups' in 0.007s.
Executed the cron event 'wpseo_start_cleanup_indexables' in 0.023s.
Executed the cron event 'upgrader_scheduled_cleanup' in 0.003s.
Executed the cron event 'upgrader_scheduled_cleanup' in 0.003s.
Executed the cron event 'upgrader_scheduled_cleanup' in 0.003s.
Executed the cron event 'update_wpml_config_index' in 0.073s.
Executed the cron event 'wpseo-reindex' in 0.006s.
Executed the cron event 'wpseo_permalink_structure_check' in 0.01s.
Executed the cron event 'flamingo_daily_cron_job' in 0.537s.
Executed the cron event 'wpseo_cleanup_cron' in 0.009s.
Success: Executed a total of 26 cron events.

**Comment by mrrobot47** [comment]
This issue has been fixed in `v4.7.1` https://github.com/EasyEngine/easyengine/releases/tag/v4.7.1

Please update your EasyEngine install using `ee cli update` and the crons should start working normally.
