### ISSUE TITLE
Proxy cache not work

### ISSUE THREAD

**Issue by vasiler** [EasyEngine/easyengine#1842]
proxy cache flag not work for me. Or yes, or no, is always disabled.

System Information
- [ ] ee cli info
-  OS                | Linux 4.19.0-26-amd64 #1 SMP Debia |
|                   | n 4.19.304-1 (2024-01-09) x86_64   |
| Shell             | /bin/bash                          |
| PHP binary        | /usr/bin/php8.0                    |
| PHP version       | 8.0.30                             |
| php.ini used      | /etc/php/8.0/cli/php.ini           |
| EE root dir       | phar://ee.phar                     |
| EE vendor dir     | phar://ee.phar/vendor              |
| EE phar path      | /root                              |
| EE packages dir   |                                    |
| EE global config  | /opt/easyengine/config/config.yml  |
| EE project config |                                    |
| EE version        | 4.7.1
- [ ] lsb_release -a

No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

- [ ] docker version

Client: Docker Engine - Community
 Version:           26.1.1
 API version:       1.45
 Go version:        go1.21.9
 Git commit:        4cf5afa
 Built:             Tue Apr 30 11:48:14 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          26.1.1
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.9
  Git commit:       ac2de55
  Built:            Tue Apr 30 11:48:14 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.31
  GitCommit:        e377cd56a71523140ca6ae87e30244719194a521
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

- [ ] docker-compose version
Docker Compose version v2.27.0

**Comment by uebmaster** [comment]
I don't know a lot, but would you write the sentence used for create the site?

**Comment by vasiler** [comment]
> I don't know a lot, but would you write the sentence used for create the site?

My mistake. I used “yes” instead of “on”
