### ISSUE TITLE
Downloading wp-core with other locales fails inside the container

### ISSUE THREAD

**Issue by L0RD-ZER0** [EasyEngine/easyengine#1874]
### Discussed in https://github.com/EasyEngine/easyengine/discussions/1873

<div type='discussions-op-text'>

<sup>Originally posted by **oitent** November 14, 2024</sup>
As of last Wordpress Update 6.7 I simply cannot create a new wordpress site.

Im using EE4 in a brand new DigitalOcean droplet. 

Command used (with example placeholders):
```
ee site create mysitedomain.com.br --type=wp --title="My Title" --locale=pt_BR --ssl=le
```
Anyone with the same issue?

```

Starting site creation.
Configuring project.
Creating WordPress site alfecafe.com.br
Copying configuration files.
Starting site's services.
Downloading and configuring WordPress.
Unable to download wp core. Retrying...
Unable to download wp core. Retrying...
Unable to download wp core. Retrying...
Unable to download wp core. Retrying...
Unable to download wp core. Retrying...
Warning: Couldn't connect to global-db:3306 or there was issue in `wp config create`. Please check logs.
Warning: Initiating clean-up.
```</div>

**Comment by L0RD-ZER0** [comment]
### We have following findings in our internal findings:

#### When specifying Portuguese - BRAZIL (`pt_BR`) locale:
![image](https://github.com/user-attachments/assets/e03da772-8acf-4e2d-922c-711694f44f7f)

#### When not specifying a locale:
![image](https://github.com/user-attachments/assets/9751c5e5-7f1e-4004-88e8-bfdbf44f301c)

#### When specifying other locales (`hi_IN`, `en_IN`, `en`): 
![image](https://github.com/user-attachments/assets/9c453f89-7c28-4ebc-9a96-86ee445884c0)

#### When explicitly specifying the default locale, English - United States (`en_US`):
![image](https://github.com/user-attachments/assets/e391f0e0-a316-475e-ac19-b5ddd1051195)

**Comment by mrrobot47** [comment]
OOM Issue:

```bash
Debug: COMMAND: docker-compose -f docker-compose.yml  exec  --user='www-data' php wp core download --path=/var/www/htdocs --locale='pt_BR'  (18.88s)
Debug: STDOUT: Downloading WordPress 6.7 (pt_BR)...
md5 hash verified: 30f66dcd375fe9cdfa2cafd6c3a8ce50                                                                                                                                     
 (22.859s)                                                                                  
Debug: STDERR: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 36864 bytes) in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Extractor.
php on line 100                         
 (22.86s)                                                                                                                                                                               
Debug: RETURN CODE: 255 (22.86s)        
Debug: ----------------------- (22.86s)                                                     
Unable to download wp core. Retrying...                                                     
```

Fixed in https://github.com/EasyEngine/easyengine/releases/tag/v4.7.6
