### ISSUE TITLE
HTTPS Option for admin pages

### ISSUE THREAD

**Issue by JosefJezek** [EasyEngine/easyengine#220]
Could you add HTTPS Option for admin pages?

Here is script for Create self-signed SSL Certificate
https://gist.github.com/6018928

```
sed -i "/<?php/adefine('FORCE_SSL_ADMIN', true);" $WP_CONFIG
sed -i "/<?php/adefine('FORCE_SSL_LOGIN', true);" $WP_CONFIG
```

**Comment by rahul286** [comment]
Related to https://github.com/rtCamp/easyengine/issues/376

**Comment by rahul286** [comment]
Related to #342

**Comment by rahul286** [comment]
EE supports LetsEncrypt which is free. Its better to put entire site behind SSL.
