### ISSUE TITLE
Log Dashboard - Feature 

### ISSUE THREAD

**Issue by shaneholloman** [EasyEngine/easyengine#256]
This is fairly awesome:
http://www.elasticsearch.org/overview/ see video
http://www.elasticsearch.org/videos/kibana-logstash/

Just FYI I found the above by way of: https://commando.io/ which is a beautiful complement to EE for people with multiple clients where you are hosting them as well as developing

**Comment by MiteshShah** [comment]
How to Install/Setup Guide

ELK - https://miteshshah.github.io/linux/elk/
Logio.org - https://miteshshah.github.io/sysadmin/realtime-log-monitoring-in-your-browser/

**Comment by cm896** [comment]
+1 @MiteshShah Great stuff
