### ISSUE TITLE
Mailpile Integration in EE 1.4?

### ISSUE THREAD

**Issue by gau1991** [EasyEngine/easyengine#265]
magichew wrote:

Whilst I'm patiently waiting the release of EasyEngine 1.4's Mail Server I've been looking around at self hosted email setups and I've come across a really promising looking front end for mail called Mailpile. It's in alpha at the moment but I was wondering if this is something that EE could include as default front end or maybe as an option as to which front end we want to use.

See more info about mailpile at https://www.mailpile.is/

Topic Link: https://rtcamp.com/support/topic/mailpile-integration-in-ee-1-4/

**Comment by rahul286** [comment]
We have dropped webmail support from v4.
