### ISSUE TITLE
Better return path for PHP/WordPress generated mail

### ISSUE THREAD

**Issue by rahul286** [EasyEngine/easyengine#279]
As of now if sender is not specified, PHP sets return path as `user@hostname`. This often creates something like `www-data@xyz.com`.

This can be changed by setting default return path to a nice value.

Edit `vim /etc/php5/fpm/pool.d/www.conf`

Look for line:

`;php_admin_value[sendmail_path] = /usr/sbin/sendmail -t -i -f www@my.domain.com`

Uncomment it and change email address at the end:

`php_admin_value[sendmail_path] = /usr/sbin/sendmail -t -i -f admin@example.com`

**Comment by mbtamuli** [comment]
@rahul286 So it should be admin@domain?

```
admin@example.com
```

**Comment by rahul286** [comment]
@mbtamuli can we set it to ee-admin email from ee config?

**Comment by mbtamuli** [comment]
Yes. This is possible.

CC: @mrrobot47

**Comment by mbtamuli** [comment]
Closed by https://github.com/EasyEngine/site-wp-command/pull/27
