### ISSUE TITLE
CalDAV/CardDAV Integration

### ISSUE THREAD

**Issue by benzon** [EasyEngine/easyengine#285]
Hi,

Your idea with EasyEngine and the upcomming mail feature are greate! BUT! What if you added CalDAV/CardDAV support to the mix? Then you would have the ultimate product, you can sync your mobile calendar and contacts directly with your own system.

This is a feature i miss, i use Google Apps for some other projects, but after they started charging, and i dont use it for E-Mail any more i lack the support of Cal/CardDAV support, so i can stay updated 100%

The greate thing about this, is the different ways to do this integration, SabreDAV looks like a good way to go, and the best part it can be integrated with Roundecube plugin.

**Comment by rahul286** [comment]
We have dropped webmail support from v4 so this is no longer relevant. Sorry.
