### ISSUE TITLE
https site create (SSL support)

### ISSUE THREAD

**Issue by duajanuari** [EasyEngine/easyengine#303]
## Update by @rahul286:

We will be adding this in 2 parts:

In first part, EE will create self-signed cert. Later on, we will add support for SSL provider, may be using API.
### Synatx

New parameter will be added to `ee site` commands: `--ssl`

Possible values

```
--ssl=force (default)
--ssl=opt
```
### Workflow
1. Private Key Generate (keep it to yourself)
2. CSR Generate (send it to SSL provider)
3. CERT File (bundle)
# 

Hello,

I'd like to see an option to create site with https on ee site create, since it's kind of pain to set up https site/wordpress and redirect all http to https;

I've try to set https wordpress up, but not ended well. when i try to redirect all http to https, it ended with redirect loop. I'd love to see if easyengine add this feature

**Comment by ghar** [comment]
Tried this last night -Awesome!

**Comment by christophermuro** [comment]
Thank you - I LOVE easyengine - it's now my go to for building out a webserver.  No more WHM/cPanel/Plesk/Webmin/etc...  No need for all that bloat IMO.  
I am currently running 4 ee servers that I manually added SSL, it's not a big deal but would be nice out of the box, while adding to the wish list, automated pagespeed conf would be nice as well (Y/N or option to include it in the site create flags --pagespeed, since I am really just cut and pasting a few conf/config files and an include in the nginx server block. ;)  I have other wish list feature requests that I'll find an appropriate thread to append.  

+1 for SSL+SPDY and firewall/Fail2Ban + pagespeed conf

**Comment by vijaiaeroastro** [comment]
So you are gonna integrate letsencrypt's acme into easy engine?

**Comment by MACscr** [comment]
Still no SSL support? Pretty much all my sites require it.

**Comment by MattyLB** [comment]
@MACscr - SSL works great when done manually as mentioned near the beginning of this thread and at this link: https://rtcamp.com/wordpress-nginx/tutorials/ssl/thawte/ - I'm using SPDY, stapling and strict transport and it works great! Super fast and A+ ssl ranking...
> server {
> 
>        listen 443 ssl spdy;
>        server_name domain.com www.domain.com;
>
>        ssl on;
>        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
>        ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA:!CAMELLIA;
>
>        ssl_certificate /var/www/domain.com/certs/domain.com.crt;
>        ssl_certificate_key /var/www/domain.com/certs/domain.com.key;
>
>        ssl_buffer_size 8k;
>        ssl_stapling on;
>        ssl_stapling_verify on;
>        ssl_trusted_certificate /etc/nginx/ssl/domain.com/ca-certs.crt;
>        proxy_ssl_session_reuse off;
>        resolver 8.8.8.8 8.8.4.4 valid=300s;
>        resolver_timeout 7s;
>        add_header Alternate-Protocol  443:npn-spdy/3;
>        add_header Strict-Transport-Security max-age=31536000;
>
>        access_log   /var/log/nginx/domain.com.ssl.access.log rt_cache;
>        error_log    /var/log/nginx/domain.com.ssl.error.log;
>        .....
> }
> server {
>
>        listen 80;
>        server_name domain.com www.domain.com;
>        #return 301 https://$server_name$request_uri; *** this one seems to cause unnecessary redirects so I stay away from it.***
>        rewrite ^ https://$server_name$request_uri? permanent;
>
> }

**Comment by rahul286** [comment]
v4 already have LetSencrypt support added. 

Wildcard support and other options are being worked here - https://github.com/EasyEngine/site-command/issues/77
