### ISSUE TITLE
phpbrew support

### ISSUE THREAD

**Issue by rahul286** [EasyEngine/easyengine#308]
**Update:**

Synatx will be:

`ee site create example.com --php=5.3`
`ee site update example.com --php=5.3`

--php will default to latest version
- [ ] We need to check how phpbrew will work with FPM and HHVM

https://github.com/phpbrew/phpbrew

I am thinking to use phpbrew to manage php versions.

As of now `ee` uses latest php only, but in future, when multiuser support and developer-features gets added, there will be use cases for older php versions.

**A sample use-case which is valid now:** 

Some sites use ioncube _(which he highly discourage)_ which many times do not play well with latest php release. 

In those cases, we can put old php version of site with ioncube only, rather than downgrading all sites.

**Comment by nezam05** [comment]
+1, this would be a very good addition to EE. Waiting for it.

**Comment by liquidia** [comment]
Any update on this i have magento module required ioncube but cant not install with latest easyengine stack.

**Comment by mustela** [comment]
Guys this feature would be awesome! 

Is there any workaround to use a different php version?

Thanks!

**Comment by rahul286** [comment]
**Update:** php version change/switch will be handed in v4 using docker image switch
