### ISSUE TITLE
Single WordPress With SubDirectory

### ISSUE THREAD

**Issue by MiteshShah** [EasyEngine/easyengine#31]
``` bash
set $dir "";
if ($request_uri ~ ^/([^/]*)/.*$ ) {
      set $dir1 /$1;
}
location / {
      try_files $uri $uri/  $dir1/index.php?$args;
 }

```

**Comment by rahul286** [comment]
Linked #66

**Comment by puccaso** [comment]
Can we get an update on this item?

Single Install Site on a sub Directory.... 

how does one accomplish it?

i'm using the most recent EE ..

**Comment by kymcarlsson** [comment]
Partially related, but I really like the way Cliff Seal is going about it here: https://youtu.be/pUGrDdvkwtk?t=19m36s

**Comment by rahul286** [comment]
Will be handled in https://github.com/EasyEngine/easyengine/issues/66
