### ISSUE TITLE
ghost blog setup support

### ISSUE THREAD

**Issue by rahul286** [EasyEngine/easyengine#319]
When we will add support for non-wordpress sites, first I wish to add is support for ghost blogging platform.

I found this - https://gist.github.com/pnommensen/707b5519766ba45366dd

So creating task here for future.

ee command could be:

```
ee site create example.com --ghost
```

**Comment by ithardeep** [comment]
While they are working on ee command, can anybody help me, How I can install a Ghost site in easyengine vps, without breaking vps?

I am newbie and I don't have much information about Ghost
Hope I will get steps to install blog!

**Comment by rahul286** [comment]
We dont have any plans to do it. Somebody can create EE v4 Package if they want.
