### ISSUE TITLE
Option to create sFTP users for sites

### ISSUE THREAD

**Issue by tinbot-development** [EasyEngine/easyengine#328]
Hi,

I love this application, but I have some clients wanting FPT access to their site. It would be awesome if EE could have a simple way to give access to sFTP for users.

Thanks!

**Comment by benzon** [comment]
There is always the option to run Virtual FTP Users, added a post about it here and on rtCamp, seams like a simple, straight forward solution, FTPs would be optimal and should be easy to setup with VSFTPD.

**Comment by rahul286** [comment]
V4 has a separation between sites through docker. We might add support for (S)FTP if there exists a way to directly land users inside docker application container. 

But as of now this is something we wont be able to focus further.

**Comment by prionkor** [comment]
> @matthewkeath Follow this tutorial to give a user access to specific site. https://rtcamp.com/easyengine/docs/chroot-sftp-easyengine/

This link no longer valid

**Comment by petermann** [comment]
> @matthewkeath
> 
> Refer: https://rtcamp.com/tutorials/linux/setup-sftp/

Configure SFTP on EE4 server: https://easyengine.io/handbook/configure-sftp-on-ee4-server/

**Comment by petermann** [comment]
> > @matthewkeath Follow this tutorial to give a user access to specific site. https://rtcamp.com/easyengine/docs/chroot-sftp-easyengine/
> 
> This link no longer valid

Configure SFTP on EE4 server: https://easyengine.io/handbook/configure-sftp-on-ee4-server/
