### ISSUE TITLE
Login security - HTTP Auth

### ISSUE THREAD

**Issue by QROkes** [EasyEngine/easyengine#342]
I always add this line in wpcommon.conf as an extra layer of security that I think it could be integrated as an option.

location = /wp-login.php {
    include common/acl.conf;     <<<<----  ADD THIS LINE
    fastcgi_pass php;
    include /etc/nginx/fastcgi_params;
}

**Comment by rahul286** [comment]
Let's do this using....

1. Put site behind HTTP auth. Use EE Admin HTTP auth user and password

```ee site create example.com --auth```


2. Put site behind HTTP auth using new HTTP user and password

```ee site create example.com --auth --auth-user=rahul --auth-pass=bansal```


2. Put part of site behind HTTP auth

```ee site create example.com --auth=admin```


--auth by default full site
--auth=admin only (for wordpress sites)

**Comment by QROkes** [comment]
Would be nice if you also add the option to put an specific subdirectory behind HTTP auth.

**Comment by rahul286** [comment]
@QROkes Can you please suggest an intuitive syntax for the same?

**Comment by QROkes** [comment]
Following the syntax you suggested before:

Put part of site behind HTTP auth
ee site create example.com --auth=admin       // For WP login

Something like this could be work:
ee site create example.com --auth=/folder
ee site create example.com/folder --auth

In this case "admin" would be like a special or reserved argument for WP sites.

**Comment by rahul286** [comment]
Good idea. I am just concerned with `/` part on command line. 

Also another concern is - if we add a nginx location block for /some/random/path, we will need to copy `location / { }` block codes to other block. I am not sure on this part and need to do some manual testing to see how nginx works in such cases.

**Comment by harshadyeola** [comment]
@rahul286 
will there be same or different users if i add two folders behind http auth.

**Comment by rahul286** [comment]
Will be handled in https://github.com/EasyEngine/easyengine/issues/1119
