### ISSUE TITLE
New user and SSH port

### ISSUE THREAD

**Issue by QROkes** [EasyEngine/easyengine#344]
It could be nice if EE had an option <command> to create a new user, if you are concern about security is well known that "ubuntu" user is enabled in the most of the server to access via SSH, so it means it is a good point to start an attack. The same for SSH port 22.

What I do is create a new user and block SSH access for ubuntu user and also I change the SSH port.

Adding an extra security layer never goes wrong!!

**Comment by rahul286** [comment]
v4 is docker based so creating system level users is something we should avoid. Atleast in core.
