### ISSUE TITLE
Nice UI for EasyEngine 22222 port 

### ISSUE THREAD

**Issue by harshadyeola** [EasyEngine/easyengine#350]
Here is nice & lightweight bootstrap theme, we can use @  ee 22222 port
http://startbootstrap.com/template-overviews/sb-admin-2/

**Comment by rahul286** [comment]
@dineshjain2911 please create a wireframe using https://moqups.com/

**Comment by MattyLB** [comment]
:+1:

**Comment by cm896** [comment]
+1 - love the idea, would love more stats/logs/details for the admin UI section.  I think we mentioned this before with either pimpmylog or goaccess for stats/log access from the admin console instead of ssh.

**Comment by romapad** [comment]
+1

**Comment by miloszorica** [comment]
any news on this one? i'd be happy to help

**Comment by romapad** [comment]
+1

**Comment by miloszorica** [comment]
anyone else? i can help with frontend

**Comment by seothemes** [comment]
+1

**Comment by rahul286** [comment]
Admin tools are handled differently in v4 so this is irrelevant.
