### ISSUE TITLE
SSH Lockdown Option & Possible (Physical) Chroot

### ISSUE THREAD

**Issue by iouxui** [EasyEngine/easyengine#380]
While relatively easy to do, for someone new to running their own private server or even full metal, not applying the correct configurations to /etc/ssh/sshd_config and /etc/ssh/ssh_config could lock them out and force console (if it's available) and I've seen this fail in the past depending on what changes were made (this happened with DigitalOcean a few times after not paying attention).

Changing just the port isn't really enough. It is, of course, security through obscurity, but it does knock off the more traditional port from being hit (22). Perhaps a randomizer that will auto-filter and select an open port that isn't used by traditional services (POP, SMTP, IMAP, NGINX, 8080 for Varnish as an example, 3306 etc),

Beyond the port, other options need to be modified and for a true lock down, a sudo user created over running as the root user, and where possible, the ability to specify the user that owns the new domain instead of using www-data for each one - I know that'd also require multiple FPM configuration files instead of a centralized single file, but giving one user complete access to all domains is asking for trouble.

For anyone running more than a handful of sites, this is going to make logging better as it won't be jumbled together as a whole.

Beyond that, having the ability to Chroot each user physically to their home dir. would be a step in the right direction. It does involve copying over quite a few files each time a user is created, but this is one feature I'd truly love to see.

**Comment by rahul286** [comment]
@iouxui Sorry for delay on this.

 v4 has docker based isolation for all sites. If you have any ideas to harden security further in v4/docker, please let us know.
