### ISSUE TITLE
Vagrant Support

### ISSUE THREAD

**Issue by rahul286** [EasyEngine/easyengine#397]
I tried ee setup inside vagrant box. It worked but with few issues.
- [ ] Vagrant uses ssh use `vagrant` which mounts synced folder. I had to change config file to add following line:

```
config.vm.synced_folder "vhosts/", "/var/www", owner: 'www-data', group: 'www-data'
```
- [ ] ee is not adding nginx to upstart. Not sure if this is one off case. Need cross-verification.

**Comment by BoweFrankema** [comment]
I've also been playing around with this.. Seems to work but ran into issues for logged in users (even with 2 CPU + 4GB of Ram). See the thread here: http://community.rtcamp.com/t/vagrant-easyengine-works-but-extremely-slow-for-logged-in-users/4004

**Comment by rahul286** [comment]
**Update** No longer required.
