### ISSUE TITLE
PhP MySQL library Version

### ISSUE THREAD

**Issue by respondiv** [EasyEngine/easyengine#410]
FYI, I am getting this alert on PhPMyAdmin on the fresh installation of easyengine 3

 Your PHP MySQL library version 5.5.41 differs from your MySQL server version 5.6.22. This may cause unpredictable behavior.

Thanks

**Comment by gau1991** [comment]
@respondiv ,
Thanks for reporting, we will look into it.

**Comment by phutchins** [comment]
FYI, I get this when just installing phpmyadmin by itself...

**Comment by RakshitThakker** [comment]
@gau1991 Please check http://stackoverflow.com/a/2357936

**Comment by rahul286** [comment]
We did a minor release today with updates. Please check https://easyengine.io/blog/easyengine-v3-8/
