### ISSUE TITLE
Subdomain Function

### ISSUE THREAD

**Issue by benzon** [EasyEngine/easyengine#466]
If EasyEngine ad some point is going to support Virtual Hosting, it would make sence that we can add subdomains to a current domain, and EE then creates ex. /var/www/domain.com/subdomain.domain.com

This way you can avoide multiple ftp accounts for one costumer.

**Comment by rahul286** [comment]
This will be reviewed at the time of starting work on shared hosting feature.

**Comment by rahul286** [comment]
**Update** The direction in which we are heading - this is unlikely supported.
