### ISSUE TITLE
Vimbadmin should be moved to subdomain

### ISSUE THREAD

**Issue by benzon** [EasyEngine/easyengine#468]
The current location of Vimbadmin under :22222 could turn out to be an issue, it should be accessible to costumers, so they can manage there mail accounts.

Never got why it was placed under :22222 since you would not share your login to this area with a costumer, would make more sence it's placed outside, since the point of Vimbadmin is to allow costumers, to create, delete, edit there mail accounts.

**Comment by gau1991** [comment]
@benzon ,
you can use following Nginx configuration to access ViMbadmin using vma.example.com

```
server {
        server_name vma.*;

        access_log   /var/log/nginx/vma.access.log;
        error_log    /var/log/nginx/vma.error.log;

        root /var/www/22222/htdocs/vimbadmin/public;
        index index.php;

        location / {
                try_files $uri $uri/ /index.php?$args;
        }

        location ~ \.php$ {
                try_files $uri =404;
                include fastcgi_params;
                fastcgi_pass 127.0.0.1:9000;
        }

}
```

**Comment by rahul286** [comment]
@gau1991 I am thinking of adding your config to default EE. Or may be making it available via some command. I am reopening this and we will look into this much later.

**Comment by rahul286** [comment]
In V4, we will be dropping support for Vimbadmin
