### ISSUE TITLE
Unable to run apt-get install - When trying to create new site.

### ISSUE THREAD

**Issue by irazasyed** [EasyEngine/easyengine#470]
Hi,

I just setup EE on a fresh DigitalOcean Droplet and whenever i try to create a new site using `ee site create domain.com --php` it ends up throwing `Unable to run apt-get install`.

What's wrong?

**Comment by irazasyed** [comment]
I also tried with `--wp` flag. Same thing.

Tested with `ee stack install` as well.

Here's the full output:

```
root@hostname:~# ee stack install
Adding repository for MySQL, please wait ...
Adding repository for NGINX, please wait ...
Adding repository for PHP, please wait ...
Updating apt-cache, please wait ...
Installing packages, please wait ...
Unable to run apt-get install
```

I'm on a 2gig Droplet. I'm use EE on another droplet too but that has previous version, dunno what's up with this one.

**Comment by gau1991** [comment]
@irazasyed ,
Can you give me output of following commands:
```
tail -n 50 /var/log/ee/ee.log
```

**Comment by irazasyed** [comment]
Here you go:

```
root@hostname:~# tail -n 50 /var/log/ee/ee.log
  libmcrypt4 libmysqlclient18 libonig2 libpango-1.0-0 libpangocairo-1.0-0
  libpangoft2-1.0-0 libpaper-utils libpaper1 libpathplan4 libpixman-1-0
  libqdbm14 libsm6 libterm-readkey-perl libthai-data libthai0 libtiff5 libvpx1
  libxaw7 libxcb-render0 libxcb-shm0 libxmu6 libxpm4 libxrender1 libxslt1.1
  libxt6 mariadb-client-10.0 mariadb-client-core-10.0 mariadb-common
  mariadb-server-10.0 mariadb-server-core-10.0 mlock mysql-common php5-json
  poppler-data ssl-cert ttf-dejavu-core x11-common
Suggested packages:
  gdb-doc gdbserver ghostscript-x hpijs graphviz-doc uw-mailutils cups-common
  libclone-perl libmldbm-perl libnet-daemon-perl libplrpc-perl
  libsql-statement-perl libfftw3-bin libfftw3-dev libgd-tools fonts-droid
  libipc-sharedcache-perl libjasper-runtime liblcms2-utils
  libmagickcore5-extra libmcrypt-dev mcrypt ttf-baekmuk ttf-arphic-gbsn00lp
  ttf-arphic-bsmi00lp ttf-arphic-gkai00mp ttf-arphic-bkai00mp tinyca mailx
  mariadb-test libcache-memcached-perl libmemcached fcgiwrap nginx-doc
  php-pear php5-user-cache poppler-utils fonts-japanese-mincho
  fonts-ipafont-mincho fonts-japanese-gothic fonts-ipafont-gothic
  fonts-arphic-ukai fonts-arphic-uming fonts-unfonts-core procmail
  postfix-mysql postfix-pgsql postfix-ldap postfix-pcre sasl2-bin
  dovecot-common postfix-cdb mail-reader postfix-doc openssl-blacklist
Recommended packages:
  libc-dbg mysql-server
The following NEW packages will be installed:
  fontconfig fontconfig-config fonts-dejavu-core fonts-liberation gdb
  ghostscript graphviz gsfonts imagemagick-common libaio1 libavahi-client3
  libavahi-common-data libavahi-common3 libc-client2007e libc6-dbg libcairo2
  libcdt5 libcgraph6 libcups2 libcupsfilters1 libcupsimage2 libdatrie1
  libdbd-mysql-perl libdbi-perl libfftw3-double3 libfontconfig1 libgd3
  libgraphite2-3 libgs9 libgs9-common libgvc6 libgvpr2 libharfbuzz0b
  libhtml-template-perl libice6 libijs-0.35 libjasper1 libjbig0 libjbig2dec0
  libjpeg-turbo8 libjpeg8 liblcms2-2 liblqr-1-0 libltdl7 libluajit-5.1-2
  libluajit-5.1-common libmagickcore5 libmagickwand5 libmariadbclient18
  libmcrypt4 libmysqlclient18 libonig2 libpango-1.0-0 libpangocairo-1.0-0
  libpangoft2-1.0-0 libpaper-utils libpaper1 libpathplan4 libpixman-1-0
  libqdbm14 libsm6 libterm-readkey-perl libthai-data libthai0 libtiff5 libvpx1
  libxaw7 libxcb-render0 libxcb-shm0 libxmu6 libxpm4 libxrender1 libxslt1.1
  libxt6 mariadb-client-10.0 mariadb-client-core-10.0 mariadb-common
  mariadb-server mariadb-server-10.0 mariadb-server-core-10.0 memcached mlock
  mysql-common mysqltuner nginx-common nginx-custom percona-toolkit php5-cli
  php5-common php5-curl php5-fpm php5-gd php5-imagick php5-imap php5-json
  php5-mcrypt php5-memcache php5-mysql php5-readline php5-xdebug poppler-data
  postfix ssl-cert ttf-dejavu-core x11-common
0 upgraded, 105 newly installed, 0 to remove and 89 not upgraded.
Need to get 50.4 MB of archives.
After this operation, 284 MB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  php5-common php5-curl php5-json php5-cli php5-fpm php5-gd php5-imap
  php5-mcrypt php5-mysql php5-readline php5-imagick php5-memcache php5-xdebug
E: There are problems and -y was used without --force-yes
2015-03-20 07:34:42,576 (ERROR) ee : Unable to run apt-get install
```

**Comment by gau1991** [comment]
@irazasyed ,,
It look like ondrej repo GPG key issue.
I am not sure why its happening on your enviornment. I am not able to reproduce this issue on my current system. 
If possible can you give me server access so that I can debug more. 
You can use http://docs.rtcamp.com/easyengine/keys.html to add my SSH Public key

**Comment by irazasyed** [comment]
@gau1991 Sure! Give me few mins and I'll add you.

**Comment by irazasyed** [comment]
@gau1991 Added your key. IP: `45.55.174.238`

**Comment by irazasyed** [comment]
@gau1991 Please confirm when you're in and also when done. I'll probably create another droplet and try setting up there. Will destroy this one when you're done.

**Comment by irazasyed** [comment]
@gau1991 It doesn't work on another droplet too. This time 4gig :| Please check ASAP.

I can give access to another droplet if you want? Let me know. Same issue.

**Comment by gau1991** [comment]
@irazasyed ,
I checked on ur droplet,
I am able to install packages on ur droplet. I just ran command
```
ee stack install
```
I also stored http auth to file 1.txt

**Comment by irazasyed** [comment]
@gau1991 How is that possible? I tried the same thing on another droplet too. Hmm. Anything else you did that I'm missing?

**Comment by gau1991** [comment]
@irazasyed ,
> Anything else you did that I'm missing?

Nope, I just logged in to your server using SSH and ran the command
```
ee stack install
```

**Comment by irazasyed** [comment]
See this one: http://cl.ly/image/0d0G2g401J1C another droplet (3rd one).

**Comment by gau1991** [comment]
@irazasyed ,
Can you please add my key to this droplet? So that I can check

**Comment by irazasyed** [comment]
Added `45.55.139.225`

**Comment by irazasyed** [comment]
Check this recording: http://cl.ly/image/0a290k3x1q3o

Fresh `Ubuntu 14.04 x64` 2gig Droplet. Fired the first command and then tried to install the stack.

**Comment by gau1991** [comment]
@irazasyed ,
This time also I am successfull. I am closing this issue, As I am not able to reproduce the same bug

**Comment by irazasyed** [comment]
@gau1991 Well that doesn't help! I tried with 4 different droplets yet it still doesn't work and when you try it works. That's quite weird.

**Comment by ynt** [comment]
Hi. I have the same issue:

```
root@s3:~# tail -n 50 /var/log/ee/ee.log
  libharfbuzz0b libhtml-template-perl libice6 libijs-0.35 libjasper1 libjbig0
  libjbig2dec0 libjpeg-turbo8 libjpeg8 liblcms2-2 liblqr-1-0 libluajit-5.1-2
  libluajit-5.1-common libmagickcore5 libmagickwand5 libmariadbclient18
  libmcrypt4 libmysqlclient18 libonig2 libpango-1.0-0 libpangocairo-1.0-0
  libpangoft2-1.0-0 libpathplan4 libpixman-1-0 libqdbm14 libreadline5 libsm6
  libterm-readkey-perl libthai-data libthai0 libtiff5 libvpx1 libx11-6
  libx11-data libxau6 libxaw7 libxcb-render0 libxcb-shm0 libxcb1 libxdmcp6
  libxext6 libxmu6 libxpm4 libxrender1 libxslt1.1 libxt6 mariadb-client-10.0
  mariadb-client-core-10.0 mariadb-common mariadb-server-10.0
  mariadb-server-core-10.0 mlock mysql-common php5-json poppler-data
  x11-common
Suggested packages:
  gdb-doc gdbserver ghostscript-x hpijs graphviz-doc uw-mailutils
  libclone-perl libmldbm-perl libnet-daemon-perl libplrpc-perl
  libsql-statement-perl libfftw3-bin libfftw3-dev libgd-tools fonts-droid
  libipc-sharedcache-perl libjasper-runtime liblcms2-utils
  libmagickcore5-extra libmcrypt-dev mcrypt ttf-baekmuk ttf-arphic-gbsn00lp
  ttf-arphic-bsmi00lp ttf-arphic-gkai00mp ttf-arphic-bkai00mp tinyca
  mariadb-test libcache-memcached-perl libmemcached fcgiwrap nginx-doc
  php-pear php5-user-cache poppler-utils fonts-japanese-mincho
  fonts-ipafont-mincho fonts-japanese-gothic fonts-ipafont-gothic
  fonts-arphic-ukai fonts-arphic-uming fonts-unfonts-core
Recommended packages:
  libc-dbg mysql-server
The following NEW packages will be installed:
  fonts-liberation gdb ghostscript graphviz gsfonts imagemagick-common libaio1
  libc-client2007e libc6-dbg libcairo2 libcdt5 libcgraph6 libcupsfilters1
  libcupsimage2 libdatrie1 libdbd-mysql-perl libdbi-perl libevent-2.0-5
  libfftw3-double3 libgd3 libgraphite2-3 libgs9 libgs9-common libgvc6 libgvpr2
  libharfbuzz0b libhtml-template-perl libice6 libijs-0.35 libjasper1 libjbig0
  libjbig2dec0 libjpeg-turbo8 libjpeg8 liblcms2-2 liblqr-1-0 libluajit-5.1-2
  libluajit-5.1-common libmagickcore5 libmagickwand5 libmariadbclient18
  libmcrypt4 libmysqlclient18 libonig2 libpango-1.0-0 libpangocairo-1.0-0
  libpangoft2-1.0-0 libpathplan4 libpixman-1-0 libqdbm14 libreadline5 libsm6
  libterm-readkey-perl libthai-data libthai0 libtiff5 libvpx1 libx11-6
  libx11-data libxau6 libxaw7 libxcb-render0 libxcb-shm0 libxcb1 libxdmcp6
  libxext6 libxmu6 libxpm4 libxrender1 libxslt1.1 libxt6 mariadb-client-10.0
  mariadb-client-core-10.0 mariadb-common mariadb-server mariadb-server-10.0
  mariadb-server-core-10.0 memcached mlock mysql-common mysqltuner
  nginx-common nginx-custom percona-toolkit php5-cli php5-common php5-curl
  php5-fpm php5-gd php5-imagick php5-imap php5-json php5-mcrypt php5-memcache
  php5-mysql php5-readline php5-xdebug poppler-data x11-common
0 upgraded, 99 newly installed, 0 to remove and 4 not upgraded.
Need to get 48.7 MB of archives.
After this operation, 278 MB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  php5-common php5-curl php5-json php5-cli php5-fpm php5-gd php5-imap
  php5-mcrypt php5-mysql php5-readline php5-imagick php5-memcache php5-xdebug
E: There are problems and -y was used without --force-yes
2015-04-17 04:29:06,944 (ERROR) ee : Unable to run apt-get install
root@s3:~# D
```

**Comment by faishal** [comment]
I am also facing same issue on `Ubuntu - 14.04 x64`

**Comment by rahul286** [comment]
@gau1991 @MiteshShah @harshadyeola 

Can we pinpoint this issue? Is it:

1. Launchpad server crashing under heavy load?
2. Network I/O issue
3. Key server issue

I came across https://packagecloud.io/ recently and I think we can use it or even our CDN if needed. 

Installation should work all the time. Atleast on digitalocean and linode where we continuously test EE.

**Comment by faishal** [comment]
@rahul286  I just noticed that there is one GPG error
```
W: GPG error: http://ppa.launchpad.net trusty Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 4F4EA0AAE5267A6C
2015-04-23 02:46:27,928 (INFO) ee : Installing packages, please wait ...
```
And also at end, I found following error 
```
WARNING: The following packages cannot be authenticated!
  php5-common php5-curl php5-json php5-cli php5-fpm php5-gd php5-imap
  php5-mcrypt php5-mysql php5-readline php5-imagick php5-memcache php5-xdebug
E: There are problems and -y was used without --force-yes
```

**Comment by faishal** [comment]
This issue exist only on `ubuntu 14.x`.
I tried to install on `ubuntu 12.04` and its working good.

**Comment by MiteshShah** [comment]
@faishal I tested this on my vagrant and i don't face this issue,
The reason for i don't fix this issue is while installing my system fetch GPG keys properly.

@gau1991 @harshadyeola Solution : https://github.com/rtCamp/easyengine/issues/495#issuecomment-94388560

First we run apt-get update and check if there is any GPG key is missing if some keys are missing you can use above solution to fetch gpg key.

I guess you should try above solution to avoid GPG keys problem in future.

**Comment by rahul286** [comment]
I am not sure about solution at the moment but the issue seems random. 

Also, some people get issue during EE install, some get during EE site create. 

But one pattern I noticed is that everytime its related to network transfer. :|

**Comment by MiteshShah** [comment]
@rahul286 As per my experience issue with keyservers.

As Ubuntu and Debian both use lots of mirrors to speed-up downloading.
So CDN don't help up as packages are downloading from nearest mirror available and apt-get detect slow speed its automatic change mirror.

**Comment by rahul286** [comment]
@MiteshShah can we host all GPG keys EE needs on a CDN? And have a cronjob to update GPG keys regularly?

How often GPG key changes? Is GPG key same for all servers?

And finally can we mirror all packages programmatically? How reliable it would be!

I don't much about this as I never built launchpad packages successfully myself.

**Comment by MiteshShah** [comment]
@rahul286 Best way to find missing gpg keys is 

apt-get update > /dev/null 2> /tmp/gpg_key
grep "NO_PUBKEY" /tmp/gpg_key |sed "s/.*NO_PUBKEY //"

We need to run above command and fetch the missing GPG keys from different key servers.

I guess @gau1991 can do this within 30 mins

@rahul286 The issue with GPG keys not with packages. As apt-get install package need to be authenticate using valid GPG keys else its through above error which can be easily fix by passing --force-yes but its create some security risk.

@rahul286 @gau1991 @harshadyeola First fix GPG keys problem using above mentioned solution and i think you never face this issue again

**Comment by irazasyed** [comment]
@rahul286 @MiteshShah Guys, I too had this issue and i know this would sound very weird but here's the thing:

Whenever i tried installing / creating new site on a new droplet after a fresh install of EE using [iTerm2](http://iterm2.com/) terminal on mac, it kept ending up with the error i reported back then and then i switch to the standard Terminal window (After several failed attempts and several droplets, even @gau1991 wasn't able to help me when i reported & ended up closing the issue) and apparently it always worked. Now i have no idea what's the connection between my terminal and the EE but there's definitely something conflicting somewhere.

Later i checked my Ohmyzsh config (Which i use over standard shell) and removed my recent installation of one of the other external shell scripts & it fixed this issue (I was always able to install just fine using iTerm2 itself). However, Recently on a new droplet, Once again this kept happening and since i knew this had happened before as well, I ended up using standard Terminal again & it worked just fine. So yeah, It's a bit weird but something's not right. Maybe this has got nothing to do with the EE itself and it's totally a different issue & just a co-incident but it works always..lmao.

**Comment by rahul286** [comment]
@irazasyed It sounds like locale issues which we fixed long time. But locale issue used to show different error messages.

I haven't used iTerm2 from long time. Not once after starting EasyEngine project.

We all (EE team) uses zsh and also have many customizations. As we never faced issues on zsh, we can rule out zsh.

@faishal by any chance are you using iTerm2 when you ran into issue?

**Comment by irazasyed** [comment]
@rahul286 Yeah, Not a ZSH issue for sure. Because that's still applying to the standard Terminal window anyway. Something to do with iTerm2.

**Comment by faishal** [comment]
@rahul286 Nope, I never try iTerm2, I am addicted to zsh  !

**Comment by sungkhum** [comment]
I got the same error but there seems to be some conflict (output of tail -n 50 /var/log/ee/ee.log):

The following packages have unmet dependencies:
 nginx-custom : Depends: nginx-common (= 1.6.2-4ppa~trusty) but 1.6.3-1+trusty0 is to be installed
                Conflicts: nginx-light but 1.6.3-1+trusty0 is to be installed
E: Unable to correct problems, you have held broken packages.
2015-04-24 16:38:32,719 (ERROR) ee : Unable to run apt-get install

I'm in Ubuntu 14.04 (upgraded from 12.04). Any ideas how to fix the dependency issue?

Thanks!

**Comment by ynt** [comment]
@MiteshShah solution solved this issue for me.

Commands:

```
apt-get update > /dev/null 2> /tmp/gpg_key
grep "NO_PUBKEY" /tmp/gpg_key |sed "s/.*NO_PUBKEY //"
```

returned `xxxxxx` key that I added here:

```
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys xxxxxx
```

Now `ee site create` works.

**Comment by sungkhum** [comment]
That solution doesn't work for me. I even uninstalled nginx, but couldn't reinstall it from easyengine and had to do the normal install.
Same error: 
The following packages have unmet dependencies:
 nginx-custom : Depends: nginx-common (= 1.6.2-4ppa~trusty) but 1.6.3-1+trusty0 is to be installed
                Conflicts: nginx-light but 1.6.3-1+trusty0 is to be installed
E: Unable to correct problems, you have held broken packages.
2015-04-24 19:19:45,146 (ERROR) ee : Unable to run apt-get install

**Comment by sungkhum** [comment]
Is this because I am on Ubuntu 14.04?

"We used custom build of nginx
This custom build of nginx support the nginx fastcgi cache purge module but this custom build of nginx is only support the nginx for Ubuntu 12.04 :(" https://github.com/rtCamp/easyengine/issues/168

**Comment by MiteshShah** [comment]
@gau1991 Need to update nginx package

> nginx-custom : Depends: nginx-common (= 1.6.2-4ppa~trusty) but 1.6.3-1+trusty0 is to be installed
Conflicts: nginx-light but 1.6.3-1+trusty0 is to be installed

As rtCamp nginx-common is behind the ubuntu main nginx package so apt-get always install latest version of package.

**Comment by sungkhum** [comment]
Is there a way for me to fix this or is it actually a bug?

**Comment by gau1991** [comment]
@sungkhum ,
Its because of old package in rtCamp nginx repo. We are building new package today only.

**Comment by kriball** [comment]
I tried this on Ubuntu 14.04 x86 and Ubuntu 14.04 x86 minimal, and yes this problem happen to me too.
When I reinstall using Debian 7 32bit it run normally.

**Comment by gau1991** [comment]
@kriball @sungkhum We now updated Nginx packages on repository.
Can you please check again if you are successful to install on Ubuntu 14.04. ?

**Comment by kriball** [comment]
@gau1991 Ok I will try again this night and give report here, I will try using a few vps provider.
@ynt thank you very much, it works! 
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4F4EA0AAE5267A6C

**Comment by sungkhum** [comment]
Thanks seems to work. Now I'm having other issues, but this one is fixed.

**Comment by jumbojett** [comment]
@gau1991 
> nginx-custom : Depends: nginx-common (= 1.6.2-4ppa~trusty) but 1.6.3-1+trusty0 is to be installed
I just tried with a fresh install of Ubuntu 14.04 and getting this error as well. Have the new packages been released on the repo?

**Comment by MiteshShah** [comment]
@jumbojett Its seems like you forget to update apt-get cache

```
sudo apt-get clean && sudo apt-get clean all && sudo apt-get update
```

**Comment by MiteshShah** [comment]
Solution suggested by @gau1991 https://github.com/rtCamp/easyengine/issues/507#issuecomment-95860569

This comment is for easily track that solution :smile:

**Comment by QROkes** [comment]
After the new release (3.1.3), now I'm getting this error:

Finished processing dependencies for ee==3.1.3
Synchronizing ee database, please wait...

For EasyEngine (ee) auto completion, run the following command

source /etc/bash_completion.d/ee_auto.rc

EasyEngine (ee) installed successfully
EasyEngine (ee) help: http://docs.rtcamp.com/easyengine/
dryweb@ip-172-31-45-74:~$ sudo ee stack install
Adding repository for MySQL, please wait...
Adding repository for NGINX, please wait...
Adding repository for PHP, please wait...
Adding repository for HHVM, please wait...
Updating apt-cache, please wait...
Fixing missing GPG keys, please wait...
Installing packages, please wait...
Oops Something went wrong!!
Check logs for reason `tail /var/log/ee/ee.log` & Try Again!!!

dryweb@ip-172-31-45-74:~$ sudo tail /var/log/ee/ee.log
0 upgraded, 160 newly installed, 0 to remove and 43 not upgraded.
Need to get 84.4 MB of archives.
After this operation, 353 MB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  mysql-common mariadb-common libmariadbclient18 libmysqlclient18
  mariadb-client-core-10.0 mariadb-client-10.0 mariadb-server-core-10.0
  mariadb-server-10.0 hhvm mariadb-server
E: There are problems and -y was used without --force-yes
2015-05-06 11:47:43,532 (INFO) ee : Oops Something went wrong!!
2015-05-06 11:47:43,533 (ERROR) ee : Check logs for reason `tail /var/log/ee/ee.                                                                             log` & Try Again!!!
dryweb@ip-172-31-45-74:~$

**Comment by MiteshShah** [comment]
@QROkes can you run following command and give us its output ?
```
sudo gpg --keyserver subkeys.pgp.net --recv CBCB082A1BB943DB
sudo apt-get clean && sudo apt-get clean all && sudo apt-get update
```

**Comment by QROkes** [comment]
This command is not working:

dryweb@ip-172-31-45-74:~$ sudo gpg --keyserver subkeys.pgp.net --recv CBCB082A1BB943DB
gpg: requesting key 1BB943DB from hkp server subkeys.pgp.net
gpg: keyserver timed out
gpg: keyserver receive failed: keyserver error
dryweb@ip-172-31-45-74:~$

**Comment by rahul286** [comment]
Can you try - http://unix.stackexchange.com/a/110594/41475 ?

So command will become:

> sudo gpg --keyserver subkeys.pgp.net:80 --recv CBCB082A1BB943DB

**Comment by MiteshShah** [comment]
@QROkes Can you try another keyserver

```
gpg --keyserver keys.gnupg.net --recv-keys CBCB082A1BB943DB
```

**Comment by rahul286** [comment]
Great. :-)

 @QROkes 
Please try other keyserver as well as adding port :80

We really want to get to the bottom of things.

**Comment by QROkes** [comment]
Not working.
Here is the output:

dryweb@ip-172-31-45-74:~$ sudo gpg --keyserver subkeys.pgp.net:80 --recv CBCB082A1BB943DB
gpg: requesting key 1BB943DB from subkeys.pgp.net:80
gpgkeys: no keyserver host provided
gpg: keyserver internal error
gpg: keyserver receive failed: keyserver error
dryweb@ip-172-31-45-74:~$ sudo gpg --keyserver keys.gnupg.net --recv-keys CBCB082A1BB943DB
gpg: requesting key 1BB943DB from hkp server keys.gnupg.net
gpg: keyserver timed out
gpg: keyserver receive failed: keyserver error
dryweb@ip-172-31-45-74:~$ sudo gpg --keyserver keys.gnupg.net:80 --recv-keys CBCB082A1BB943DB
gpg: requesting key 1BB943DB from keys.gnupg.net:80
gpgkeys: no keyserver host provided
gpg: keyserver internal error
gpg: keyserver receive failed: keyserver error
dryweb@ip-172-31-45-74:~$

**Comment by QROkes** [comment]
Now is working!!
I had the port 11371 blocked in my security group and forcing to use the port 80 seems like is not working out.

I unblocked the port 11371 and everything is working just fine.

**Comment by MiteshShah** [comment]
@QROkes 
Can you tell me following details ?

OS
RAM 
CPU 

Any special instruction to re-produce this issue ?

I want to test this on same environment as you are using right now.

I'd tested this on fresh Ubuntu 14.04 vagrant 
```
root@vagrant-ubuntu-trusty-64:~# gpg --keyserver keys.gnupg.net --recv-keys CBCB082A1BB943DB
gpg: directory `/root/.gnupg' created
gpg: new configuration file `/root/.gnupg/gpg.conf' created
gpg: WARNING: options in `/root/.gnupg/gpg.conf' are not yet active during this run
gpg: keyring `/root/.gnupg/secring.gpg' created
gpg: keyring `/root/.gnupg/pubring.gpg' created
gpg: requesting key 1BB943DB from hkp server keys.gnupg.net
gpg: /root/.gnupg/trustdb.gpg: trustdb created
gpg: key 1BB943DB: public key "MariaDB Package Signing Key <package-signing-key@mariadb.org>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1
root@vagrant-ubuntu-trusty-64:~# gpg --keyserver keys.gnupg.net --recv-keys CBCB082A1BB943DB
gpg: requesting key 1BB943DB from hkp server keys.gnupg.net
gpg: key 1BB943DB: "MariaDB Package Signing Key <package-signing-key@mariadb.org>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
```

**Comment by rahul286** [comment]
@QROkes firewall issue is something will need manual intervention. EE can print better and helpful message.

What I am wondering is why port 80 did not work for you? Most threads I came across google mentioned same port 80 solution. We will look deeper into this but we will definitely improve error messages.

**Comment by QROkes** [comment]
@rahul286 I understand that firewall is something that everybody can have their own very custom configuration. In this case, I have port 80 completely open.
Just tell me if you need / want me to do more testing.

Best regards.
You guys really bend over backwards.

**Comment by rahul286** [comment]
@QROkes This month we are focusing on fixing all pending issues wherever possible and when not possible atleast print error messages that will be helpful.

**Comment by rahul286** [comment]
**Update:** No further action needed as v4 is docker-based.
