### ISSUE TITLE
User Specified MySQL host configuration (~/.my.cnf) is overwritten and ignored

### ISSUE THREAD

**Issue by brennentsmith** [EasyEngine/easyengine#482]
With the 2.x branch of EE, it was possible to set a my.cnf file in the home directory to specify an external MySQL host for EE. See: https://rtcamp.com/easyengine/docs/remote-mysql/

However in the 3.x branch, the user-set ~/.my.cnf gets overwritten in stack.py, and is then ignored by the rest of the program's logic (as the host field no longer exists). As a result, the installer installs MariaDB to the local machine and proceeds as if there was no user specified ~/.my.cnf file. See: https://github.com/rtCamp/easyengine/blob/fff68d1183a92cdbe6568e803acf3041bde08825/ee/cli/plugins/stack.py#L121-L131

This is also related to: https://github.com/rtCamp/easyengine/issues/147

**Comment by gau1991** [comment]
Hi,
Right now Programms logic is this:
1. EasyEngine checks the output of command `mysqladmin ping`, which return local/remote MySQL connection is alive or not.
2. If alive then it does not install MySQL server.
3. But if not found then only it install MySQL server.
Refer: https://github.com/rtCamp/easyengine/blob/stable/ee/cli/plugins/stack.py#L1222

So, if you set values of Host, you need check you are able to access remote mysql server from EasyEngine server by using `mysql` or `mysqladmin ping` command.

**Comment by rahul286** [comment]
Sorry for a delayed reply. I hope your issue is fixed by now.

If you are still facing the issue, please use http://community.rtcamp.com/c/easyengine for further support.

We are cleaning up issue tracker and closing this issue because we won't be able to contribute to this discussion further.
