### ISSUE TITLE
custom webroot location

### ISSUE THREAD

**Issue by anantshri** [EasyEngine/easyengine#489]
enhancement request:

add an option to allow for custom webroot location.

**Comment by aronwp** [comment]
I think this was covered in a previous ticket. I don't remember the reason given but there's allot of files that would need to be changed. The best workaround is to create a symlink to your webroot. I Symlink to a mounted glusterFS cluster and have had no issues. Hope this helps.

**Comment by anantshri** [comment]
Thanks for the tip @aronwp

**Comment by vercotux** [comment]
+1 please add this
In my setup EE is completely undeployable without a custom webroot.

**Comment by ahansson89** [comment]
I agree. It would be awesome to be able to do something like this:
ee site create example.com --php --hhvm --webroot=/var/www/html

This would also make migrations way easier IMO

**Comment by rahul286** [comment]
Sorry for a delayed reply.  In v4, we will be doing this differently.
