### ISSUE TITLE
[Poll] InnoDB v/s TokuDB engine in MariaDB

### ISSUE THREAD

**Issue by rahul286** [EasyEngine/easyengine#494]
A user requested this. 

If anyone used TokuDB before please share your experience.

For conversion, this seems helpful - http://dba.stackexchange.com/a/46793/24859

**Comment by MiteshShah** [comment]
@rahul286 IMHO if we can use POLL label whenever we need users review.
As we before created some POLL so EasyEngine users are aware of POLL label

Refer: https://github.com/rtCamp/easyengine/labels/Poll

**Comment by rahul286** [comment]
Nice idea about label. :)

**Comment by rahul286** [comment]
Added that label and changed topic. We need InnoDB v/s TokuDB feedback here mainly.

We can always do conversion from one format to another. So this is more like poll rather than conversion task.

**Comment by ddelaey** [comment]
I think it's also important to look at the active development for each of the possibilities.
From what I've read from InnoDB vs TokuDB, TokuDB should perform better on sites with lots of (frequently changed) content.

**Comment by cakobox** [comment]
+ TokuDB. And was looking to do it manually, but MariaDB by EE is custom built, so I stuck changing the engine from InnoDB to TokuDB.

**Comment by rahul286** [comment]
Update: I did not see TokuDB gaining any traction in WP ecosystem. So closing this.
