### ISSUE TITLE
After update, website not in ee site list anymore, ee sync not updating

### ISSUE THREAD

**Issue by lemartinet** [EasyEngine/easyengine#505]
Hi,
Following the upgrade to 3.1, my website still works but when I do ee site list, the site doesn't show up and with ee site edit, I get a "site does not exist" error. I tried using ee sync but it's not clear to me what this is doing, and it is not solving my problem. How do I add back my website to the list? Is there a way to edit ee database manually?

Thanks!
Best,
Manu

**Comment by vedatkamer** [comment]
+1

root@pusula:/# ee site list
Unable to query database
root@pusula:/# ee sync
Synchronizing ee database, please wait...
Unable to query database

**Comment by vedatkamer** [comment]
I solved the problem by running sqlite alter comments manually:
```
root@pusula:~# cat /root/eeup | grep sqlite
```
```
echo "ALTER TABLE sites ADD COLUMN db_name varchar;" | sqlite3 /var/lib/ee/ee.db
echo "ALTER TABLE sites ADD COLUMN db_user varchar; " | sqlite3 /var/lib/ee/ee.db
echo "ALTER TABLE sites ADD COLUMN db_password varchar;" | sqlite3 /var/lib/ee/ee.db
echo "ALTER TABLE sites ADD COLUMN db_host varchar;" | sqlite3 /var/lib/ee/ee.db
echo "ALTER TABLE sites ADD COLUMN is_hhvm INT DEFAULT '0';" | sqlite3 /var/lib/ee/ee.db
echo "ALTER TABLE sites ADD COLUMN is_pagespeed INT DEFAULT '0';" | sqlite3 /var/lib/ee/ee.db
```

**Comment by lemartinet** [comment]
Great idea! I readded by hand and it worked it seems : 

```
insert into sites values(2,'XXX', 'wp', 'wpfc', 'XXX', '2015-04-16 17:01:21', 1, 0, 'ext4', 'mysql', 'XXX', 'XXX', 'XXX', 'localhost', 0, 0);
```

**Comment by rahul286** [comment]
Sorry for a delayed reply. 

@vedatkamer thanks for a fix then.

If you are still facing the issue, please use http://community.rtcamp.com/c/easyengine for further support.

We are cleaning up issue tracker and closing this issue because we won't be able to contribute to this discussion further.
