### ISSUE TITLE
No error thrown when pagespeed.conf contains errors.

### ISSUE THREAD

**Issue by ddelaey** [EasyEngine/easyengine#506]
When putting some rubbish in '/var/www/example.com/conf/nginx/pagespeed.conf' via 'ee site edit mysite.com --pagespeed',and saving that, nginx gets restarted but no error is thrown.

I have the impression pagespeed.conf is not processed. How can this be checked? Is pagespeed actually running? How to check that? I don't see any references to pages speed in the browser html code.

Thanks,
  David

**Comment by ddelaey** [comment]
I've found the issue.

Because I use an SSL certificate I have an adapted nginx config file.

I needed to replace following lines:
    include common/wpfc.conf;
    include common/wpcommon.conf;
    include common/locations.conf;

with:
    include common/wpfc-hhvm.conf;
    include common/wpcommon.conf;
    include common/locations.conf;
    include /var/www/daviddelaey.com/conf/nginx/*.conf;

Otherwise the pagespeed.conf file and wpfc-hhvm.conf file are not loaded.

Would it be possible to automatically adapt an existing nginx config file when --hhvm and --pagespeed are used with an 'ee site update' command?

Thanks, David

**Comment by rahul286** [comment]
Sorry for a delayed reply. We no longer support pagespeed.

We are cleaning up issue tracker and closing this issue because we won't be able to contribute to this discussion further.

Please use http://community.rtcamp.com/c/easyengine for future support questions.
