### ISSUE TITLE
Ubuntu 15.04 Roadmap

### ISSUE THREAD

**Issue by shaneholloman** [EasyEngine/easyengine#514]
I have client that has server on 15.04. I presume since **systemd has replaced Upstart** as the standard boot and service manager that EE is not ready for this server release yet?

https://wiki.ubuntu.com/VividVervet/ReleaseNotes

**Comment by gau1991** [comment]
Hi, 
> I have client that has server on 15.04

Ubuntu 15.04 will give support for 9 months only as it is not LTS release, so I recommend you to use 14.04 LTS version.

> I presume since systemd has replaced Upstart as the standard boot and service manager that EE is not ready for this server release yet?

We are allready testing this, we hope EasyEngine will support this.

Supporting new release of Ubuntu and Debian with EasyEngine is always takes time, as for packages, PHP, MySQL, HHVM EasyEngine is heavily dependent upon external repositories. 
So when all this repository create packages for new release of Ubuntu and Debian, then and then only we are able to give  support to that new release of Ubuntu and Debian. 

Although we have future plan to create our own repository for all packages like we did for Nginx in past.

**Comment by liquidia** [comment]
I am using easyenigne on  Ubuntu 15.04  running magento with redis hhvm support no issue so far.
