### ISSUE TITLE
Support for Vitess from Google

### ISSUE THREAD

**Issue by JosefJezek** [EasyEngine/easyengine#517]
Could you add support for Vitess from Google?
- http://vitess.io
- http://googlecloudplatform.blogspot.cz/2015/03/scaling-MySQL-in-the-cloud-with-Vitess-and-Kubernetes.html

**Comment by MattyLB** [comment]
+1.

**Comment by aronwp** [comment]
This looks like a great idea to add to easy engine. Just what I need.

**Comment by rahul286** [comment]
Sorry for a delayed reply. EE currently has no plan to add something like this to core.
