### ISSUE TITLE
Add switch for choice version of wp

### ISSUE THREAD

**Issue by JosefJezek** [EasyEngine/easyengine#518]
Could you add switch for choice version by installation of wp? I need stable v4.1, because my any plugins don't support latest 4.2.

Example: --ver=4.1
- http://wp-cli.org/commands/core/download/

**Comment by MiteshShah** [comment]
@JosefJezek IMHO its a bad idea as just for one plugin put entire website on risk.
As latest version always fix most critical security issues.

Refer: https://wordpress.org/news/2015/04/wordpress-4-1-2/

**Comment by JosefJezek** [comment]
I would like specify previous stable major ver with latest minor number, ex. 4.1.2. Great idea is from @rahul286 Or script for get latest minor number for maj ver. ex. for 4.1 ee will install 4.1.2

https://github.com/rtCamp/easyengine/issues/116#issuecomment-97134867

**Comment by MattyLB** [comment]
-1.   I agree with Mitesh that this is a bad idea because of critical
security updates that are not available for prior releases, even if they
are listed as "stable".  In my opinion, this would create a liability risk
that the rtCamp team does not need, nor us as end users.

**Comment by rahul286** [comment]
We all aware that WordPress need to latest but if wp-cli is giving choice, EE should also honor it.

I am planning to pursue - https://github.com/rtCamp/easyengine/issues/116#issuecomment-97134867

Idea is to leave wordpress related stuff to wp-cli wherever possible. That way we (EE team) will get some breathing space. We can use that time to focus on php/mysql/nginx optimization + security and other non-wordpress specific issues.

At some point, EE will have some sort of "notifications" and "monitoring" system. So server admin will be updated about outdated wordpress, among other things. I guess that can address concerns shown by @MattyLB 

@MattyLB rest assured, EE defaults will be always to use latest codes of everything (not only wordpress). :-)

**Comment by MattyLB** [comment]
+1 @RahulBansal - that is a good plan.

**Comment by JosefJezek** [comment]
Ok. Previous version 4.1 have latest security fixes aka 4.1.2.

**Comment by rahul286** [comment]
@mbtamuli Can we pass all parameters that EE itself doesn't handle to wp-cli as it is?

**Comment by rahul286** [comment]
This will be handled in #1029
