### ISSUE TITLE
ee secure --auth  (installed 3.1.2 on DO)

### ISSUE THREAD

**Issue by cm896** [EasyEngine/easyengine#520]
ee secure --auth
When I enter:  x7a!G$9bKWG6$@mk as the password, it accepts it, but I am not able to log in.
I don't mind being limited to using allowable characters, but a warning that what I entered won't work would be helpful.

What are the allowed/acceptable characters for the password for http auth?

The user's input should be tested in this command, and an error returned if there are characters that are not allowed.  I believe the @ is not allowed in an auth password in my example password.

The IETF site won't resolve the dns to load, so here is a google cache link: http://webcache.googleusercontent.com/search?q=cache:SrOBaeErOuQJ:https://www.ietf.org/rfc/rfc2617.txt+&cd=9&hl=en&ct=clnk&gl=us
I think this RFC defines allowable characters.

**Comment by rahul286** [comment]
I think `!@#` needs special handling.

Ref: https://technodedigest.wordpress.com/2012/04/14/tackling-special-characters-in-proxy-passwords-on-linux/

**Comment by cm896** [comment]
Yes - I also tried % escaping those special characters, but ee it took it as literal.
The ee command might need to encode those special characters.

I tested and entered this on the command line for the password: x7a%21G%249bKWG6%24%40mk
When prompted for http auth, I entered this: x7a!G$9bKWG6$@mk which didn't work, but rather this worked:  x7a%21G%249bKWG6%24%40mk

**Comment by MattyLB** [comment]
@cm896 - I hope that is a randomly generated password that you're trying to
rework because otherwise you may be sharing some sensitive password usage
patterns. Just a thought. :)

**Comment by cm896** [comment]
LOL - yes - all random.  I'd never post a password in use ever.  At a minimum I try for a 16 character, [A-Za-z0-9] + !@#$-_.*%(){}  With the algo the bit strength is 93+ I believe.  When allowed I use a random string 32 characters in length for a 190+ bit strength. :)  All random, all the time, mostly unique as far as I can tell.  Password manager generates and stores them.  The string above is not in use anywhere for any of my passwords.  
I am curious as to what pattern could be discerned from that string though. :)

**Comment by MattyLB** [comment]
@cm896 - I figured it was but I've seen some less than security conscious
folks post some pretty sensitive info from logs, etc on these threads so I
thought I would check to be sure. ;)

I'm no super sleuth but I was seeing x7a....9..KWG6... showing up a lot.
That's basically what piqued my concern.

Cheers and good luck with figuring out a nice solution for the ee to wp PW
debacle!

**Comment by cm896** [comment]
@MattyLB no problems - I appreciate the heads up and keeping an eye out for others.  I wish more of this system of tubes was like that.

**Comment by rahul286** [comment]
Being worked in https://github.com/EasyEngine/easyengine/issues/1119

@mrrobot47 please check this issue for allowed characters
