### ISSUE TITLE
How to cache wp-admin

### ISSUE THREAD

**Issue by MiteshShah** [EasyEngine/easyengine#531]
**NOTE:** This issue is just for my finding and you are free to test this things on your development environment not in production environments.

**Step 1:** Add following lines at the top

```
root@vagrant-ubuntu-trusty-64:~# vim /etc/nginx/common/wpfc.conf
set $wp_login_cache "";

if ($http_cookie ~* "wordpress_logged_in_[^=]*=([^%]+)%7C") {
        set $wp_login_cache wordpress_logged_in_$1;
}

fastcgi_cache_key "$scheme$request_method$host$request_uri$wp_login_cache";

```

**Step2:** Comment out following blocks

```
#if ($query_string != "") {
#  set $skip_cache 1;
#}
# Don't cache URL containing the following segments
#if ($request_uri ~* "(/wp-admin/|/xmlrpc.php|wp-.*.php|index.php|/feed/|sitemap(_index)?.xml|[a-z0-9_-]+-sitemap([0-9]+)?.xml)") {
#  set $skip_cache 1;
#}
# Don't use the cache for logged in users or recent commenter
#if ($http_cookie ~* "comment_author|wordpress_[a-f0-9]+|wp-postpass|wordpress_no_cache|wordpress_logged_in") {
#  set $skip_cache 1;
#}

```

**Step 3:** Reload nginx

```
root@vagrant-ubuntu-trusty-64:~# service nginx reload
 * Reloading nginx configuration nginx                                                                                  [ OK ]
```

**Step 4:** Login into http://example.com/wp-admin/
**Step 5:** After successful login stop php5-fpm and/or hhvm service
**Step 6:** Check your   http://example.com/wp-admin/ is working or not

**Step 7:** Start php5-fpm and/or hhvm service
**Step 8:** Register new user
**Step 9:** Login into http://example.com/wp-admin/ with newly created user
**Step 10:** Repeat step 5 and step 6

Let me know your finding if you test this also write your test case here so i will test all those test cases

Thanks

**Comment by rahul286** [comment]
@MiteshShah closing this issue as part of the cleanup drive. If you need any inputs from me, please let me know. :)
