### ISSUE TITLE
Options to set ENV Variables

### ISSUE THREAD

**Issue by irazasyed** [EasyEngine/easyengine#545]
Hi,

Is there a possibility for you guys to add a way for us to add site specific ENV variables to the PHP Config?

Something like `include` you've done with nginx, just maybe also include `.env` file along with other `fastcgi_params` ?

That way we can optionally set ENV Variables for that specific install and in fact this should also be used with WP install, instead of hardcoding it.

**Comment by rahul286** [comment]
@irazasyed sorry for a delayed reply. 

We do use `.env` files with `wp-config.php` but how do you plan to use it with Nginx? Can you please provide a detailed use case? I am unable to understand your usage.

**Comment by irazasyed** [comment]
@rahul286 No worries. While this issue is quite an old one and I've since moved to Laravel Forge setup for all my servers but I'll still explain my use case.

So basically, Since the nginx config files are auto-generated (site config), modifying them manually and managing them is a bit of an issue, especially if we have multiple accounts and sites.

So the idea was to set up a `conf` dir within the site's root dir and any nginx config file within this dir will automatically be included within the server block of the site's config file (i.e. in `sites-enabled`).

This way, we can add all sorts of config files for that particular site within its own directory and can organize it as well as lock it within the user account (if any) and don't have to make changes to the core file. It's also useful to backup, setup and migrate since we just need to drop-in the file and can also send the config files to the clients/others to drop-in as well and don't have to mess around with the core config files.

Here's a preview of my current setup with forge which I've been using it for years now:
<img width="385" src="https://user-images.githubusercontent.com/1915268/40878180-d5515d9e-66aa-11e8-822f-6402fe7acbc0.png">

**Comment by rahul286** [comment]
@irazasyed Thanks for explaining.

EE already does this. Here is one sample code line https://github.com/EasyEngine/easyengine/blob/v3.8.1/ee/cli/templates/virtualconf.mustache#L46

```
-     {{^vma}}{{^rc}}include {{webroot}}/conf/nginx/*.conf;{{/rc}}{{/vma}}
```

For `example.com`, it roughly translates to

```
 	include /var/www/example.com/conf/nginx/*.conf;
```

In EE V4 also, we have kept similar provision. In fact in EE v4, since we are using containers, every site has its own copy of complete (and minimal) nginx conf in one location. So we believe it will be easier to manage.

I am closing this issue since this is already solved. :)
