### ISSUE TITLE
Reload: mysql [Failed] / Setting up database (2003, "Can't connect to MySQL server on 'localhost' (111)")

### ISSUE THREAD

**Issue by ghost** [EasyEngine/easyengine#568]
Well,

as stated in the title I get the mysql-error if I want to create a site on a complete new setup ubuntu 14.04 LTS (64 Bit).

I reinstalled the server already several times and always get this error.
- apt-get update && apt-get upgrade
- wget -qO ee rt.cx/ee && sudo bash ee
- sudo ee site create DOMAIN.TLD --wpfc --pagespeed

Adding repository for MySQL, please wait...
Adding repository for NGINX, please wait...
Adding repository for PHP, please wait...
Updating apt-cache, please wait...
Installing packages, please wait...
Downloading MySQLTuner           [Done]
Downloading WP-CLI               [Done]
Reload : postfix   [OK]
Reload : nginx     [OK]
Restart : php5-fpm  [OK]
Reload : mysql     [Failed]
Running pre-update checks, please wait...
Setting up NGINX configuration  [Done]
Setting up webroot              [Done]
Downloading Wordpress           [Done]
Setting up database             (2003, "Can't connect to MySQL server on 'localhost' (111)")

Unfortunately I always also have to completely reinstall, cuz it's not possible to delete the site at this point, as he can't remove it from the database.

Service MySQL resart works fine and is stopping and running the process as intended.

Any advice? Do I need to install something in first hand which got forgotten in the doc or something? kinda frustrated at this point, cuz I'm on this since 8 hours -,-

**Comment by Vyndariel** [comment]
ok, it seems that if you run ee stack install --mysql manually before and 
service mysql restart

before creating a new site it works - but I still think the script should cover this properly

**Comment by TotalLag** [comment]
I am also running into this issue with the latest version of ee:

```
Adding repository for MySQL, please wait...
Updating apt-cache, please wait...
Installing packages, please wait...
Downloading MySQLTuner           [Done]
Reload : mysql     [Failed]
Successfully installed packages
```
ghost's suggestion does indeed work.  thank you!

**Comment by rahul286** [comment]
Sorry for a delayed reply. I hope your issue is fixed by now.

If you are still facing the issue, please use http://community.rtcamp.com/c/easyengine for further support.

We are cleaning up issue tracker and closing this issue because we won't be able to contribute to this discussion further.
