### ISSUE TITLE
Using Nginx Upload Module to speed up uploads and reduce load on PHP

### ISSUE THREAD

**Issue by gagan0123** [EasyEngine/easyengine#578]
http://wiki.nginx.org/HttpUploadModule

In current scenario, PHP is taking the upload request via nginx, so a PHP process is spawned till the upload is completed. As PHP is the bottle neck for the performance of the server, we can delegate the handling of Uploads to Nginx, which can take care of a lot more requests simultaneously than PHP-FPM. 

The best use case would be a server running BuddyPress with rtMedia, having a lot of users, constantly uploading media files. If PHP-FPM is going to take care of all the uploads, server is going to slow down, but if Nginx takes control of the uploads, it can handle a lot more traffic.

**Comment by gagan0123** [comment]
Also, we can use it to give upload functionality to simple HTML sites as well, no need for PHP just for uploads.

**Comment by rahul286** [comment]
@gagan0123 did you test this Nginx upload module with PHP and WordPress manually?

**Comment by rahul286** [comment]
Closing this issue as this needs external contributors.
