### ISSUE TITLE
Fatal error: unexpected St13runtime_error: locale::facet::_S_create_c_locale name not valid

### ISSUE THREAD

**Issue by RavanH** [EasyEngine/easyengine#583]
After trying `ee site update example.com --hhvm=on` I find all pages return an empty response. The hhvm/error.log says many times over:

```
Fatal error: unexpected St13runtime_error: locale::facet::_S_create_c_locale name not valid
```

After searching the net it turns out this error occurs when the some locale stuff is missing. I ran `dpkg-reconfigure locales` choosing both en_US.UTF8 and fr_FR.UTF8, the language that was selected when I ordered the VPS and then chose C as default (don't know why).

Then after a `service hhvm restart` the site is back up :)

Could there be added a locale check in easyengine? Maybe aborting the switch to HHVM when a locale is missing or some config mismatch and then some instructions on how to fix locales before attempting again?

**Comment by RavanH** [comment]
Looks like https://github.com/rtCamp/easyengine/issues/580 is related to missing locale too...

**Comment by rahul286** [comment]
Sorry for a delayed reply. We no longer support HHVM. Please use PHP 7.

Beside this can be locale issue as well.

**Comment by RavanH** [comment]
Hi @rahul286 yes I've long since abandoned HHVM for PHP7 :)
