### ISSUE TITLE
[Feature Req.] Add support for external redis server

### ISSUE THREAD

**Issue by brennentsmith** [EasyEngine/easyengine#597]
Having the ability to attach a external redis server would be great for handling multiserver/geolocated distribution. 

Perhaps having a variable within /etc/ee/ee.conf which then maps to `upstream redis` within the /etc/nginx/conf.d/upstream.conf template?

See https://github.com/rtCamp/easyengine/blob/ddd825bb889db1596699beea97f444d2a83aae6a/ee/cli/plugins/stack.py#L459

**Comment by ahansson89** [comment]
+1

**Comment by MattyLB** [comment]
+1

I would love to connect to my AWS ElastiCache redis server but I can't seem to find where or how to change the strings in my EE config(s) and I'm afraid I'll break something if I do.

If this is documented, I apologize for not finding it.

**Comment by ali-husain** [comment]
Just fyi for anyone confused about this setting.  The file mentioned about writes to /etc/nginx/conf.d/upstream.conf

You can edit the 
`upstream redis {
    server 127.0.0.1:6379;
    keepalive 10;
}`
Section to your external redis server.

**Comment by rahul286** [comment]
Yep. We recommend @ali-husain method. It just one line change so we do not plan to add such thing in EE core at the moment.
