### ISSUE TITLE
WP API Caching

### ISSUE THREAD

**Issue by JosefJezek** [EasyEngine/easyengine#605]
Could you add support for caching WP API?
- https://github.com/WP-API/WP-API
- http://wpquestions.com/question/showChrono/id/9931

**Comment by espellcaste** [comment]
Not sure if here is the place to add this.. Right?!

**Comment by mbtamuli** [comment]
The WP REST API has been merged into WordPress core.
Thanks for the comments. Closing this issue for now, feel free to continue the discussion.
