### ISSUE TITLE
Composer support

### ISSUE THREAD

**Issue by dimadin** [EasyEngine/easyengine#607]
It is surprising that [Composer](https://getcomposer.org/) isn't supported by EasyEngine nor does any issue about it exist.

I always find myself needing to install it globally so I think it would be great to have this auto installed on all servers like `wp cli`.

Thing to take in consideration is how to install it on existing servers when running update and how to do that when Composer is already installed either globally or locally.

**Comment by rahul286** [comment]
@dimadin can you please write down a use case? 

Installing composer is just a command. I have written a lot about composer - https://rtcamp.com/tutorials/composer-wordpress/ but I am not yet sure how composer will work with easyengine.

So any use-case, easyengine + composer integration ideas will be helpful.

**Comment by dimadin** [comment]
@rahul286 I didn't know that, thanks.

I know it is simple command, however, I find myself using `composer` command only to realize it is not installed, then going to their website for installing command.

That is why I thought it would be good idea to include it, it is not something big, yet it will make EasyEngine more friendly to developers. Another thing that I forgot to mention is that it can be updated when other tools.

I don't know about technical side, I only know that you can install it globally since I am using that on multiple servers.

**Comment by joeguilmette** [comment]
This is an interesting question. At what point should the answer be "no, we
won't auto install that software." Things like nginx are necessary, and
things like ClamAV aren't.

Is composer necessary for EasyEngine to function? Does it make WP installs
created by EasyEngine any better?

If the answers are no, then I think it should not be included.

**Comment by dimadin** [comment]
@joeguilmette That would be fine, but I was not aware if policy or approach like that exists.

**Comment by w33zy** [comment]
This could become a 'slippery-slope' issue because the same thing could be said for node, npm, grunt, gulp, etc.

**Comment by joeguilmette** [comment]
Are those installed by EasyEngine? Does EasyEngine do anything besides just
install them?

Those aren't rhetorical questions, I genuinely don't know the answer.

**Comment by hannahwarmbier** [comment]
As someone who is playing around with the idea of using EE on my server used mostly for non-WP PHP projects, Composer would definitely be useful.

**Comment by rahul286** [comment]
Sorry for a delayed reply.

EasyEngine v4 is based on WP-CLI and uses composer itself for its own dependency management. Later in 4.1, we have the plan to bring "EE Packages" which are internally managed using composer.

But we are still undecided if final packaging will be a PHAR archive or a docker image or both (with the choice to use either).

So EEv4 installer may have composer pre-installed if its needed get EE working itself. Otherwise, I am sorry to say we do not wish to add extra tools to the core.

That being said we are a huge fan of composer itself https://easyengine.io/tutorials/composer-wordpress/
