### ISSUE TITLE
hhvm with php-fpm  but hhvm offen stop

### ISSUE THREAD

**Issue by lanranjun** [EasyEngine/easyengine#614]
command failed: "lsof -t -i :9000 | xargs kill -9"
Unable to start page server
Shutting down due to failure(s) to bind in HttpServer::runAndExitProcess
command failed: "lsof -t -i :9000 | xargs kill -9"
command failed: "lsof -t -i :9000 | xargs kill -9"
command failed: "lsof -t -i :9000 | xargs kill -9"
Unable to start page server
Shutting down due to failure(s) to bind in HttpServer::runAndExitProcess
[Fri Sep 11 14:11:30 2015] [hphp] [21938:7f77e5bff700:6:000001] [] Finished singleJitRequest 1
[Fri Sep 11 14:11:33 2015] [hphp] [21938:7f77eabff700:10:000001] [] Finished singleJitRequest 2
[Fri Sep 11 14:11:44 2015] [hphp] [21938:7f77e5bff700:7:000001] [] Finished singleJitRequest 3
[Fri Sep 11 14:11:46 2015] [hphp] [21938:7f77eabff700:11:000001] [] Finished singleJitRequest 4
[Fri Sep 11 14:11:48 2015] [hphp] [21938:7f77e5bff700:8:000001] [] Finished singleJitRequest 5
[Fri Sep 11 15:03:01 2015] [hphp] [22301:7f0aa4fff700:11:000001] [] Finished singleJitRequest 1
[Fri Sep 11 15:03:01 2015] [hphp] [22301:7f0a9dbff700:2:000001] [] Finished singleJitRequest 2
[Fri Sep 11 15:03:29 2015] [hphp] [22301:7f0aa4fff700:13:000001] [] Finished singleJitRequest 3
[Fri Sep 11 15:04:03 2015] [hphp] [22301:7f0a9dbff700:3:000001] [] Finished singleJitRequest 4
[Fri Sep 11 15:04:03 2015] [hphp] [22301:7f0aa4fff700:15:000001] [] Finished singleJitRequest 5
[Fri Sep 11 23:01:09 2015] [hphp] [24189:7f1e0a7ff700:12:000001] [] Finished singleJitRequest 1
[Fri Sep 11 23:01:13 2015] [hphp] [24189:7f1e033ff700:7:000001] [] Finished singleJitRequest 2
[Fri Sep 11 23:01:20 2015] [hphp] [24189:7f1e0a7ff700:13:000001] [] Finished singleJitRequest 3
[Fri Sep 11 23:01:44 2015] [hphp] [24189:7f1e033ff700:8:000001] [] Finished singleJitRequest 4
[Fri Sep 11 23:01:55 2015] [hphp] [24189:7f1e0a7ff700:16:000001] [] Finished singleJitRequest 5
[Fri Sep 11 23:09:13 2015] [hphp] [1909:7fd621bff700:5:000001] [] Finished singleJitRequest 1
[Fri Sep 11 23:09:29 2015] [hphp] [1909:7fd621bff700:6:000001] [] Finished singleJitRequest 2
[Fri Sep 11 23:09:39 2015] [hphp] [1909:7fd628bff700:14:000001] [] Finished singleJitRequest 3
[Fri Sep 11 23:09:41 2015] [hphp] [1909:7fd621bff700:11:000001] [] Finished singleJitRequest 4
[Fri Sep 11 23:09:42 2015] [hphp] [1909:7fd628bff700:15:000001] [] Finished singleJitRequest 5
[Sat Sep 12 09:22:33 2015] [hphp] [4169:7f0bdb7ff700:12:000001] [] Finished singleJitRequest 1
[Sat Sep 12 09:23:20 2015] [hphp] [4169:7f0bdb7ff700:13:000001] [] Finished singleJitRequest 2
[Sat Sep 12 09:24:47 2015] [hphp] [4169:7f0bdb7ff700:14:000001] [] Finished singleJitRequest 3
[Sat Sep 12 09:25:05 2015] [hphp] [4169:7f0bdb7ff700:15:000001] [] Finished singleJitRequest 4
[Sat Sep 12 09:25:26 2015] [hphp] [4169:7f0bdb7ff700:16:000001] [] Finished singleJitRequest 5
[Sat Sep 12 20:15:44 2015] [hphp] [1910:7f3b223ff700:1:000001] [] \nWarning: unable to connect to 127.0.0.1 [111]: Connection refused
[Sat Sep 12 20:15:44 2015] [hphp] [1910:7f3b223ff700:1:000002] [] \nWarning: Failed connecting to redis server at 127.0.0.1: Connection refused
[Sat Sep 12 20:17:10 2015] [hphp] [1910:7f3b223ff700:5:000001] [] Finished singleJitRequest 1
[Sat Sep 12 20:17:10 2015] [hphp] [1910:7f3b1d7ff700:15:000001] [] Finished singleJitRequest 2
[Sat Sep 12 20:17:14 2015] [hphp] [1910:7f3b223ff700:6:000001] [] Finished singleJitRequest 3
[Sat Sep 12 20:17:29 2015] [hphp] [1910:7f3b1d7ff700:16:000001] [] Finished singleJitRequest 4
[Sat Sep 12 20:17:41 2015] [hphp] [1910:7f3b223ff700:7:000001] [] Finished singleJitRequest 5

**Comment by rahul286** [comment]
Sorry for a delayed reply. We no longer support HHVM. Please use PHP 7.

We are cleaning up issue tracker and closing this issue because we won't be able to contribute to this discussion further.

Please use http://community.rtcamp.com/c/easyengine for future support questions.
