### ISSUE TITLE
WP Super Cache config doesn't pass query strings to REST API

### ISSUE THREAD

**Issue by dimadin** [EasyEngine/easyengine#635]
Steps to reproduce:
- Create site with `--wpsc` command.
- Install WP REST API (version 2) plugin (currently 2.0-beta4, v1 is a separate plugin).
- Go to URL for simple posts retrieving, e.g. `http://example.com/wp-json/wp/v2/posts`.
- Now add some query strings to it, e.g. `http://example.com/wp-json/wp/v2/posts?page=2` or `http://example.com/wp-json/wp/v2/posts?filter[s]=test`. Same results.
- Compare that to normal REST API installation (e.g. `--wpfc` on EE will work).

Problem is on server level because even if you enter `print_r( $_GET );` in `index.php` you get empty array.

I think that EE should become compatible with REST API because parts of this plugin are being merged in next WordPress version, while rest is being merged in the next WP version (see [article](http://wptavern.com/the-first-half-of-the-rest-api-is-officially-added-to-wordpress-core)), so it means it is here to stay.

**Comment by rahul286** [comment]
I think if issue happens with wp-super-cache only, may be it is issue with wp-super-cache.

We are using REST API and excited about it's inclusion in WordPress core. :-)

**Comment by dimadin** [comment]
I forgot to mention that even if you deactivate WP Super Cache same thing happens.

**Comment by andremacola** [comment]
I did a post about that in the past at RTCamp Community Forum and they answer is something about the compatibility with WooCommerce 

In wpsc.conf add/change:

# Use cached or actual file if they exists, Otherwise pass request to WordPress
location / {
	# try_files /wp-content/cache/supercache/$http_host/$cache_uri/index.html $uri $uri/ /index.php$args;
	# try_files /wp-content/cache/supercache/$http_host/$cache_uri/index.html $uri $uri/ /index.php?$query_string;
	try_files /wp-content/cache/supercache/$http_host/$cache_uri/index.html $uri $uri/ /index.php?$args;
}

**Comment by rahul286** [comment]
Sorry for a delayed reply. I hope your issue is fixed by now.

We will be dropping support for wp super cache anyway.

If you are still facing the issue, please use http://community.rtcamp.com/c/easyengine for further support.

We are cleaning up issue tracker and closing this issue because we won't be able to contribute to this discussion further.
