### ISSUE TITLE
EE Site Create Fails @ DB Creation if mysql password has special characters in my.cnf

### ISSUE THREAD

**Issue by aksuited** [EasyEngine/easyengine#639]
I guess it is a bug. To have a mysql password with special characters (# for example) you have to enclose in in quotes in my.cnf (i.e. password = "p@s$") which seems to break the EE Site Create at the mysql portion even when both my.cnf files have the correct password in correct format.

Example:   

(mysql root password is set to 'pass' & mysql command auto logs on)
tail /etc/mysql/conf.d/my.cnf & tail /root/.my.cnf:
[client]
user = root
password = pass
**This Works fine**

 (mysql root password is set to 'p@$$' & mysql command auto logs on)
tail /etc/mysql/conf.d/my.cnf & tail /root/.my.cnf:
[client]
user = root
password = "p@$$"
**This DOES NOT WORK with EE SITE CREATE**

**Comment by aksuited** [comment]
Just verified this exact problem on fresh Ubuntu 16.04 install and new clean EE install.  Change root password in mysql to use special characters, then edit /etc/mysql/conf.d/my.cnf to have proper password (must use single or double quotes for special characters to work), breaks all  EE Site Create commands with a DB as stated previously.

**Comment by liquidia** [comment]
me too its seems its wide spread issue should be fixed on urgent basis.

**Comment by rahul286** [comment]
Sorry for a delayed reply. I hope your issue is fixed by now.

If you are still facing the issue, please use http://community.rtcamp.com/c/easyengine for further support.

We are cleaning up issue tracker and closing this issue because we won't be able to contribute to this discussion further.
