### ISSUE TITLE
Feature Request:  Awstats 

### ISSUE THREAD

**Issue by manjeshpv** [EasyEngine/easyengine#642]
Its nice to see easyengine with easystats,:)

http://blog.bytetouch.com/system-administration/how-to-awstats-installation-and-configuration-on-debian/
http://kamisama.me/2013/03/20/install-configure-and-protect-awstats-for-multiple-nginx-vhost-on-debian/

**Comment by manjeshpv** [comment]
I followed [http://blog.bytetouch.com/system-administration/how-to-awstats-installation-and-configuration-on-debian/](this article)

1. Installed awstats` awstats 7.2 (build 1.992) . `apt-get install 
2. Created a sample file [https://gist.github.com/manjeshpv/97ea6402ac0ce1f603ae]( /etc/awstats/awstats.sample.conf)
3. Created a domain to see stats `ee site create awstats.mydomain.com --html`
4. Create a shell script [https://gist.github.com/manjeshpv/e81990c668d89a7ddd40](/root//awstats.sh)
5. Created a folder `/var/bin/awstats` for build static awstats script
6. Added above static page generation script to logrotate config [https://gist.github.com/manjeshpv/5ccb4921e0d559378d7d](/etc/logrotate.d/nginx)
5. Enable awstats for easyengine site using - `$ ./awstats.sh my-domain.com`
6. Added another site using - `$ ./awstats.sh another-domain.com`

Manual Test -  Generated Awstats using
```sh
logrotate -vf /etc/logrotate.conf
```

Result:
http://awstats.mydomain.com/awstats.my-domain.com.html
http://awstats.mydomain.com/awstats.another-domain.com.html

**Comment by simonbouchard** [comment]
+1

**Comment by mbtamuli** [comment]
Thanks for the comments. As EasyEngine v4 will be Docker container based, it makes sense to use a compatible application for monitoring and/or statistics. We can consider something like [Prometheus](https://prometheus.io/)
Closing this issue for now.
