### ISSUE TITLE
Feature Request: Expression Engine

### ISSUE THREAD

**Issue by simonbouchard** [EasyEngine/easyengine#647]
Hello guys !

Thanks for your wonderful contribution ! I'm using EasyEngine over a dozen servers, mainly for WordPress sites and now I need to setup a huge corporate website using [Expression Engine](https://ellislab.com/). 

I don't know much about Expression Engine, I created a site with the --php parameter, it's working though... but I don't know if it's the optimal configuration for this CMS. 

Cheers !

**Comment by frederichoule** [comment]
Hi Simon,

Creating a website with --php is a good start, but you may have to modify your NGINX conf to match with the caching system in Express Engine, if there's one. If not, you could build one using NGINX Fast Cache, if you expect a good amount of traffic.

**Comment by rahul286** [comment]
In v4, we will have package support. This can be done via EE packages later.
