### ISSUE TITLE
Executing command return wrong status code even after successful execution

### ISSUE THREAD

**Issue by pradeepbishnoi** [EasyEngine/easyengine#648]
Performed the EasyEngine stack installation using below command as follows -

root@vTest2:/opt/temp# sudo ee stack install
PHP already installed
MySQL connection is already alive
Adding repository for NGINX, please wait...
Adding SWAP file, please wait...
Updating apt-cache, please wait...
Installing packages, please wait...
Downloading WP-CLI               [Done]
Downloading phpMyAdmin           [Done]
Downloading Adminer              [Done]
Downloading phpMemcachedAdmin    [Done]
Downloading clean.php            [Done]
Downloading opcache.php          [Done]
Downloading Opgui                [Done]
Downloading OCP.php              [Done]
Downloading Webgrind             [Done]
Downloading pt-query-advisor     [Done]
Downloading Anemometer           [Done]
Reload : postfix   [OK]
Reload : nginx     [OK]

root@vTest2:/opt/temp# echo $?
1

Expected Result - 
Ideally it should return 0 for success.

**Comment by gau1991** [comment]
@pradeepbishnoi ,
Hi we are not able to reproduce this issue on testing env.
Can you please move this thread to community forum http://community.rtcamp.com/c/easyengine?
