### ISSUE TITLE
PHP 7.0 

### ISSUE THREAD

**Issue by vikas5914** [EasyEngine/easyengine#651]
When will we get php 7.0 ?

**Comment by MattyLB** [comment]
The PHP team is still working out some lingering bugs so I would expect the
next point release to be as close to gold as we need. Patience young Jedi

**Comment by harshadyeola** [comment]
We are waiting for complete set of packages to be built. 
Please refer  https://github.com/gplessis/dotdeb-php/issues/106

**Comment by andremacola** [comment]
Any update on this ?

**Comment by kklemen** [comment]
Can we see php7 implemented as "experimental" feature, like hhvm and redis are?

A lot of us are waiting to use php7 with redis cache and care not much for memcache package or imagick.

**Comment by mrmad** [comment]
Lacking support for HTTP/2  is even a bigger issue...

**Comment by warlock666** [comment]
Bumping this up for PHP 7.0 support.

**Comment by gino8080** [comment]
bump thank you!

**Comment by MattyLB** [comment]
+1 bump for PHP 7.0.3

**Comment by MattyLB** [comment]
Will this be available as a beta version initially? If there is a beta available, I would love to help with testing. Thanks!

**Comment by rockdrigo** [comment]
@MattyLB i want to try the php 7 version how i can install and try the beta version of easy engine???

**Comment by MattyLB** [comment]
@rockdrigo - I'm not the developer so I can't help you with this. I was simply asking if a beta version will be available for us to test before releasing it live and running into potential problems with servers running both versions of PHP, etc.

**Comment by gino8080** [comment]
Just update easyengine to 3.5,

how to update php to 7?

thank you!

**Comment by harshadyeola** [comment]
@gino8080 
Please check  https://easyengine.io/docs/php7/
