### ISSUE TITLE
error installing wordpress

### ISSUE THREAD

**Issue by Endy121** [EasyEngine/easyengine#652]
its says :

Running pre-update checks, please wait...
Setting up NGINX configuration [Done]
Setting up webroot [Done]
Downloading Wordpress [Done]
Setting up database [Done]
Oops Something went wrong !!
Calling cleanup actions ...
Reload : nginx [OK]
Check logs for reason `tail /var/log/ee/ee.log` & Try Again!!!

**Comment by harshadyeola** [comment]
@Endy121 
Can you please provide me EasyEngine version with command `ee -v`.
As this issue has been fixed in EasyEngine version `3.3.15`
Please update your EasyEngine to` v3.3.15`

**Comment by Endy121** [comment]
im installing on new vps here.

**Comment by gagomap** [comment]
@harshadyeola : What command can i use to update WP-CLI
```bash
ee update
```
or
``` bash
ee stack upgrade
```
?
So if i have installed Wordpress on EE 3.3.10, should i upgrade EE to 3.3.15 for update WP to 4.4 ?

**Comment by harshadyeola** [comment]
@gagomap 

`ee update` will update EasyEngine and WP-CLI version on your system.

**Comment by gagomap** [comment]
Thank you :+1:

**Comment by harshadyeola** [comment]
@Endy121 

Could you provide me output for `ee -v`?

**Comment by gagomap** [comment]
@harshadyeola : i just have updated ee to 3.3.15, it's complete but it show:
```bash
dpkg: error: --compare-versions takes three arguments: <version> <relation> <version>

Type dpkg --help for help about installing and deinstalling packages [*];
Use 'apt' or 'aptitude' for user-friendly package management;
Type dpkg -Dhelp for a list of dpkg debug flag values;
Type dpkg --force-help for a list of forcing options;
Type dpkg-deb --help for help about manipulating *.deb files;

Options marked [*] produce a lot of output - pipe it through 'less' or 'more' !
```

Is it an error ?

**Comment by harshadyeola** [comment]
@gagomap 

can you provide me output for `which wp` and `wp --allow-root cli version | awk '{print $2}'`

**Comment by gagomap** [comment]
yes, it's here:

```bash
root@vps:  which wp
/usr/bin/wp
```

and this command:
```bash
wp --allow-root cli version | awk '{print $2}'
```
show nothing.

**Comment by harshadyeola** [comment]
@gagomap 

seems like you have very old version of `wp-cli` installed so it could not compare versions.
In this case you need manual upgrade `ee update && ee stack upgrade --wpcli`

**Comment by screamolic** [comment]
Im reinstalling again and its works. Thanks... :)

**Comment by gagomap** [comment]
@harshadyeola : i had updated to EE 3.3.14 before. But after i used command:  ```bash ee update && ee stack upgrade --wpcli``` , this command ```bash wp --allow-root cli version | awk '{print $2}' ``` still show nothing.
