### ISSUE TITLE
GeoIP2

### ISSUE THREAD

**Issue by frederichoule** [EasyEngine/easyengine#654]
Any (plan to/way to) enable support for GeoIP2 MaxMind databases?

See: https://github.com/leev/ngx_http_geoip2_module/blob/master/README.md

Thanks.

**Comment by frederichoule** [comment]
I think this would make GeoIP requests faster, using the new Maxmind database format. Seems like relatively simple to enable. What do you think?

**Comment by MattyLB** [comment]
https://github.com/leev/ngx_http_geoip2_module/blob/master/README.md (working
URL link)

+1

**Comment by frederichoule** [comment]
Any update on this? Seems like relatively easy to implement. Thanks!

**Comment by MattyLB** [comment]
I'm now getting warnings from WooCommerce stating that the MaxMind GeoIP Database does not exist. I never had this issue before, so I'm assuming it's a new requirement in WooCommerce 2.6.x and/or WP 4.5.x?

Anyway, here is the warning from Admin > WooCommerce (2.6.1) > System Status ...

> MaxMind GeoIP Database: 		The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: /var/www/zipswap.com/htdocs/wp-content/uploads/GeoIP.dat

**Comment by frederichoule** [comment]
Any update on GeoIP2 Module?

**Comment by frederichoule** [comment]
Ok so I built it using the nginx-build repo from EasyEngine. Here is the dynamic module you can include with "load_module".
[ngx_http_geoip2_module.zip](https://github.com/EasyEngine/easyengine/files/977386/ngx_http_geoip2_module.zip)

**Comment by mexiter** [comment]
So @frederichoule  How do I install this module on easyengine, and do I need to remove the old Geoip(version1)?

**Comment by frederichoule** [comment]
This is how I did it:

**/etc/nginx/nginx.conf**
```
include /etc/nginx/modules/*.conf;
```

**/etc/nginx/modules/geoip2.conf**
```
load_module /etc/nginx/modules/ngx_http_geoip2_module.so;

geoip2 /etc/nginx/modules/GeoIP2-Country.mmdb {
  $geoip2_country_code default=CA country iso_code;
}
```

**Comment by mexiter** [comment]
@frederichoule  Thank you, 

I get an error ""load_module" directive is not allowed here in /etc/nginx/conf.d/geoip2.conf:1"

**Comment by rahul286** [comment]
In V4, we are using https://openresty.org/ and it seems geoip2 is not already included. If anyone has a workaround for this with openresty, please send a pull request or atleast provide details for us to work on.

**Comment by s-a-s-k-i-a** [comment]
Any chances to see this in ee 3.8.2?

**Comment by frederichoule** [comment]
@s-a-s-k-i-a there you go: https://www.dropbox.com/s/dar518fff5ciysd/ngx_http_geoip2_module.so?dl=0

**Comment by frederichoule** [comment]
@s-a-s-k-i-a there you go https://www.dropbox.com/s/dar518fff5ciysd/ngx_http_geoip2_module.so?dl=0

**Comment by frederichoule** [comment]
@s-a-s-k-i-a there you go
[ngx_http_geoip2_module.zip](https://github.com/EasyEngine/easyengine/files/2119935/ngx_http_geoip2_module.zip)

**Comment by frederichoule** [comment]
Sorry, I uploaded the wrong version, not once, but twice. Here is the good one for Nginx 1.14.0, and it works with EE 3.8.2.

[ngx_http_geoip2_module.zip](https://github.com/EasyEngine/easyengine/files/2120035/ngx_http_geoip2_module.zip)

**Comment by rahul286** [comment]
We will be happy to add this either via a contribution to openresty or an EE package. Currently we wont be able to put any efforts into handling this in core.
