### ISSUE TITLE
Build nginx with the last OpenSSL version

### ISSUE THREAD

**Issue by jmesam** [EasyEngine/easyengine#658]
Hi,
I'm testing the brand new http/2 support (v3.4.0) and it works amazing, but ALPN because it need OpenSSL >= 1.0.2. Currently ee build nginx with OpenSSL 1.0.1f 6 Jan 2014.

ALPN is necessary to negotiate the protocol to use between server and client. If it is not implemented by the TLS lib on your server, the client will only ever talk HTTP/1.1. With ALPN, the client gives the server a list of protocols in its order of preference and the server picks the one it wants, while with NPN the client makes the final choice.

Thank you in advance!

**Comment by MattyLB** [comment]
+1

**Comment by karlhaworth** [comment]
+1

**Comment by klausbrinch** [comment]
+1

**Comment by gau1991** [comment]
This is know issue. Its related to our https://github.com/EasyEngine/nginx-build repo. We need to build our own OpenSSL packages to support for ALPN. 
We are already trying to build our own OpenSSL on our local repo. We will update Mainline repo once we successfully built OpenSSL.

**Comment by gau1991** [comment]
We have now built Nginx with OpenSSL 1.0.2e, please update Nginx package to 1.9.9-7ppa so that you will get ALPN support also.

You can use following commands to update Nginx mainline
```
apt-get update
apt-get install nginx-mainline
service nginx restart
```
You can test ALPN support on https://tools.keycdn.com/http2-test
