### ISSUE TITLE
Http/2 with Own SSL

### ISSUE THREAD

**Issue by vikas5914** [EasyEngine/easyengine#659]
It's great to see that with v 3.4 we get HTTP/2 support.
I already have my own ssl from namecheap.com. I am currently using it with EE. Used this tutorial for installing ssl: [click here](https://ar.al/scribbles/setting-up-ssl-with-nginx-using-a-name-cheap-essentials-wildcard-certificate-on-digital ocean/)

So how to use new HTTP/2 with my own ssl. there is no documentation or command info given in EE site.

**Comment by w33zy** [comment]
All you have to do is edit ````/etc/nginx/sites-available/yourdomain.com```` and add ````http2;```` to where it says  ````listen 443 ssl;````  so that line now becomes ````listen 443 ssl http2;```` and save.

Then run ````nginx -t & service nginx reload````

**Comment by mrmad** [comment]
When trying to enable letsencrypt via command line it get's tuck forever and nothing happens. This is not beta, this need a complete rewrite....:

ee site update example.com --letsencrypt=on
Letsencrypt is currently in beta phase. 
Do you wish to enable SSl now for example.com?
Type "y" to continue [n]:y

**Comment by MattyLB** [comment]
The SSL process takes me about 1 to 3 minutes, depending on server speed.
There are a lot of things happening in the background to create the certs,
update the configs, etc. I slight delay, especially at peak times for the
LetsEncrypt server, is to be expected. It would be nice in a future EE
release if we could get some kind of progress bar or warning that it may
take a few minutes to complethe.

Hopefully we're not bogging down let's encrypts servers to a point where
they remove free ssl options, so while it is still free, it's hard to ask
for too much.

**Comment by mrmad** [comment]
Actually you are right and I was too impatient. I signed the ssl-certificates with leyt's encrypt a couple of days ago (without easyengine) and it was a superfast, seamingless process.

**Comment by karlhaworth** [comment]
I'm having issues with the --letsencrypt option as well. I left it running for 10 minutes before I killed he process. I created my own certs manually.

**Comment by mrmad** [comment]
Could someone post a default config page for a site that was created via easy engine with ssl / http2 enabled? The creation process fails here, but I have manually installed let's encrypt manually so I could merge the config files.
