### ISSUE TITLE
Enabling SO_REUSEPORT by default

### ISSUE THREAD

**Issue by vefaliahmet** [EasyEngine/easyengine#660]
From version 1.9.1, nginx introduces a new feature that enables use of the SO_REUSEPORT socket option.

Is there anyway to use via easyengine?

**Comment by rahul286** [comment]
We have updated nginx build to 1.14. https://easyengine.io/blog/easyengine-v3-8/

Please use http://community.rtcamp.com/c/easyengine for future support questions.
