### ISSUE TITLE
disable weak Diffie-Hellman (DH) key exchange parameters

### ISSUE THREAD

**Issue by christoferw** [EasyEngine/easyengine#661]
should that be fixed to increase security, or is this still necessary?
infos: https://weakdh.org/

test with: https://www.ssllabs.com/ssltest/analyze.html

**Comment by harshadyeola** [comment]
@christoferw 
Thanks for pointing out the issue.
Those who have issue currently please check fix here. https://easyengine.io/tutorials/nginx/diffie-hellman-logjam-attack-fix/
We will be releasing fix for this issue soon.

**Comment by christoferw** [comment]
@harshadyeola your welcome!

**Comment by MattyLB** [comment]
+1

Great info. Thank you!

**Comment by QROkes** [comment]
+1 I used to fix it manually.

**Comment by brianjking** [comment]
Thanks, also fixed this manually.

**Comment by MattyLB** [comment]
I've fixed this manually on all of my sites. Any word when this will be
included in EE when SSL is activated? I went from a D to an A rating on a
couple sites by adding the cipher list and switching to 2048 bit dhparams.
Either way, this article works!

Matt

**Comment by bynicolas** [comment]
ETA on updating ee template to include this automatically on SSL enabled site?

**Comment by rahul286** [comment]
@mbtamuli is it added to core? https://easyengine.io/tutorials/nginx/diffie-hellman-logjam-attack-fix/

**Comment by kirtangajjar** [comment]
Created a site in v4 and tested it on https://tools.keycdn.com/logjam and https://www.ssllabs.com/ssltest/analyze.html. 

Issue seems to be fixed.

**Comment by mbtamuli** [comment]
An example - https://www.ssllabs.com/ssltest/analyze.html?d=easyengine.io
