### ISSUE TITLE
Webmail access along with Wordpress multisite

### ISSUE THREAD

**Issue by dhiraj-r** [EasyEngine/easyengine#662]
I have created Wordpress Multisite with subdirectory. The problem is webmail.mysite.com get directed to mysite.com, which is expected. I found out it is because of ordering of domains and subdomains. The wordpress guide https://codex.wordpress.org/Configuring_Wildcard_Subdomains_for_multi_site_under_Plesk_Control_Panel is written for apache server. How can I award subdomain, webmail.mysite.com higher priority.

**Comment by garrettcam** [comment]
+1 this also happens for Wordpress Multisite with subdomains.

**Comment by Wemago** [comment]
+1 

Did anyone figured a solution for this?

**Comment by Wemago** [comment]
I've been searching and reading for a solution regarding this but none worked. 
In apache you can set an order so subdomains/domains can be read, but in nginx the only way of doing it is adding a second block specifying the server name and root, but still no success..

Any help with this?

**Comment by Wemago** [comment]
Ok, managed to do it.

Solution was to create the config

> /etc/nginx/sites-available/webmail.site.com

copy the data from 

> /etc/nginx/sites-available/webmail

then enabled the site in

> /etc/nginx/sites-enabled/webmail.site.com

after all this do this commands

> nginx -t 
> /etc/init.d/nginx stop
> /etc/init.d/nginx start

Don't forget to chmod the rights to the config file

**Comment by rahul286** [comment]
Sorry for a delayed reply. I hope your issue is fixed by now.

By the way in v4 we will be dropping webmail support.

If you are still facing the issue, please use http://community.rtcamp.com/c/easyengine for further support.

We are cleaning up issue tracker and closing this issue because we won't be able to contribute to this discussion further.
