### ISSUE TITLE
EE 3.4.0 - cannot create additional site

### ISSUE THREAD

**Issue by MattyLB** [EasyEngine/easyengine#664]
After updating to EE 3.4.0 and upgrading my existing site to --wpredis --letsencrypt and switching to --nginxmainline, everything works fine for that site. In fact, it's faster than ever!

Problem is, when I try to create another site with only --wpredis, it fails on "Reload : nginx". Something I tried was to change the existing site's "redis prefix key" in Nginx-Helper to "nginx-cache1:" in case that was causing a conflict. Actually, I'm not sure why that key isn't the same as the redis key listed in the Redis plugin and the salt key in my wp-config - but I digress. Either way, I cannot add another site.

Any suggestions are appreciated!

Below is the log ...

>Redis is experimental feature and it may not work with all CSS/JS/Cache of your site.
You can disable it by changing cache later.
Do you wish to enable Redis now for yoursite.com?
Type "y" to continue [n]:y
Running pre-update checks, please wait...
Setting up NGINX configuration  [Done]
Setting up webroot              [Done]
Downloading Wordpress           [Done]
Setting up database             [Done]
Installing plugin nginx-helper, please wait...
Setting plugin nginx-helper, please wait...
Installing plugin redis-cache, please wait...
**Reload : nginx     [Failed]**
Oops Something went wrong !!
Calling cleanup actions ...
**Reload : nginx     [Failed]**
service nginx reload failed. check issues with `nginx -t` command.
Check logs for reason `tail /var/log/ee/ee.log` & Try Again!!!
root@ip-172-31-31-224:~# tail /var/log/ee/ee.log
2016-01-14 07:30:46,081 (INFO) ee : [Failed]
2016-01-14 07:30:46,088 (DEBUG) ee : Removing /var/www/yoursite.com
2016-01-14 07:30:46,088 (DEBUG) ee : Removing /var/www/yoursite.com
2016-01-14 07:30:46,122 (DEBUG) ee : dropping database `yoursite_com`
2016-01-14 07:30:46,123 (DEBUG) ee : Exceuting MySQL Statement : drop database `yoursite_com`
2016-01-14 07:30:46,238 (DEBUG) ee : dropping user `yoursite_com`
2016-01-14 07:30:46,240 (DEBUG) ee : Exceuting MySQL Statement : drop user `yoursite_com`@`localhost`
2016-01-14 07:30:46,241 (DEBUG) ee : Exceuting MySQL Statement : flush privileges
2016-01-14 07:30:46,252 (INFO) ee : service nginx reload failed. check issues with `nginx -t` command.
2016-01-14 07:30:46,252 (ERROR) ee : Check logs for reason `tail /var/log/ee/ee.log` & Try Again!!!
root@ip-172-31-31-224:~# nginx -t
**nginx: the configuration file /etc/nginx/nginx.conf syntax is ok**
**nginx: configuration file /etc/nginx/nginx.conf test is successful**
root@ip-172-31-31-224:~# nginx -v
**nginx version: nginx/1.9.9**

**Comment by iam404** [comment]
Hii Matt

Could you please provide output of below command:

`ls -l /etc/nginx/common/`

**Comment by MattyLB** [comment]
@iam404 - here you go, hope this helps!

root@ip-172-31-31-224:~# ls -l /etc/nginx/common/
total 56
-rw-r--r-- 1 root root  208 Nov  3 09:42 acl.conf
-rw-r--r-- 1 root root 1716 Jan  6 21:33 locations.conf
-rw-r--r-- 1 root root  236 Nov  3 09:42 php.conf
-rw-r--r-- 1 root root  237 Nov 11 05:05 php-hhvm.conf
-rw-r--r-- 1 root root 1629 Jan  6 21:33 redis.conf
-rw-r--r-- 1 root root 1671 Jan  6 21:33 redis-hhvm.conf
-rw-r--r-- 1 root root 1137 Nov  3 09:42 w3tc.conf
-rw-r--r-- 1 root root 1138 Nov 11 05:05 w3tc-hhvm.conf
-rw-r--r-- 1 root root 1243 Nov  3 09:42 wpcommon.conf
-rw-r--r-- 1 root root 1247 Nov  3 09:42 wpfc.conf
-rw-r--r-- 1 root root 1248 Nov 11 05:05 wpfc-hhvm.conf
-rw-r--r-- 1 root root 1169 Nov  3 09:42 wpsc.conf
-rw-r--r-- 1 root root 1170 Nov 11 05:05 wpsc-hhvm.conf
-rw-r--r-- 1 root root  358 Nov  3 09:42 wpsubdir.conf

**Comment by iam404** [comment]
also could you please provide output of ee.log

`tail -n100 /var/log/ee/ee.log`

**Comment by MattyLB** [comment]
@iam404 - sent the requested output directly to your email due to sensitive info.

>also could you please provide output of ee.log
tail -n100 /var/log/ee/ee.log

**Comment by MattyLB** [comment]
I noticed that the nginx config is OK and test is successful, then it says "Job is not running: nginx" after the reload. Odd.

**Comment by iam404** [comment]
Hii @MattyLB 

Please use the following command to kill NGINX and restart:

`fuser -k tcp/80`
`fuser -k tcp/443`
`service nginx restart`

and try creating site again.

**Comment by MattyLB** [comment]
Those commands say the filenames do not exist:

I've sent an email with server info for you to log in and check for
yourself if you wish.

**Comment by iam404** [comment]
@MattyLB 
3.4.0beta was installed on the server. Above issue was fixed in the latest stable release.
Closing this ticket.

**Comment by MattyLB** [comment]
My other server was having the same issue and it says (ee -v) EasyEngine
v3.4.0 ... I tried ee update and it tells me I have the latest version. If
this is the beta, how do I remove it and install the correct version of EE
3.4.0?

**Comment by MattyLB** [comment]
Please explain the steps you took to remove EE 3.4.0 beta and install
regular EE 3.4.0 because I have another LIVE server that is affected by
this same issue, even though EE -v shows that it is version 3.4.0, not
3.4.0-beta.

Thank you.

**Comment by MattyLB** [comment]
Thank you @iam404 for the following solution if anyone else is experiencing this AFTER updating to the non-beta version of 3.4.0 ...

>If you are facing the issue on other server, please try below fix:

1. service nginx stop

2. ps -aux | grep nginx

3. kill -9 {every nginx PID} <-- each number, eg: 2220 without {brackets} - repeat for each PID

4. service nginx restart

*Hope this helps anyone else having similar issues!*
