### ISSUE TITLE
New Linode, New EE 3.4.1, WP memory limit stuck at 256M

### ISSUE THREAD

**Issue by MattyLB** [EasyEngine/easyengine#667]
I noticed my WP memory limit on one of my sites changed to 256M shortly after upgrading to 3.4.X and when I checked my wp-config.php it was defined at only 128M, as I had set it.

I decided to create a new EC2 Linode, fresh install of EE 3.4.1, and create two --wpredis sites to test my theory without changing anything in wp-config.php ... **sure enough, each site is set to 256M and I cannot override this at the wp-config level**.

Is this hard-set by EE in the php.ini or another config now?

**UPDATE:** to clarify, I am using Ubuntu 14.04

**Comment by MattyLB** [comment]
Am I the only one having this issue?

**Comment by rahul286** [comment]
Did u try changing limit from php.ini file? Try `memory_limit` setting in `/etc/php5/fpm/php.ini` - http://php.net/manual/en/ini.core.php#ini.memory-limit

By the way `--wpredis` sites do not require any changes to php.ini's memory limit. Redis's memory usage is not controlled by php.ini.

**Comment by MattyLB** [comment]
@rahul286 

> By the way --wpredis sites do not require any changes to php.ini's memory limit. Redis's memory usage is not controlled by php.ini.

 - does this mean --wpredis decides the memory limit and passes that on to WordPress? If so, where can I change the redis memory limit for specific site(s) on my server?  I have limited resources and some sites require more memory than others to operate correctly. The current 256M each means they could all be fighting each other for limited memory resources and I am unable to stipen. Is that a correct assumption?

> Did u try changing limit from php.ini file? Try memory_limit setting in /etc/php5/fpm/php.ini - http://php.net/manual/en/ini.core.php#ini.memory-limit

- This is already set to 128M and since all of my sites are ---wpredis I understand why this limit isn't able to override what redis has in its configuration.  So again, is this a global redis setting or can it be adjusted per site?

**Sorry if I don't understand the limitations or functions of how redis works as much as I would like - if this 256M is shared among all sites, I may actually want to increase it, no?**
