### ISSUE TITLE
Letsencrypt support for multisite (subdir) + Domain Mapping

### ISSUE THREAD

**Issue by QROkes** [EasyEngine/easyengine#668]
Doing some testing I realize that is not easy to get multisite subdirectory working with letsencrypt. Would be nice to have this feature available.

**Comment by s-a-s-k-i-a** [comment]
+1

**Comment by altugank** [comment]
+1

**Comment by santiazpi** [comment]
+1

**Comment by kumosal** [comment]
+1

**Comment by pmb6tz** [comment]
+1

**Comment by tiagocasagrande** [comment]
+1

**Comment by TerenceMilbourn** [comment]
+100

**Comment by wusatiuk** [comment]
+1

**Comment by christoferw** [comment]
+1 for subdomain

**Comment by chrispage1** [comment]
+1

**Comment by s-a-s-k-i-a** [comment]
Please also see this thread in community forum:
http://community.rtcamp.com/t/create-ssl-with-multisite-domain-mapping/7935/11

**Comment by xigem** [comment]
+1

**Comment by rahul286** [comment]
Sorry for a delayed reply. I am wondering why not use multisite + subdomains with domain mapping?

**Comment by TerenceMilbourn** [comment]
I think the question thats being asked is ~ now that Letsencrypt supports wildcard domains ~ "why can't [or when will?] the following `ee site create xyz.tld --wpsubdom --le` create a multisite install together with a letsencrypt wildcard cert enabled?"

**Comment by s-a-s-k-i-a** [comment]
There are actually two separate problems here:

1st problem is, that when we setup new sites (i.e. new domains as vhosts) to be used in the very multisite setup, route them to the multisite webroot, the le script implemented with ee, nginx is unable to provide a working acme directory for the le cert renewal. 
this causes a lot of extra work every 90 days, if you want to renew le certs for domains that are mapped on such a multisite installation. 

2nd problem is, when we setup a multisite with subdomains via ee and simply use subdomains, then the le client script which is implemented with ee is unable to get matching le certs. it woul dbe a lot easier if the le client script received some love and le acme version was updated to v2 so we could have wildcard certs.

**Comment by cfrazier** [comment]
The somewhat brilliant, but no-longer-maintained WP Encrypt handled domain mapping really well, and processed subdomains on their own which eliminated the need for wildcard in some cases.

Wildcard support would be perfect for subdomains, but it would be nice to have EE query the site via WP-CLI to pull mapped domains as well and add them to the renewal conf for LE.

Finally, it would be nice if this wasn't a 4.0 feature as this is something most of are implementing on our own in the current build.

**Comment by TerenceMilbourn** [comment]
The other day I found a bash script to [install Let's Encrypt SSL certificates automatically using acme.sh](https://virtubox.github.io/ee-acme-sh/) with EasyEngine.  I didn't try it out because I read that a limitation was that "wildcard certs are only available with Cloudflare DNS API"  I don't understand that and didn't have much time to investigate, so I moved on.  Perhaps its worth some further investigation?

**Comment by VirtuBox** [comment]
Hello, it's because wildcard certificates can only use DNS validation to be issued. And Cloudflare is one of the most popular DNS hosting service, and provide a fast DNS propagation. But you can easily adapt my script to use another DNS provider supported by acme.sh

**Comment by TerenceMilbourn** [comment]
OK, many thanks for the information. 

That wasn't clear from the quick reading of the project description.

The reason it put me off trying is that I used to find Cloudflare very good, when they first started, but of late both the free and the PRO version tend to slow down TTFB too much to useful.

Am I right in assuming that, if the DNS was configured let's say 24 hours in advance of running the script, then most DNS providers would be able to validate the IP address?

I have always had problems with validation on Linode's DNS servers, but very rarely had a problem with DigitalOcean's, even when I have only configured the PTR at my registrar a couple of hours earlier.

**Comment by rahul286** [comment]
@TerenceMilbourn wildcard support is on the roadmap. We are using https://traefik.io/

I see there is no answer to my original question "why anyone would use WordPress multisite subdir + domain mapping". As far as WordPress multisite subdomains and optional domain mapping - they are already being worked upon in v4. So closing this issue as our discussion is going bit off-topic.
