### ISSUE TITLE
ee site list in CSV

### ISSUE THREAD

**Issue by janiosarmento** [EasyEngine/easyengine#669]
I'd like to suggest a feature to ee site list that would be very useful for mass site migrations: a CSV version of ee site list, with all the information from ee site info in a single line per site, with now colouring, just values separated by comma (or even better: a user defined separator, default to commas). @

**Comment by ingobaab** [comment]
`sqlite3 -header -csv /var/lib/ee/ee.db "SELECT * FROM sites"`

**Comment by janiosarmento** [comment]
Thank you very, very much!

**Comment by rahul286** [comment]
@mbtamuli this might be possible in v4 already because of our wp-cli base. Can you please confirm?

**Comment by mbtamuli** [comment]
Yes. This is certainly possible in EasyEngine v4.

**Comment by kirtangajjar** [comment]
In addition to CSV - json, table and yaml support is also added. This PR - https://github.com/EasyEngine/site-command/pull/32 will fix this issue.
