### ISSUE TITLE
Letsencrypt + HSTS Issue

### ISSUE THREAD

**Issue by QROkes** [EasyEngine/easyengine#671]
After setting up Letsencypt and added HSTS (HTTP Strict Transport Security) header, then EE Admin Tools become completely unavailable due to the certificate EE uses in port 22222.

**Comment by w33zy** [comment]
WordPress admin pages or the EE admin pages at port 22222?

**Comment by QROkes** [comment]
@w33zy EasyEngine Admin Tools like: PhpMyAdmin, Adminer, Anemometer, etc.

**Comment by w33zy** [comment]
I thought so. That has always been the case, it's not a LE problem. I have the same issue with commercial SSL certificates. It's the expected behaviour of HSTS. 

You connected to your site/domain with a valid SSL/TLS certificate, your browser saves the signature of this certificate, according to the specs of HSTS. You then try to connect to the same domain at port 22222, with a new self-signed (not trusted) so your browser refuses the connection as it should.

**Comment by rsmith4321** [comment]
Use your server IP address and In chrome just click advanced and proceed even though it's unsafe. You know it's safe so don't worry about the warning.

**Comment by QROkes** [comment]
@w33zy I know it isn't an LE problem, but SSL + HSTS is very common, so it shouldn't be an expected behavior in EE, specially now that EE supports LE. Don't you think?

@rsmith4321 Thanks for the solution, actually I fixed it adding my own LE keys in 22222 conf file.

**Comment by HQRaja** [comment]
@rsmith4321 Can you please guide on how to do that? (Adding our own LE keys in 22222 conf file, that is.)

**Comment by QROkes** [comment]
@HQRaja In your 22222 nginx conf file (/etc/nginx/sites-available/22222) you need to replace the actual cert path for your LE cert path.

You can do it mannually, but I do this running this two commands:

sudo sed -i '/22222.crt/c\ssl_certificate /etc/letsencrypt/live/qrokes.com/fullchain.pem;' /etc/nginx/sites-available/22222

sudo sed -i '/22222.key/c\ssl_certificate_key /etc/letsencrypt/live/qrokes.com/privkey.pem;' /etc/nginx/sites-available/22222

Really easy!!

**Comment by w33zy** [comment]
@QROkes 
How would you go about handling port 22222 for each site created by EE using the SSL cert that port 443 of the site is using? E.g. 'https://example1.com:22222' uses the SSL cert the site is already using, and 'https://example2.com:22222' does the same?

**Comment by QROkes** [comment]
@w33zy Actually, I ran into that issue because I have a subdir multisite with domain mapping.

First of all, I'm not using the LE script provided by EasyEngine because they don't support multiple domains in one cert (WP Multisite + Domain Mapping).

So, I install and create my LE certs manually and then I have my own automated script for automatically renew all my certs.

What I exactly do, is create one cert with multiple domains.

./letsencrypt-auto certonly --webroot -w /var/www/example.com/htdocs/ -d example.com -d www.example.com -d subsite.com -d www.subsite.com -d another.com -d www.another.com --email user@example.com --text --agree-tos

**Comment by HQRaja** [comment]
@QROkes Thank you for your very prompt help. I used both the commands that you provided, replacing your domain with mine. However, I still can't access the Admin Tools, as that page appears to be served with the same self-signed certificate. Are there any other commands I need to use (perhaps to restart any services) for the changes to come into effect?
(Please forgive my ignorance, as I'm rather new at this.)

**Comment by QROkes** [comment]
@HQRaja you need to restart nginx service.

**Comment by HQRaja** [comment]
@QROkes Works like a charm! Can't thank you enough; I was being driven insane trying to figure it out using my limited knowledge.

**Comment by w33zy** [comment]
@QROkes 
What I am getting at, is if you've found a simple solution for getting 'https://example1.com:22222' to use the single SSL cert issued for 'example1.com' and have that solution work for for other single domains with there single SSL cert.

**Comment by QROkes** [comment]
@w33zy you want to use multiple certs to access 22222, I think that's not possible or at least I don't know how to do it.

Maybe using conditions (if) in your 22222 nginx conf file to select a different cert depending on the domain request... but I'm not really sure about it. Just an idea!

**Comment by w33zy** [comment]
@QROkes 
Yeah... that idea just popped up in my head but I am thinking Nginx can't be performant by switching SSL certs on the fly.

I also tried creating a '22222.conf' file in ````/var/www/example1.com/conf/nginx/```` but that introduces the issue of have 2 declarations of 'root' in the server block.

**Comment by rahul286** [comment]
The way v4 is being developed, this will get handled in a better way.

Please review https://github.com/EasyEngine/easyengine/issues/1013 add your suggestions.
