### ISSUE TITLE
EE install script structure

### ISSUE THREAD

**Issue by rahul286** [EasyEngine/easyengine#672]
I liked https://get.docker.com/
1. Adding comments on top
2. Using different subdomains for different release channel.

Should at least accomplish these tasks -
- [ ] Install PHP v7 with minimal deps. No php-fpm.
- [ ] ee will be delivered as phar archive or via https://packagist.org/

**Comment by vikas5914** [comment]
+1

**Comment by mbtamuli** [comment]
Mentioned in [#781 ](https://github.com/EasyEngine/easyengine/issues/781#issue-181666522)
> Installer itself will be in bash 
> - [ ] Install PHP v7 with minimal deps. No php-fpm.
> - [ ] ee will be delivered as phar archive or via https://packagist.org/

**Comment by mrrobot47** [comment]
The minimum requirements are: 

1. Docker
```
wget get.docker.com -O docker-setup.sh
sh docker-setup.sh
```

2. Docker-Compose:
```
sudo curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
```

3. PHP with three required extensions:

Ubuntu 14, 16, 18
```
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:ondrej/php
sudo apt-get update
sudo apt-get -y install php7.2-cli php7.2-curl php7.2-sqlite3
```
Debian 8, 9:
```
sudo apt-get install apt-transport-https lsb-release ca-certificates -y
sudo wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/php.list
sudo apt-get update
sudo apt-get install php7.2-cli php7.2-curl php7.2-sqlite3 -y
```

**Comment by michacassola** [comment]
Why no php-fpm? Isn't it the fastest?

**Comment by mbtamuli** [comment]
@michacassola These are the minimal dependencies required for running the software EasyEngine and are not related to a Site's dependencies.

**Comment by michacassola** [comment]
@mbtamuli Thanks for clearing that up!
