### ISSUE TITLE
Uppercase P in WordPress

### ISSUE THREAD

**Issue by Nikschavan** [EasyEngine/easyengine#674]
First off all, Easyengine works great at what it does, so kudos to that.

There are some strings that do have WordPress written differently, for Eg - 

![putty_2016-02-02_11-46-14](https://cloud.githubusercontent.com/assets/2931091/12752401/64f163fc-c9e8-11e5-88b0-3bcbf78be0ca.png)

**Comment by MiteshShah** [comment]
Closing issue as fixed was merged.
