### ISSUE TITLE
Typo on the homepage

### ISSUE THREAD

**Issue by austinpray** [EasyEngine/easyengine#685]
![image](https://cloud.githubusercontent.com/assets/2192970/13702729/4f9f5154-e756-11e5-8256-7bc8e0b9241c.png)

Should be "Update EasyEngine for new features with one simple command". Arguable should just be "Update EasyEngine with one simple command".

**Comment by nitun** [comment]
Agreed. It could be bugs and/or features. So to make it simple I used now "Update EasyEngine with one simple command". 

Thanks,
