### ISSUE TITLE
HHVM and PHP-fpm problem

### ISSUE THREAD

**Issue by KuneStudio** [EasyEngine/easyengine#690]
Hi,

I have the following errors : 
`[Mon Mar 21 10:26:32 2016] [hphp] [4431:7f1171bff700:17:000001] [] \nWarning: failed to connect to 127.0.0.1 [111]: Connection refused
[Mon Mar 21 10:26:32 2016] [hphp] [4431:7f1171bff700:17:000002] [] \nWarning: Failed connecting to redis server at 127.0.0.1: Connection refused
[Mon Mar 21 10:26:39 2016] [hphp] [4431:7f1169fff700:15:000001] [] \nWarning: failed to connect to 127.0.0.1 [111]: Connection refused
[Mon Mar 21 10:26:39 2016] [hphp] [4431:7f1169fff700:15:000002] [] \nWarning: Failed connecting to redis server at 127.0.0.1: Connection refused
[Mon Mar 21 10:26:43 2016] [hphp] [4431:7f1171bff700:18:000001] [] \nWarning: failed to connect to 127.0.0.1 [111]: Connection refused
[Mon Mar 21 10:26:43 2016] [hphp] [4431:7f1171bff700:18:000002] [] \nWarning: Failed connecting to redis server at 127.0.0.1: Connection refused
[Mon Mar 21 10:26:47 2016] [hphp] [4431:7f1169fff700:16:000001] [] \nWarning: failed to connect to 127.0.0.1 [111]: Connection refused
[Mon Mar 21 10:26:47 2016] [hphp] [4431:7f1169fff700:16:000002] [] \nWarning: Failed connecting to redis server at 127.0.0.1: Connection refused
[Mon Mar 21 10:27:24 2016] [hphp] [4431:7f1171bff700:19:000001] [] \nWarning: failed to connect to 127.0.0.1 [111]: Connection refused
[Mon Mar 21 10:27:24 2016] [hphp] [4431:7f1171bff700:19:000002] [] \nWarning: Failed connecting to redis server at 127.0.0.1: Connection refused
[Mon Mar 21 10:28:25 2016] [hphp] [4431:7f1169fff700:17:000001] [] \nWarning: failed to connect to 127.0.0.1 [111]: Connection refused
[Mon Mar 21 10:28:25 2016] [hphp] [4431:7f1169fff700:17:000002] [] \nWarning: Failed connecting to redis server at 127.0.0.1: Connection refused` 

**sb_release -a** : [ 
`No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:    14.04
Codename:`trusty`
- **ee -v** : 
  EasyEngine v3.4.1
- **ee info** : 
  `NGINX (1.8.1):
  user                             www-data
  worker_processes                 auto
  worker_connections               4096
  keepalive_timeout                30
  fastcgi_read_timeout             300
  client_max_body_size             100m
  allow                            127.0.0.1

PHP (5.6.19-1):

user
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  500
pm.max_children                  100
pm.start_servers                 20
pm.min_spare_servers             10
pm.max_spare_servers             30
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           127.0.0.1:9000

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  500
pm.max_children                  100
pm.start_servers                 20
pm.min_spare_servers             10
pm.max_spare_servers             30
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9001

MySQL (10.1.12-MariaDB) on localhost:

port                             3306
wait_timeout                     30
interactive_timeout              28800
max_used_connections             2
datadir                          /var/lib/mysql/
socket                           /var/run/mysqld/mysqld.sock`

**wp --allow-root --info**
`PHP binary:    /usr/bin/php5
PHP version:    5.6.19-1+deb.sury.org~trusty+1
php.ini used:   /etc/php5/cli/php.ini
WP-CLI root dir:    phar://wp-cli.phar
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 0.22.0` 

Any idea ? 

Thanks !

**Comment by rahul286** [comment]
Sorry for a delayed reply. We no longer support HHVM. Please use PHP 7.

We are cleaning up issue tracker and closing this issue because we won't be able to contribute to this discussion further.

Please use http://community.rtcamp.com/c/easyengine for future support questions.
