### ISSUE TITLE
Laravel will be supported?

### ISSUE THREAD

**Issue by wedojava** [EasyEngine/easyengine#691]
Hi,

It seems Laravel support is nice, Not much changing codes I guess and I hope.

**Comment by janiosarmento** [comment]
I've deployed a VPS for a customer wishing to run a Laravel app. I just created the site with `--mysql` and made one manual adjustment (`ee site edit`) in order to change the website root from `htdoc` to `htdocs/public`.

To me, it seems there is no need to change how EasyEngine works just because of Laravel.

**Comment by rahul286** [comment]
I guess idea is to remove need to make that once change required. :-)

Anything that cannot be accomplished in a single command is not "easy". ;-)

If you make any other changes/tweak, please report here.

**Comment by janiosarmento** [comment]
For Laravel that's all that was needed.

Perhaps you could:

    ee site create example.com --laravel

Then EE would download latest version of Laravel Framework, unpack it and create the vhost with the correct root location.

**Comment by wedojava** [comment]
@janiosarmento @rahul286 
Thanks for your back and best job,before EE, I try to use docker to my development environment,just now I really want to try EE in my poor computer with Ubuntu, so slowly as my computer is，I usually used Homestead.box by vagrant to develop my laravel things.
There is a question，which way is best on ee,Operation environment or Development environment?
Is it can used for some php service on about 1000 IP/day?
Certainly,I aim for develop but not make LEMP etc.

The end, I'am glad to meet EE in this Internet Times.

**Comment by janiosarmento** [comment]
@rahul286, there are additional steps on configuring Laravel that could be accomplished by EE (setting up database and email per project).

Unfortunately I can't tell what are the necessary changes, since my customer did all of them as soon as I configured Nginx to serve his app. :( Perhaps @wedojava can enlighten us on this subject.

**Comment by captainswain** [comment]
+1 any updates/news on this?

**Comment by qriouslad** [comment]
Just managed to get Laravel going on EasyEngine v3.7.4.

Steps:

0. sudo apt-get install php-cli php-mbstring php7.0-mbstring php-xml php7.0-xml 
(keep existing config)

1. Install composer https://www.digitalocean.com/community/tutorials/how-to-install-and-use-composer-on-ubuntu-16-04 

2. sudo ee site create example.com --mysql

3. sudo rm -rf htdocs
Yes, delete htdocs folder of /var/www/example.com

4. sudo composer create-project --prefer-dist laravel/laravel htdocs
From /var/www/example.com

5. sudo chown -R www-data:www-data htdocs

6. sudo ee site edit example.com -> change root folder to /htdocs/public

**Comment by IsoftTech** [comment]
please i need help on how to host my laravel project, am new to laravel.

**Comment by mbtamuli** [comment]
Laravel as a site type might be introduced in EasyEngine v4. We can discuss that after v4 is released.
Thanks for the comments. Closing this issue for now, feel free to continue the discussion.

**Comment by jasperf** [comment]
Setting up a basic Laravel site is already possible, but what I miss is setting up with a container for Redis queues and or the option to set up a Laravel Horizon container.
