### ISSUE TITLE
Feature request: Ubuntu Xenial LTS support

### ISSUE THREAD

**Issue by RavanH** [EasyEngine/easyengine#694]
~# wget -qO ee rt.cx/ee && sudo bash ee
Executing apt-get update, please wait...
EasyEngine (ee) only support Ubuntu 12.04/14.04 and Debian 7.x/8.x

~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu Xenial Xerus (development branch)
Release:	16.04
Codename:	xenial

So for testing purposes, I changed line 66 in /root/ee to
`
lsb_release -d | egrep -e "12.04|14.04|Xenial|wheezy|jessie" &>> /dev/null
`
and issued a "sudo bash ee" again. Initial EE installation proceeded without errors...

Will be testing further :)

**Comment by RavanH** [comment]
Nah, no dice...
`
~# ee stack install --nginx
Adding repository for NGINX, please wait...
type object 'EEVariables' has no attribute 'ee_nginx_repo'
`
(note that nginx and php7 are already in the default repos for xenial)

**Comment by ingobaab** [comment]
I am also interessted i this Information +1 :)

**Comment by iam404** [comment]
referring #708
