### ISSUE TITLE
HHVM 3.13 redis config

### ISSUE THREAD

**Issue by caaol** [EasyEngine/easyengine#696]
When I upgrade hhvm to 3.13, Object Cache Redis settings inside the display
HHVM Extension Client: (v3.13.0), but when I was  flush cache, set it into the PECL Extension Client: (v2.2.7), the site is very slow
- [ ] lsb_release -a
  No LSB modules are available.
  Distributor ID: Ubuntu
  Description:    Ubuntu 14.04.2 LTS
  Release:    14.04
  Codename:   trusty
- [ ] ee -v
  EasyEngine v3.5.4
  Copyright (c) 2015 rtCamp Solutions Pvt. Ltd. 
- [ ] ee info
  NGINX (1.8.1):

user                             www-data
worker_processes                 auto
worker_connections               4096
keepalive_timeout                30
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1 

PHP (5.6.19-6):

user  
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  500
pm.max_children                  100
pm.start_servers                 20
pm.min_spare_servers             10
pm.max_spare_servers             30
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           127.0.0.1:9000

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  500
pm.max_children                  100
pm.start_servers                 20
pm.min_spare_servers             10
pm.max_spare_servers             30
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9001

MySQL (10.1.12-MariaDB) on localhost:

port                             3306
wait_timeout                     600
interactive_timeout              28800
max_used_connections             2
datadir                          /var/lib/mysql/
socket                           /var/run/mysqld/mysqld.sock
my.cnf [PATH]                    /etc/mysql/conf.d/my.cnf
- [ ] wp --allow-root --info
  PHP binary: /usr/bin/php5.6
  PHP version:    5.6.19-6+deb.sury.org~trusty+3
  php.ini used:   /etc/php/5.6/cli/php.ini
  WP-CLI root dir:    phar://wp-cli.phar
  WP-CLI global config:  
  WP-CLI project config:  
  WP-CLI version: 0.21.1

**Comment by caaol** [comment]
hhvm upgrade 3.13 , but it can't work.

**Comment by caaol** [comment]
ps -aux | grep hhvm
root      7188  0.0  0.1   8812   780 pts/0    S+   00:36   0:00 grep --color=auto hhvm

**Comment by rahul286** [comment]
Sorry for a delayed reply. We no longer support HHVM. Please use PHP 7.

We are cleaning up issue tracker and closing this issue because we won't be able to contribute to this discussion further.

Please use http://community.rtcamp.com/c/easyengine for future support questions.
