### ISSUE TITLE
Google has detected that your site is currently running PageSpeed < 1.9.32.14 or < 1.10.33.7, an older version of PageSpeed.

### ISSUE THREAD

**Issue by sirshurf** [EasyEngine/easyengine#697]
Just got this message from WMT...

Google has detected that your site is currently running PageSpeed < 1.9.32.14 or < 1.10.33.7, an older version of PageSpeed.

My versions are:

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty

EasyEngine v3.5.4
Copyright (c) 2015 rtCamp Solutions Pvt. Ltd. 

NGINX (1.8.1):

user                             www-data
worker_processes                 auto
worker_connections               4096
keepalive_timeout                30
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1 
PHP5.6 is not installed

PHP binary:	/usr/bin/php5
PHP version:	5.5.34-1+deb.sury.org~trusty+1
php.ini used:	/etc/php5/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	0.22.0

How can I update it? On another server I can manually recompile nginx with it. but here?

**Comment by rahul286** [comment]
Please check this - https://easyengine.io/blog/disabling-pagespeed/

Our Nginx Build repo is here - https://github.com/EasyEngine/nginx-build

Sorry for inconvenience.

**Comment by sirshurf** [comment]
How can I change it from your nginx to my own???

I would really like to compile and run my own version with your settings...
I know that I can easily compile openresty with pagespeed.

**Comment by rahul286** [comment]
We have provided our nginx-build code here - https://github.com/EasyEngine/nginx-build

May be you can try `apt-get remove` our nginx package and try your own complied version. 

It may work or it may not.

**Comment by jacobmmp** [comment]
Think this needs to be looked in to, since we just got that message to from Google Webmaster tools about pagespeed being out of date.
