### ISSUE TITLE
--letsencrypt doesn't work if www subdomain doesn't exist

### ISSUE THREAD

**Issue by dimadin** [EasyEngine/easyengine#699]
While most root domains have `www` subdomain enabled (so for `example.com` works `www.example.com` too), on most configurations `www` is on enabled for subdomains (so for `sub.example.com` doesn't work `www.sub.example.com`).

Problem is that EE always requests certificate for `www` subdomain too (see [ee/cli/plugins/site_functions.py](https://github.com/EasyEngine/easyengine/blob/c143f26e3a18feda571974a384dbd6fe42f751ab/ee/cli/plugins/site_functions.py#L1366)) and when this is unreachable, verification fails and can't be done using EE.

Example of command to reproduce this:
`ee site update sub.example.com --letsencrypt`
where `www.sub.example.com` doesn't work.

This was already posted on forum ([1](http://community.rtcamp.com/t/easyengine-and-letsencrypt-setup/5849/9), [2](http://community.rtcamp.com/t/letsencrypt-on-subdomain/6112)) and in other issues (#663).

My proposal is to add some function that should request certificate for `www` subdomain only after checking if that subdomain exists (for example if there is 200 response).

**Comment by jacobmmp** [comment]
Just create the cname in your dns called www.sub.example.com and point it to sub.example.com and you got your www issue fixed.

**Comment by dimadin** [comment]
My point was that there is no message shown to user about this, it just fails. Maybe there could be message before AYS like "Please make sure that both www and no-www versions of your site work. Here is a guide: (link)", where link would point to EE docs. Or message after it was unsuccessfull.

Many people don't pay attention that their www version doesn't work, for years I am stumbling upon such sites.

**Comment by jacobmmp** [comment]
The error message that shows if it fails is from what i know direct from the letsencrypt binary, but ye the easyengine could do a message when you enable it to warn you about when you enable it.

**Comment by khromov** [comment]
Would love to see this get solved.

**Comment by w33zy** [comment]
I remember reading instructions saying to make sure the 'www' version of your site works before using LE. It is as simple as create a CNAME record for 'www' where ever your DNS is managed.

**Comment by julien731** [comment]
Agreed that some improvement could be done on this front. I just spent some time wondering why LE was failing on a site using a sub-domain. I finally figured it out when looking through the EE log, but honestly that'd be a good thing to *at least* inform the user that `www` should be setup, *even when using a sub-domain*.

**Comment by willxy** [comment]
I just ran into this myself.

I see two problems, that are independent from each other:
- The error output doesn't give the actual error from letsencrypt, which makes troubleshooting much harder.
- It's requiring that the "www." exists.

I would love to see BOTH of these problems fixed.  At the very least, offer an option not to include the "www." in the SSL request.  I don't have it on any of my domains, don't want it, and don't consider it appropriate to have to create it in DNS just to satisfy this script's expectations.

**Comment by hakabe** [comment]
The issue still remains.

**Comment by georgeappiah** [comment]
I'm dealing with a situation where I cannot setup www for the sub-domain.
And this annoying "feature" is stopping me from using the LE client bundled with EE.

**Comment by rahul286** [comment]
This will be handled in EE 4.

You may check this PR #1005

Please use http://community.rtcamp.com/c/easyengine for future support questions.
