### ISSUE TITLE
EasyEngine cache keys are too generic

### ISSUE THREAD

**Issue by lukechilds** [EasyEngine/easyengine#705]
EasyEngine uses `$host` in the cache key which converts to lowercase among a few other things so both `Example.com` and  `example.com` share the same cache key. This can cause serious issues.

On one of our client's WordPress installs, improper site URLs get `301`d to the correct URL. For example requesting `Example.com` would return a 301 redirect to `example.com`. Due to the way EasyEngine sets the keys it means if someone requests `Example.com` when the homepage cache has expired it caches the 301 response and returns it for all requests to `Example.com` and `example.com` resulting in an infinite redirect loop.

I have a fix in place on our server, I'll submit a PR

**Comment by rahul286** [comment]
Sorry to say we are closing this issue as we couldn't test this deeply.
