### ISSUE TITLE
php.ini entry is missing for json(decode): extension=json.so

### ISSUE THREAD

**Issue by s-a-s-k-i-a** [EasyEngine/easyengine#707]
Since a couple of versions the php.ini entry to activate json(decode) support is missing. I have to manually add the line in every php.ini on every server I administrate and runs ee, each time I update ee.
It is needed for phpmyadmin to work as well.

this [json] section is simply missing in php.ini:

[json]
extension=json.so

Could you please add this so I won't have to do it manually each time as ee replaces my php.ini during update?
Thanks!

**Comment by rahul286** [comment]
@mbtamuli please check this. We will need this in EE v4 core.

**Comment by mbtamuli** [comment]
```
docker-compose exec php bash -c 'php -m | grep json'
json
```

Json module seems to be enabled by default.

**Comment by mbtamuli** [comment]
I believe this must've been an earlier version of EasyEngine that @s-a-s-k-i-a is talking about. We checked on EE3 install also, we are enabling the json module. I am closing this issue for now. If you are still facing the issue, please feel free to reopen the issue @s-a-s-k-i-a
