### ISSUE TITLE
 Ubuntu 16.04 Support?

### ISSUE THREAD

**Issue by irazasyed** [EasyEngine/easyengine#708]
Just wanted to confirm, If EE supports Ubuntu 16.04 LTS?

**Comment by irazasyed** [comment]
I just tested. It doesn't support. Can you guys add the support for it?

**Comment by jacobmmp** [comment]
Still wondering why the devs are not getting back on this matter so fare.

The php packages EasyEngine uses PHP 5.6 and PHP 7.0: ppa:ondrej/php (Ubuntu 14.04 LTS - Ubuntu 16.04 LTS)

Works with Ubuntu 16.04,  so it's not that holding it back, hope we will get a update soon.

**Comment by ddelaey** [comment]
+1

**Comment by jacobmmp** [comment]
Go to the community forum to and up vote the thread someone did there to, we need to get some answers from the devs they are lige gone gone

**Comment by arush-sal** [comment]
Hi Everyone,

We are ready with EasyEngine version 3.6. We avoid releasing a major version on Fridays as we do not provide support on weekends unless of critical nature.

Hence we will be releasing the new version on Monday.

Thanks for your patience. :-)

- Salil
(on behalf of EasyEngine core team)

**Comment by hbakhtiyor** [comment]
@arush-sal any news about supporting?

**Comment by iam404** [comment]
@hbakhtiyor Latest release of EasyEngine do support Ubuntu 16.04LTS. For more information can refer https://easyengine.io/blog/easyengine-3-6-nginx-1-10-ubuntu-16-04-support/
