### ISSUE TITLE
max_input_vars in php.ini should be set bigger

### ISSUE THREAD

**Issue by lemartinet** [EasyEngine/easyengine#709]
Hi,

When using a multi-language plugin, the php variable describing the menu can get big. I add the problem that it was bigger than the php basic limit. So I think this limit should be made bigger by default, something like 
max_input_vars = 4000
It will not be a performance issue I think, and could help avoid troubles! In my case, the trouble was that when I tried to save the menu after editing it, it would be cut (i.e. missing some entries).

Best,
Manu

**Comment by gagomap** [comment]
You can create user.ini in htdocs folder, and paste your php setting into it.

**Comment by rahul286** [comment]
@lemartinet Sorry for a delayed reply.

We recommend user fix this own end as suggested by @gagomap .
