### ISSUE TITLE
Error 403 Forbidden

### ISSUE THREAD

**Issue by brasiltemass** [EasyEngine/easyengine#720]
Hello,

I install ee normally in my htttp site and it Works.

After I installed a certificate SSL and configure it my site got 403 Forbidden error when I try to access.

My server config:

server {
	listen 443 ssl;
	server_name mydomain.com;

   	ssl_certificate /home/sammy/mydomain.com.chained.crt;
    ssl_certificate_key /home/sammy/mydomain.com.key;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_prefer_server_ciphers on;
    ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';

	root /var/www/mydomain.com;
	index index.php index.html index.htm;

	location / {
		# First attempt to serve request as file, then
		# as directory, then fall back to displaying a 404.
		try_files $uri $uri/ =404;
	}

	# pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
	#
	location ~ \.php$ {
		include snippets/fastcgi-php.conf;
	
		# With php5-cgi alone:
		fastcgi_pass 127.0.0.1:9000;
		# With php5-fpm:
		#fastcgi_pass unix:/var/run/php5-fpm.sock;
	}

	# deny access to .htaccess files, if Apache's document root
	# concurs with nginx's one
	#
	#location ~ /\.ht {
	#	deny all;
	#}
}

Please attach the output of following command when open a new support request.

- [ ] lsb_release -a
- [ 3.6.0] ee -v
- [user                             www-data
worker_processes                 auto
worker_connections               4096
keepalive_timeout                30
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1

PHP (5.6.21-8):

user
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  500
pm.max_children                  100
pm.start_servers                 20
pm.min_spare_servers             10
pm.max_spare_servers             30
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           127.0.0.1:9000

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  500
pm.max_children                  100
pm.start_servers                 20
pm.min_spare_servers             10
pm.max_spare_servers             30
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9001

MySQL (10.1.14-MariaDB) on localhost:

port                             3306
wait_timeout                     600
interactive_timeout              28800
max_used_connections             3
datadir                          /var/lib/mysql/
socket                           /var/run/mysqld/mysqld.sock
my.cnf [PATH]                    /etc/mysql/conf.d/my.cnf
 ] ee info
- [ PHP binary:     /usr/bin/php5.6
PHP version:    5.6.21-8+donate.sury.org~trusty+4
php.ini used:   /etc/php/5.6/cli/php.ini
WP-CLI root dir:        phar://wp-cli.phar
WP-CLI packages dir:    /root/.wp-cli/packages/
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 0.23.0
root@ultrapackv2:~# wp --allow-root --info
PHP binary:     /usr/bin/php5.6
PHP version:    5.6.21-8+donate.sury.org~trusty+4
php.ini used:   /etc/php/5.6/cli/php.ini
WP-CLI root dir:        phar://wp-cli.phar
WP-CLI packages dir:    /root/.wp-cli/packages/
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 0.23.0
] wp --allow-root --info

**Comment by iam404** [comment]
Hi
Is the `root /var/www/mydomain.com;` path correct. Check for files/folder permission and  index.php at this location.
As this not a current EasyEngine issue, I am closing this issue. 
For further discussion please create a topic at - http://community.rtcamp.com/c/easyengine
