### ISSUE TITLE
Vimbadmin - if mailbox_deletion_fs_enabled = true and cronjob set: /var/vmail/ will be deleted

### ISSUE THREAD

**Issue by s256** [EasyEngine/easyengine#721]
Hello everyone!

The current configuration of vimbadmin should be:
`defaults.mailbox.homedir = "/var/vmail/%d/%u"`
instead of:
`defaults.mailbox.homedir = "/var/vmail/"`
in application.conf.
If `mailbox_deletion_fs_enabled = true` is set, the whole /var/vmail folder is deleted after the cron job.

There is no reason why default.mailbox.homedir should be /var/vmail/.

Best
se

**Comment by rahul286** [comment]
Sorry for a delayed reply. We are in the process of deprecating support for Vimbadmin.

We are cleaning up issue tracker and closing this issue because we won't be able to contribute to this discussion further.

Please use http://community.rtcamp.com/c/easyengine for future support questions.
