### ISSUE TITLE
No section: 'client'

### ISSUE THREAD

**Issue by xreeckz** [EasyEngine/easyengine#722]
So, I recently ran into a weird issue, and I've got no idea what caused it. But anytime I try to run any ee commands It just says " No section: 'client' ". Any help would be much appreciated! 
Also, any site on the system, which as far as I can tell should work fine return error 404. 

- [ ] lsb_release -a

No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.4 (jessie)
Release:        8.4
Codename:       jessie
- [ ] ee -v

No section: 'client'
- [ ] ee info

No section: 'client'
- [ ] wp --allow-root --info

-bash: wp: command not found

**Comment by rahul286** [comment]
It seems your `/etc/mysql/conf.d/my.cnf` file is missing.
Also `wp` (wp-cli) is not present.

Is this fresh EasyEngine setup?

**Comment by xreeckz** [comment]
It's not fresh, it was set up and worked fine around the 4th of may. I've no clue what caused this to occur. 

The /etc/mysql/conf.d/my.cnf file does exist, but had no client tag. I was using ee to run a php site, so minimal installs.

**Comment by iam404** [comment]
@xreeckz  Can you please verify ` /etc/mysql/conf.d/my.cnf ` file content as below : 
```
[client]
user = root
password = PASSWORD
```
`PASSWORD` would be any random generated string.
