### ISSUE TITLE
Error not download file adminer

### ISSUE THREAD

**Issue by PHUONGNTP** [EasyEngine/easyengine#726]
Please attach the output of following command when open a new support request.

- [ ] lsb_release -a
- [ ] ee -v
- [ ] ee info
- [ ] wp --allow-root --info

**Comment by PHUONGNTP** [comment]
I have error:' Unable to download file, /var/www/22222/htdocs/db/adminer/index.php' when i run the first code setup ee. I use 5$ of digial ocean and use unbuntu16x64. Please tell me how to fix error

**Comment by iam404** [comment]
HI @PHUONGNTP 
Looks like adminer moved their download URL.
Thanks for pointing out the issue. We will release a fix soon.
