### ISSUE TITLE
BINLOG_FORMAT  not defiened in my.cnf

### ISSUE THREAD

**Issue by liquidia** [EasyEngine/easyengine#730]
Please attach the output of following command when open a new support request.

Getting following error:General error: 1665 Cannot execute statement: impossible to write to binary log since BINLOG_FORMAT = STATEMENT and at least one table uses a storage engine limited to row-based logging. InnoDB is limited to row-logging when transaction isolation level is READ COMMITTED or READ UNCOMMITTED., query was: UPDATE `cron_schedule` SET `job_code` = ?, 

Easyeninge version:3.5.6

Can be solved by defining binlog_format in /etc/mysql/my.cnf under " [mysqld]" section
 [mysqld]
binlog_format = MIXED

**Comment by rahul286** [comment]
Sorry for a delayed reply. I hope your issue had been resolved by now.

We are cleaning up issue tracker and closing this issue because we won't be able to contribute to this discussion further.

Please use http://community.rtcamp.com/c/easyengine for future support questions.
