### ISSUE TITLE
how to set multiple domain to 1 serverblock like serverpilot ?

### ISSUE THREAD

**Issue by screamolic** [EasyEngine/easyengine#732]
how to set multiple domain to 1 serverblock like serverpilot ?

**Comment by tobiasmuehl** [comment]
Just run the `ee site create domain.com --wp` again with the new domain

**Comment by rahul286** [comment]
Sorry for a delayed reply. I hope your issue is fixed by now.

If you are still facing the issue, please use http://community.rtcamp.com/c/easyengine for further support.

We are cleaning up issue tracker and closing this issue because we won't be able to contribute to this discussion further.
