### ISSUE TITLE
Increase strength of HTTP Auth password

### ISSUE THREAD

**Issue by khromov** [EasyEngine/easyengine#735]
Currently the generated password is only 6 characters long and uses a standard port (22222) and user (easyengine), which makes it easy to bruteforce.

Please make the password at least double the length and let users choose the username that should be used for authentication.

- [ ] lsb_release -a N/A
- [ ] ee -v N/A
- [ ] ee info N/A 
- [ ] wp --allow-root --info N/A

**Comment by rsmith4321** [comment]
Just change it yourself. This doesn't seem to be a bug at all. Just follow the faq.

On Sun, Jun 12, 2016 at 5:25 PM, Stanislav Khromov <notifications@github.com> wrote:
Currently the generated password is only 6 characters long and uses a standard port (22222) and user (easyengine), which makes it easy to bruteforce.

Please make the password at least double the length and let users choose the username that should be used for authentication.

 * lsb_release -a N/A
 * ee -v N/A
 * ee info N/A
 * wp --allow-root --info N/A

**Comment by khromov** [comment]
@rsmith4321 It's not a bug report, it's a feature improvement suggestion.

**Comment by gagomap** [comment]
You can change it yourself by this command:

sudo ee secure --auth

**Comment by agucova** [comment]
I agree, the password strength should be higher. Also the generated mysql password.

**Comment by eliasjnior** [comment]
@agucova I think because mysql is not allowed external access (just localhost), won't be a problem the current password. By the way, you can change the HTTP password and also mysql.

**Comment by iam404** [comment]
EE has option to set custom Authentication password.
```sudo ee secure --auth```
