### ISSUE TITLE
Cant login in phpmyadmin (401 HTTP Error)

### ISSUE THREAD

**Issue by JankingDE** [EasyEngine/easyengine#739]
Hey,

I want to use phpmyadmin in a Subdirectory, but if I try to log in in the HTTP Auth, the username/password of the `/etc/mysql/conf.d/my.cnf` is not working. Even if I reset my Password with 
`UPDATE mysql.user SET Password=PASSWORD('mypass') WHERE User='root';` I still can't log in.

The Output you asked for:

- [ ] lsb_release -a
`No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.5 (jessie)
Release:        8.5
Codename:       jessie
`

- [ ] ee -v
`EasyEngine v3.6.2
Copyright (c) 2016 rtCamp Solutions Pvt. Ltd.
`

- [ ] ee info
http://hastebin.com/ohogalaced.hs

- [ ] wp --allow-root --info
`PHP binary:     /usr/bin/php5
PHP version:    5.6.22-0+deb8u1
php.ini used:   /etc/php5/cli/php.ini
WP-CLI root dir:        phar://wp-cli.phar
WP-CLI packages dir:    /root/.wp-cli/packages/
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 0.23.0
`

**Comment by iam404** [comment]
Hi @JankingDE 

Credential in `/etc/mysql/conf.d/my.cnf` are for Mysql login only. Which you can use to login phpMyAdmin also.
But credentials for HTTP AUTH are different. You can change current HTTP AUTH using below command: 
`ee secure --auth`

While prompt for user name use default as `easyengine` .

If you have any other issue please raise a topic on our community support forum: http://community.rtcamp.com/c/easyengine
