### ISSUE TITLE
Force SSL rules should be in <site>/conf/nginx/ instead of /etc/nginx

### ISSUE THREAD

**Issue by haggen** [EasyEngine/easyengine#740]
When using `--letsencrypt` EE creates a `force-ssl-<site>.conf` in `/etc/nginx/conf.d` but since it's a per site configuration it should be located in `<site>/conf/nginx/`.

**Comment by rahul286** [comment]
You may check this PR #1005 to see how we are doing it in v4.

In v4, nginx confs will be handled much differently.
