### ISSUE TITLE
Warning Unable to load dynamic library '/usr/lib/php/20151012/redis.so'  and Unable to load dynamic library '/usr/lib/php/20151012/memcached.so'  

### ISSUE THREAD

**Issue by tlandn** [EasyEngine/easyengine#741]
Hi

When I run php -v I got these warnings:
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/redis.so' - /usr/lib/php/20151012/redis.so: undef             ined symbol: igbinary_serialize in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/memcached.so' - /usr/lib/php/20151012/memcached.s             o: undefined symbol: igbinary_serialize in Unknown on line 0

Here are commands I ran to install EE:
wget -qO ee rt.cx/ee && sudo bash ee
sudo ee stack install 
sudo ee stack install --redis
sudo ee stack install --php7

After these 4 commands, I run php -v and got warnings above

Please attach the output of following command when open a new support request.
- [x] lsb_release -a
  No LSB modules are available.
  Distributor ID: Ubuntu
  Description:    Ubuntu 14.04.4 LTS
  Release:        14.04
  Codename:       trusty
- [x] ee -v
  EasyEngine v3.7.0
- [x] ee info
  NGINX (1.10.0):

user                             www-data
worker_processes                 auto
worker_connections               4096
keepalive_timeout                30
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1

PHP (5.6.23-1):

user
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  500
pm.max_children                  100
pm.start_servers                 20
pm.min_spare_servers             10
pm.max_spare_servers             30
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           127.0.0.1:9000

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  500
pm.max_children                  100
pm.start_servers                 20
pm.min_spare_servers             10
pm.max_spare_servers             30
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9001

MySQL (10.1.14-MariaDB) on localhost:

port                             3306
wait_timeout                     600
interactive_timeout              28800
max_used_connections             2
datadir                          /var/lib/mysql/
socket                           /var/run/mysqld/mysqld.sock
my.cnf [PATH]                    /etc/mysql/conf.d/my.cnf
- [x] wp --allow-root --info

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/redis.so' - /usr/lib/php/20151012/redis.so: undefined symbol: igbinary_serialize in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/memcached.so' - /usr/lib/php/20151012/memcached.so: undefined symbol: igbinary_serialize in Unknown on line 0
PHP binary:     /usr/bin/php7.0
PHP version:    7.0.8-2+deb.sury.org~trusty+1
php.ini used:   /etc/php/7.0/cli/php.ini
WP-CLI root dir:        phar://wp-cli.phar
WP-CLI packages dir:    /root/.wp-cli/packages/
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 0.23.0

**Comment by AbbeyLashly** [comment]
I am facing this same issue too.

**Comment by mrother** [comment]
Same here.

**Comment by tlandn** [comment]
Thanks @mrother for the solution :+1:

**Comment by supermoney1709** [comment]
How do you disable the modules? @mrother (sorry new to this)

**Comment by rahul286** [comment]
@tlandn Sorry for a delayed reply. I hope your issue is fixed by now with @mrother help.

If you are still facing the issue, please use http://community.rtcamp.com/c/easyengine for further support.

We are cleaning up issue tracker and closing this issue because we won't be able to contribute to this discussion further.
