### ISSUE TITLE
MariaDB 10.0.26 - Stable GA - released June 24 - Upgrade Request

### ISSUE THREAD

**Issue by MattyLB** [EasyEngine/easyengine#746]
I've noticed some recent discrepancies with the version of MySQL/MariaDB and/or Innodb that WooCommerce and other WP plugins are looking for at minimum and the warnings they are throwing appear to be correctable by updating to MariaDB 10.0.26 released June 24 and considered Stable (GA). *see*: https://mariadb.com/kb/en/mariadb/mariadb-10026-release-notes/

My first question is why my release is showing: _mysql  Ver 15.1 **Distrib 10.1.14-MariaDB**, for debian-linux-gnu (x86_64) using readline 5.2_ ... when I cannot find a version 10.1.14 release note anywhere on the MariaDB official website?

Maybe this update could solve some of the open GIT issues regarding MySQL, MariaDB, Innodb v TokuDB, etc errors and questions.  It seems to have a LOT of bug fixes and improvements in this release.

Please correct me if I'm way off base here - I'm simply trying to make sure WooCommerce, WordPress and the function of my site is happy and optimized. **If this cannot be added to core, is there an easy/safe way for me to manually update to this version?**

- [ ] lsb_release -a

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04 LTS
Release:        16.04
Codename:       xenial
- [ ] ee -v

EasyEngine v3.7.0
Copyright (c) 2016 rtCamp Solutions Pvt. Ltd.
- [ ] ee info

NGINX (1.10.0):
user                             www-data
worker_processes                 auto
worker_connections               4096
keepalive_timeout                30
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1
PHP (5.6.23-2):
user
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300
Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  500
pm.max_children                  100
pm.start_servers                 20
pm.min_spare_servers             10
pm.max_spare_servers             30
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           127.0.0.1:9000
Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  500
pm.max_children                  100
pm.start_servers                 20
pm.min_spare_servers             10
pm.max_spare_servers             30
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9001
MySQL (10.1.14-MariaDB) on localhost:
port                             3306
wait_timeout                     600
interactive_timeout              28800
max_used_connections             3
datadir                          /var/lib/mysql/
socket                           /var/run/mysqld/mysqld.sock
my.cnf [PATH]                    /etc/mysql/conf.d/my.cnf

- [ ] wp --allow-root --info

PHP binary:     /usr/bin/php7.0
PHP version:    7.0.8-3+deb.sury.org~xenial+1
php.ini used:   /etc/php/7.0/cli/php.ini
WP-CLI root dir:        phar://wp-cli.phar
WP-CLI packages dir:    /root/.wp-cli/packages/
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 0.23.0

**Comment by renatonascalves** [comment]
+1

**Comment by MattyLB** [comment]
After the latest ee release (v 3.7.4) which includes MariaDB 10.1, this issue can now be closed.

To check your version of MariaDB, use: ee info --mysql
To upgrade your version manually, use: ee stack upgrade --mysql

This resolved known vulnerabilities in older versions of MariaDB that have been fixed.
