### ISSUE TITLE
Some frontend theme builder (drag and drop) not work

### ISSUE THREAD

**Issue by MrXichy** [EasyEngine/easyengine#752]
line 23 of wpsc.conf is
  try_files /wp-content/cache/supercache/$http_host/$cache_uri/index.html $uri $uri/ /index.php;
should be
try_files /wp-content/cache/supercache/$http_host/$cache_uri/index.html $uri $uri/ /index.php?$args;

Because if dont have ?$args at the end, some frontend theme builder (drag and drop) will not work.
I see"Themify builder" and "Beaver Builder" plugin, only work at home page, cannot work at other pages.

After i add "?$args" at the end, it fixed.

Please check and fix again, thanks :)

**Comment by rahul286** [comment]
@MrXichy Sorry for the delay in looking into this.

In EE v4, we wont be supporting supercache.

So I am closing this.
