### ISSUE TITLE
phpMyAdmin - Error

### ISSUE THREAD

**Issue by CGAP** [EasyEngine/easyengine#756]
Error during session start; please check your PHP and/or webserver log file and configure your PHP installation properly. Also ensure that cookies are enabled in your browser.

session_start(): open(C:\Windows\TEMP\sess_ipiitudu0tlnlhom6nd4jfrcfn6ptbrq, O_RDWR) failed: Invalid argument (22)

Can anyone assist me to solve this issue?

**Comment by w33zy** [comment]
Can you please use the provided new issue template to provide us with details on your installation and environment?

**Comment by MiteshShah** [comment]
@CGAP  open(C:\Windows\TEMP\

Definitely not related to Linux server take a look into your browser settings.

**Comment by CGAP** [comment]
it is installed on IIS.

php.ini file :- session.save_path = "C:\temp\phpsessions"
before it was fine and running.
Now If I want to open PHPmyadmin it is showing me PHPMYADMIN error.

**Comment by w33zy** [comment]
@CGAP 
How did you manage to install ````ee```` on IIS?

**Comment by CGAP** [comment]
Thank you so much for your response.
I have installed PHPMyadmin, my SQL & PHP to host wordpress site.
It was sucessfully running since 4 months & now so sudden there is an error message for phpmyadmin.
I followed this link
https://www.pluralsight.com/blog/tutorials/install-phpmyadmin-on-iis7-and-server-2008.
http://www.drewslair.com/2015/09/installing-mysql-php-iis-complete-guide/

**Comment by w33zy** [comment]
Are you using EasyEngine?

**Comment by CGAP** [comment]
no

**Comment by w33zy** [comment]
So why did you create an 'issue' for a GitHub repo you are not using?

**Comment by CGAP** [comment]
I am not aware of easy engine.

Do you have any suggestion for above error. I have tried to clear my cache but nothing seems to be work.

I will really appreciate your help.

**Comment by w33zy** [comment]
Can you please close this ticket. This is not a support forum. Try reposting your questions to an appropriate StackExchange forum or similar.

**Comment by MiteshShah** [comment]
@CGAP Kindly read Guideline before randomly create an issue on random Github repository.

> Do you have any suggestion for above error. I have tried to clear my cache but nothing seems to be work.

Google it or ask Micro$hit IIS.

@iam404 close this issue as nothing related to EE.
