### ISSUE TITLE
ee stack install --utils error

### ISSUE THREAD

**Issue by huytrq** [EasyEngine/easyengine#757]
root@ubuntu:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:        14.04
Codename:       trusty
root@ubuntu:~# ee -v
EasyEngine v3.7.3
Copyright (c) 2016 rtCamp Solutions Pvt. Ltd.
root@ubuntu:~# ee info
grep: /etc/nginx/common/acl.conf: No such file or directory

NGINX (1.10.0):

user                             www-data
worker_processes                 auto
worker_connections               4096
keepalive_timeout                30
fastcgi_read_timeout             300
client_max_body_size             100m
allow
'ping.path'
root@ubuntu:/tmp# ee stack install --utils
Downloading phpMemcachedAdmin    Unable to download file, /tmp/memcache.tar.gz

**Comment by iam404** [comment]
This issue is fixed with latest release of EE.
