### ISSUE TITLE
Unable to clean opcache

### ISSUE THREAD

**Issue by rsmith4321** [EasyEngine/easyengine#762]
Please attach the output of following command when open a new support request.

- [No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial ] lsb_release -a
- [ EasyEngine v3.7.4] ee -v
- [NGINX (1.10.0):

user                             www-data
worker_processes                 auto
worker_connections               4096
keepalive_timeout                30
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1 

PHP (5.6.25-2):

user                             
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  500
pm.max_children                  100
pm.start_servers                 20
pm.min_spare_servers             10
pm.max_spare_servers             30
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           127.0.0.1:9000

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  500
pm.max_children                  100
pm.start_servers                 20
pm.min_spare_servers             10
pm.max_spare_servers             30
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9001

MySQL (10.1.17-MariaDB) on localhost:

port                             3306
wait_timeout                     600
interactive_timeout              28800
max_used_connections             3
datadir                          /var/lib/mysql/
socket                           /var/run/mysqld/mysqld.sock
my.cnf [PATH]                    /etc/mysql/conf.d/my.cnf ] ee info
- [ PHP binary:	/usr/bin/php7.0
PHP version:	7.0.10-2+deb.sury.org~xenial+1
php.ini used:	/etc/php/7.0/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI packages dir:	
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	0.24.1] wp --allow-root --info

I've been having strange problems with things like updating plugins reporting they still needed updating and things like that.  I think I've narrowed down the issue to not being able to clear opcache.  If I restart my server the problems go away because it forces a clear of the cache.  If I do ee clean --all I get an Unable to clean opcache error.  Any ideas?  Thanks!

**Comment by iam404** [comment]
Hi @rsmith4321 
Is object cache installed on site. Like redis-cache plugin.
Also try installing EE admin tools (`ee stack install --admin`) and try running `ee clean --all` again.

**Comment by rsmith4321** [comment]
Thanks for the help, yes I have the redis-cache plugin installed.  Perhaps I shouldn't be using opcache at all, I was under the understanding it caches all the php scripts and is built into php7.  I tried to run ee stack install again, the ee clean this is the results
Cleaning MemCache
Cleaning NGINX FastCGI cache
Cleaning opcache
Unable to clean opcache
Cleaning Redis cache

I created a php file on my site that contains `<?php
opcache_reset();
?>`
I just bookmarked that page and use it to clear the cache.  This solved my problems with wordpress and plugin updates for now.

**Comment by iam404** [comment]
Please try installing EE admin tools or Utils tools (`ee stack install --admin` or `ee stack install --utils
`) and try running `ee clean --all` again.

If you still face this issue after installing admin tools please create a topic at http://community.rtcamp.com/c/easyengine

**Comment by rsmith4321** [comment]
Thanks, the ee admin tools are installed and work correctly and will clear the cache.  I checked the ee logs and I'm getting this error.  I will post it here incase it's helpful in any way.  
`2016-10-06 21:34:00,858 (DEBUG) ee : <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)>
2016-10-06 21:34:00,859 (DEBUG) ee : Unable hit url,  https://127.0.0.1:22222/cache/opcache/opgui.php?page=reset, please check you have admin tools installed
2016-10-06 21:34:00,859 (DEBUG) ee : please check you have admin tools installed, or install them with `ee stack install --admin`
2016-10-06 21:34:00,859 (ERROR) ee : Unable to clean opcache`

**Comment by ashishdungdung** [comment]
Any update on this, this problem still persists around. Specially in AWS instances.
