### ISSUE TITLE
ee site info reports ssl being disabled while it's actually enabled

### ISSUE THREAD

**Issue by bynicolas** [EasyEngine/easyengine#763]
If I run the command `ee site info example.com` I get

```
Information about example.com:

Nginx configuration  wp wpredis (enabled) 
PHP Version          5.6
HHVM                 disabled
SSL                  disabled
```

I have installed the let's encrypt certificate by using `ee site update example.com --letsencrypt` and I saw the `ee site info example.com` command give SSL information but testing around with different setup, It's now reporting as disabled.
-  This happens on 2 different domains hosted on that server.
-  The server is serving SSL pages fine for each domain.
-  How to make _EasyEngine_ report correct information?
-  I doubt the renewal will take place if _ee_ doesn't report the correct certificate values.
-  I am not exactly sure what broke the report, since I didn't notice it right away while I was testing different scenario (cache settings and SSL ciphers)

---

Please attach the output of following command when open a new support request.
- [x] `lsb_release -a`
  
  No LSB modules are available.
  Distributor ID: Ubuntu
  Description:    Ubuntu 16.04.1 LTS
  Release:    16.04
  Codename:   xenial
- [x] `ee -v`
  
  EasyEngine v3.7.4
  Copyright (c) 2016 rtCamp Solutions Pvt. Ltd.
- [x] `ee info`
  
  NGINX (1.10.0):
  
  user                             www-data
  worker_processes                 auto
  worker_connections               4096
  keepalive_timeout                30
  fastcgi_read_timeout             300
  client_max_body_size             100m
  allow                            127.0.0.1 
  
  PHP (5.6.25-2):
  
  user  
  expose_php                       Off
  memory_limit                     128M
  post_max_size                    100M
  upload_max_filesize              100M
  max_execution_time               300
  
  Information about www.conf
  ping.path                        /ping
  pm.status_path                   /status
  process_manager                  ondemand
  pm.max_requests                  500
  pm.max_children                  100
  pm.start_servers                 20
  pm.min_spare_servers             10
  pm.max_spare_servers             30
  request_terminate_timeout        300
  xdebug.profiler_enable_trigger   off
  listen                           127.0.0.1:9000
  
  Information about debug.conf
  ping.path                        /ping
  pm.status_path                   /status
  process_manager                  ondemand
  pm.max_requests                  500
  pm.max_children                  100
  pm.start_servers                 20
  pm.min_spare_servers             10
  pm.max_spare_servers             30
  request_terminate_timeout        300
  xdebug.profiler_enable_trigger   on
  listen                           127.0.0.1:9001
  
  MySQL (10.1.17-MariaDB) on localhost:
  
  port                             3306 
  wait_timeout                     600
  interactive_timeout              28800
  max_used_connections             4
  datadir                          /var/lib/mysql/
  socket                           /var/run/mysqld/mysqld.sock
  my.cnf [PATH]                    /etc/mysql/conf.d/my.cnf
- [x] `wp --allow-root --info`
  
  PHP binary: /usr/bin/php7.0
  PHP version:    7.0.10-2+deb.sury.org~xenial+1
  php.ini used:   /etc/php/7.0/cli/php.ini
  WP-CLI root dir:    phar://wp-cli.phar
  WP-CLI packages dir:  
  WP-CLI global config:  
  WP-CLI project config:  
  WP-CLI version: 0.24.1

**Comment by mbtamuli** [comment]
This will be fixed automatically once #1022 is fixed. Closing this issue in favor of #1022
