### ISSUE TITLE
Automatted Instalation Enhancements

### ISSUE THREAD

**Issue by ahmadawais** [EasyEngine/easyengine#769]
While building a very basic cPanel to EE (hosted on Vultr) automation script, I have had trouble finding a way for automated installation.

Current version has the ability to define these parameters

``` bash
ee site create domain.ext --wp --user --email 
```

What I want instead is to automated the migration and for that something like this would be needed

``` bash
ee site create domain.ext --wp --user --email --db_name --db_user --db_pass --db_prefix
```

Any luck with that?

**Comment by rahul286** [comment]
@ahmadawais we have already done some work on this in v4 esp around. Overall this should be present in first EE v4 release.

**Comment by mrrobot47** [comment]
We are already tracking this feature in #1029
