### ISSUE TITLE
Docs Suggestion!

### ISSUE THREAD

**Issue by ahmadawais** [EasyEngine/easyengine#771]
On a clean Ubuntu 16.04 install. I was not able to install Let's Encrypt. After searching a lot, I found this weird LE issue. I think it should be documented.

LE has a weird issue with having locales set. Make sure you have them set up. 
Just run 

``` bash
export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
```

If that doesn't work, try the following and run the command again.

``` bash
locale-gen en_US en_US.UTF-8
dpkg-reconfigure locales
```

I hope it helps.

**Comment by mbtamuli** [comment]
Thanks for the comments. We'll update the documentation and  make sure this doesn't recur in EasyEngine v4.
Closing this issue for now.
