### ISSUE TITLE
Let's Encrypt cron time

### ISSUE THREAD

**Issue by hmaesta** [EasyEngine/easyengine#773]
When I set my first cert from Let's Encrypt, **ee** created the auto-renew cron.

But, different from what is [showed in the docs](https://easyengine.io/docs/lets-encrypt/), the `cron` was set to `0 0 * * *`, [which does not serve its purpose](http://crontab.guru/#0_0_*_*_*) – and I had to manually renew every site.

I think this is a bug ([other people](http://community.rtcamp.com/t/cron-job-not-working-for-letsencrypt/7282) appears to have a similar issue), but besides that,  **it would not be better if the cron was executed every 10 days or something like that?** 

[The documentation](https://easyengine.io/docs/lets-encrypt/) shows `0 12 * * *`, which means everyday 12:00. That's not necessary, since Let's Encrypt allows renews 20 days before the expiration.

In my server, I use `0 23 */10 * *`, so it can renew everything every 10 days at 23:00 (11pm), when load is low.

_Right now I am running ee v3.7.4, but it was an older version when I set Let's Encrypt._

–

`0 23 */10 * * ee site update --le=renew --all 2> /dev/null`

**Comment by rsmith4321** [comment]
Thanks, I seem to have this same issue.

**Comment by cfrazier** [comment]
@hmaesta, are you getting automatic renewals processing correctly with the changes cron time?

**Comment by hmaesta** [comment]
@cfrazier I want to say **Yes!**, but one single website is not renewing and I don't know why – but I don't think it is crontime's fault.

**Comment by hermesmarcom** [comment]
I recommend you set the cron job to renew SSL every 70 - 80 days like this:
`0 23 */70 * * ee site update --le=renew --all 2> /dev/null`
Because I myself got this error when renew SSL manually:

> More than 30 days left for certificate Expiry. Not renewing now.

**Comment by janiosarmento** [comment]
What if you have two or more sites, with non coincident expiry dates?

Think twice.

**Comment by hermesmarcom** [comment]
@janiosarmento If you have two or more sites with non coincident expiry dates, IMHO, there is no other way but setting the cron job for each website:
instead of
0 23 */70 * * ee site update --le=renew --all 2> /dev/null
using:
`0 23 */60 * * ee site update site1.com --le=renew 2> /dev/null `#if site1 has SSL from 1/1/2017 and today is no later than 30 days from 1/1/2017.

`0 23 */60 * * ee site update site2.com --le=renew 2> /dev/null` #if site2 has SSL from 15/3/2017 and today is no later than 30 days from 15/3/2017.

and so on.

You may have more efficient way to configure above crons. Read more at: https://www.pantz.org/software/cron/croninfo.html

**Comment by tuxcomputing** [comment]
Or you can make it run every day on midnight for both sites and then you're certain that your certificate is renewed :)

**Comment by hermesmarcom** [comment]
@tuxcomputing Have you tried? Have you got the error message:

> More than 30 days left for certificate Expiry. Not renewing now.

**Comment by tuxcomputing** [comment]
@hermesmarcom it does not matter if you get the error or not. just run it through cron every night, set the output to 2> /dev/null and it will renew itself when you have less than 30 days. :)

**Comment by rahul286** [comment]
We have handled this in a better way in v4.

You may check this PR https://github.com/EasyEngine/easyengine/pull/1005

Please use http://community.rtcamp.com/c/easyengine for future support questions.
