### ISSUE TITLE
[RESOLVED] 'ee_mysql_grant_host' Oops Something went wrong !! Calling cleanup actions ...

### ISSUE THREAD

**Issue by ahmadawais** [EasyEngine/easyengine#775]
I am getting  `'ee_mysql_grant_host'` error. I have gone through every issue similar to mine and was unable to fix it. 

## What's Happened?
- Everything was working fine.
- I was creating a new site `ee site create xyz --wp` and looks like MySQL is not accessible anymore.
- I am trying to fix it and also trying to understand what caused this issue.

If I run `mysql` command this is what I get
```bash
$ mysql
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
```
If I enter the root mysql pass as mentioned in the ` st /etc/mysql/conf.d/my.cnf` I still get the same response

```bash
$ mysql -u root -p XXXX
Enter password:
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
```

Why did this happen? What should I do?

## Sepcs
- [X ] lsb_release -a
```bash
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
```
- [x] ee -v
```bash
EasyEngine v3.7.4
Copyright (c) 2016 rtCamp Solutions Pvt. Ltd.
```
- [x] ee info

```bash
NGINX (1.10.0):

user                             www-data
worker_processes                 auto
worker_connections               4096
keepalive_timeout                30
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1

PHP (5.6.26-1):

user
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  500
pm.max_children                  100
pm.start_servers                 20
pm.min_spare_servers             10
pm.max_spare_servers             30
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           127.0.0.1:9000

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  500
pm.max_children                  100
pm.start_servers                 20
pm.min_spare_servers             10
pm.max_spare_servers             30
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9001
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)

MySQL (10.1.18-MariaDB) on localhost:

port
wait_timeout
interactive_timeout
max_used_connections
datadir
socket
my.cnf [PATH]                    /etc/mysql/conf.d/my.cnf
```

- [x] wp --allow-root --info

```bash
PHP binary:	/usr/bin/php5.6
PHP version:	5.6.26-1+deb.sury.org~xenial+1
php.ini used:	/etc/php/5.6/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version:	0.24.1
```

## What have I done?

There are similar issues. #688, [forum thread](http://community.rtcamp.com/t/site-create-fails-ee-mysql-grant-host-despite-seemingly-valid-config/5246), [second](http://community.rtcamp.com/t/error-when-i-add-new-wordpress-site-setting-up-database-oops-something-went-wrong-calling-cleanup-actions-ee-mysql-grant-host/6116/7) and [this one](http://community.rtcamp.com/t/oops-something-went-wrong/6107/7) which is still inresolved.

**EE Custom Config looks like**
 `/etc/ee/ee.conf`
```bash
[mysql]

### MySQL database grant host name
grant-host = localhost

### Ask for MySQL db name while site creation
db-name = true

### Ask for MySQL user name while site creation
db-user = true
```

**MySQL Config has `lc_messages` parameter **
`/etc/mysql/my.cnf`
```bash
#
# * Basic Settings
#
user		= mysql
pid-file	= /var/run/mysqld/mysqld.pid
socket		= /var/run/mysqld/mysqld.sock
port		= 3306
basedir		= /usr
datadir		= /var/lib/mysql
tmpdir		= /tmp
lc_messages_dir	= /usr/share/mysql
lc_messages	= en_US
skip-external-locking
```

**Tailing the log**

```bash
2016-10-03 19:00:34,464 (DEBUG) ee : Running command: mysqladmin ping
2016-10-03 19:00:34,474 (DEBUG) ee : Command Output: ,
Command Error: mysqladmin: connect to server at 'localhost' failed
error: 'Access denied for user 'root'@'localhost' (using password: YES)'

2016-10-03 19:00:34,542 (DEBUG) ee : loading template file /usr/lib/ee/templates/info_mysql.mustache
```

I am currently thinking of reseting the `mysql` pass but why did this happen? 
Looking forward!

**Comment by ahmadawais** [comment]
While, I would still like to know what caused this issue. I do have resolved it be resetting the pass for `root` user. This [tutorial](https://easyengine.io/tutorials/mysql/reset-root-password/) [credits](http://www.cyberciti.biz/tips/recover-mysql-root-password.html) came in handy.

P.S. Make sure you do not use any characters in the new pass since `ZSH` started tripping on that.

**Comment by rahul286** [comment]
@ahmadawais thanks for posting what worked for you. 

Unfortunately, it's hard to find out why password got changed! :|

**Comment by robwilde** [comment]
I had the same problem and this helped also. May have something to do with updating MySQL and choosing the provider package.

**Comment by robert1112** [comment]
Hi I go the same issue and tried @ahmadawais 's advice but still no luck. Anyone can help? I am stuck. Thanks.

**Comment by fxaviers** [comment]
I have the same problem. Resetting the MySQL password did not work.

**Comment by fxaviers** [comment]
@robert1112 I found what is causing the error and also a way to fix it temporarily:

**Error:**
Basically, what causes this is a decompression failure of WP 4.8.2 en_US
https://github.com/EasyEngine/easyengine/issues/932
https://github.com/wp-cli/wp-cli/issues/4370

**Solution:**
Download the file wordpress-4.8.2-pt_BR.tar.gz (Or other than the en_US), rename to en_US and upload to /root/.wp-cli/cache/core

I know that there may be a simpler, or even more correct, way of doing this, but I do not have the necessary knowledge to do so.

**Comment by robert1112** [comment]
Hi @fxaviers  I will give it a try. Thank you so much.

**Comment by singlow** [comment]
You can also install wp-cli nightly (`wp cli update --nightly`). It has added a fallback to use the system tar/gzip commands if it fails in decompressing the downloaded wordpress targzip file. The wordpress archive may have something wrong, but it decompresses fine with other gzip tools, just not php.

**Comment by nfsarmento** [comment]
Hi @fxaviers, thanks a lot, it did work for me :)

**Comment by dejioke** [comment]
@fxaviers method works. 
However, it might be an extra task to download and reupload a new version of of wordpres.
If you have installed a site before on that Easy Engine installation, you will see all the previous versions of wordpress that worked fine at /root/.wp-cli/cache/core.
rename one of them to wordpress-4.8.2-en_US.tar.gz and retry creating site.

NOTE: This way easy engine will install earlier version of wordpress that you renamed, you can update it to the latest via WP dashboard

**Comment by vpedrosa** [comment]
EasyEngine is installing WP CLI v0.24.1, which is causing the bug (https://github.com/wp-cli/wp-cli/issues/1962 was in v0.19.1). Current version is v1.4.0.

```shell
$ wp cli version
WP-CLI 0.24.1
$ which wp
/usr/bin/wp
```

As long as EE is installing wp cli with root permissions, you can do:

```shell
sudo wp cli update --allow-root
```
Delete the site if you have already created it and recreate again.

**Comment by emanuellimeira** [comment]
@singlow thank you very much `wp cli update --nightly --allow-root` works for me ;)
