### ISSUE TITLE
Remove experimental status for php7, wpredis

### ISSUE THREAD

**Issue by rahul286** [EasyEngine/easyengine#779]
We are removing HHVM

We need to remove experimental flag for
- [ ] `--wpredis`
- [ ] `--php7`

**Comment by khromov** [comment]
👍

**Comment by tuxcomputing** [comment]
+1.  php7 should be default tbh

**Comment by rahul286** [comment]
@tuxcomputing I do feel same. We haven't seen a single WP sites failing on PHP7. :)

**Comment by tuxcomputing** [comment]
@rahul286 totally forgot. Speaking of --wpredis, any plans to include a launchpad repo build for Ubuntu 14.04 LTS that would hold the actual stable redis server? Current build available via apt for 14.04 is only 3.0.7

**Comment by benzon** [comment]
But having the option to run different php versions is quite nice so keep that build in :)

**Comment by rahul286** [comment]
@mbtamuli if we can add multiple PHP version support then we can make php7 as default for new sites.

We don't need to support each and every PHP version. Just one from PHP 5.x and PHP 7.x

**Comment by kirtangajjar** [comment]
@tuxcomputing v4 will be docker based. Hence I don't think there would be any plans to include a launchpad repo build for redis server.

**Comment by michacassola** [comment]
It only has to be PHP7.0/.1/.2 and PHP 5.6 in my opinion.

What about Redis?

**Comment by vibhi19** [comment]
Why are you removing HHVM. 
I think it great and can handle more traffic than php7

**Comment by nsgoyat** [comment]
+1 for PHP 7 & Redis Experimental Flag Removal. Using PHP 7 and Redis on different types of Wordpress Sites and the combination works great.

**Comment by rahul286** [comment]
v4 doesnt have any experimental flag at the moment.
