### ISSUE TITLE
v3 to v4 Automated Migration Script

### ISSUE THREAD

**Issue by rahul286** [EasyEngine/easyengine#782]
- [ ] Check for deprecated feature. Show warning. Default is stop migration.
- [ ] Remove python version (v3)
- [ ] Install php version (v4)
- [ ] Run sanity checks _(to be decided)_

**Comment by kirtangajjar** [comment]
WIP doc - https://docs.google.com/document/d/1h8J3d7c8rDy-O45eEPMPy-SW2NNmpHzH5FC6YLwCTfE/edit#

**Comment by mbtamuli** [comment]
Closing this issue in favor of https://github.com/EasyEngine/easyengine/issues/993
