### ISSUE TITLE
ee v3 commands to migrate

### ISSUE THREAD

**Issue by rahul286** [EasyEngine/easyengine#783]
Commands:
- [ ] `clean` - Clean NGINX FastCGI cache, Opcache, Memcache, Redis Cache
- [ ] `debug` - Used for server level debugging
- [ ] `stack` - Stack command manages stack operations
- [x] `update` - update EasyEngine to latest version
- [x] `info` - Display configuration information related to Nginx, PHP and MySQL
- [x] `log` - Perform operations on Nginx, PHP, MySQL log file
- [x] `secure` - Secure command secure auth, ip and port
- [x] `site` - Performs website specific operations

Google Doc - https://docs.google.com/spreadsheets/d/1ybo3z5dImNFmx1LoqNJ2PjJGh4_s2RH3MCKQj_LyRlQ/edit#gid=0

**Comment by chandra-patel** [comment]
Hello @rahul286, @iam404 

I think, `import-slow-log` command is deprecated and we are using `ee debug --import-slow-log`. Please confirm. If its true than please remove from list.

Regards,

**Comment by kirtangajjar** [comment]
@rahul286 As v4 will have only one caching mechanism, I think the correct command to have would be `ee cache clear` and we can keep `ee clean` as its alias for backward compatibility.

**Comment by rahul286** [comment]
@kirtangajjar this should be documented as a separate doc "Migration from V3" in handbook

**Comment by rahul286** [comment]
@kirtangajjar Have a look at https://github.com/EasyEngine/docs/issues/20 
Checklist part.

**Comment by rahul286** [comment]
* `ee clean` will be added in one of 4.0.x minor release
* `ee debug` will be added likely in 4.1
* `ee stack` is no longer required. There is somewhat equivalent ee service command now
