### ISSUE TITLE
ee site create [sitename.com] --wpfc --php7 installs w3-total-cache and enables php5.6

### ISSUE THREAD

**Issue by dsifford** [EasyEngine/easyengine#784]
Please attach the output of following command when open a new support request.
- [ ] lsb_release -a
- [ ] ee -v
- [ ] ee info
- [ ] wp --allow-root --info

``` sh
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty
```

``` sh
EasyEngine v3.7.4
Copyright (c) 2016 rtCamp Solutions Pvt. Ltd.
```

``` sh
NGINX (1.10.0):

user                             www-data
worker_processes                 auto
worker_connections               4096
keepalive_timeout                30
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1

PHP (5.6.26-2):

user
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  500
pm.max_children                  100
pm.start_servers                 20
pm.min_spare_servers             10
pm.max_spare_servers             30
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           127.0.0.1:9000

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  500
pm.max_children                  100
pm.start_servers                 20
pm.min_spare_servers             10
pm.max_spare_servers             30
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9001

MySQL (10.1.18-MariaDB) on localhost:

port                             3306
wait_timeout                     600
interactive_timeout              28800
max_used_connections             2
datadir                          /var/lib/mysql/
socket                           /var/run/mysqld/mysqld.sock
my.cnf [PATH]                    /etc/mysql/conf.d/my.cnf
```

I was able to get php7 enabled after fiddling around with it and explicitly stopping php5.6, however w3-total-cache is still installed. It's my understanding that with fastcgi caching, this isn't needed?

**Comment by dsifford** [comment]
Also: I have wp installed and running, but there is not `wp-config.php` anywhere to be found (other than the sample one).. How can this be?

**Comment by rsmith4321** [comment]
Use --wpredis instead and w3tc won't be installed.  With fastcgi it's still needed for object caching I believe.  Redis works great.  Also php5.6 and 7.0 are always both installed, but your site should use php 7. Your command line can be on php 5.6 but your site is running on 7.  Look up how to create a phpinfo file on your website and you can view what it's running on.

**Comment by dsifford** [comment]
Thanks for the `--wpredis` tip @rsmith4321. Super helpful!

I (vaguely) believe that I did create and inspect a `phpinfo` file and it was showing up as 5.6. I'm like 98% sure I did. That said, I can try again sometime this weekend and double check if needed.

**Comment by rahul286** [comment]
@dsifford Sorry for a delayed reply. I hope your issue is fixed by now.

Thanks @rsmith4321 for the recommendation. We recommend `--wpredis` too. There is a whole new thread around it. https://github.com/EasyEngine/easyengine/issues/1015

We are cleaning up issue tracker and closing this issue.
