### ISSUE TITLE
Postfix is sending thousands mails a day

### ISSUE THREAD

**Issue by lutfuahmet** [EasyEngine/easyengine#787]
I have two vps installed with Easyengine.

Firstly I recognized some unwanted script at header.php. Some php files at server was adding fake jquery script to header files. 

Then I looked up nginx access log file. There was irregular Post Requests made to some php file.

Whenever I looked postfix mail queue, there was about 200000 emails. My server had become spam server.

I found the solution for stop to sending spam mail.

My solution is; deny execution of php at "wp-content"  directory via nginx.

Can you add this config to next easyengine release?

I think I was not only victim about this issue.

**Comment by timelf123** [comment]
Do you have a copy of the infected code?

**Comment by rahul286** [comment]
Sorry for a delayed reply. I hope your issue is fixed by now.

If you are still facing the issue, please use http://community.rtcamp.com/c/easyengine for further support.

We are cleaning up issue tracker and closing this issue because we won't be able to contribute to this discussion further.
