### ISSUE TITLE
MySQL Keeps Crashing

### ISSUE THREAD

**Issue by ahmadawais** [EasyEngine/easyengine#791]
I am using EE to host about 10 WP installs with very low traffic on a $10 Vultr with 1GB RAM. MySQL kept crashing for no reason, I installed Monit it takes care of automatically restarting MySQL when it crashes. 

I am trying to figure things out.

I have read https://easyengine.io/docs/prevent-mysql-crashing/

I have optimized my cnf like this

``` bash
# MariaDB database server configuration file.
#
# You can copy this file to one of:
# - "/etc/mysql/my.cnf" to set global options,
# - "~/.my.cnf" to set user-specific options.
#
# One can use all long options that the program supports.
# Run program with --help to get a list of available options and with
# --print-defaults to see which it would actually understand and use.
#
# For explanations see
# http                            ://dev.mysql.com/doc/mysql/en/server-system-variables.html

# This will be passed to all mysql clients
# It has been reported that passwords should be enclosed with ticks/quotes
# escpecially if they contain "#" chars...
# Remember to edit /etc/mysql/debian.cnf when changing the socket location.
[client]
port                              = 3306
socket                            = /var/run/mysqld/mysqld.sock

# Here is entries for some specific programs
# The following values assume you have at least 32M ram

# This was formally known as [safe_mysqld]. Both versions are currently parsed.
[mysqld_safe]
socket                            = /var/run/mysqld/mysqld.sock
nice                              = 0

[mysqld]
#
# * Basic Settings
#
user                              = mysql
pid-file                          = /var/run/mysqld/mysqld.pid
socket                            = /var/run/mysqld/mysqld.sock
port                              = 3306
basedir                           = /usr
datadir                           = /var/lib/mysql
tmpdir                            = /tmp
lc_messages_dir                   = /usr/share/mysql
lc_messages                       = en_US
skip-external-locking
#
# Instead of skip-networking the default is now to listen only on
# localhost which is more compatible and is not less secure.
bind-address                      = 127.0.0.1
#
# * Fine Tuning
#
max_connections                   = 35
connect_timeout                   = 5
wait_timeout                      = 600
max_allowed_packet                = 16M
thread_cache_size                 = 128
sort_buffer_size                  = 4M
bulk_insert_buffer_size           = 16M
tmp_table_size                    = 32M
max_heap_table_size               = 32M
#
# * MyISAM
#
# This replaces the startup script and checks MyISAM tables if needed
# the first time they are touched. On error, make copy and try a repair.
myisam_recover_options            = BACKUP
key_buffer_size                   = 23M
#open-files-limit                 = 2000
table_open_cache                  = 401
myisam_sort_buffer_size           = 256M
concurrent_insert                 = 2
read_buffer_size                  = 2M
read_rnd_buffer_size              = 1M
#
# * Query Cache Configuration
#
# Cache only tiny result sets, so we can fit more in the query cache.
query_cache_limit                 = 512K
query_cache_size                  = 64M
# for more write intensive setups, set to DEMAND or OFF
#query_cache_type                 = DEMAND
#
# * Logging and Replication
#
# Both location gets rotated by the cronjob.
# Be aware that this log type is a performance killer.
# As of 5.1 you can enable the log at runtime!
#general_log_file                 = /var/log/mysql/mysql.log
#general_log                      = 1
#
# Error logging goes to syslog due to /etc/mysql/conf.d/mysqld_safe_syslog.cnf.
#
# Error log - should be very few entries.
#
log_error                         = /var/log/mysql/error.log
# we do want to know about network errors and such
log_warnings                      = 2
#
# Enable the slow query log to see queries with especially long duration
slow_query_log                    = 1
slow_query_log_file               = /var/log/mysql/mariadb-slow.log
long_query_time                   = 10
#log_slow_rate_limit              = 1000
log_slow_verbosity                = query_plan

#log-queries-not-using-indexes
#log_slow_admin_statements
#
# The following can be used as easy to replay backup logs or for replication.
# note                            : if you are setting up a replication slave, see README.Debian about
#       other settings you may need to change.
#server-id                        = 1
#report_host                      = master1
#auto_increment_increment         = 2
#auto_increment_offset            = 1
log_bin                           = /var/log/mysql/mariadb-bin
log_bin_index                     = /var/log/mysql/mariadb-bin.index
# not fab for performance, but safer
#sync_binlog                      = 1
expire_logs_days                  = 10
max_binlog_size                   = 100M
# slaves
#relay_log                        = /var/log/mysql/relay-bin
#relay_log_index                  = /var/log/mysql/relay-bin.index
#relay_log_info_file              = /var/log/mysql/relay-bin.info
#log_slave_updates
#read_only
#
# If applications support it, this stricter sql_mode prevents some
# mistakes like inserting invalid dates etc.
#sql_mode                         = NO_ENGINE_SUBSTITUTION,TRADITIONAL
#
# * InnoDB
#
# InnoDB is enabled by default with a 10MB datafile in /var/lib/mysql/.
# Read the manual for more InnoDB related options. There are many!
default_storage_engine            = InnoDB
# you can't just change log file size, requires special procedure
#innodb_log_file_size             = 50M
# innodb_buffer_pool_size         = 256M
innodb_buffer_pool_instances      = 1
innodb_buffer_pool_size           = 64M
innodb_log_buffer_size            = 8M
innodb_file_per_table             = 1
innodb_open_files                 = 400
innodb_io_capacity                = 400
innodb_flush_method               = O_DIRECT
#
# * Security Features
#
# Read the manual, too, if you want chroot!
# chroot                          = /var/lib/mysql/
#
# For generating SSL certificates I recommend the OpenSSL GUI "tinyca".
#
# ssl-ca                          =/etc/mysql/cacert.pem
# ssl-cert                        =/etc/mysql/server-cert.pem
# ssl-key                         =/etc/mysql/server-key.pem

#
# * Galera-related settings
#
[galera]
# Mandatory settings
#wsrep_on                         =ON
#wsrep_provider                   =
#wsrep_cluster_address            =
#binlog_format                    =row
#default_storage_engine           =InnoDB
#innodb_autoinc_lock_mode         =2
#
# Allow server to accept connections on all interfaces.
#
#bind-address                     =0.0.0.0
#
# Optional setting
#wsrep_slave_threads              =1
#innodb_flush_log_at_trx_commit   =0

[mysqldump]
quick
quote-names
max_allowed_packet                = 16M

[mysql]
#no-auto-rehash # faster start of mysql but no tab completion

[isamchk]
key_buffer                        = 16M

# Custom by Mike.
[mariadb]
aria_pagecache_buffer_size        = 1M

#
# * IMPORTANT                     : Additional settings that can override those from this file!
#   The files must end with '.cnf', otherwise they'll be ignored.
#
!includedir /etc/mysql/conf.d/

```
- [x] lsb_release -a

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:    16.04
Codename:   xenial
- [x] ee -v

EasyEngine v3.7.4
Copyright (c) 2016 rtCamp Solutions Pvt. Ltd.
- [x] ee info
  NGINX (1.10.0):

user                             www-data
worker_processes                 auto
worker_connections               4096
keepalive_timeout                30
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1

PHP (5.6.27-1):

user
expose_php                       Off
memory_limit                     256M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  500
pm.max_children                  10
pm.start_servers                 20
pm.min_spare_servers             10
pm.max_spare_servers             30
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           127.0.0.1:9000

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  500
pm.max_children                  100
pm.start_servers                 20
pm.min_spare_servers             10
pm.max_spare_servers             30
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9001

MySQL (10.1.18-MariaDB) on localhost:

port                             3306
wait_timeout                     600
interactive_timeout              28800
max_used_connections             2
datadir                          /var/lib/mysql/
socket                           /var/run/mysqld/mysqld.sock
my.cnf [PATH]                    /etc/mysql/conf.d/my.cnf
- [x] wp --allow-root --info

PHP binary: /usr/bin/php5.6
PHP version:    5.6.27-1+deb.sury.org~xenial+1
php.ini used:   /etc/php/5.6/cli/php.ini
WP-CLI root dir:    phar://wp-cli.phar
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 0.24.1

While I am still testing, I need suggestions on how to make it better. I used this [tool](http://www.omh.cc/mycnf/) to help optimize my conf to use max 1GB memory. 

Any suggestions?

**Comment by kingkool68** [comment]
I was facing the same issue. The MySQL service would crash and not restart automatically leaving me with the dreaded `Error establishing connection to the database` screen of death. You don't need `monit` as Ubunutu/Debian use `systemd` to do the same thing. You only need to change one line in an EasyEngine setup. I changed `Restart` from `on-abort` to `always` and I changed `RestartSec` from `5s` to `3s` in `/etc/systemd/system/mysqld.service` 

So my final configuration looks like this:
```
# Restart crashed server only, on-failure would also restart, for example, when
# my.cnf contains unknown option
Restart=always
RestartSec=3s
```

There's another file in that same directory called `mysql.service` so you can change that to if you want.

Setting `Restart` to `always` will restart the service automatically after a crash. `RestartSec` determines the number of seconds to wait before restarting the service. 

@rahul286 You might consider making this configuration change the default when EasyEngine is setting up a site.

**Comment by MattyLB** [comment]
I'm facing the same issues about every other week so I really appreciate the info here, especially the "restart always" tip until I can adjust my resource settings.

I also vote yes to making "Restart Always" the default going forward, though I agree it could just be a bandaid for those of us who don't have our DB resources set correctly. Either way, at least it would prevent another lengthy outage!

**Comment by MiteshShah** [comment]
@MattyLB If you are using Ubuntu 16.04 then mostly its due to kernel bug - https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1655842

you can verify it by checking /var/log/kern.log file

**Comment by ahmadawais** [comment]
The issue was and is the `my.cnf` file which has been setup for a server with at least 3 GB RAM. When running a server with RAM less than that, ee config fails and MySQL shuts down.

Use this tool http://www.omh.cc/mycnf/ to upload your `/etc/mysql/my.cnf` file. After your upload it will calculate and tell you the memory required to run that config. After that adjust the max connections or several other parameters as per your server and make sure the mem required is less than that of the available RAM.

Good luck.
