### ISSUE TITLE
HTTP request sent, awaiting response... 404 Not Found When downloading rt.cx/ee

### ISSUE THREAD

**Issue by ikolubr** [EasyEngine/easyengine#794]
root@mail:~# wget -O ee rt.cx/ee
--2016-11-04 10:23:58--  http://rt.cx/ee
Resolving rt.cx (rt.cx)... 138.201.89.76
Connecting to rt.cx (rt.cx)|138.201.89.76|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://raw.githubusercontent.com/EasyEngine/easyengine/master/install [following]
--2016-11-04 10:23:58--  https://raw.githubusercontent.com/EasyEngine/easyengine/master/install
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.52.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.52.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-11-04 10:24:04 ERROR 404: Not Found.

Please attach the output of following command when open a new support request.

- [x] lsb_release -a
root@mail:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.6 (jessie)
Release:	8.6
Codename:	jessie

**Comment by iam404** [comment]
Please try below command for Installation
```wget -qO ee rt.cx/ee && sudo bash ee```
