### ISSUE TITLE
Remove $scheme from cache key

### ISSUE THREAD

**Issue by pjv** [EasyEngine/easyengine#795]
Can anyone say why $scheme is part of the cache key for either fastcgi cache or redis page cache?

I have been thinking about it and I can't see any good reason at all to include it in the key. But I can think of a very obvious good reason to exclude it.

The result of including it is that you potentially have two separately cached versions of what should, I think, always be the same resource:

`http://example.com`
`https://example.com`

And then when you edit that page and want to purge the cache, say with nginx-helper, you only end up purging one of the two copies (unless you have a hacked version of nginx-helper like I do).

On any server that is configured to be able to serve both http and https - which is a lot of servers right now, during this presumably transitional period between a mostly http world and a mostly https world - that is going to be a real issue.

Unless there is some good reason that I can't see for having duplicate cache entries for accessing a resource via SSL and non-SSL, I really think that $scheme should be eliminated from all cache keys throughout ee and also nginx-helper.

**Comment by rahul286** [comment]
@pjv in my case, whenever I use HTTPS, I force HTTP > HTTPS redirection.

So the following will return different output:

http://example.com => 301
https://example.com => 200

I cache 301 also at Nginx level.

If cache purge needs more flexibility, then it can be accomplished. Redis full-page cache supports wildcards in purge keys. Though nginx-helper UI can be improved.

**Comment by pjv** [comment]
Hi @rahul286,

Two things:

1. I think that if you are forcing a 301 from http > https in your nginx config, that caching the 301 is probably actually a performance hit or at best break-even. And you are also potentially doubling the number of entries in your cache for no real gain. If you are doing the 301 from PHP then I can see the argument for caching it, but I think I can make a better argument for doing it with nginx so you never have to fire up PHP for those requests.

2. For those who have their servers configured to respond to either http or https - which again these days is more and more - I think it is cleaner, more efficient, and better performance to have one cached entry per URI regardless of scheme.

So here are the arguments for each use case:

A. If your server is only doing either http or https, it doesn't matter and since there is only one scheme, adding either http or https to the front of every cache entry key has no benefit (but uses slightly more memory for the extra characters).

B. If your server forces http > https at the nginx config level, caching the 301 has no performance benefit, but having the scheme in the cache key potentially doubles the number of cache entries.

C. If your server forces http > https at the PHP level, caching the 301 gives a performance benefit, but you get the same downside of B. plus you'd be much better off doing the 301 at the nginx config level anyway.

D. If your server responds to either http or https, having the scheme in the cache key creates the undesirable situation of both potentially doubling the size of the cache (two identical copies of each page) and having to do some gymnastics to make sure you are purging the two presumably identical copies of each cache entry.

**Comment by rahul286** [comment]
We force HTTP > HTTPS at Nginx Level. So PHP never sees HTTP scheme and thus there are no HTTP keys in the cache. 

We discourage using HTTP/HTTPS mix. Especially with free Let's Encrypt and HTTP2 benefits if you are going to use HTTPS, why not use for the full site?

Can you please give me any reason/use-case for mix HTTP/HTTPS usage?

**Comment by pjv** [comment]
I have some clients who, for their own reasons, want to have their public-facing site served via http and want to have their login and admin served via https (FORCE_ADMIN_SSL). I agree that it would be better, now that there is http/2, if they went all-https, and I am working to convince them, but in the mean time the reality is that there are lots of WP sites configured like this. And I would guess this remains true for at least another year or two.

I 100% agree with you it would be better for people to not mix and to go 100% SSL. But to me that isn't the issue here. The issue that I am trying to raise here is that no matter how people are serving their sites -- 100% http, 100% https, or mixed -- having the scheme as part of the key provides zero benefit as far as I can tell and in the mixed http/https case can create problems.

Can you tell me if there is a benefit that I am not seeing to including the extra character strings `http` or `https` in the key? Especially since they will be identical in every key for servers configured with best practice (non-mixed http/https)?

**Comment by rahul286** [comment]
As we do not allow or cache HTTP requests, when HTTPS is being used, we get only one cache-key.

About removing `$scheme` from key - I am not sure what will be impact as it is there from the beginning.

Besides that for your issue, there is a simpler solution. 

When you are using nginx-helper with full-page redis-cache, you can send * in-place of $scheme. 

Please let me know if this works for you.

**Comment by rahul286** [comment]
@pjv We are closing this issue. In V4, we will likely have one caching option and will try to make it easy for users to send wildcard * for `$scheme` as well as other parts.
