### ISSUE TITLE
Fastcgi caching some admin options and not caching main site in Multisite

### ISSUE THREAD

**Issue by QROkes** [EasyEngine/easyengine#799]
All plugins are deactivated and fastcgi is caching some admin options/sections, I need to purge cache to see the updated version of some admin pages.

Please attach the output of following command when open a new support request.

- [ ] lsb_release -a

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial

- [ ] ee -v

EasyEngine v3.7.4
Copyright (c) 2016 rtCamp Solutions Pvt. Ltd.

- [ ] ee info

NGINX (1.10.0):

user                             www-data
worker_processes                 auto
worker_connections               4096
keepalive_timeout                30
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1

PHP (5.6.28-1):

user
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  500
pm.max_children                  100
pm.start_servers                 20
pm.min_spare_servers             10
pm.max_spare_servers             30
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           127.0.0.1:9000

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  500
pm.max_children                  100
pm.start_servers                 20
pm.min_spare_servers             10
pm.max_spare_servers             30
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9001

MySQL (10.1.19-MariaDB) on localhost:

port                             3306
wait_timeout                     600
interactive_timeout              28800
max_used_connections             2
datadir                          /var/lib/mysql/
socket                           /var/run/mysqld/mysqld.sock
my.cnf [PATH]                    /etc/mysql/conf.d/my.cnf

- [ ] wp --allow-root --info

PHP binary:     /usr/bin/php5.6
PHP version:    5.6.28-1+deb.sury.org~xenial+1
php.ini used:   /etc/php/5.6/cli/php.ini
WP-CLI root dir:        phar://wp-cli.phar
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 0.24.1

**Comment by ikcam** [comment]
Use `ee clean --fastcgi`

Doc: https://easyengine.io/docs/commands/clean/

**Comment by QROkes** [comment]
I know @ikcam but its a problem when you have to do that every time you change something in the admin section.

**Comment by Grexy** [comment]
you should have a line like this in you site config file.

`	#Don't cache the following URLs
	if ($request_uri ~* "/wp-admin/|/xmlrpc.php|wp-.*.php|/feed/|index.php|sitemap(_index)?.xml")
	{
		set $no_cache 1;
	}`

This will tell it to not cache anything under /wp-admin.

**Comment by QROkes** [comment]
Yeah @Grexy that line is included in wpfc.conf file (easyengine) wich is called by mysite.conf. Thats why I don't understand why its this issue happening.

**Comment by QROkes** [comment]
Also, in multisite is not caching the main site, only subsites. I did a fresh install without plugins and this can be easily reproducible in addition to the admin section issue.

**Comment by QROkes** [comment]
Still happenning, but now I know its not a fast_cgi issue. It's only happening when EasyEngine Fast_Cgi site uses redis plugin for object cache, then redis is caching some admin options, if I deactivate redis OR fast_cgi, everything works normal as expected. Seems like a fast_cgi and redis plugin compatibility issue.

**Comment by QROkes** [comment]
At the end it was just an nginx conf issue causin fastcgi bypass not working.
wpfc.conf should be first always.

**Incorrect:**
    include /var/www/qrokes.com/conf/nginx/*.conf;
    include common/wpfc.conf;
    include common/wpsubdir.conf;
    include common/wpcommon.conf;
    include common/locations.conf;

**Correct:**
    include common/wpfc.conf;
    include /var/www/qrokes.com/conf/nginx/*.conf;
    include common/wpsubdir.conf;
    include common/wpcommon.conf;
    include common/locations.conf;
