### ISSUE TITLE
How to make EE work with Ubuntu 16.10?

### ISSUE THREAD

**Issue by TopologyApplied** [EasyEngine/easyengine#800]
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.10
Release:	16.10
Codename:	yakkety

Ubuntu 16.10 (GNU/Linux 4.8.0-26-generic x86_64)

sudo bash ee 
[sudo] password for user: 
Executing apt-get update, please wait...
**EasyEngine (ee) only support Ubuntu 12.04/14.04 and Debian 7.x/8.x**

Since EE supports Ubuntu 16.04, I thought it should work with 16.10 as well.

Any fix to install EE on Ubuntu 16.10?

**Comment by miloszorica** [comment]
you can circumvent this by disabling OS version check in the ee file itself by removing this part

if [ "$ee_linux_distro" != "Ubuntu" ] && [ "$ee_linux_distro" != "Debian" ]; then
    ee_lib_echo_fail "EasyEngine (ee) is made for Ubuntu and Debian only as of now"
    ee_lib_echo_fail "You are free to fork EasyEngine (ee): https://github.com/rtCamp/easyengine/fork"
    ee_lib_echo_fail "EasyEngine (ee) only support Ubuntu 12.04/14.04 and Debian 7.x/8.x"
    exit 100
fi

not sure if it will work and will it crash something, but you can still try

**Comment by andrew40** [comment]
did this work?

**Comment by mbtamuli** [comment]
In the [installer script](http://rt.cx/ee),

You can simply modify these lines and add _16.10_,

```
lsb_release -d | egrep -e "12.04|14.04|16.04|16.10|wheezy|jessie" &>> /dev/null
if [ "$?" -ne "0" ]; then
    ee_lib_echo_fail "EasyEngine (ee) only support Ubuntu 12.04/14.04 and Debian 7.x/8.x"
    exit 100
fi
```
But EE is only supported for LTS releases and YMMV. Closing this issue for now. You may continue the discussion.

**Comment by andrew40** [comment]
Sounds like a plan but not sure how you would do this from the standard install procedure listed in the docs, as your pulling the package using wget which obviously fires up the installation script?

**Comment by bnap00** [comment]
@andrew40 if you tinker a little, you'll find out that those are two different commands, one being wget and another being  running that file.
So you can do a `wget -qO ee rt.cx/ee`, then edit the `ee` file in your favorite editor and then use `sudo bash ee`

**Comment by andrew40** [comment]
It seems to work with a few caveats and fails but recovered - doing some testing now..

`Executing apt-get update, please wait...
Creating EasyEngine log directory, please wait...
E: Package 'python3-setuptools' has no installation candidate
E: Package 'python3-dev' has no installation candidate
E: Unable to locate package sqlite3
E: Package 'python-software-properties' has no installation candidate
Reading package lists...
Building dependency tree...
Reading state information...
Package python3-setuptools is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package python3-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package python-software-properties is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  software-properties-common

[ Wed  1 Feb 11:21:36 GMT 2017 ] Unable to install pre depedencies, exit status  1
Cloning EasyEngine, please wait...
Installing EasyEngine, please wait...
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from setuptools import setup, find_packages
ImportError: No module named 'setuptools'
[ Wed  1 Feb 11:22:04 GMT 2017 ] Unable to install EasyEngine, exit status  1
chown: cannot access '/var/lib/ee/': No such file or directory
chmod: cannot access '/var/lib/ee/': No such file or directory
ee: line 717: cd: /etc/ee: No such file or directory
ee: line 795: ee: command not found

For EasyEngine (ee) auto completion, run the following command

source /etc/bash_completion.d/ee_auto.rc

EasyEngine (ee) installed/updated successfully
EasyEngine (ee) help: http://docs.rtcamp.com/easyengine/`

**Comment by bnap00** [comment]
@andrew40 just install those packages manually and rerun the installation command.

**Comment by andrew40** [comment]
nah doesnt work either. Only installed 16.10 on an old mac server so going to roll back to 16.04, just so I can use its simplicity.

Too many missing packages and changed references to some of the python packages. Will look in more detail when i have a bit more time, but am assuming this will be on the roadmap?
