### ISSUE TITLE
Nginx stopped writing any entries of type “error” to error_log directives

### ISSUE THREAD

**Issue by s-a-s-k-i-a** [EasyEngine/easyengine#801]
After I used tail /myerrorloglocation-path as root user in console, my nginx error_log stopped logging events of type error. Events of type "warn", "debug", etc are still listed, when I change loglevel in server block.

But I would like to get my error type log back :(

any suggestions?

nginx -t returns no issues.

thanks

- [ ] lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty

- [ ] ee -v
EasyEngine v3.7.4
Copyright (c) 2016 rtCamp Solutions Pvt. Ltd.

- [ ] ee info
NGINX (1.10.0):

user                             www-data
worker_processes                 8
worker_connections               4096
keepalive_timeout                30
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1 

PHP (5.6.23-2):

user                             
expose_php                       Off
memory_limit                     128M
post_max_size                    1G
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  500
pm.max_children                  100
pm.start_servers                 20
pm.min_spare_servers             10
pm.max_spare_servers             30
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           127.0.0.1:9000

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  500
pm.max_children                  100
pm.start_servers                 20
pm.min_spare_servers             10
pm.max_spare_servers             30
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9001

MySQL (10.0.25-MariaDB) on localhost:

port                             3306
wait_timeout                     600
interactive_timeout              28800
max_used_connections             15
datadir                          /var/lib/mysql/
socket                           /var/run/mysqld/mysqld.sock

- [ ] wp --allow-root --info
PHP binary:	/usr/bin/php7.0
PHP version:	7.0.11-1+deb.sury.org~trusty+1
php.ini used:	/etc/php/7.0/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI packages dir:	
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	0.24.1

**Comment by s-a-s-k-i-a** [comment]
it miraculuosly started working again without any changes I could recall making

**Comment by iam404** [comment]
@s-a-s-k-i-a try restarting nginx service if you face this again. Issue could be due to logrotater not creating error.log file
