### ISSUE TITLE
Main Site with Subdomain Sites all with --wpredis Redis Shows Home Page of Another Site

### ISSUE THREAD

**Issue by yyhmsg** [EasyEngine/easyengine#802]
I believe I've found a bug but it's a little hard to explain.  My fix, however, works which more or less verifies this is a bug.

Create a new subdomain site like:
ee site create bob.mainsite.com --wpredis

That works fine.

Then create the main (www) site like:
ee site create mainsite.com --wpredis

After (at least in my couple tests) when you are viewing the sites without bypassing the cache (i.e. you are not logged in as admin, etc.) when you go to the homepage of mainsite.com you will see the homepage of bob.mainsite.com instead.  But bob.mainsite.com will show the correct page and all other pages on both sites unless they have the same url are correct.

after looking through every file, I narrowed it down to this:

ee creates the following in each wp-config.php file

define( 'WP_CACHE_KEY_SALT', 'bob.mainsite.com:' );
define( 'WP_CACHE_KEY_SALT', 'mainsite.com:' );

Somehow REDIS or some other NGINX setting doesn't read this correctly, mixing pages in the cache.

If you change it to:
define( 'WP_CACHE_KEY_SALT', 'bobmain:' );
define( 'WP_CACHE_KEY_SALT', 'frontmain:' );

Or anything that's different everything works fine.

That's lengthy and I apologize for that, but this seems like a bug.  Either EE should create a random cache key or whatever it is in redis that doesn't see past x characters or whatever it is doing should be looked at.

**Comment by rahul286** [comment]
Sorry for a delayed reply. The EE default key should have been working correctly. If you are still facing the issue, please use http://community.rtcamp.com/c/easyengine for further support.

We are cleaning up issue tracker and closing this issue because we won't be able to contribute to this discussion further.
