### ISSUE TITLE
wp multisite letsencrypt domain alias

### ISSUE THREAD

**Issue by nordurljosahvida** [EasyEngine/easyengine#803]
When running wp multisite with letsencrypt there's no way [that I've found] to have le add alias domains to the cert registration. I've found this [unofficial solution](http://community.rtcamp.com/t/how-to-add-a-subdomain-or-mapped-domain-to-a-ms-installation-secured-with-lets-encrypt/7082) [only one around - how can this be?]. It'd be nice to have a way to specify alias domain upon `ee site create` or to be able to add them with `ee site update`. Forgive me if this has already been mentioned before but I haven't found anything related.

Thank you

––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––

Version info:

Description:    Ubuntu 16.04.1 LTS

––––––––––––––––

EasyEngine v3.7.4

––––––––––––––––

NGINX (1.10.0):

user                             www-data
worker_processes                 auto
worker_connections               4096
keepalive_timeout                30
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1 

PHP (5.6.28-1):

user                             
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  500
pm.max_children                  100
pm.start_servers                 20
pm.min_spare_servers             10
pm.max_spare_servers             30
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           127.0.0.1:9000

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  500
pm.max_children                  100
pm.start_servers                 20
pm.min_spare_servers             10
pm.max_spare_servers             30
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9001

MySQL (10.1.19-MariaDB) on localhost:

port                             3306
wait_timeout                     600
interactive_timeout              28800
max_used_connections             3
datadir                          /var/lib/mysql/
socket                           /var/run/mysqld/mysqld.sock
my.cnf [PATH]                    /etc/mysql/conf.d/my.cnf

––––––––––––––––

PHP binary:     /usr/bin/php5.6
PHP version:    5.6.28-1+deb.sury.org~xenial+1
php.ini used:   /etc/php/5.6/cli/php.ini
WP-CLI root dir:        phar://wp-cli.phar
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 0.24.1

**Comment by NicoJuicy** [comment]
Having the same issue. Only it's not really a multisite, but a site translated with WPML.
WPML supports multiple domains ( one per language) and currently this can't be integrated into easyengine.

I manually configured nginx to support the other domain.

Perhaps something like

    ee site update originalsite.nl --alias myrandomsite.fr

This changes nginx. But when executing 

    ee site update originalsite.nl --letsencrypt

It also sets a SSL certificate for the alias.

**Comment by dtbaker** [comment]
Just running into this as well.

I need a way to easily add new aliases to an existing site and have those new alises covered with letsencrypt.

Right now I'm going down the path of sharing htdocs between multiple sites intead of using alises, but would be nice to keep them all together.

**Comment by rahul286** [comment]
We are handling this in a better way in v4.

You may check this PR #1005

Please use http://community.rtcamp.com/c/easyengine for future support questions.

**Comment by puccaso** [comment]
hello folks, 

im using the digitialocean dns api from acme.sh. 

ok so this is my current set up, 

a.com >wp main site
b.a.com > wp subdom site

i have a wildcard ssl setup for a.com and *.a.com

then, i forward
b.com to b.a.com

i have tried both domain aliasing and challenging a second domain in acme.sh settings, but i just cannot get
ssl validation to work correctly

if you goto 
b.a.com no SSL errors

if you goto b.com (which fowards to b.a.com)
i get a domain mismatch error, 
or when i goto the cert info in url of a browser, i only see *.a.com and a.com as valid domains.

how do i make a cert for b.com also - and have that picked up when you goto the b.a.com wordpress multipress subdomain site. 



any ideas?
