### ISSUE TITLE
Is it possible to deploy with ftp too? Is running a command making ftp user too for each website?

### ISSUE THREAD

**Issue by kangarooo** [EasyEngine/easyengine#805]
Is it possible to deploy with ftp too? Is running a command making ftp user too for each website?

**Comment by w33zy** [comment]
The installation file is a bash script so it needs access to a bash terminal, so it won't work via FTP. It doesn't create a FTP user.

Also, this is a support question, not an issue with EE. Please close this issue and move your question to [http://community.rtcamp.com/c/easyengine](http://community.rtcamp.com/c/easyengine)
