### ISSUE TITLE
EasyEngine install is not working

### ISSUE THREAD

**Issue by alexcbz** [EasyEngine/easyengine#807]
I'm trying to run `wget -qO ee rt.cx/ee && sudo bash ee` but nothing happens and when I run the `ee` command I get `ee: command not found`.

When you are going to the URL [rt.cx/ee](http://rt.cx/ee) you'll see a fatal error: "Incorrect DB config, or could not connect to DB".

I'm using Ubuntu 16.04 on DigitalOcean.

**Comment by geckoseo** [comment]
I have also experienced this. It makes no difference what OS is running, or the location. Something has changed between last night and now that broke the connection. 

Not sure if this is related:

wget -O ee rt.cx/ee && suso bash ee
--2016-12-10 18:25:12-- http://rt.cx/ee
Resolving rt.cx (rt.cx)... 138.201.89.76
Connecting to rt.cx (rt.cx)|138.201.89.76|:80... connected.
HTTP request sent, awaiting response... 503 Service Unavailable
2016-12-10 18:25:12 ERROR 503: Service Unavailable.

**Comment by iam404** [comment]
@alexcbz @geckoseo 

For quick solution try below

```wget -qO ee https://raw.githubusercontent.com/EasyEngine/easyengine/master/install && sudo bash ee```

**Comment by geckoseo** [comment]
works
