### ISSUE TITLE
UI / admin panel

### ISSUE THREAD

**Issue by miloszorica** [EasyEngine/easyengine#808]
any plans for adding at least a basic and optional admin panel in foreseeable future?

**Comment by brightidea** [comment]
Based on recent blog posts by the developers V4 will have a restful api included and will be based on wp-cli. This will empower not only the team behind easyengine to create their own hosting dashboard for their hosted version of easy engine but also allow other hosting companies and developers to build their own dashboard / control panels based on this api.

**Comment by miloszorica** [comment]
thanks!

**Comment by rahul286** [comment]
@brightidea Thanks for adding to it.

EE v4 has some admin-tools but no web interface.
