### ISSUE TITLE
ip:22222/phpmyadmin not working

### ISSUE THREAD

**Issue by kangarooo** [EasyEngine/easyengine#810]
First time trying and setting up first all tools, no domain yet.
Did sudo ee stack install --all
ip:22222/phpmyadmin not working

accidentally found it in ip:22222/db/pma/index.php
Also not root or 2nd user i created in sudoers list doesnt log in.
#1045 - Access denied for user 'root'@'localhost' (using password: YES)
mysqli_real_connect(): (HY000/1045): Access denied for user 'root'@'localhost' (using password: YES)

#1045 - Access denied for user '2nduser'@'localhost' (using password: YES)
mysqli_real_connect(): (HY000/1045): Access denied for user '2nduser'@'localhost' (using password: YES)

Also i had saved some credentials when doing sudo ee stack install --all and they also dont work
#1045 - Access denied for user 'easyengine'@'localhost' (using password: YES)
mysqli_real_connect(): (HY000/1045): Access denied for user 'easyengine'@'localhost' (using password: YES)

At one point i did also
sudo ee stack install --admin
and
sudo ee stack install --phpmyadmin

they said that phpmyadmin already installed

- [ ] lsb_release -a

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial

- [ ] ee -v

EasyEngine v3.7.4
Copyright (c) 2016 rtCamp Solutions Pvt. Ltd.

- [ ] ee info

NGINX (1.10.0):

user                             www-data
worker_processes                 auto
worker_connections               4096
keepalive_timeout                30
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1

PHP (5.6.29-1):

user
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  500
pm.max_children                  100
pm.start_servers                 20
pm.min_spare_servers             10
pm.max_spare_servers             30
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           127.0.0.1:9000

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  500
pm.max_children                  100
pm.start_servers                 20
pm.min_spare_servers             10
pm.max_spare_servers             30
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9001

MySQL (10.1.20-MariaDB) on localhost:

port                             3306
wait_timeout                     600
interactive_timeout              28800
max_used_connections             2
datadir                          /var/lib/mysql/
socket                           /var/run/mysqld/mysqld.sock
my.cnf [PATH]                    /etc/mysql/conf.d/my.cnf

- [ ] wp --allow-root --info

PHP binary:     /usr/bin/php5.6
PHP version:    5.6.29-1+deb.sury.org~xenial+1
php.ini used:   /etc/php/5.6/cli/php.ini
WP-CLI root dir:        phar://wp-cli.phar
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 0.24.1

**Comment by tuxcomputing** [comment]
Seems you are using the wrong pass to log in? Try ee site status sitename.com

**Comment by tuxcomputing** [comment]
Btw phpmyadmin is supposed to work in site.com/phpmyadmin and not ip:22222/phpmyadmin so the behaviour is expected

**Comment by openmtbmap** [comment]
Sorry to bump this one up...
It really should be possible to access it via: ip:22222/phpmyadmin - else if you enable hsts for your domain you cannot pass!
Even worse the default configuration of easyengine will not let you access your own instance of phpmyadmin in website root..... So essentially it's impossible to get to any admin tools if hsts is enabled.

e.g. Chrome throws you a:
DOMAIN.COM normally uses encryption to protect your information. When Google Chrome tried to connect to DOMAIN.COM this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be DOMAIN.COM, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Google Chrome stopped the connection before any data was exchanged.

You cannot visit DOMAIN.com right now because the website uses HSTS. Network errors and attacks are usually temporary, so this page will probably work later. Learn more.

**Comment by mbtamuli** [comment]
We're taking a different approach in EasyEngine v4 and this issue will hopefully not persist. If it does, we'll tackle it in a new issue.

Closing this issue.
