### ISSUE TITLE
ChRoot with /var/www/site.com/htdocs

### ISSUE THREAD

**Issue by sagargulati** [EasyEngine/easyengine#811]
`- [Description:    Ubuntu 16.04.1 LTS ] lsb_release -a`
`- [EasyEngine v3.7.4 ] ee -v`
- [ ] ee info

```
NGINX (1.10.0):

user                             www-data
worker_processes                 auto
worker_connections               4096
keepalive_timeout                30
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1

PHP (5.6.29-1):

user
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  500
pm.max_children                  100
pm.start_servers                 20
pm.min_spare_servers             10
pm.max_spare_servers             30
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           127.0.0.1:9000

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  500
pm.max_children                  100
pm.start_servers                 20
pm.min_spare_servers             10
pm.max_spare_servers             30
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9001

MySQL (10.1.20-MariaDB) on localhost:

port                             3306
wait_timeout                     600
interactive_timeout              28800
max_used_connections             53
datadir                          /var/lib/mysql/
socket                           /var/run/mysqld/mysqld.sock
my.cnf [PATH]                    /etc/mysql/conf.d/my.cnf

```
- [  ] wp --allow-root --info

Greetings,
Scenario: user1 | Group: www-data | Site: site.com
We tried to do this [https://github.com/EasyEngine/easyengine/wiki/SFTP-chroot#setup-usergroup](https://github.com/EasyEngine/easyengine/wiki/SFTP-chroot#setup-usergroup) on an `/var/www/site.com/htdocs`. It works fine and now `user1` have access on it. All the files have permissions like user1:www-data where we mount `/var/www/site.com` to `/home/user1/public_html`

So the issue arises on wordpress side where it asks for FTP details to install theme or plugin etc.
If we do `chown -R www-data:www-data on /home/user1/public_html`, it doesn't then let user1 to edit files via SFTP/FTP.

Please help!

Thanks!

**Comment by rahul286** [comment]
@sagargulati 

Sorry for a delayed reply. The EE doesn't support shared-hosting model. So all sites are supposedly owned by same user www-data.

We are cleaning up issue tracker and closing this issue because we won't be able to contribute to this discussion further.

Please use http://community.rtcamp.com/c/easyengine for future support questions.

**Comment by sagargulati** [comment]
Any new feature update or roadmap we could expect more into this?

**Comment by rahul286** [comment]
@sagargulati currently we are not thinking about it. But docker/containers are already chrooted. So there is automatic isolation between two different sites. 

The only thing we may need to work on is figuring our host filesystem layout and ACL for multiple users over SFTP or SSH or both. 

One more straightforward way is to give each real user a Linux user account and allow ee to run without sudo/root access for site creation. This way every user can create sites under their Linux home dir.

Another way is to put all sites in the single location such as `/var/www/` (like now) and then use an SFTP software to map virtual users to site for read/write access. 

Also in both cases, we may need to do some work to tweak file system permission between host OS and guest (docker).

Concerning coding, this shouldn't take more than two weeks to code. But we do not need shared hosting ourselves so we won't be able to give time to research on this. Any haphazard implement can result in security nightmare!

**Comment by sagargulati** [comment]
Rather than docker, any direct releases with these features we could expect?

**Comment by rahul286** [comment]
@sagargulati I am not sure what do you mean by a direct release. We have very limited resources so can only work Docker-based v4 at the moment. Nothing else.

**Comment by sagargulati** [comment]
I mean feature requests like installing WordPress in sub-folders over a domain.

Thanks!

**Comment by rahul286** [comment]
@sagargulati `WordPress in sub-folders` would be an entirely different topic.

**Comment by sagargulati** [comment]
CHroot in a subfolder I mean.
The basic thing want exactly I want to ask here is there any way we could merge up EasyEngine functions and use it in a way of shared hosting like I mentioned.
