### ISSUE TITLE
PHP 7.1

### ISSUE THREAD

**Issue by benzon** [EasyEngine/easyengine#812]
Is there any plan for integrating PHP 7.1 in to the EasyEngine release?

It would be nice to be able to switch between PHP 5.6, PHP 7 and 7.1

**Comment by MattyLB** [comment]
+1

**Comment by tutv95** [comment]
👍

**Comment by agengdp** [comment]
Yeah, I really need this. 👍

**Comment by techjewel** [comment]
+1

**Comment by MattyLB** [comment]
At this point in the game, PHP 7.2 is released and it fixes too many issues that 7.1 had that we should refocus our efforts on the latest release to keep EE relevant today and months ahead. We would be stepping back while stepping forward to simply update EE to 7.1.

Thoughts?

**Comment by robwilde** [comment]
I don't know anything about Python but I am tempted to learn at this point just so I can update the current EasyEngine distribution. Not only adding in more options for PHP, up to 7.2 but also updating the NGINX version as well. Adding in an option for Laravel would be awesome also. Then there are the minor things like removing warnings and notices for PHP 7 and letsencrypt.
I have played with so many devtools, Docker, Vagrant, Wamp, FlyWheel local and recently runcloud. Some of them are OK but none are as simple and fast as EE.

**Comment by rahul286** [comment]
In v4, site create and update command will have the option to accept/switch PHP version as a command parameter. Something like `--php=7.1` and  `--php=5.6` etc.
