### ISSUE TITLE
Automatically restart php-fpm if it goes down

### ISSUE THREAD

**Issue by khromov** [EasyEngine/easyengine#827]
I had an out-of-memory error on one of my servers today. Most services came back up again thanks to `systemd` but not `php5.6-fpm` and `php7.0-fpm`, which cause sites to be unavailable. with a 502 gateway error message from Nginx. Can we add the `Restart=always` directive under `[Service]` to the files:

`/etc/systemd/system/multi-user.target.wants/php5.6-fpm.service`
`/etc/systemd/system/multi-user.target.wants/php7.0-fpm.service`

That will automatically restart them if they go down, regardless of reason.

**Comment by iam404** [comment]
Not related to EE.
Since EE is using 3rd party PHP build ( http://ppa.launchpad.net/ondrej/php/ubuntu ) and not its own. 
But you can create a issue here https://github.com/oerdnj/deb.sury.org .

**Comment by khromov** [comment]
Thanks @iam404 

Will ask over in that repo.
