### ISSUE TITLE
CloudFlare Origin CA SSL Certificate + EasyEngine [Feature Request]

### ISSUE THREAD

**Issue by vivienney** [EasyEngine/easyengine#833]
CloudFlare offers free SSL certificate which can be generated and revoked through [CloudFlare API](https://api.cloudflare.com/#cloudflare-ca-create-certificate). SSL certificates from CloudFlare are valid up to 15 years. While I appreciate Let's Encrypt support in EasyEngine, it doesn't play well with CloudFlare CDN which many use along with CloudFlare DNS. An alternative, like the one from CloudFlare Origin CA, may be valuable. The feature is in step with some of @rahul286's views expressed at #509.

Feedback would be appreciated.

**Comment by rahul286** [comment]
@vivienney EE v4 will have better handling of Let's Encrypt certificates. So this is something we won't be able to work on.

If you can provide more details about issues you face with Let's Encrypt certs and CloudFlare CDN we can re-look into this.
