### ISSUE TITLE
We need an update of phpmyadmin

### ISSUE THREAD

**Issue by benzon** [EasyEngine/easyengine#835]
The current version of EasyEngine still sends out a broke version of PhpMyAdmin where  ENUM dont work, could you please fix this and send out a version with an updated PhpMyAdmin.

I know you are working on the next big release, but you cant just forget the old one ppl stil use.

**Comment by mbtamuli** [comment]
We're installing latest [stable PHPMyAdmin](https://github.com/EasyEngine/easyengine/blob/master/ee/cli/plugins/stack.py#L2305) on fresh installation. The update command doesn't handle update for the admin tools. We're handling this in a different way in EasyEngine v4.

If you can send a PR fixing this issue, we'll surely merge it to EasyEngine v3. If you need help with the PR, feel free to reopen the issue.
