### ISSUE TITLE
Add support for multiple domains on one Account (Multisite)

### ISSUE THREAD

**Issue by Helmi** [EasyEngine/easyengine#837]
Hey,

to be able to easily run Multisite installations with Domain mapping it would be great to have the option to easily add multiple domains to one vhost (including letsencrypt support).

It would be great if this could be added as a feature to v4.

Thanks

**Comment by s-a-s-k-i-a** [comment]
same as https://github.com/EasyEngine/easyengine/issues/847

**Comment by RavanH** [comment]
yes it would be great :)

**Comment by rahul286** [comment]
We are handling this in a better way in v4.

You may check this PR #1005

Please use http://community.rtcamp.com/c/easyengine for future support questions.
