### ISSUE TITLE
ee fails ungracefully when it cannot read user name or email

### ISSUE THREAD

**Issue by noogeu** [EasyEngine/easyengine#841]
When ee cannot read users name or email then it fails to install.
At  that point pressing either control-C or control-D is pressed causes inelegant aborts.
Sometimes one only wishes to run a local test install without giving input.
This should be possible.

# lsb_release -a : 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

# ee -v : 
EasyEngine v3.7.4
Copyright (c) 2016 rtCamp Solutions Pvt. Ltd.

# ee info : 
grep: /etc/nginx/common/acl.conf: No such file or directory

NGINX (1.10.0):

user                             www-data
worker_processes                 auto
worker_connections               4096
keepalive_timeout                30
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            
'ascii' codec can't decode byte 0xc2 in position 926: ordinal not in range(128)

# wp --allow-root --info : 
PHP binary:	/usr/bin/php5.6
PHP version:	5.6.30-1+deb.sury.org~xenial+1
php.ini used:	/etc/php/5.6/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI packages dir:	
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	0.24.1

**Comment by rahul286** [comment]
Sorry for a delayed reply. If you still have this issue, please use http://community.rtcamp.com/c/easyengine for further support.
