### ISSUE TITLE
ee fails to create a new site with --wpfc

### ISSUE THREAD

**Issue by noogeu** [EasyEngine/easyengine#842]
ee fails to create a new wp site with:
ee site create localhost --wpfc
it reports the following:

# ee site create localhost --wpfc
Running pre-update checks, please wait...
Setting up NGINX configuration 	[Done]
Setting up webroot 		[Done]
Downloading WordPress 		[Done]
Setting up database		[Done]
Installing plugin nginx-helper, please wait...
Setting plugin nginx-helper, please wait...
Installing plugin w3-total-cache, please wait...
Reload : nginx     [Failed]
Oops Something went wrong !!
Calling cleanup actions ...
Reload : nginx     [OK]
service nginx reload failed. check issues with `nginx -t` command.
Check logs for reason `tail /var/log/ee/ee.log` & Try Again!!!

However, nginx says it is fine:
# nginx -t ; echo $?
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
0

So why should ee complain?
It appears there is a problem with nginx pid file:

# systemctl status -l nginx.service | cat
â nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2017-02-21 14:00:10 CET; 38min ago
  Process: 1181 ExecReload=/usr/sbin/nginx -g daemon on; master_process on; -s reload (code=exited, status=0/SUCCESS)
  Process: 587 ExecStart=/usr/sbin/nginx -g daemon on; master_process on; (code=exited, status=0/SUCCESS)
  Process: 557 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=0/SUCCESS)
 Main PID: 598 (nginx)
   CGroup: /system.slice/nginx.service
           ââ 598 nginx: master process /usr/sbin/nginx -g daemon on; master_process on
           ââ1183 nginx: worker process                           

Feb 21 14:00:10 ubu1 systemd[1]: Starting A high performance web server and a reverse proxy server...
Feb 21 14:00:10 ubu1 systemd[1]: nginx.service: Failed to read PID from file /run/nginx.pid: Invalid argument
Feb 21 14:00:10 ubu1 systemd[1]: Started A high performance web server and a reverse proxy server.
Feb 21 14:02:03 ubu1 systemd[1]: Reloading A high performance web server and a reverse proxy server.
Feb 21 14:02:03 ubu1 systemd[1]: Reloaded A high performance web server and a reverse proxy server.
Feb 21 14:21:51 ubu1 systemd[1]: Reloading A high performance web server and a reverse proxy server.
Feb 21 14:21:51 ubu1 systemd[1]: Reloaded A high performance web server and a reverse proxy server.

However, /run/nginx.pid is OK:

# cat /run/nginx.pid
598

So what is the problem??

# lsb_release -a : 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

# ee -v : 
EasyEngine v3.7.4
Copyright (c) 2016 rtCamp Solutions Pvt. Ltd.

# ee info : 
grep: /etc/nginx/common/acl.conf: No such file or directory

NGINX (1.10.0):

user                             www-data
worker_processes                 auto
worker_connections               4096
keepalive_timeout                30
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            
'ascii' codec can't decode byte 0xc2 in position 926: ordinal not in range(128)

# wp --allow-root --info : 
PHP binary:	/usr/bin/php5.6
PHP version:	5.6.30-1+deb.sury.org~xenial+1
php.ini used:	/etc/php/5.6/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI packages dir:	
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	0.24.1

**Comment by noogeu** [comment]
Found a relevant error in the log:

(DEBUG) ee : nginx: [emerg] open() "/etc/nginx/common/wpfc.conf" failed (2: No such file or directory) in /etc/nginx/sites-enabled/localhost:19
nginx: configuration file /etc/nginx/nginx.conf test failed

Directory /etc/nginx/common is totally missing!

**Comment by manojchandrashekar** [comment]
Try this:

`sudo ee stack remove --nginx`
`sudo ee stack remove --php`

Then:

`sudo fuser -k 80/tcp`
`sudo fuser -k 443/tcp`

`sudo nginx -t`
`sudo service nginx restart`

Then, run your `ee site create ...` command again.

**Comment by rahul286** [comment]
@noogeu Sorry for a delayed reply. I hope your issue is fixed by now with @manojchandrashekar answer.

If you are still facing the issue, please use http://community.rtcamp.com/c/easyengine for further support.

We are cleaning up issue tracker and closing this issue because we won't be able to contribute to this discussion further.
