### ISSUE TITLE
Bug/Improvement/Feature: Multisite multi domain mapping - wp and nginx config

### ISSUE THREAD

**Issue by s-a-s-k-i-a** [EasyEngine/easyengine#847]
As reported in community forum in this thread:
http://community.rtcamp.com/t/multisite-setup-with-domain-mapping-ssl-etc/8402

This needs improvement and testing.

Pls note that it is not necessary to install the Domain Mapping plugin to get domain mapping to work. Everything could be handled via ee. 
An add new site ee command within the multisite network is missing.
An ee update site for sites within multisite network is missing.
A letsencrypt routine and nginx ssl configuration for domains within multisite network is missing.
Letsencrypt is capable of handling multi domain certs. ee's le script is not covering this -> needs improvement or different approach when handling multi domains within mu network.
Same goes for multisite with subdomain setup.

Pls spare some time and give multisite setup some love.

**Comment by s-a-s-k-i-a** [comment]
There also seems to be a caching issue when using multiple domains. I am seeing my error log filled with these warnings caused by nginx helper plugin:

2017/04/04 09:45:38 [error] 1771#0: *193981 FastCGI sent in stderr: "PHP message: PHP Warning:  Redis::connect(): connect() failed: Connection refused in /var/www/mydomain.de/htdocs/wp-content/plugins/nginx-helper/includes/redis-delete.php on line 15" while reading response header from upstream, client: 66.249.76.56, server: erlebniskochen.de, request: "GET /firmen-gruppen/weihnachtsfeiern/ HTTP/1.1", upstream: "fastcgi://127.0.0.1:9070", host: "www.mydomain.de"

**Comment by RavanH** [comment]
+1 for this request

it even sais "uncomment this line for domain mapping" in each site conf file but whenever that site gets updated (for whatever other reason outside this issue) by ee, added domaines (and other mods) are removed... 

only solution is to not use ee commands anymore for a site once it has passed to map multiple domains.
annoying, to say the least :(

**Comment by s-a-s-k-i-a** [comment]
Since Lets Encrypt added the option to issue wildcard certs, ee should really update their letsencrypt client script, so we can cover multisite environments in a more convenient way.

**Comment by rahul286** [comment]
We will be adding wildcard support in v4.

You may check this PR #1005

Please use http://community.rtcamp.com/c/easyengine for future support questions.
