### ISSUE TITLE
Let's encrypt is no longer in beta (as of 1yr ago)

### ISSUE THREAD

**Issue by mrphs** [EasyEngine/easyengine#848]
When trying to create a new site using `--letsencrypt` flag, I get a warning that says:

```
Letsencrypt is currently in beta phase. 
Do you wish to enable SSl now for taa20.com?
Type "y" to continue [n]:
```
This statement is false as Let's Encrypt has [left beta](https://letsencrypt.org/2016/04/12/leaving-beta-new-sponsors.html) about a year ago. This might discourage users from deciding to proceed with installing HTTPS on their website

- [x] ee -v
```
EasyEngine v3.7.4
```

**Comment by rahul286** [comment]
We have handled this in a better way in v4.

You may check this PR #1005

Please use http://community.rtcamp.com/c/easyengine for future support questions.
