### ISSUE TITLE
Build phar package for v4

### ISSUE THREAD

**Issue by rahul286** [EasyEngine/easyengine#857]
Box - https://github.com/box-project/box2

Automation - https://mwop.net/blog/2015-12-14-secure-phar-automation.html

**Comment by rahul286** [comment]
https://github.com/MacFJA/PharBuilder

**Comment by mrrobot47** [comment]
@rahul286 Currently, EasyEngine v4 is using the phar building and deploying process very similar to the wp-cli build and release process. The doc for current build and release: https://github.com/mrrobot47/easyengine/blob/feature/docs/docs/build-and-release.md
And the phar repository: https://github.com/EasyEngine/easyengine-builds/tree/master/phar
Hence, this issue can be closed.

**Comment by rahul286** [comment]
Thanks @mrrobot47 for clarification
