### ISSUE TITLE
Not able to change password when there is a space in username for v4

### ISSUE THREAD

**Issue by BhargavBhandari90** [EasyEngine/easyengine#865]
`ee site update` - command
It shows that password updated successfully but actually it is not changing .

**Comment by rahul286** [comment]
Sorry for a delayed reply. I hope your issue is fixed by now.

If you are still facing the issue, please use http://community.rtcamp.com/c/easyengine for further support.

We are cleaning up issue tracker and closing this issue because we won't be able to contribute to this discussion further.
