### ISSUE TITLE
"ee stack" with Ansible Help

### ISSUE THREAD

**Issue by rahul286** [EasyEngine/easyengine#869]
This is alternative approach to #866

Rathe than building an OS package manager wrapper in Core PHP, use ansible (or for that matter chef/puppet) wrapper in PHP and then handle stack related commands heavy-lifting in those tools.

**Concerns**

Will it be efficient and feasible to perform all tasks we need? Such as:

- [ ] Add a third-party package repo
- [ ] Install/Remove/Purge packages
- [ ] Check if a package is installed
- [ ] Get Info such as version, compile time flags, etc about a package

**References:**

1. http://phansible.com/

**Comment by mbtamuli** [comment]
I guess phansible might not meaningful here. This may be more appropriate -
 [https://github.com/maschmann/php-ansible](https://github.com/maschmann/php-ansible)

**Comment by mbtamuli** [comment]
Since we're using Docker containers, the above issue doesn't help us anymore. So closing this.
