### ISSUE TITLE
Etag and Cache-Control in WP posts and pages

### ISSUE THREAD

**Issue by QROkes** [EasyEngine/easyengine#871]
In a completely fresh installation and a WP site without caching (--wp).
I just noticed that Etag, Cache-Control, Last-Modified, Expires, none of these headers are included in the response for posts and pages (text/HTML mime type). It only works with static content (Images, CSS and JS).
I don't know if its an expected behaviour. For HTML sites (text/HTML mime type)  in EE its working, Etag and Last-Modified headers are included in the response.

**curl -I http://domain.com**
HTTP/1.1 200 OK
Server: nginx
Date: Fri, 14 Apr 2017 22:38:50 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding
Link: <http://domain.com/wp-json/>; rel="https://api.w.org/"
X-Powered-By: EasyEngine 3.7.4

**curl -I http://domain.com/wp-content/themes/twentyseventeen/assets/images/header.jpg**
HTTP/1.1 200 OK
Server: nginx
Date: Fri, 14 Apr 2017 22:39:31 GMT
Content-Type: image/jpeg
Content-Length: 114854
Last-Modified: Fri, 14 Apr 2017 22:34:19 GMT
Connection: keep-alive
ETag: "58f14e6b-1c0a6"
Expires: Thu, 31 Dec 2037 23:55:55 GMT
Cache-Control: max-age=315360000
Access-Control-Allow-Origin: *
Accept-Ranges: bytes

**curl -I http://domain.com/wp-content/themes/twentyseventeen/style.css**
HTTP/1.1 200 OK
Server: nginx
Date: Fri, 14 Apr 2017 22:40:35 GMT
Content-Type: text/css
Content-Length: 81817
Last-Modified: Fri, 14 Apr 2017 22:34:19 GMT
Connection: keep-alive
Vary: Accept-Encoding
ETag: "58f14e6b-13f99"
Expires: Thu, 31 Dec 2037 23:55:55 GMT
Cache-Control: max-age=315360000
Access-Control-Allow-Origin: *
Accept-Ranges: bytes

**curl -I http://domain.com/wp-includes/js/jquery/jquery.js**
HTTP/1.1 200 OK
Server: nginx
Date: Fri, 14 Apr 2017 22:41:19 GMT
Content-Type: application/javascript
Content-Length: 97184
Last-Modified: Fri, 14 Apr 2017 22:34:19 GMT
Connection: keep-alive
Vary: Accept-Encoding
ETag: "58f14e6b-17ba0"
Expires: Thu, 31 Dec 2037 23:55:55 GMT
Cache-Control: max-age=315360000
Access-Control-Allow-Origin: *
Accept-Ranges: bytes

**curl -I http://domain.com/2017/04/14/hello-world/**
HTTP/1.1 200 OK
Server: nginx
Date: Fri, 14 Apr 2017 22:41:43 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding
X-Pingback: http://domain.com/xmlrpc.php
Link: <http://domain.com/wp-json/>; rel="https://api.w.org/"
Link: <http://domain.com/?p=1>; rel=shortlink
X-Powered-By: EasyEngine 3.7.4

**curl -I http://htmlsite.com/**
HTTP/1.1 200 OK
Server: nginx
Date: Fri, 14 Apr 2017 22:59:35 GMT
Content-Type: text/html
Content-Length: 22162
Last-Modified: Wed, 15 Feb 2017 05:04:24 GMT
Connection: keep-alive
Vary: Accept-Encoding
ETag: "58a3e158-5692"
Accept-Ranges: bytes

Please attach the output of following command when open a new support request.

- [ ] lsb_release -a
- [ ] ee -v
- [ ] ee info
- [ ] wp --allow-root --info

**Comment by rahul286** [comment]
@QROkes  Sorry for a delayed reply. I hope your issue is fixed by now.

If you are still facing the issue, please use http://community.rtcamp.com/c/easyengine for further support. If you are need to create issue again, please include how does WordPress behave differently when using something other than EE for setup.

We are cleaning up issue tracker and closing this issue because we won't be able to contribute to this discussion further.
