### ISSUE TITLE
Move LetsEncrypt installation to apt and certificate generation with certbot

### ISSUE THREAD

**Issue by iam404** [EasyEngine/easyengine#873]
Current implementation of LE does not seems to be working well with Ubuntu 16.04.

```
Creating virtual environment...
, 
Command Error: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 2363, in <module>
    main()
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 719, in main
    symlink=options.symlink)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 988, in create_environment
    download=download,
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 918, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 812, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /root/.local/share/letsencrypt/bin/python2.7 - setuptools pkg_resources pip wheel failed with error code 1
```

Recently LE team released a PPA for installation in Ubuntu/Debian environment. 
Please refer https://certbot.eff.org/#ubuntuxenial-other

Supported issue : https://github.com/certbot/certbot/issues/4062

**Comment by iam404** [comment]
@rahul286  Let me know if PR for version EE v3 is still accepted. Would like to open a PR for above on current master branch.

**Comment by rahul286** [comment]
Feel free to send PR. We are not accepting new features in v3 but we need to maintain what is already people are using. :-)

**Comment by ahmadawais** [comment]
@iam404 were you able to provide a fix for this?

**Comment by rahul286** [comment]
Sorry for a delayed reply.

We are using https://traefik.io in v4 so (hopefully) this will be handled automatically.
