### ISSUE TITLE
Enabling ftp_connect, ftp_login, ftp_nb_fput

### ISSUE THREAD

**Issue by hsgreen92** [EasyEngine/easyengine#875]
I installed UpdraftPlus Backups plugin which offers uploading your wordpress backup to remote location via FTP. However, I am getting this when I go to FTP backup option of UpdraftPlus.

> Warning: Your web server's PHP installation has these functions disabled: ftp_connect, ftp_login, ftp_nb_fput. Your hosting company must enable these functions before regular non-encrypted FTP can work.

I used following command to install wordpress on my server.
ee site create mywebsite.com --wpfc --hhvm

How do I enable ftp_connect, ftp_login, ftp_nb_fput. I couldn't find such option in /etc/php/5.6/fpm/php.ini

------------------------------------------------------------------------------------------------------------------

root@webserver ~ # lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial
root@webserver ~ # ee -v
EasyEngine v3.7.4
Copyright (c) 2016 rtCamp Solutions Pvt. Ltd.
root@webserver ~ # ee info

NGINX (1.10.3):

user                             www-data
worker_processes                 auto
worker_connections               4096
keepalive_timeout                30
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1

PHP (5.6.30-10):

user
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  500
pm.max_children                  100
pm.start_servers                 20
pm.min_spare_servers             10
pm.max_spare_servers             30
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           127.0.0.1:9000

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  500
pm.max_children                  100
pm.start_servers                 20
pm.min_spare_servers             10
pm.max_spare_servers             30
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9001

MySQL (10.1.22-MariaDB) on localhost:

port                             3306
wait_timeout                     600
interactive_timeout              28800
max_used_connections             18
datadir                          /var/lib/mysql/
socket                           /var/run/mysqld/mysqld.sock
my.cnf [PATH]                    /etc/mysql/conf.d/my.cnf
root@webserver ~ # wp --allow-root --info
PHP binary:     /usr/bin/php5.6
PHP version:    5.6.30-10+deb.sury.org~xenial+2
php.ini used:   /etc/php/5.6/cli/php.ini
WP-CLI root dir:        phar://wp-cli.phar
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 0.24.1

**Comment by w33zy** [comment]
You created the site using HHVM instead of PHP. The ````ftp_connect, ftp_login, ftp_nb_fput```` functions are specific to PHP. 

Your options are either:

1. Switch the site to using PHP7, as HHVM is no longer necessary, as far as WP is concerned.
2. Enable ````hhvm.enable_zend_compat```` in HHVM ````server.ini```` which may resolve the problem.

This error is not related to EE.

**Comment by hsgreen92** [comment]
Thank you.
It helped. Added `hhvm.enable_zend_compat = true` into /etc/hhvm/server.ini and then restarted hhvm by `service hhvm restart`

**Comment by mbtamuli** [comment]
Feel free to comment if you need more help. Closing the issue for now.
