### ISSUE TITLE
Add zesty support

### ISSUE THREAD

**Issue by asm0dey** [EasyEngine/easyengine#876]
Please attach the output of following command when open a new support request.
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty
```

**Comment by mbtamuli** [comment]
EasyEngine supports only the LTS releases for Ubuntu.

**Comment by asm0dey** [comment]
So no way to setup all the things on modern hostings? I like zesty for newer kernel, which docker support is better… Is there I can build packages myself?

**Comment by mbtamuli** [comment]
In future, there may be a time where EE will use docker images for all required software. If that happens, we will be able to support every OS that supports docker. But for now, I am sorry to say we can't help.

Would you be interested in building and maintaining the packages for zesty?

**Comment by asm0dey** [comment]
Yes, I am interested, but I need instructions.

**Comment by mbtamuli** [comment]
Awesome. 
This is the our nginx build's repository - [Nginx-build](https://github.com/EasyEngine/nginx-build). The actual steps are mentioned in the [wiki](https://github.com/EasyEngine/nginx-build/wiki).

It would be great if you can join the [EasyEngine Slack Channel](http://slack.easyengine.io/) for further discussion.

**Comment by asm0dey** [comment]
@mbtamuli nobody answers my question in slack…

**Comment by rsmith4321** [comment]
If you don’t know what you are doing really well just stick to what is supported.  16.04 works great.

Ryan Smith
https://www.ryansmithphotography.com

**Comment by asm0dey** [comment]
@rsmith4321 well, everything is fine, but I've never deployed anything to opensuse build system, that's the only problem.

**Comment by rahul286** [comment]
Sorry for a delayed reply.  

This will be handled automatically in v4. We have no plan to work on this in v3.

**Comment by asm0dey** [comment]
@rahul286 any estimates on when will it be released?

**Comment by rahul286** [comment]
@asm0dey Sorry I cant give you a solid ETA. 

You may keep an eye on https://github.com/EasyEngine/easyengine/milestones?direction=asc&sort=title&state=open

By the way, we added Ubuntu 18.04 LTS support recently in v3 - https://easyengine.io/blog/easyengine-v3-8/
