### ISSUE TITLE
ee stack install postfix - Not Working

### ISSUE THREAD

**Issue by mwaterhouse** [EasyEngine/easyengine#879]
Just tried ee stack install postfix, but got:-

> usage: ee stack (command) [options]
> ee: error: unrecognized arguments: postfix

Using v3.7.4.

Installed postfix manually, but just in case it's useful to know.

**Comment by khairulfaizi** [comment]
It should be:
ee stack install --postfix

**Comment by mwaterhouse** [comment]
Darn - thanks, didn't spot that :-)

I guess that's a documentation bug then - most of the commands list doesn't include the hyphens.

**Comment by BoxMediaUK** [comment]
A big documentation bug, none of the commands work listed in the docs..

**Comment by bnap00** [comment]
The documentation has been fixed.

**Comment by mbtamuli** [comment]
As the documentation was fixed, closing this issue.

**Comment by rahul286** [comment]
Thanks @mwaterhouse and @BoxMediaUK for reporting the bug in the docs.
