### ISSUE TITLE
WP Install Truncates User/Password Containing $

### ISSUE THREAD

**Issue by mwaterhouse** [EasyEngine/easyengine#880]
For info:-
I did a site create (wpredis) using the --user and --pass parameters, both of which happened to include a '$' sign in them. Both were truncated at the dollar sign.

**Comment by mbtamuli** [comment]
To have special characters in the password, you need to quote them.
```--pass='my$secret&'```

Also updated the documentation. https://easyengine.io/docs/commands/site/create/
Feel free to comment if you need more help. Closing the issue for now.
