### ISSUE TITLE
letsencrypt can't access the test file - nginx conf problem?

### ISSUE THREAD

**Issue by eddr** [EasyEngine/easyengine#881]
1. latest ee version, Debian 8 (on Linode)
2. Worked well few months ago, on another Linode VPS installation
3. Can't enable letsencrypt. Even tried clean install
4. letsencrypt logs show that xxx/.well-known/acme-challenge/testfile can't be accessed, which is true
5. New VPS installation + EE installed perfectly + new site created via EE. Nothing special. WP site is accessible and running

Thanks!

**Comment by pelmered** [comment]
Same for me. When I run this the SSL Certificate generation fails:
`ee site create mydomain.com --wpfc  --letsencrypt --user=me  --email=my@email.com --php7`

When I run `/opt/letsencrypt/letsencrypt-auto certonly --webroot -w /var/www/mydomain.com/htdocs/ -d mydomain.com -d www.mydomain.com --email my@email.com --text --agree-tos` 

You get the following error:

```
   Domain: mydomain.com
   Type:   unauthorized
   Detail: Invalid response from
   http://mydomain.com/.well-known/acme-challenge/P70j2Bf1LwNB-xHOjKG9vjkAQ1PhiLChVglt0EV8wnw:
   "<html>
   <head><title>404 Not Found</title></head>
   <body bgcolor="white">
   <center><h1>404 Not Found</h1></center>
   <hr><center>"
```

My real domain is of course replaced by `mydomain.com`.

**Comment by eddr** [comment]
They confirmed (quickly replying, btw), that it is a known issue and will be addressed in the coming update
For the meanwhile
http://community.rtcamp.com/t/workaround-for-letsencrypt-error-unable-to-setup-lets-encrypt/8864

**Comment by pelmered** [comment]
Thank you @eddr! That worked great! 😁

**Comment by eddr** [comment]
Glad to hear. You might need to renew the certs yourself though (or make a cron job)

**Comment by rahul286** [comment]
This looks like a fixed one. :)

We are cleaning up issue tracker and closing this issue because we won't be able to contribute to this discussion further.

Please use http://community.rtcamp.com/c/easyengine for future support questions.
