### ISSUE TITLE
Issue when installing wordpress

### ISSUE THREAD

**Issue by jijonj** [EasyEngine/easyengine#882]
Cannot create new wordpress site, says following:
EasyEngine detected a previously installed Nginx package. It may or may not have required modules.
If you need help, please create an issue at https://github.com/EasyEngine/easyengine/issues/

INFO: EasyEngine detected a previously installed Nginx package. It may or may not have required modules.
If you need help, please create an issue at https://github.com/EasyEngine/easyengine/issues/

INFO: Restart : nginx
Restart : nginx     [OK]
INFO: [OK]
Running pre-update checks, please wait...
INFO: Running pre-update checks, please wait...
INFO: Setting up NGINX configuration
Setting up NGINX configuration  [Done]
INFO: [Done]
INFO: Setting up webroot
Setting up webroot              [Done]
INFO: [Done]
No section: 'wordpress'

Please attach the output of following command when open a new support request.

- [x] lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial

- [x] ee -v
EasyEngine v3.7.4
Copyright (c) 2016 rtCamp Solutions Pvt. Ltd.

- [x] ee info

INFO: Initializing EasyEngine Database

NGINX (1.10.3):

user                             www-data
worker_processes                 auto
worker_connections               4096
keepalive_timeout                30
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1

PHP (5.6.30-11):

user
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  500
pm.max_children                  100
pm.start_servers                 20
pm.min_spare_servers             10
pm.max_spare_servers             30
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           127.0.0.1:9000

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  500
pm.max_children                  100
pm.start_servers                 20
pm.min_spare_servers             10
pm.max_spare_servers             30
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9001

MySQL (10.1.23-MariaDB) on localhost:

port                             3306
wait_timeout                     600
interactive_timeout              28800
max_used_connections             3
datadir                          /var/lib/mysql/
socket                           /var/run/mysqld/mysqld.sock
my.cnf [PATH]                    /etc/mysql/conf.d/my.cnf

- [x] wp --allow-root --info

PHP binary:     /usr/bin/php7.1
PHP version:    7.1.5-1+deb.sury.org~xenial+2
php.ini used:   /etc/php/7.1/cli/php.ini
WP-CLI root dir:        phar://wp-cli.phar
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 0.24.1

**Comment by antopj** [comment]
@jijonj it is preferred to install EasyEngine on a fresh server or a server which don't have LEMP packages preinstalled(Nginx/Php/Mysql). The optimised configurations of Nginx/PHP generated by easyengine require additional modules. 

In your current server, you can try purging Nginx and php-fpm using 
`apt purge nginx` and `apt purge php<fpm version>` 
and try re-installing using 
`ee stack install --nginx`
and 
 `ee stack install --php7`
or just create a wordpress site.(it will install required packages)

**Comment by rahul286** [comment]
@jijonj 
Sorry for a delayed reply. I hope your issue is fixed by now with @antopj's help

If you are still facing the issue, please use http://community.rtcamp.com/c/easyengine for further support.

We are cleaning up issue tracker and closing this issue because we won't be able to contribute to this discussion further.
