### ISSUE TITLE
502 error

### ISSUE THREAD

**Issue by koonk** [EasyEngine/easyengine#887]
Please attach the output of following command when open a new support request.

- [ ] lsb_release -a

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04 LTS
Release:	14.04
Codename:	trusty

- [ ] ee -v

EasyEngine v3.7.4
Copyright (c) 2016 rtCamp Solutions Pvt. Ltd.

- [ ] ee info
NGINX (1.10.0):

user                             www-data
worker_processes                 auto
worker_connections               4096
keepalive_timeout                30
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1 

PHP (5.6.29-1):

user                             
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  500
pm.max_children                  100
pm.start_servers                 20
pm.min_spare_servers             10
pm.max_spare_servers             30
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           127.0.0.1:9000

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  500
pm.max_children                  100
pm.start_servers                 20
pm.min_spare_servers             10
pm.max_spare_servers             30
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9001
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)

MySQL (10.1.20-MariaDB) on localhost:

port                             
wait_timeout                     
interactive_timeout              
max_used_connections             
datadir                          
socket                           
my.cnf [PATH]                    /etc/mysql/conf.d/my.cnf

- [x] wp --allow-root --info

PHP binary:	/usr/bin/php5.6
PHP version:	5.6.29-1+deb.sury.org~trusty+1
php.ini used:	/etc/php/5.6/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI packages dir:	
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	0.24.1

I have been using ee for nearly 8 months now and all of a sudden today I started getting 502 gateway error, I tried rebooting quite a few times and restarted php frm, it kept going up and down.

**Comment by bnap00** [comment]
For this type of issues you can create support ticket on http://community.rtcamp.com/

**Comment by bnap00** [comment]
closing this issue as it is a community issue.
