### ISSUE TITLE
Can't install on Debian 9 "stretch" - check needs to be changed

### ISSUE THREAD

**Issue by eddr** [EasyEngine/easyengine#888]
Message "EasyEngine (ee) only support Ubuntu 12.04/14.04 and Debian 7.x/8.x"

That's from the install script in line
lsb_release -d | egrep -e "12.04|14.04|16.04|wheezy|jessie" &>> /dev/null

"|strech" should be added

**Comment by lunarthegrey** [comment]
Yes! Please support Debian Stretch.

**Comment by wnolfm** [comment]
Even adding stretch to the installer does not work. 

I get the following when trying to run ee site create 
type object 'EEVariables' has no attribute 'ee_nginx_repo'

**Comment by mbtamuli** [comment]
We'll be adding Debian 9 support soon in a future release. Closing this issue for now.
