### ISSUE TITLE
Change location of site creation

### ISSUE THREAD

**Issue by Ruriko** [EasyEngine/easyengine#890]
Is there a way to change the location of how the site is created? currently easyengine creates the site in /var/www/ I want to change the location since I'm running low on space in that location. I mounted a new drive so i want to switch site location to /data/var/www/ Is there any trick to do this?

**Comment by miloszorica** [comment]
you don't want to do that. many things can go wrong

what could get the job pain-free and risk-free is moving all of your /var/www/ data to a new volume and then either mounting it to /var/www/  or creating a symbolic link

https://askubuntu.com/questions/843740/how-to-create-a-symbolic-link-in-a-linux-directory is how linking works in a nutshell. if i were you, i'd avoid messing with EE core features and core settings

**Comment by rahul286** [comment]
Sorry for a delayed reply. I hope your issue is fixed by now.

If you are still facing the issue, please use http://community.rtcamp.com/c/easyengine for further support.

We are cleaning up issue tracker and closing this issue because we won't be able to contribute to this discussion further.
