### ISSUE TITLE
Nginx + w3tc page cache - fires php even though page is cached

### ISSUE THREAD

**Issue by eddr** [EasyEngine/easyengine#891]
EDIT:

0. When using w3tc, you should use the "Cache SSL (https) requests" option, even though it says "Cache SSL requests (**uniquely**) for improved performance.", making you think that it caches request, only not uniquely. At least in my test system, it doesn't.
Could be related to the error message that appears when enabling debug mode for w3tc page cache:
**"W3 Total Cache error: It appears Page Cache URL rewriting is not working. Please verify that all configuration files are included in the configuration file (and that you have reloaded / restarted nginx).
Unfortunately disk enhanced page caching will not function without custom rewrite rules. Please ask your server administrator for assistance. Also refer to the install page for the rules for your server.
Technical info"**

1. After your SSL runs well and w3tc configured, you need to update the appropriate conf files - "w3tc.conf" and "w3tc-php7.conf" files to reflect the fact that the cached files will now have "_ssl" suffix.

2. I guess the ee script does that automatically, but the ee LE script doesn't work lately. Perhaps it will be fixed with next versions?

----

Testing a site running on a Linode. It works well with w3tc page cache enabled:
0. Page cache is using the "Disk : Enhanced" option
1. Cached pages are created and they are ok
2. However, accessing them causes PHP7.0 processes to fire (lots of them, for high traffic)
3. Tried to access the cached html file directly - works well and doesn't fire PHP, as should be
4. Didn't change nginx conf configuration, only added ssl stuff in a different file under the /var/www/[site]/conf/nginx
Edit: 5. Tested with a clean page (literally only a div element, no php, head element or others) - again, cached html version created, but again, php7.0 processes are fired. Makes no sense

What's going on? why is the php fired up? 
Tried other sites on my linode, and it happens there too

Any clue? How can I trace the source of the problem?

Requested info below:

**- [ ] lsb_release -a**
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.8 (jessie)
Release:        8.8
Codename:       jessie

**- [ ] ee -v**
EasyEngine v3.7.4

**- [ ] ee info**

NGINX (1.10.3):

user                             www-data
worker_processes                 auto
worker_connections               4096
keepalive_timeout                30
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1

PHP (7.0.20-1~dotdeb):

user
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  500
pm.max_children                  100
pm.start_servers                 20
pm.min_spare_servers             10
pm.max_spare_servers             30
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           127.0.0.1:9000

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  500
pm.max_children                  100
pm.start_servers                 20
pm.min_spare_servers             10
pm.max_spare_servers             30
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9001

MySQL (10.1.25-MariaDB) on localhost:

port                             3306
wait_timeout                     600
interactive_timeout              28800
max_used_connections             101
datadir                          /var/lib/mysql/
socket                           /var/run/mysqld/mysqld.sock
my.cnf [PATH]                    /etc/mysql/conf.d/my.cnf

**- [ ] wp --allow-root --info**
PHP binary:     /usr/bin/php7.0
PHP version:    7.0.20-1~dotdeb+8.2
php.ini used:   /etc/php/7.0/cli/php.ini
WP-CLI root dir:        phar://wp-cli.phar
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 0.24.1

**Comment by rahul286** [comment]
@eddr w3tc has not been actively supported anymore. Can you try using `--wpredis`  cache?

https://easyengine.io/blog/easyengine-3-3-full-page-redis-cache/

**Comment by eddr** [comment]
Rahul, it's quite old. It works now with the changes I've mentioned.

Why is W3TC not supported? I don't want everything to be kept in memory, in my case

**Comment by janiosarmento** [comment]
If I may ask, please consider also supporting `--wpsc`.

**Comment by sleepycommerce** [comment]
I think the consolidation of options is a good move especially for the community to have an easier time crowd sourcing support for each other. @rahul286 what option(s) 1 or 2 are your leaning towards or decided on at the moment or will that be decided at a later date.

**Comment by rahul286** [comment]
@sleepycommerce I was planning to get a new one based on `memcache`. The idea is to use batcache https://wordpress.org/plugins/batcache/ to write to memcache and then use nginx core module to read from memcache http://nginx.org/en/docs/http/ngx_http_memcached_module.html

This way there will be no dependencies on third-party nginx modules.

Batcache is maintained by Automattic and is used on WordPress.com.

**Comment by rahul286** [comment]
To be honest - all full page caching have similar performance. I see it's binary. If Nginx can "get" a page without getting PHP & MySQL involved - it matters less nginx do it using redis, fastcgi-cache or WordPress plugins.

**Comment by eddr** [comment]
@rahul286 Thx for replying
batcache hasn't been maintained for quite some time..

And also, I still don't think that saving everything in memory is a good path. It's limited and SSDs today are relatively fast..

**Comment by sleepycommerce** [comment]
@rahul286 I think it's a desirable direction given it's scalable to distributed setups. but as @eddr mentioned it hasn't been updated for a minute on .org however The github has alot more activity which is good and as automatic relies on it for .com "supercache" it should be fairly safe to say it will be around or easier to to fork and maintain if it's the only setup.

But maybe just no cache or cache as options for those who would like to integrate their own preferences. I still would lean most on one cache setup to benefit the community support over many.

**Comment by eddr** [comment]
@sleepycommerce thanks for the heads up. From I read in their github page, it's not the same thing at all.. I was talking about object cache, **not page cache**.
