### ISSUE TITLE
Your PGP keys are expired for custom nginx build (16.04)

### ISSUE THREAD

**Issue by pySilver** [EasyEngine/easyengine#893]
This key: http://download.opensuse.org/repositories/home:/rtCamp:/EasyEngine/xUbuntu_16.04/ is reported as exired (KEYEXPIRED ERROR).

Can you do something about that?

**Comment by pySilver** [comment]
```
# admin @ in /etc/apt/sources.list.d [2:53:59] C:2
$ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 3050AC3CD2AE6F03
Executing: /tmp/tmp.fVWQMfBFnh/gpg.1.sh --keyserver
keyserver.ubuntu.com
--recv
3050AC3CD2AE6F03
gpg: requesting key D2AE6F03 from hkp server keyserver.ubuntu.com
gpg: key D2AE6F03: "home:rtCamp OBS Project <home:rtCamp@build.opensuse.org>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1

# admin @ in /etc/apt/sources.list.d [2:55:06]
$ sudo apt-key list | grep "expired:"
pub   2048R/D2AE6F03 2015-05-24 [expired: 2017-08-01]
```

**Comment by tzitzigr** [comment]
@rahul286 your help would be appreciated here. PGP keys need to be updated in the repo.

**Comment by mbtamuli** [comment]
The expiry date for the key has been extended. You can update it on existing installations using
```
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 3050AC3CD2AE6F03
```
Users installing EasyEngine on a new VM will not have to do anything extra. The updated key will automatically be used.

Closing this issue for now. Feel free to continue discussion if any issue persists.

**Comment by tommyent** [comment]
Port is open but it's not making a connection

prod:~# sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 3050AC3CD2AE6F03
Executing: /tmp/tmp.Zhcu3d4fLp/gpg.1.sh --keyserver
keyserver.ubuntu.com
--recv
3050AC3CD2AE6F03
gpg: requesting key D2AE6F03 from hkp server keyserver.ubuntu.com
?: keyserver.ubuntu.com: Connection refused
gpgkeys: HTTP fetch error 7: couldn't connect: Connection refused
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver communications error: keyserver unreachable
gpg: keyserver communications error: public key not found
gpg: keyserver receive failed: public key not found

**Comment by pySilver** [comment]
@tommyent what does it has to do with this repo?

**Comment by tommyent** [comment]
Expired PGP 
 http://download.opensuse.org/repositories/home:/rtCamp:/EasyEngine/xUbuntu_16.04  Release.gpg
Mine seems to be port related since I was able to get around this by using port 80

**Comment by joglomedia** [comment]
Hello, there is new issue related your nginx repository

W: The repository 'http://download.opensuse.org/repositories/home:/rtCamp:/EasyEngine/xUbuntu_16.04  Release' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://download.opensuse.org/repositories/home:/rtCamp:/EasyEngine/xUbuntu_16.04/Release.gpg  Bad header line Bad header data [IP: 195.135.221.134 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
