### ISSUE TITLE
Debian 8 repo is broken: getting "Size mismatch" error

### ISSUE THREAD

**Issue by mrphs** [EasyEngine/easyengine#905]
```
Get:1 http://download.opensuse.org/repositories/home:/rtCamp:/EasyEngine/Debian_8.0/  nginx-ee 1.10.3-10ppa~stable [78.8 kB]
Get:2 http://download.opensuse.org/repositories/home:/rtCamp:/EasyEngine/Debian_8.0/  nginx-custom 1.10.3-10ppa~stable [629 kB]
Get:3 http://download.opensuse.org/repositories/home:/rtCamp:/EasyEngine/Debian_8.0/  nginx-common 1.10.3-10ppa~stable [93.5 kB]
Fetched 801 kB in 0s (2506 kB/s)       
E: Failed to fetch http://download.opensuse.org/repositories/home:/rtCamp:/EasyEngine/Debian_8.0/./amd64/nginx-ee_1.10.3-10ppa~stable_amd64.deb  Size mismatch

E: Failed to fetch http://download.opensuse.org/repositories/home:/rtCamp:/EasyEngine/Debian_8.0/./amd64/nginx-custom_1.10.3-10ppa~stable_amd64.deb  Size mismatch

E: Failed to fetch http://download.opensuse.org/repositories/home:/rtCamp:/EasyEngine/Debian_8.0/./all/nginx-common_1.10.3-10ppa~stable_all.deb  Size mismatch
```

- [x] lsb_release -a
```
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.8 (jessie)
Release:	8.8
Codename:	jessie
```
- [x] ee -v
`EasyEngine v3.7.4`

**Comment by mbtamuli** [comment]
I just tested on a fresh Debian 8 instance. I didn't face any issues.
Can you provice more information on this? Maybe start with what command you ran and was this run on a fresh instance?

**Comment by khromov** [comment]
I am also having this issue on Ubuntu 16.04 for the same packages. 

```
sudo apt-get --with-new-pkgs upgrade
Fetched 15.4 MB in 2s (5,533 kB/s)
E: Failed to fetch http://download.opensuse.org/repositories/home:/rtCamp:/EasyEngine/xUbuntu_16.04/./amd64/nginx-ee_1.10.3-10ppa~stable_amd64.deb  Writing more data than expected (21148 > 21134) [IP: 195.135.221.134 80]

E: Failed to fetch http://download.opensuse.org/repositories/home:/rtCamp:/EasyEngine/xUbuntu_16.04/./amd64/nginx-custom_1.10.3-10ppa~stable_amd64.deb  Hash Sum mismatch

E: Failed to fetch http://download.opensuse.org/repositories/home:/rtCamp:/EasyEngine/xUbuntu_16.04/./all/nginx-common_1.10.3-10ppa~stable_all.deb  Hash Sum mismatch

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by mbtamuli** [comment]
Okay. I tried the same myself, but can't seem to replicate the error. Can you try this and see if it solves the problem?

```bash
sudo rm -rf /var/lib/apt/lists/*
sudo apt-get clean
sudo apt-get update
sudo apt-get --with-new-pkgs upgrade
```
_(Please run all the commands and in sequence)_

**Comment by khromov** [comment]
@mbtamuli This did solve the issue for me, thanks! However, I have four machines that all exhibit this behaviour (mix of 14.04 and 16.04) so at some point something must have gotten corrupted in the repos?

**Comment by mbtamuli** [comment]
I am not sure about the root cause of this issue. If this problem is recurring, we'll take a closer look.

**Comment by mr119** [comment]
Same issue here, trying to resolve with @mbtamuli command.
Receiving `W: Failed to fetch http://download.opensuse.org/repositories/home:/rtCamp:/EasyEngine/Debian_8.0/Packages  403  Forbidden [IP: 195.135.221.134 80]`

**Comment by mbtamuli** [comment]
@mr119 It is an issue with [download.opensuse.org](https://status.opensuse.org/incidents/18). Please keep an eye on [status.opensuse.org](https://status.opensuse.org/).

**Comment by mrphs** [comment]
Why isn't easy engine packaged for and available on official Debian and Ubuntu repositories?
