### ISSUE TITLE
CachetHQ Status Page

### ISSUE THREAD

**Issue by rahul286** [EasyEngine/easyengine#929]
https://github.com/CachetHQ/Cachet

Good to have it in EE. I think the way EE works, it can setup everything automatically making it even more appealing.

**Comment by MiteshShah** [comment]
@rahul286 I'd set up CachetHQ long back I guess in 2014 
https://miteshshah.github.io/linux/centos/how-to-configure-status-pages-using-cachet/

CachetHQ is Good if we want to schedule downtime.

If you are just looking for display all Webserver/API/ uptime i think best way is use UptimeRobot status page with CNAME so https://status.easyengine.io display EE Website API and all other on one single page without much developer work :)

https://blog.uptimerobot.com/introducing-public-status-pages-yay/

**Comment by rahul286** [comment]
CachetHQ API https://docs.cachethq.io/reference can record incidents I think. 

I am not sure exactly how we are going to use it but this is not for EE website. Idea is to configure create a status page per site that EasyEngine creates. So as an example for a WordPress site, a status page can list incidents such as php, mysql, cron etc failures.

**Comment by rahul286** [comment]
@mbtamuli will this be needed in docker world or we have alternatives.

**Comment by rahul286** [comment]
Will be handled differently in v4 because of docker.
