### ISSUE TITLE
can't upgrade to --php7

### ISSUE THREAD

**Issue by BoxMediaUK** [EasyEngine/easyengine#930]
getting errors on upgrading a site to php7 - it seems there is a connection issue of root@localhost to the mysql DB

`sudo ee site update example.dev --php7
PHP7.0 is experimental feature and it may not work with all plugins of your site.
You can disable it by passing --php7=off later.
Do you wish to enable PHP now for example.dev?
Type "y" to continue [n]:y
Running pre-update checks, please wait...
Backup location : /var/www/example.dev/backup/06Sep2017163519
Backing up database 		[Fail]
Check logs for reason `tail /var/log/ee/ee.log` & Try Again!!!`

Here are the log delails:

`$ sudo tail /var/log/ee/ee.log
2017-09-06 16:35:32,140 (INFO) ee : Backup location : /var/www/example.dev/backup/06Sep2017163519
2017-09-06 16:35:32,140 (DEBUG) ee : Copying file, Source:/etc/nginx/sites-available/example.dev, Dest:/var/www/example.dev/backup/06Sep2017163519
2017-09-06 16:35:32,141 (INFO) ee : Backing up database
2017-09-06 16:35:32,141 (DEBUG) ee : Running command: mysqldump example_dev > /var/www/example.dev/backup/06Sep2017163519/example_dev.sql
2017-09-06 16:35:32,226 (DEBUG) ee : Command Output: ,
Command Error: mysqldump: Got error: 1045: "Access denied for user 'root'@'localhost' (using password: YES)" when trying to connectlease attach the output of following command when open a new support request.`

- [ ] lsb_release -a
- [x] ee -v   EasyEngine v3.7.4
- [x] ee info

NGINX (1.10.3):

user                             www-data
worker_processes                 auto
worker_connections               4096
keepalive_timeout                30
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1

PHP (5.6.31-4):

user
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  500
pm.max_children                  100
pm.start_servers                 20
pm.min_spare_servers             10
pm.max_spare_servers             30
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           127.0.0.1:9000

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  500
pm.max_children                  100
pm.start_servers                 20
pm.min_spare_servers             10
pm.max_spare_servers             30
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9001
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)

MySQL (10.1.26-MariaDB) on localhost:

port
wait_timeout
interactive_timeout
max_used_connections
datadir
socket
my.cnf [PATH]                    /etc/mysql/conf.d/my.cnf
- [ ] wp --allow-root --info

**Comment by VirtuBox** [comment]
Hello, it seems the mysql credentials available in /etc/mysql/conf.d/my.cnf are not correct.

**Comment by rahul286** [comment]
Sorry for a delayed reply. I hope your issue is fixed by now.

If you are still facing the issue, please use http://community.rtcamp.com/c/easyengine for further support.

We are cleaning up issue tracker and closing this issue because we won't be able to contribute to this discussion further.
