### ISSUE TITLE
Bundling/Distributing ee v4 as docker image

### ISSUE THREAD

**Issue by rahul286** [EasyEngine/easyengine#934]
https://spin.atomicobject.com/2015/11/30/command-line-tools-docker/

https://github.com/codeclimate/codeclimate example

v4 being in PHP have a language dependency which is uncommon on fresh Linux distros.

Making ee v4 as a docker image and wrapper script means, we need to only make sure the OS has docker installed.

Also, it will seprate PHP intrepreter EE uses from PHP interpreter (version) required by PHP/WordPress sites. Hence it will make it easy to support multiple php versions in future.

**Comment by vanthaiunghoa** [comment]
Hello,

First, thanks for your great work.

May I ask how soon the docker images will be available?

Thanks

**Comment by benzon** [comment]
Hmm not sure i would like that it's a docker image, i would like to avoid using something like docker.

**Comment by rahul286** [comment]
Current status - all system packages such as php, mysql, nginx that EE needs are finalised. 

To handle future transitions smoothly we have created own dockerfiles for each https://github.com/EasyEngine/dockerfiles
In some cases - they are just wrapper around existing docker images.

@mbtamuli can you comment here how EE v4 will be delivered?

**Comment by rahul286** [comment]
@mbtamuli if we have dropped this idea, please close this issue

**Comment by mbtamuli** [comment]
Yes. This issue can be closed.
