### ISSUE TITLE
Oops Something went wrong !! Calling cleanup actions ...

### ISSUE THREAD

**Issue by AliYmn** [EasyEngine/easyengine#936]
<center><img src="https://image.prntscr.com/image/PzEu9M-ZTFeVIoJ2Nng1ow.png"/></center>

# [ 3.7.4 ] ee -v

# ee info ;
    port                             3306
    wait_timeout                     600
    interactive_timeout              28800
    max_used_connections             1
    datadir                          /var/lib/mysql/
    socket                           /var/run/mysqld/mysqld.sock
    my.cnf [PATH]                    /etc/mysql/conf.d/my.cnf
    root@ubuntu-1gb-nyc3-01:~# wp --allow-root --info
    PHP binary:	/usr/bin/php5.6
    PHP version:	5.6.31-6+ubuntu16.04.1+deb.sury.org+1
    php.ini used:	/etc/php/5.6/cli/php.ini
    WP-CLI root dir:	phar://wp-cli.phar
    WP-CLI packages dir:
    WP-CLI global config:
    WP-CLI project config:
    WP-CLI version:	0.24.1
    root@ubuntu-1gb-nyc3-01:~# clear
    root@ubuntu-1gb-nyc3-01:~# ee info

    NGINX (1.10.3):

    user                             www-data
    worker_processes                 auto
    worker_connections               4096
    keepalive_timeout                30
    fastcgi_read_timeout             300
    client_max_body_size             100m
    allow                            127.0.0.1

    PHP (5.6.31-6):

    user
    expose_php                       Off
    memory_limit                     128M
    post_max_size                    100M
    upload_max_filesize              100M
    max_execution_time               300

    Information about www.conf
    ping.path                        /ping
    pm.status_path                   /status
    process_manager                  ondemand
    pm.max_requests                  500
    pm.max_children                  100
    pm.start_servers                 20
    pm.min_spare_servers             10
    pm.max_spare_servers             30
    request_terminate_timeout        300
    xdebug.profiler_enable_trigger   off
    listen                           127.0.0.1:9000

    Information about debug.conf
    ping.path                        /ping
    pm.status_path                   /status
    process_manager                  ondemand
    pm.max_requests                  500
    pm.max_children                  100
    pm.start_servers                 20
    pm.min_spare_servers             10
    pm.max_spare_servers             30
    request_terminate_timeout        300
    xdebug.profiler_enable_trigger   on
    listen                           127.0.0.1:9001

    MySQL (10.1.28-MariaDB) on localhost:

    port                             3306
    wait_timeout                     600
    interactive_timeout              28800
    max_used_connections             1
    datadir                          /var/lib/mysql/
    socket                           /var/run/mysqld/mysqld.sock
    my.cnf [PATH]                    /etc/mysql/conf.d/my.cnf

# wp --allow-root --info ;
    PHP version:	5.6.31-6+ubuntu16.04.1+deb.sury.org+1
    php.ini used:	/etc/php/5.6/cli/php.ini
    WP-CLI root dir:	phar://wp-cli.phar
    WP-CLI packages dir:
    WP-CLI global config:
    WP-CLI project config:
    WP-CLI version:	0.24.1

**Comment by MiteshShah** [comment]
https://easyengine.io/blog/solution-couldnt-extract-wordpress-archive-error/

**Comment by vpedrosa** [comment]
EasyEngine is installing WP CLI v0.24.1, which is causing the bug (https://github.com/wp-cli/wp-cli/issues/1962 was in v0.19.1). Current version is v1.4.0.

```shell
$ wp cli version
WP-CLI 0.24.1
$ which wp
/usr/bin/wp
```

As long as EE is installing wp cli with root permissions, you can do:

```shell
sudo wp cli update --allow-root
```
Delete the site if you have already created it and recreate again.

**Comment by AliYmn** [comment]
Problem is fix but it was not so before
