### ISSUE TITLE
EasyEngine caches WordPress settings [for plugins]

### ISSUE THREAD

**Issue by sillyonthestreet** [EasyEngine/easyengine#937]
I'm using the latest version of EE on an Ubuntu 16.04 VPS with PHP 7 and Redis cache.

When trying to update whatever setting through /wp-admin/, it just reverts back to the old one.

If I disable the Redis cache, the settings go to the updated ones, so the Redis cache is caching WordPress settings.

I tried flushing the cache and clearing my browser's cache (also using a different browser), but it didn't work.

So what's my solution here, other than disabling the Redis cache altogether? Something with "WP_REDIS_IGNORED_GROUPS" ? Currently ignored groups: ["counts","plugins","themes"]

- [ ] lsb_release -a

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

- [ ] ee -v

EasyEngine v3.7.4
Copyright (c) 2016 rtCamp Solutions Pvt. Ltd.

- [ ] ee info

NGINX (1.10.3):

user                             www-data
worker_processes                 auto
worker_connections               4096
keepalive_timeout                30
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1

PHP (5.6.31-6):

user
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  500
pm.max_children                  100
pm.start_servers                 20
pm.min_spare_servers             10
pm.max_spare_servers             30
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           127.0.0.1:9000

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  500
pm.max_children                  100
pm.start_servers                 20
pm.min_spare_servers             10
pm.max_spare_servers             30
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9001

MySQL (10.1.28-MariaDB) on localhost:

port                             3306
wait_timeout                     60
interactive_timeout              28800
max_used_connections             44
datadir                          /var/lib/mysql/
socket                           /var/run/mysqld/mysqld.sock
my.cnf [PATH]                    /etc/mysql/conf.d/my.cnf

- [ ] wp --allow-root --info

PHP binary:     /usr/bin/php7.0
PHP version:    7.0.24-1+ubuntu16.04.1+deb.sury.org+1
php.ini used:   /etc/php/7.0/cli/php.ini
WP-CLI root dir:        phar://wp-cli.phar
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 0.24.1

**Comment by QROkes** [comment]
I had the same issue some time ago, it was a headache just to find out that W3 Total Cache plugin was causing it. That's when I decided to replace it. I still miss the Minify module! It's important to mention that only CDN and Minify modules was enabled, weird!!!
Another thing, if you use Akismet plugin you need to add "widget" to the redis ignored groups list.

**Comment by sillyonthestreet** [comment]
I don't use the w3tc plugin though. Any tips on how to find which plugin is causing this other than disabling/enabling them one by one? How did you find out?

Thanks for the Akismet tip

**Comment by QROkes** [comment]
1 - As you said, enable/disable each plugin.
2 - Any nginx conf file modified? (fastcgi)
3 - Use the redis-cli monitor to see what is caching.

**Comment by sillyonthestreet** [comment]
A workaround I found is just adding the 'options' cache group to WP_REDIS_IGNORED_GROUPS

**Comment by QROkes** [comment]
That's weird!
I don't have the "options" group added and everything works fine.

**Comment by HarrisJT** [comment]
I have had this issue, it is very frustrating. I am using these options.

Nginx configuration: wp wpredis (enabled)
PHP Version: 7.0
HHVM: enabled
SSL: enabled

I have to use `ee clean --all` to get it to work again, and I'm not sure that always works.

**Comment by mwaterhouse** [comment]
@QROkes 
> I still miss the Minify module!

Try the Autoptimize plugin - it just does the minify bit :-)

**Comment by QROkes** [comment]
@mwaterhouse I actually tried Autoptimize, believe me, it's not as good as W3TC is. You can not manually select files to minify and choose the order to process it, among many other features that only W3TC has. It's a pity that W3TC is almost abandoned. If I had the time I would make a fork of this module.

**Comment by sillyonthestreet** [comment]
Noticed a really specific issue now. When I delete a product category in WooCommerce, all my category data like Images, Thumbnails etc. get lost. Not sure if this is a theme-specific issue or WooCommerce-specific issues.

What are the most common WooCommerce cache groups that I can ignore? Or maybe some settings/options/wp-admin groups that I can add to WP_REDIS_IGNORED_GROUPS?

**Comment by brianjking** [comment]
Following...

**Comment by vibhi19** [comment]
Open object cache option in W3TC and disable cache for wp admin are
Do same with database cache

**Comment by rahul286** [comment]
We will be dropping support for W3TC and WP Super Cache in v4. 

That being said, we can't rule out object-cache itself running into issues mentioned here but there is no workaround that we can add in EasyEngine at this moment. 

If you can reproduce the issue and also a workaround, we would be happy to handle it in EasyEngine. 

For anything that cannot be fixed from EasyEngine itself, please use support forum - http://community.rtcamp.com/c/easyengine

**Comment by robrecord** [comment]
The redis cache flush isn't operating normally because when you turn on redis using `ee site update --wpredis`, the WP_CACHE_KEY_SALT definition is added too late in the wp-config.php file. It should be moved up before the require statement.
