### ISSUE TITLE
Upgrade Nginx to 1.13.6 and is EasyEngine Dead?

### ISSUE THREAD

**Issue by benzon** [EasyEngine/easyengine#939]
Think we need an update soon on the state of EasyEngine, is the project dead or a live?

Besides that we need to get a updated version Nginx Released, so we aint behind like we are now.

**Comment by ashishdungdung** [comment]
I wonder about that; there hasn't been any updates for so long and we are behind a lot of things.

**Comment by benzon** [comment]
Ye 14 days with out a reply from the guys behind is to long, i decided 1 week ago to migrate away from EasyEngine, i cant keep supporting it since  it feels dead.

Not a single update for almost 1 year, so we actually changed to using Plesk, rather use 5 USD pr. month then keep using a dead solution, and Plesk got a lot more security and other stuff build right in.

**Comment by eddr** [comment]
Very disappointing indeed.. 

@benzon - how did plessk come to $5/month?

**Comment by benzon** [comment]
@eddr got the 30 domains version for VPS since we run ESXI setup on our Dedicated server, and bought the license with at a company called hostingbuy or something like that.

And to be honest, plesk offers way more features, better security, better everything, and can be optimized quite abit, so no reason to stay on EasyEngine if you got the cash to use plesk.

**Comment by eddr** [comment]
Got you, thanks!

**Comment by VirtuBox** [comment]
@benzon there is no way to compare Plesk and EasyEngine. I use and I'm happy with both of them, but features provided are not the same, and that's why I use Plesk or EasyEngine depending on my needs.

Nginx version currently shipped with Plesk is v1.11.10. And the only solution to use the latest nginx release is the same for Plesk than for EasyEngine : you have to compile nginx from sources.

**Comment by rahul286** [comment]
> Upgrade Nginx to 1.13.6 

Our Nginx build is here https://build.opensuse.org/project/show/home:rtCamp:EasyEngine
You can help us update to latest Nginx. We do not have resources to update Nginx.
The source for the same is here https://github.com/EasyEngine/nginx-build

Also, 1.13.6 is not a stable release. Nginx follows a different version number convention so we will only update to stable releases which are even, so 1.12.2 is current stable version (at the time of posting this comment)

> is EasyEngine Dead? #939

Read - https://easyengine.io/blog/easyengine-v4-status-update/

I am closing this issue as being non-constructive. 

If anyone has a question about the blog post, they can post a comment there.

If anyone wishes to help manage nginx package, please create an issue on https://github.com/EasyEngine/nginx-build
