### ISSUE TITLE
Backing up database failed

### ISSUE THREAD

**Issue by princev558** [EasyEngine/easyengine#944]
When i created my site i used this command `sudo ee site create example.com --wpredis`
it worked fine but i want to minify my css and html so what i did yesterday i
i ran this code `ee site update example.com --wp --w3tc`
so this code removed the wordpress redis cache and installed w3 total cache
when i cleared the cache my site was briked it says that error establishing database connection
so i run this code `ee site update example.com --wp --wp` 
This command remove the w3 total cache and my website start working normally but after some time it says that error establishing database connection, so i reboot my vps
but when i run this code `ee site update example.com --wp --w3tc` again to install w3 total cache 
it shows that Backing up database [Fail]
```
root@example:/var/log/ee# ee site update example.com --wp --w3tc
Running pre-update checks, please wait...
Backup location : /var/www/example.com/backup/28Nov2017104752
Backing up database             [Fail]
Check logs for reason `tail /var/log/ee/ee.log` & Try Again!!!
```

When i checked ee.log i saw that i Got error: `1045: "Access denied for user 'root'@'localhost' (using password: YES)" when trying to connect`

Please help me to solve this issue

**Comment by VirtuBox** [comment]
Hello,
the command to update cache system site with easyengine should not include --wp 
The argument --wp is the wordpress configuration without additional cache. So running --wp --w3tc give two configuration at the same time.

For example, you can use  : 
```
ee site update example.com --wp
ee site update example.com --wpredis
ee site update example.com --w3tc
```

**Comment by rahul286** [comment]
@princev558 Sorry for a delayed reply. I hope your issue is fixed by now. Thanks @VirtuBox for helping.

If you are still facing the issue, please use http://community.rtcamp.com/c/easyengine for further support.

We are cleaning up issue tracker and closing this issue because we won't be able to contribute to this discussion further.
