### ISSUE TITLE
Add OCSP Stapling by default

### ISSUE THREAD

**Issue by jasomdotnet** [EasyEngine/easyengine#951]
When OCSP Stapling is disabled, user browser (Firefox) checks to whether a website certificate has been revoked or not. It's within Online Certificate Status Protocol or OCSP.

It 'leaks' user vistis to the cert issuer + causing heavy traffic on the cert issuer servers + slows down page load since it is additional request. Enabled OCSP Stapling reduces this.

![Example](https://i.imgur.com/lyxqR53.png)

See [this](https://www.maxcdn.com/one/visual-glossary/ocsp-stapling/) article.

## How to enable OCSP Stapling:

Add to the end of your /etc/nginx/sites-available/example.com conf this:

```
...
    ssl_stapling on;
    ssl_stapling_verify on;
    ssl_trusted_certificate /etc/letsencrypt/live/example.com/chain.pem;
}
```

then 

```
nginx -t
service nginx restart
```

Use this [tool](https://www.digicert.com/help/) (or [this](https://www.ssllabs.com/ssltest/index.html)) to see OCSP Stapling is enabled on your server.

**Make OCSP Stapling default within EasyEngine configuration.**

**Comment by kirtangajjar** [comment]
@rahul286 Can't this be shipped in 3.x release :/

**Comment by rahul286** [comment]
@kirtangajjar Yep. But updating conf files for existing sites will be a big task prone to error.

You are free to send a two separate PRs:
1. Handles OCSP Stapling for new sites created on v3 in future
2. `ee update` codes which do some `sed` magic, test `nginx -t`, if success => does `service nginx reload` or if fail revert conf changes and displays a warning requesting a user to manually update conf file.

For:
> revert conf changes

EE uses git to version control all conf changes. We normally write a `ee update` routing as below:

1. `git commit` any unsaved changes since previous run (humans can make edits they forget to save).
2. Update conf files. Usually `sed` + `awk` commands.
3. Test, if success `git commit` changes. If fail, `git reset` to discard changes.

**Comment by rahul286** [comment]
I think we are lucky here.

http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_stapling is a http{} level block.

You may get around by moving some or all changes to `/etc/nginx/conf.d/ocsp-stapling.conf` (new file).

**Comment by janiosarmento** [comment]
If it helps, this is my `ssl-optimized.conf` file, in use in an actual website:

```
ssl_session_cache shared:SSL:20m;
ssl_session_timeout 180m;
ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
ssl_prefer_server_ciphers on;
ssl_ciphers ECDH+AESGCM:ECDH+AES256:ECDH+AES128:DHE+AES128:!ADH:!AECDH:!MD5;
ssl_dhparam /etc/nginx/cert/dhparam.pem;

ssl_stapling on;
ssl_stapling_verify on;
ssl_trusted_certificate /etc/letsencrypt/live/lucrandonarede.com.br/fullchain.pem;
resolver 8.8.8.8 8.8.4.4;
```

It would be better, I think as an user, to keep these settings in server level (`/var/www/domain.com/conf/nginx/`), just like `ssl.conf`.

**Comment by janiosarmento** [comment]
Actually, I think even the *force-ssl* configuration should not be in `/etc/nginx/conf.d` because it does not make sense, in my mind.

**Comment by VirtuBox** [comment]
Yes, ssl_stapling directives can added in the file /var/www/domain/nginx/conf/ssl.conf, 
but all other SSL directives can stay in nginx.conf, it's not needed to set them in each vhost.

Some other settings to harden nginx configuration : 

- older TLS version than 1.2 can be removed (TLS 1.3 is only available with nginx v1.13.x)
- ssl_dhparam can now be replaced with ssl_ecdh_curve (better security and performance)

```
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers 'TLS13-CHACHA20-POLY1305-SHA256:TLS13-AES-256-GCM-SHA384:TLS13-AES-128-GCM-SHA256:EECDH+CHACHA20:EECDH+AESGCM';
	ssl_ecdh_curve X25519:sect571r1:secp521r1:secp384r1;
        ssl_session_timeout 1d;
        ssl_session_cache shared:SSL:50m;
        ssl_session_tickets off;
        ssl_prefer_server_ciphers on;
```
Additional security headers should also be set in nginx.conf

```
	##Common headers for security
        more_set_headers "X-Frame-Options : SAMEORIGIN";
        more_set_headers "X-Xss-Protection : 1; mode=block";
        more_set_headers "X-Content-Type-Options : nosniff";
        more_set_headers "Referrer-Policy : strict-origin-when-cross-origin";
```

**Comment by jasomdotnet** [comment]
Yes @VirtuBox, headers are poorly done in current EasyEngine. Test your WP site with [this](https://www.dareboost.com/en/home) tool.

In my case I have PHP7 site with <iframe> feature so header "X-Frame-Options : SAMEORIGIN" should be easily disabled per website.

@janiosarmento Thanks for your config.

**Comment by VirtuBox** [comment]
@jasomdotnet iframe usage isn't secure at all (it's the easiest way to inject ads, code or anything else on your website) and most website do not include iframes.

To analyze your website security settings, [Observatory by Mozilla ](https://observatory.mozilla.org/) is the best one and run several website analyzers, including [ssllabs](https://www.ssllabs.com/ssltest/), [securityheaders](https://securityheaders.io/), [tls.imirhil.fr](https://tls.imirhil.fr).

And to generate a secure nginx configuration, Mozilla also provide a SSL/TLS configuration tool available here: https://mozilla.github.io/server-side-tls/ssl-config-generator/

**Comment by jasomdotnet** [comment]
In opposite to apache2, nginx headers cannot be unset in server block. There is no such directive in nginx core, headers are [interited](https://www.ruby-forum.com/topic/6876105). Unset directive per server block for apache2 looks like:

`Header always unset X-Frame-Options`

Maybe EE nginx should be compiled with [ngx_headers_more](https://github.com/openresty/headers-more-nginx-module) module. 

@VirtuBox Observatory is nice tool, thanks
