### ISSUE TITLE
Administrate Access to Admin Tools

### ISSUE THREAD

**Issue by s-a-s-k-i-a** [EasyEngine/easyengine#954]
This request is related to this article:
https://easyengine.io/docs/admin-tools-22222/

Currently there is one HTTP Auth user added to htpasswd for access to any of the administrative tools in any directory under Port 22222.

This is unfortunate, because for example VimbAdmin should be accessible without giving also permissions to access any of the other admin tools. 

VimbAdmin allows users to change their mailbox passwords. It allows to setup administrators for each Domain pointing to the server. So they can setup mailboxes and alias-emailaddresses for domains they have been assigned to.

Currently, even if I set up an additional htpasswd user and password combination for Vimbadmin Access, those users could if they wanted, also access phpmyadmin and all the other admin tools, if they navigated to server.com:22222 instead of server.com:22222/vimbadmin

Request:
Please improve this :)

**Comment by VirtuBox** [comment]
EasyEngine configuration is for a single administrator but not for multi-users management.

But you should be able to edit the nginx configuration to use another port and htpasswd file for Vibadmin or for Admin tools. Just take a look on the file /etc/nginx/sites-available/22222

**Comment by s-a-s-k-i-a** [comment]
Thanks for you reply. As I mentioned in my post, I am aware of the fact, that I can add more than one http auth users/password combination to grant different people access to admin tools.

However I am pointing out the fact we are using a GUI called VimbAdmin (offered by ee stack installation even), which provides possibility to manage mailboxes for domains pointing to current server.
Vimbadmin allows managing several admins as superadmin. so admins can for example only manage  1 specific domain and corresponding mailboxes and alias email addresses etc.

Also VimbAdmin allows mailbox users to change their mailbox password. However they can only access Vimbadmin after entering http auth data. Once they gained access to vimbadmin, they can also access all other admin tools. 
This is not optimal as it is a fact, that there will be more than 1 mailbox user over time.

Thus I am requesting an improvement here.

An easy improvement could for example be:
moving vimbadmin from 22222 to another port. So we can add http auth there, which will no longer allow access to the other more sensitive server admin tools.

**Comment by rahul286** [comment]
We will keep this for V4 later releases. Let's see how does this fits naturally once the first v4 goes out! 🤞

**Comment by rahul286** [comment]
Being handled in https://github.com/EasyEngine/easyengine/issues/1119
