### ISSUE TITLE
Compile nginx with nginx-push-stream-module

### ISSUE THREAD

**Issue by jasomdotnet** [EasyEngine/easyengine#960]
Compile nginx with [nginx-push-stream-module](https://www.nginx.com/resources/wiki/modules/push_stream/#push-stream-installation) for support of http2 [push](
https://www.smashingmagazine.com/2017/04/guide-http2-server-push/) request type.

**Comment by mbtamuli** [comment]
We've updated the Nginx version to 1.14.0 and _the "http2_push" and "http2_push_preload" directives_ are included in this latest version. [Source](http://nginx.org/en/CHANGES-1.14)
Blog post regarding Nginx update in EasyEngine - https://easyengine.io/blog/easyengine-v3-8/
