### ISSUE TITLE
All URI starting with /status, /ping, /pma, /adminer etc. are treated as special locations

### ISSUE THREAD

**Issue by RavanH** [EasyEngine/easyengine#965]
Say someone writes a page or post about the game Ping Pong or a television animation Pingu or an urban dictionary about PMA (Positive Mental Attitude). It'd be likely that page slug would start with "ping" or "pma". In such a case, visiting that page would give an unexpected result.

I've added pull request #964 to address this.

**Comment by mbtamuli** [comment]
Fixed by #964
