### ISSUE TITLE
encoding with 'idna' codec failed (UnicodeError: label too long)

### ISSUE THREAD

**Issue by lawrencetaur** [EasyEngine/easyengine#967]
Kindly, attach the output of the following commands while creating a new support request.

- [x] lsb_release -a : 16.04
- [x] ee -v : 3.7.4 or 3.7.5
- [ ] ee info 
- [ ] wp --allow-root --info

Cannot run any ee command. I get "encoding with 'idna' codec failed (UnicodeError: label too long)" when I run "ee ..."

**Comment by VirtuBox** [comment]
Hello, 
do you get this error on all ee commands or only when you create a new vhost ?
Do you use some domain with  Internationalised Domain Names (IDNs) format ?

**Comment by lawrencetaur** [comment]
On all ee commands.

No, just using .com

**Comment by lawrencetaur** [comment]
When I try to run  wget -qO ee rt.cx/ee && sudo bash ee , it asks me if I want to install 3.7.5 and when I say yes, I get the following:

```
Using /usr/local/lib/python3.5/dist-packages/pystache-0.5.4-py3.5.egg
Searching for cement==2.4.0
Best match: cement 2.4.0
Processing cement-2.4.0-py3.5.egg
cement 2.4.0 is already the active version in easy-install.pth

Using /usr/local/lib/python3.5/dist-packages/cement-2.4.0-py3.5.egg
Finished processing dependencies for ee==3.7.5
Updating Nginx configuration, please wait...
no crontab for root
Updating WP-CLI version to resolve compatibility issue.
**encoding with 'idna' codec failed (UnicodeError: label too long)**

For EasyEngine (ee) auto completion, run the following command

source /etc/bash_completion.d/ee_auto.rc

EasyEngine (ee) installed/updated successfully
EasyEngine (ee) help: http://docs.rtcamp.com/easyengine/
```

**Comment by VirtuBox** [comment]
Hello, what is your server hostname ?

**Comment by lawrencetaur** [comment]
Digital Ocean

**Comment by VirtuBox** [comment]
Hello,  can you try the following command : 
```bash
env LANG=C.UTF-8 
```

It's likely an issue with your environment, check you set your preferred file encoding either in LANG, LANGUAGE, LC_ALL or LC_CTYPE:

**Comment by lawrencetaur** [comment]
I ran that command and got 
LANG=C.UTF-8
LANGUAGE=en_US:en
LC_CTYPE=UTF-8

I don't see an LC_ALL

I moved the site to a new server and EE command worked for a while. Looks like it stopped after 'ee site update example.com --type'

**Comment by lawrencetaur** [comment]
While running  `wget -qO ee rt.cx/ee && sudo bash ee` I get this at the end 

```
Using /usr/local/lib/python3.5/dist-packages/pystache-0.5.4-py3.5.egg
Searching for cement==2.4.0
Best match: cement 2.4.0
Processing cement-2.4.0-py3.5.egg
cement 2.4.0 is already the active version in easy-install.pth

Using /usr/local/lib/python3.5/dist-packages/cement-2.4.0-py3.5.egg
Finished processing dependencies for ee==3.7.5
Updating Nginx configuration, please wait...
no crontab for root
Updating WP-CLI version to resolve compatibility issue.
encoding with 'idna' codec failed (UnicodeError: label too long)

For EasyEngine (ee) auto completion, run the following command

source /etc/bash_completion.d/ee_auto.rc

EasyEngine (ee) installed/updated successfully
EasyEngine (ee) help: http://docs.rtcamp.com/easyengine/
```

**Comment by VirtuBox** [comment]
Try to run :
```
sudo dpkg-reconfigure locales
```
And choose an UTF-8 locale. I have found those informations in [Isso documentation](https://posativ.org/isso/docs/troubleshooting/), and it's also a tool written in python

**Comment by VirtuBox** [comment]
I have noticed a similar error by installing EE on a digitalocean droplet.

Here the message displayed on ondrej ppa repository : 

> WARNING: add-apt-repository is broken with non-UTF-8 locales, see
https://github.com/oerdnj/deb.sury.org/issues/56 for workaround:
```
LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php
```

**Comment by lawrencetaur** [comment]
Doesn't seem to work. I've moved the site to a new droplet for now. 

locale gives: 
```
LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

**Comment by VirtuBox** [comment]
It seems there is an issue with the add-apt-repository and digitalocean ubuntu image related to non-UTF8 locales, but I have managed to install easyengine and to create a nginx vhost.

**Comment by lawrencetaur** [comment]
EE does work on my other digital ocean droplets. I did notice that even when I installed s3cmd I got the LC_ALL not found warning on another droplet.

**Comment by rahul286** [comment]
We are closing this issue as we won't be able to look further into it.

Please use http://community.rtcamp.com/c/easyengine for future support questions.
