### ISSUE TITLE
Install packages by displaying progress bar

### ISSUE THREAD

**Issue by MiteshShah** [EasyEngine/easyengine#97]
- [ ] Show pv style progress bar for each package that is being installed behind the scene. Also add something like 1/5, 2/5, etc
#### Reference:

For the pv style output we can used following software's
1. smart (apt-get install smartpm-core)
2. debconf-apt-progress

Something Interesting: http://iloveubuntu.net/apt-0913-landed-ubuntu-1404-fancy-progress-bar-and-new-options

**Comment by rahul286** [comment]
**Update:** EE v4 installer will be very simple so something like this is not needed anymore.
