### ISSUE TITLE
error 'ee_mysql_grant_host' last ee

### ISSUE THREAD

**Issue by CristianPietrobon** [EasyEngine/easyengine#971]
running this command from a fresh vm (google cloud):
sudo ee site create xxxx.com --wp --php7

same error on Debian 8

- [x] **lsb_release -a**
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial
- [x] **ee -v**
EasyEngine v3.7.5
Copyright (c) 2016 rtCamp Solutions Pvt. Ltd.
- [x] **ee info**
NGINX (1.10.3):
user                             www-data
worker_processes                 auto
worker_connections               4096
keepalive_timeout                30
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1 
'ping.path'
- [x] **wp --allow-root --info**
OS:     Linux 4.13.0-1011-gcp #15-Ubuntu SMP Mon Feb 12 16:29:04 UTC 2018 x86_64
Shell:  /bin/bash
PHP binary:     /usr/bin/php7.0
PHP version:    7.0.28-1+ubuntu16.04.1+deb.sury.org+1
php.ini used:   /etc/php/7.0/cli/php.ini
WP-CLI root dir:        phar://wp-cli.phar
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /home/freesmscp
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 2.0.0-alpha-cfc0ed9

**Comment by VirtuBox** [comment]
Error is related to Issue https://github.com/EasyEngine/easyengine/issues/969

**Comment by CristianPietrobon** [comment]
solved following #969
