### ISSUE TITLE
ee update doesn't work

### ISSUE THREAD

**Issue by sillyonthestreet** [EasyEngine/easyengine#975]
Trying to update ee to 3.7.5, but running `sudo ee update` returns the following:
`Downloading update script        Unable to download file, /tmp/eeupdate20180401-115516
`
Tried this on several different servers and I still get the same error.

I'm running Ubuntu 16.04

**Comment by mbtamuli** [comment]
This is a known issue with the update command and has already been worked on. It will be fixed in the next release.

In the meantime, you can run the easy install command itself to update to the new version.
```bash
wget -qO ee rt.cx/ee && sudo bash ee
```
