### ISSUE TITLE
EE Not Autoupdating LetsEncrypt SSL

### ISSUE THREAD

**Issue by lothsun** [EasyEngine/easyengine#977]
My server is a linode server. For some reason the ssl isn't automatically upgrading. 

Kindly, attach the output of the following commands while creating a new support request.
-----------------------------------------------------------------------------------
- [ ] lsb_release -a

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
-----------------------------------------------------------------------------------
- [ ] ee -v

EasyEngine v3.7.5
Copyright (c) 2016 rtCamp Solutions Pvt. Ltd.
-----------------------------------------------------------------------------------
- [ ] ee info

NGINX (1.10.3):

user                             www-data
worker_processes                 auto
worker_connections               4096
keepalive_timeout                30
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1 

PHP (5.6.33-1):

user                             
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  500
pm.max_children                  100
pm.start_servers                 20
pm.min_spare_servers             10
pm.max_spare_servers             30
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           127.0.0.1:9000

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  500
pm.max_children                  100
pm.start_servers                 20
pm.min_spare_servers             10
pm.max_spare_servers             30
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9001

MySQL (10.1.30-MariaDB) on localhost:

port                             3306
wait_timeout                     600
interactive_timeout              28800
max_used_connections             6
datadir                          /var/lib/mysql/
socket                           /var/run/mysqld/mysqld.sock
my.cnf [PATH]                    /etc/mysql/conf.d/my.cnf
-----------------------------------------------------------------------------------
- [ ] wp --allow-root --info

PHP binary:	/usr/bin/php5.6
PHP version:	5.6.33-1+ubuntu16.04.1+deb.sury.org+1
php.ini used:	/etc/php/5.6/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/home/lothsun
WP-CLI packages dir:	
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	1.4.1

**Comment by jsonUK** [comment]
Switch out the EE cron for the regular LetsEncrypt cron. EE auto renew has been broken for quite some time.

`30 0 * * 0   /opt/letsencrypt/letsencrypt-auto renew > /dev/null 2>&1`

**Comment by rahul286** [comment]
We are handling this in a better way in v4.

You may check this PR #1005

Please use http://community.rtcamp.com/c/easyengine for future support questions.
