### ISSUE TITLE
Fail2ban & WordPress

### ISSUE THREAD

**Issue by tzitzigr** [EasyEngine/easyengine#995]
**Description:** Fail2ban fails to monitor WordPress bruteforce attacks, in its factory config.

**Sugesstion:** Offering a ready-made jail.local, with some extra lines, related to WordPress login attemps:

```
[wordpress]
enabled = true
filter = wordpress
logpath = /var/log/auth.log
port = http,https
maxretry = 3
```

and adding **wpfail2ban** plugin as a dependency (the same way **--wpredis** command installs **Wp Redis** plugin).

PS: The following is only a suggestion. I understand that it will create a new dependency, however, it should be considered, since it will affect only WordPress installations. There are much more possibilities and things that can be prevented in **jail.local**, i.e, ssh brute force jail:

```
[ssh]
enabled = true
port = ssh
filter = sshd
logpath = /var/log/auth.log
maxretry = 3
```

but lets stick to WordPress brute force attack prevention.

**Comment by VirtuBox** [comment]
The easiest way to detect bruteforce on WordPress with fail2ban is to limit POST requests on wp-login.php for the same IP. 

fail2ban filter : https://github.com/VirtuBox/ubuntu-nginx-web-server/blob/master/etc/fail2ban/filter.d/ee-wordpress.conf

fail2ban jails : https://github.com/VirtuBox/ubuntu-nginx-web-server/blob/master/etc/fail2ban/jail.d/custom.conf

**Comment by mbtamuli** [comment]
EasyEngine helps prevent WordPress brute force attack by using the `limit_req` Nginx module. You can look at this article for more details - https://easyengine.io/tutorials/nginx/block-wp-login-php-bruteforce-attack/.

I am closing this issue for now.
