### ISSUE TITLE
HHVM. won't start Automatically

### ISSUE THREAD

**Issue by vibhi19** [EasyEngine/easyengine#999]
Using Ubuntu 16.04 
Installed WordPress with WpFC and HHVM
To take snapshot i Power off the the droplet 
After restarting when I check Process via Htop
It shows PHP instead of HHVM
I have manually restart it via cmd
Service Hhvm start

- [ ] lsb_release -a
- [ ] ee -v
- [ ] ee info
- [ ] wp --allow-root --info

**Comment by rahul286** [comment]
We do not support HHVM. Please use PHP 7.
